Repository goharbor/harbor, pull requests merged in 2018-04, with the labels that each got.

#4511 add all in one migrator scripts
  tools/migration/Dockerfile
  tools/migration/cfg/run.py
  tools/migration/db/alembic.tpl
  tools/migration/db/migration_cfg/harbor_1_1_0_template
  tools/migration/db/migration_cfg/upgrade
  tools/migration/db/run.sh
  tools/migration/docker-entrypoint.sh
  tools/migration/migrator.py
Labels: cla-not-required

#4523 Upgrade migrator to 1.5.0
  make/photon/db/registry.sql
  tools/migration/db/db_meta.py
  tools/migration/db/migration_harbor/versions/1_5_0.py
Labels: cla-not-required

#4548 Fix up ldap testcase
  tests/ldap_test.ldif
  tests/robot-cases/Group11-Nightly/LDAP.robot
Labels: cla-not-required

#4542 Add repo read only
  src/ui_ng/lib/src/create-edit-label/create-edit-label.component.css.ts
  src/ui_ng/lib/src/create-edit-rule/create-edit-rule.component.css.ts
  src/ui_ng/lib/src/label-piece/label-piece.template.ts
  src/ui_ng/lib/src/label/label.component.ts
  src/ui_ng/lib/src/repository-listview/repository-listview.component.ts
  src/ui_ng/lib/src/tag/tag-detail.component.html.ts
  src/ui_ng/lib/src/tag/tag-detail.component.spec.ts
  src/ui_ng/lib/src/tag/tag-detail.component.ts
  src/ui_ng/lib/src/tag/tag.component.css.ts
  src/ui_ng/lib/src/tag/tag.component.html.ts
  src/ui_ng/lib/src/tag/tag.component.ts
  src/ui_ng/package.json
  src/ui_ng/src/app/app-config.ts
  src/ui_ng/src/app/base/harbor-shell/harbor-shell.component.css
  src/ui_ng/src/app/base/navigator/navigator.component.ts
  src/ui_ng/src/app/config/config.component.html
  src/ui_ng/src/app/config/config.component.ts
  src/ui_ng/src/app/config/config.module.ts
  src/ui_ng/src/app/config/repo/repo-read-only.component.ts
  src/ui_ng/src/app/config/repo/repo-read-only.html
  src/ui_ng/src/app/global-message/message.component.css
  src/ui_ng/src/app/repository/tag-detail/tag-detail-page.component.html
  src/ui_ng/src/app/repository/tag-detail/tag-detail-page.component.ts
  src/ui_ng/src/app/shared/message-handler/message-handler.service.ts
  src/ui_ng/src/app/shared/route/auth-user-activate.service.ts
  src/ui_ng/src/i18n/lang/en-us-lang.json
  src/ui_ng/src/i18n/lang/es-es-lang.json
  src/ui_ng/src/i18n/lang/fr-fr-lang.json
  src/ui_ng/src/i18n/lang/zh-cn-lang.json
  tests/resources/Harbor-Pages/Configuration.robot
Labels: cla-not-required

#4561 Enable output parameter in harbor migrator
  tools/migration/db/run.sh
  tools/migration/docker-entrypoint.sh
  tools/migration/migrator.py
Labels: cla-not-required

#4565 Fix issue of stopping periodic job
  src/jobservice/job/impl/demo_job.go
  src/jobservice/opm/op_commands.go
  src/jobservice/opm/redis_job_stats_mgr.go
  src/jobservice/opm/redis_job_stats_mgr_test.go
  src/jobservice/period/redis_scheduler.go
  src/jobservice/pool/message_server.go
  src/jobservice/pool/message_server_test.go
  src/jobservice/pool/redis_pool.go
  src/jobservice/utils/utils.go
  src/replication/target/target.go
Labels: cla-not-required

#4549 Add manual test cases for label
  tests/testcases/Group11-Label/11-01-system-admin-manage-global-level-labels.md
  tests/testcases/Group11-Label/11-02-project-admin-manage-project-level-labels.md
  tests/testcases/Group11-Label/11-03-add-labels-to-images-and-remove-labels-from-images.md
  tests/testcases/Group11-Label/11-04-filter-images-by-label.md
Labels: cla-not-required

#4568 Scan job migrate
  src/common/job/client_test.go
  src/common/job/test/server.go
  src/common/job/test/test.log
  src/ui/api/repository.go
  src/ui/utils/utils.go
Labels: cla-not-required

#4562 Modify label filter issue and add stick label to image case
  src/ui_ng/lib/src/create-edit-label/create-edit-label.component.ts
  src/ui_ng/lib/src/create-edit-rule/create-edit-rule.component.ts
  src/ui_ng/lib/src/label-piece/label-piece.component.ts
  src/ui_ng/lib/src/label-piece/label-piece.template.ts
  src/ui_ng/lib/src/tag/tag.component.html.ts
  src/ui_ng/lib/src/tag/tag.component.ts
  src/ui_ng/package.json
  src/ui_ng/src/i18n/lang/en-us-lang.json
  src/ui_ng/src/i18n/lang/es-es-lang.json
  src/ui_ng/src/i18n/lang/fr-fr-lang.json
  src/ui_ng/src/styles.css
  tests/resources/Harbor-Pages/Project.robot
  tests/robot-cases/Group11-Nightly/Nightly.robot
Labels: cla-not-required

#4572 Hide schedule job when listing replication jobs
  src/common/dao/base.go
  src/common/dao/dao_test.go
  src/common/dao/replication_job.go
  src/common/models/replication_job.go
  src/replication/trigger/schedule.go
  src/ui/api/replication.go
  src/ui/api/replication_job.go
  src/ui/api/replication_policy.go
Labels: cla-not-required

#4558 Update harbor chart README.md with a known issue on K8s 1.9.4 [Skip CI]
  contrib/helm/harbor/README.md
Labels: area/k8s-support, cla-not-required

#4545 Add contributers list for Harbor Chart
  contrib/helm/harbor/CONTRIBUTING.md
  contrib/helm/harbor/README.md
Labels: cla-not-required

#4577 Reduce properties in hbr repository
  src/ui_ng/lib/README.md
  src/ui_ng/lib/package.json
  src/ui_ng/lib/pkg/package.json
  src/ui_ng/lib/src/repository-gridview/repository-gridview.component.html.ts
  src/ui_ng/lib/src/repository-gridview/repository-gridview.component.ts
  src/ui_ng/lib/src/repository/repository.component.ts
  src/ui_ng/package.json
  src/ui_ng/src/app/repository/tag-repository/tag-repository.component.html
Labels: cla-not-required, priority/high

#4576 Fix bug vulnerability notification not showing
  src/ui_ng/lib/package.json
  src/ui_ng/lib/pkg/package.json
  src/ui_ng/lib/src/repository-gridview/repository-gridview.component.html.ts
  src/ui_ng/lib/src/repository-gridview/repository-gridview.component.ts
  src/ui_ng/package.json
Labels: cla-not-required

#4514 Use new health check api for docker files
  make/photon/adminserver/Dockerfile
  make/photon/nginx/Dockerfile
  make/photon/postgresql/Dockerfile
  make/photon/postgresql/docker-healthcheck.sh
  make/photon/ui/Dockerfile
Labels: cla-not-required

#4401 Abstract repo click as a output event
  src/ui_ng/lib/README.md
Labels: cla-not-required

#4592 Store secret in header instead of cookie
  src/adminserver/auth/auth.go
  src/adminserver/auth/auth_test.go
  src/common/http/modifier/auth/auth.go
  src/common/http/modifier/auth/auth_test.go
  src/common/models/replication_job.go
  src/common/secret/request.go
  src/common/secret/request_test.go
  src/common/utils/registry/auth/credential.go
  src/common/utils/registry/auth/credential_test.go
  src/jobservice/job/impl/replication/replicate.go
  src/jobservice/job/impl/replication/transfer.go
  src/jobservice/job/impl/utils/utils.go
  src/ui/config/config.go
  src/ui/filter/security.go
  src/ui/filter/security_test.go
Labels: cla-not-required

#4593 Fix issue: failed to update the status of job if runtme error occurred
  src/jobservice/config.yml
  src/jobservice/job/impl/demo_job.go
  src/jobservice/opm/redis_job_stats_mgr.go
  src/jobservice/pool/message_server.go
  src/jobservice/pool/redis_job_wrapper.go
Labels: cla-not-required

#4585 Modify read only mode position, fix other issue
  src/ui_ng/lib/src/config/system/system-settings.component.html.ts
  src/ui_ng/lib/src/config/system/system-settings.component.ts
  src/ui_ng/lib/src/create-edit-rule/create-edit-rule.component.spec.ts
  src/ui_ng/lib/src/list-replication-rule/list-replication-rule.component.html.ts
  src/ui_ng/lib/src/log/recent-log.template.ts
  src/ui_ng/lib/src/replication/replication.component.html.ts
  src/ui_ng/lib/src/repository/repository.component.html.ts
  src/ui_ng/lib/src/tag/tag-detail.component.css.ts
  src/ui_ng/lib/src/tag/tag-detail.component.html.ts
  src/ui_ng/lib/src/tag/tag-detail.component.spec.ts
  src/ui_ng/lib/src/tag/tag.component.html.ts
  src/ui_ng/lib/src/tag/tag.component.ts
  src/ui_ng/package.json
  src/ui_ng/src/app/base/harbor-shell/harbor-shell.component.css
  src/ui_ng/src/app/config/config.component.css
  src/ui_ng/src/app/config/config.component.html
  src/ui_ng/src/app/config/config.component.ts
  src/ui_ng/src/app/config/config.module.ts
  src/ui_ng/src/app/config/repo/repo-read-only.component.ts
  src/ui_ng/src/app/config/repo/repo-read-only.html
  src/ui_ng/src/app/project/member/member.component.html
  src/ui_ng/src/app/project/project-detail/project-detail.component.html
  src/ui_ng/src/app/replication/destination/destination-page.component.html
  src/ui_ng/src/app/replication/replication-page.component.html
  src/ui_ng/src/app/replication/total-replication/total-replication-page.component.html
  src/ui_ng/src/app/replication/total-replication/total-replication.component.css
  src/ui_ng/src/app/repository/repository-page.component.html
  src/ui_ng/src/app/user/user.component.css
  src/ui_ng/src/i18n/lang/en-us-lang.json
  src/ui_ng/src/i18n/lang/es-es-lang.json
  src/ui_ng/src/i18n/lang/fr-fr-lang.json
  src/ui_ng/src/i18n/lang/zh-cn-lang.json
  src/ui_ng/src/styles.css
Labels: cla-not-required, target/1.5.0

#4596 Add harbor migrator into offline installer
  Makefile
Labels: cla-not-required

#4595 Apply auth checking to all the incoming requests
  src/jobservice/api/authenticator.go
  src/jobservice/api/handler_test.go
  src/jobservice/api/router.go
  src/jobservice/config/config.go
  src/jobservice/errs/errors.go
  src/jobservice/runtime/bootstrap.go
Labels: cla-not-required

#4589 Fix doc bug in high_availability_installation_guide.md
  docs/high_availability_installation_guide.md
Labels: cla-not-required

#4602 Label case
  src/ui_ng/lib/src/create-edit-label/create-edit-label.component.html.ts
  src/ui_ng/lib/src/create-edit-label/create-edit-label.component.ts
  src/ui_ng/lib/src/label-piece/label-piece.component.ts
  src/ui_ng/lib/src/label-piece/label-piece.template.ts
  src/ui_ng/lib/src/label/label.component.html.ts
  src/ui_ng/lib/src/shared/shared.const.ts
  src/ui_ng/lib/src/tag/tag.component.css.ts
  src/ui_ng/package.json
  src/ui_ng/src/i18n/lang/en-us-lang.json
  src/ui_ng/src/i18n/lang/es-es-lang.json
  src/ui_ng/src/i18n/lang/fr-fr-lang.json
  src/ui_ng/src/i18n/lang/zh-cn-lang.json
  tests/resources/Harbor-Pages/Configuration.robot
  tests/resources/Harbor-Pages/Project.robot
  tests/robot-cases/Group11-Nightly/Nightly.robot
Labels: cla-not-required

#4608 Fix log API random failure on travis
  src/ui/api/api_test.go
  src/ui/api/log_test.go
Labels: cla-not-required

#4599 Update keyword
  tests/resources/Docker-Util.robot
  tests/resources/Harbor-Pages/Project-Repository.robot
  tests/resources/Harbor-Pages/Replication.robot
Labels: cla-not-required

#4614 Add deploy and add additional info on action bar
  src/ui_ng/lib/package.json
  src/ui_ng/lib/pkg/package.json
  src/ui_ng/lib/src/repository-gridview/repository-gridview.component.html.ts
  src/ui_ng/lib/src/repository-gridview/repository-gridview.component.ts
  src/ui_ng/package.json
Labels: cla-not-required

#4626 Fix issue about links text and i18n
  src/ui_ng/lib/src/create-edit-rule/create-edit-rule.component.html.ts
  src/ui_ng/lib/src/repository-gridview/repository-gridview.component.ts
  src/ui_ng/lib/src/repository/repository.component.html.ts
  src/ui_ng/lib/src/tag/tag-detail.component.html.ts
  src/ui_ng/package.json
  src/ui_ng/src/i18n/lang/en-us-lang.json
  src/ui_ng/src/i18n/lang/es-es-lang.json
  src/ui_ng/src/i18n/lang/fr-fr-lang.json
  src/ui_ng/src/i18n/lang/zh-cn-lang.json
  src/ui_ng/{
Labels: cla-not-required

#4627 Log error when to write response body in readonly filter
  src/ui/filter/readonly.go
Labels: cla-not-required

#4625 Update user guide for label management
  docs/img/add_labels_to_images.png
  docs/img/filter_images_by_label.png
  docs/img/manage_global_level_labels.png
  docs/img/manage_project_level_labels.png
  docs/user_guide.md
Labels: cla-not-required

#4629 Fix up keyword and test case
  tests/resources/Docker-Util.robot
  tests/robot-cases/Group11-Nightly/Nightly.robot
  tests/robot-cases/Group11-Nightly/Replication.robot
Labels: cla-not-required

#4639 Update harbor default log level to info
  make/common/templates/adminserver/env
  make/common/templates/ui/env
Labels: cla-not-required

#4642 Update ci test images to busybox
  src/ui/api/repository_test.go
  src/ui/api/search_test.go
  tests/pushimage.sh
Labels: cla-not-required

#4645 Fix issue about label filter #4636
  src/ui_ng/lib/src/tag/tag.component.ts
  src/ui_ng/package.json
Labels: cla-not-required

#4640 Update HA template and User guide
  docs/high_availability_installation_guide.md
  make/ha/docker-compose.clair.tpl
  make/ha/docker-compose.tpl
Labels: cla-not-required

#4637 Bug fix
  src/ui/api/repository.go
Labels: cla-not-required

#4643 Add testcase and doc for cardview
  docs/img/browse_project_repositories.png
  docs/user_guide.md
  tests/resources/Harbor-Pages/Project.robot
  tests/robot-cases/Group11-Nightly/Nightly.robot
Labels: cla-not-required

#4675 Fix the failure api test cases because API implementation changed
  tests/apitests/api-testing/client/harbor_api_client.go
  tests/apitests/api-testing/lib/project.go
  tests/apitests/api-testing/lib/report.go
  tests/apitests/api-testing/models/member.go
  tests/apitests/api-testing/models/project.go
  tests/apitests/api-testing/tests/suites/suite01/suite.go
  tests/apitests/api-testing/tests/suites/suite02/suite.go
Labels: cla-not-required

#4677 Update migration document
  docs/migration_guide.md
Labels: cla-not-required

#4679 Update migrator image tag to v1.5.0
  Makefile
Labels: cla-not-required

#4680 Update version to v1.5.0-rc1
  VERSION
Labels: cla-not-required

#4674 Add project member search by name
  docs/swagger.yaml
  src/common/dao/project/projectmember.go
  src/common/dao/project/projectmember_test.go
  src/ui/api/ldap.go
  src/ui/api/projectmember.go
  src/ui/api/projectmember_test.go
Labels: cla-not-required

#4673 Fix bug 4665 project admin can not change the role of some user
  src/ui_ng/src/app/project/member/member.component.ts
Labels: cla-not-required

#4678 Fix drone fail on photon tdnf call
  .drone.yml
Labels: cla-not-required

#4684 Add filter images by label testcase
  src/ui_ng/lib/src/create-edit-label/create-edit-label.component.html.ts
  src/ui_ng/lib/src/tag/tag.component.ts
  src/ui_ng/package.json
  src/ui_ng/src/i18n/lang/en-us-lang.json
  src/ui_ng/src/i18n/lang/es-es-lang.json
  src/ui_ng/src/i18n/lang/fr-fr-lang.json
  src/ui_ng/src/i18n/lang/zh-cn-lang.json
  src/ui_ng/{
  tests/resources/Harbor-Pages/Project.robot
  tests/robot-cases/Group11-Nightly/Nightly.robot
Labels: cla-not-required

#4698 Fix configure save err
  src/ui_ng/lib/package.json
  src/ui_ng/lib/pkg/package.json
  src/ui_ng/lib/src/repository-gridview/repository-gridview.component.html.ts
  src/ui_ng/lib/src/repository-gridview/repository-gridview.component.ts
  src/ui_ng/package.json
  src/ui_ng/src/app/config/config.component.ts
Labels: cla-not-required

#4691 Fix ui issues
  src/ui_ng/lib/package.json
  src/ui_ng/lib/pkg/package.json
  src/ui_ng/lib/src/repository-gridview/repository-gridview.component.html.ts
  src/ui_ng/lib/src/repository-gridview/repository-gridview.component.ts
  src/ui_ng/package.json
Labels: cla-not-required

#4700 Fix readonly mode show in vic and rewording the tooltip
  src/ui_ng/lib/package.json
  src/ui_ng/lib/pkg/package.json
  src/ui_ng/lib/src/config/registry-config.component.html.ts
  src/ui_ng/lib/src/config/registry-config.component.ts
  src/ui_ng/lib/src/config/system/system-settings.component.html.ts
  src/ui_ng/lib/src/config/system/system-settings.component.ts
  src/ui_ng/package.json
  src/ui_ng/src/i18n/lang/en-us-lang.json
  src/ui_ng/src/i18n/lang/es-es-lang.json
  src/ui_ng/src/i18n/lang/fr-fr-lang.json
  src/ui_ng/src/i18n/lang/zh-cn-lang.json
Labels: cla-not-required

#4686 Merge pull request #4674 from stonezdj/filter_not_work
  docs/swagger.yaml
  src/common/dao/project/projectmember.go
  src/common/dao/project/projectmember_test.go
  src/ui/api/ldap.go
  src/ui/api/projectmember.go
  src/ui/api/projectmember_test.go
Labels: cla-not-required

#4672 Add query string when get members
  src/ui_ng/src/app/project/member/member.service.ts
Labels: cla-not-required

#4714 Fix the issue of missing copying the setting.json to container image
  make/dev/nodeclarity/entrypoint.sh
Labels: area/build, cla-not-required

#4696 Cheery-pick bugs fix to Release 1.5.0
  src/ui_ng/lib/package.json
  src/ui_ng/lib/pkg/package.json
  src/ui_ng/lib/src/config/registry-config.component.html.ts
  src/ui_ng/lib/src/config/registry-config.component.ts
  src/ui_ng/lib/src/config/system/system-settings.component.html.ts
  src/ui_ng/lib/src/config/system/system-settings.component.ts
  src/ui_ng/lib/src/repository-gridview/repository-gridview.component.css.ts
  src/ui_ng/lib/src/repository-gridview/repository-gridview.component.html.ts
  src/ui_ng/lib/src/repository-gridview/repository-gridview.component.ts
  src/ui_ng/package.json
  src/ui_ng/src/app/config/config.component.ts
  src/ui_ng/src/app/project/member/member.component.ts
  src/ui_ng/src/app/project/member/member.service.ts
  src/ui_ng/src/app/repository/repository-page.component.html
  src/ui_ng/src/app/repository/repository-page.component.ts
  src/ui_ng/src/i18n/lang/en-us-lang.json
  src/ui_ng/src/i18n/lang/es-es-lang.json
  src/ui_ng/src/i18n/lang/fr-fr-lang.json
  src/ui_ng/src/i18n/lang/zh-cn-lang.json
Labels: cla-not-required

#4718 Fix up card view keyword
  tests/resources/Harbor-Pages/Project.robot
  tests/robot-cases/Group11-Nightly/Nightly.robot
Labels: cla-not-required

#4720 Fix default view problem and styles issues
  src/ui_ng/lib/package.json
  src/ui_ng/lib/pkg/package.json
  src/ui_ng/lib/src/repository-gridview/repository-gridview.component.css.ts
  src/ui_ng/lib/src/repository-gridview/repository-gridview.component.html.ts
  src/ui_ng/lib/src/repository-gridview/repository-gridview.component.ts
  src/ui_ng/package.json
  src/ui_ng/src/app/repository/repository-page.component.html
  src/ui_ng/src/app/repository/repository-page.component.ts
Labels: cla-not-required

#4721 Promote version to v1.5.0-rc2
  VERSION
Labels: cla-not-required

#4671 Add documemt for read only
  docs/img/read_only.png
  docs/img/read_only_enable.png
  docs/user_guide.md
Labels: cla-not-required

#4725 Fix the issue of causing the UI UT cases failed
  src/ui_ng/lib/package.json
  src/ui_ng/package.json
Labels: area/build, cla-not-required

#4726 Fix the issue of causing the UI UT cases failed
  src/ui_ng/lib/package.json
  src/ui_ng/package.json
Labels: area/build, cla-not-required

#4703 Update ui clarity builder version to 1.4.0
  .travis.yml
  tests/resources/Harbor-Util.robot
Labels: cla-not-required

#4716 Fix bug #4688
  src/common/security/admiral/authcontext/authcontext.go
Labels: cla-not-required

#4723 Modify login bg image position about skinnable
  src/ui_ng/src/app/account/sign-in/sign-in.component.html
Labels: cla-not-required

#4727 Modify bread crumb and modify loginBg position about skinnable
  src/ui_ng/lib/src/repository/repository.component.css.ts
  src/ui_ng/lib/src/repository/repository.component.html.ts
  src/ui_ng/lib/src/repository/repository.component.ts
  src/ui_ng/lib/src/tag/tag-detail.component.css.ts
  src/ui_ng/lib/src/tag/tag-detail.component.html.ts
  src/ui_ng/lib/src/tag/tag-detail.component.ts
  src/ui_ng/package.json
  src/ui_ng/src/app/account/sign-in/sign-in.component.html
  src/ui_ng/src/app/repository/tag-detail/tag-detail-page.component.html
  src/ui_ng/src/app/repository/tag-detail/tag-detail-page.component.ts
  src/ui_ng/src/app/repository/tag-repository/tag-repository.component.css
  src/ui_ng/src/app/repository/tag-repository/tag-repository.component.html
  src/ui_ng/src/app/repository/tag-repository/tag-repository.component.ts
Labels: cla-not-required

#4728 Add document for read only
  docs/img/read_only.png
  docs/img/read_only_enable.png
  docs/user_guide.md
Labels: cla-not-required

#4739 Return the logger.Interface instead of the pointer of logger to avoid nil checking issue
  src/jobservice/job/impl/logger/job_logger.go
Labels: cla-not-required

#4731 Do not call `chown` to config files
  make/common/templates/notary/server-config.json
  make/docker-compose.clair.tpl
  make/docker-compose.notary.tpl
  make/photon/clair/docker-entrypoint.sh
  make/photon/jobservice/start.sh
  make/photon/notary/server-start.sh
  make/photon/notary/signer-start.sh
  make/photon/registry/entrypoint.sh
  make/photon/ui/start.sh
  make/prepare
  src/common/utils/notary/helper.go
  src/ui/config/config.go
  src/ui/config/config_test.go
  src/ui/service/token/authutils.go
  tests/testprepare.sh
Labels: cla-not-required

#4738 Return the logger.Interface instead of the pointer of logger to avoid nil checking issue
  src/jobservice/job/impl/logger/job_logger.go
Labels: cla-not-required

#4754 Fix security issue found by gas
  src/common/http/modifier/auth/auth.go
  src/jobservice/period/sweeper.go
Labels: cla-not-required

#4755 Modify replication rule list not seleted when load first
  src/ui_ng/lib/src/list-replication-rule/list-replication-rule.component.ts
  src/ui_ng/lib/src/replication/replication.component.html.ts
  src/ui_ng/lib/src/replication/replication.component.ts
  src/ui_ng/package.json
Labels: cla-not-required

#4756 Fix bug sent multiple scan request
  src/ui_ng/lib/package.json
  src/ui_ng/lib/pkg/package.json
  src/ui_ng/lib/src/tag/tag.component.html.ts
  src/ui_ng/lib/src/tag/tag.component.ts
  src/ui_ng/lib/src/vulnerability-scanning/result-bar-chart.component.ts
  src/ui_ng/package.json
Labels: cla-not-required

#4757 Modify replication rule list not seleted when load first
  src/ui_ng/lib/src/list-replication-rule/list-replication-rule.component.ts
  src/ui_ng/lib/src/replication/replication.component.html.ts
  src/ui_ng/lib/src/replication/replication.component.ts
  src/ui_ng/package.json
Labels: cla-not-required

#4758 Modify click to registry link under project
  src/ui_ng/src/app/replication/replication-page.component.html
  src/ui_ng/src/app/replication/replication-page.component.ts
Labels: cla-not-required

#4759 Modify click to registry link under project
  src/ui_ng/src/app/replication/replication-page.component.html
  src/ui_ng/src/app/replication/replication-page.component.ts
Labels: cla-not-required

#4760 Fix bug sent multiple scan request
  src/ui_ng/lib/package.json
  src/ui_ng/lib/pkg/package.json
  src/ui_ng/lib/src/tag/tag.component.html.ts
  src/ui_ng/lib/src/tag/tag.component.ts
  src/ui_ng/lib/src/vulnerability-scanning/result-bar-chart.component.ts
  src/ui_ng/package.json
Labels: cla-not-required

#4715 [Chart] Add support for deploying Notary
  contrib/helm/harbor/README.md
  contrib/helm/harbor/templates/NOTES.txt
  contrib/helm/harbor/templates/_helpers.tpl
  contrib/helm/harbor/templates/adminserver/adminserver-cm.yaml
  contrib/helm/harbor/templates/ingress/ingress.yaml
  contrib/helm/harbor/templates/ingress/secret.yaml
  contrib/helm/harbor/templates/notary/notary-cm.yaml
  contrib/helm/harbor/templates/notary/notary-db.yaml
  contrib/helm/harbor/templates/notary/notary-server.yaml
  contrib/helm/harbor/templates/notary/notary-signer.yaml
  contrib/helm/harbor/templates/notary/notary-svc.yaml
  contrib/helm/harbor/values.yaml
Labels: area/k8s-support, cla-not-required

#4763 Modify tooltips size about authentication
  src/ui_ng/src/app/config/auth/config-auth.component.html
Labels: cla-not-required

#4775 Workaround for golint issue in travis
  .travis.yml
Labels: cla-not-required

#4767 Modify color panel and add labels to imgs frequently click problem
  src/ui_ng/lib/src/create-edit-label/create-edit-label.component.css.ts
  src/ui_ng/lib/src/create-edit-label/create-edit-label.component.html.ts
  src/ui_ng/lib/src/create-edit-label/create-edit-label.component.ts
  src/ui_ng/lib/src/tag/tag.component.html.ts
  src/ui_ng/lib/src/tag/tag.component.ts
  src/ui_ng/package.json
Labels: cla-not-required

#4778 Cherry-pick: Fix mis-interpretation of severity in Clair
  src/common/models/pro_meta.go
  src/common/utils/clair/utils.go
  src/common/utils/clair/utils_test.go
Labels: cla-not-required

#4777 Fix mis-interpretation of severity in Clair
  src/common/models/pro_meta.go
  src/common/utils/clair/utils.go
  src/common/utils/clair/utils_test.go
Labels: cla-not-required, priority/high

#4781 Cherry-pick: modify color panel and add labels to imgs click problem
  src/ui_ng/lib/src/create-edit-label/create-edit-label.component.css.ts
  src/ui_ng/lib/src/create-edit-label/create-edit-label.component.html.ts
  src/ui_ng/lib/src/create-edit-label/create-edit-label.component.ts
  src/ui_ng/lib/src/tag/tag.component.html.ts
  src/ui_ng/lib/src/tag/tag.component.ts
  src/ui_ng/package.json
  src/ui_ng/src/app/config/config.component.ts
Labels: cla-not-required

#4780 promote version to v1.5.0
  VERSION
Labels: cla-not-required

#4768 Fix bug on search result ui
  src/ui_ng/src/app/shared/list-repository-ro/list-repository-ro.component.ts
Labels: cla-not-required

#4773 Fix the issue of intermittent restarting of job service
  src/jobservice/core/controller_test.go
  src/jobservice/pool/interface.go
  src/jobservice/pool/message_server.go
  src/jobservice/pool/redis_pool.go
  src/jobservice/runtime/bootstrap.go
Labels: area/job-services, cla-not-required, enhancement

#4783 Add url before repo name
  src/ui_ng/lib/package.json
  src/ui_ng/lib/pkg/package.json
  src/ui_ng/lib/src/repository-gridview/repository-gridview.component.ts
  src/ui_ng/package.json
Labels: cla-not-required

#4779 Change the order of power off machine and pvscan command in step 2
  docs/migrate_ova_guide.md
Labels: cla-not-required

#4789 Fix bugs infinity copy of reponame and auth
  src/ui_ng/lib/package.json
  src/ui_ng/lib/pkg/package.json
  src/ui_ng/lib/src/create-edit-rule/create-edit-rule.component.html.ts
  src/ui_ng/lib/src/repository-gridview/repository-gridview.component.html.ts
  src/ui_ng/lib/src/repository-gridview/repository-gridview.component.ts
  src/ui_ng/lib/src/utils.ts
  src/ui_ng/package.json
Labels: cla-not-required

#4800 Cherry pick: Fix bug #4791
  src/common/dao/repository.go
Labels: cla-not-required

#4792 Fix bug #4791
  src/common/dao/repository.go
Labels: cla-not-required

#4784 Add sort fun when filter labels in tag page #4617
  src/ui_ng/lib/src/create-edit-label/create-edit-label.component.ts
  src/ui_ng/lib/src/tag/tag-detail.component.css.ts
  src/ui_ng/lib/src/tag/tag-detail.component.html.ts
  src/ui_ng/lib/src/tag/tag.component.html.ts
  src/ui_ng/lib/src/tag/tag.component.ts
  src/ui_ng/lib/src/vulnerability-scanning/result-grid.component.spec.ts
  src/ui_ng/lib/src/vulnerability-scanning/result-grid.component.ts
  src/ui_ng/lib/src/vulnerability-scanning/scanning.css.ts
  src/ui_ng/lib/src/vulnerability-scanning/scanning.html.ts
  src/ui_ng/package.json
Labels: cla-not-required

#4798 Return 404 if user is not found
  docs/swagger.yaml
  src/ui/api/projectmember.go
  src/ui/api/projectmember_test.go
  src/ui/auth/authenticator.go
Labels: cla-not-required

#4799 Fix bugs that some place hardcode url addr
  src/ui_ng/lib/package.json
  src/ui_ng/lib/pkg/package.json
  src/ui_ng/lib/src/harbor-library.module.ts
  src/ui_ng/lib/src/service.config.ts
  src/ui_ng/lib/src/service/project.service.ts
  src/ui_ng/lib/src/service/tag.service.ts
  src/ui_ng/package.json
Labels: cla-not-required

#4802 Modify unique constraint of table harbor_label
  make/photon/db/registry.sql
  make/photon/db/registry_sqlite.sql
  src/common/dao/label_test.go
  tools/migration/db/db_meta.py
Labels: cla-not-required

#4794 Fix up keyword add label
  tests/resources/Harbor-Pages/Configuration.robot
Labels: cla-not-required

#4807 Modify unique constraint of table harbor_label
  make/photon/db/registry.sql
  make/photon/db/registry_sqlite.sql
  src/common/dao/label_test.go
  tools/migration/db/db_meta.py
Labels: cla-not-required

#4808 Merge pull request #4798 from stonezdj/release-1.5.0
  docs/swagger.yaml
  src/ui/api/projectmember.go
  src/ui/api/projectmember_test.go
  src/ui/auth/authenticator.go
Labels: cla-not-required

#4811 Modify unique constraint of table harbor_label in pgsql
  make/photon/db/postgresql/registry.sql
Labels: cla-not-required

#4813 Cherry pick add sort fun when filter label in tag page
  src/ui_ng/lib/src/create-edit-label/create-edit-label.component.css.ts
  src/ui_ng/lib/src/create-edit-label/create-edit-label.component.ts
  src/ui_ng/lib/src/tag/tag-detail.component.css.ts
  src/ui_ng/lib/src/tag/tag-detail.component.html.ts
  src/ui_ng/lib/src/tag/tag.component.html.ts
  src/ui_ng/lib/src/tag/tag.component.ts
  src/ui_ng/lib/src/vulnerability-scanning/result-grid.component.spec.ts
  src/ui_ng/lib/src/vulnerability-scanning/result-grid.component.ts
  src/ui_ng/lib/src/vulnerability-scanning/scanning.css.ts
  src/ui_ng/lib/src/vulnerability-scanning/scanning.html.ts
  src/ui_ng/package.json
Labels: cla-not-required

#4810 Cherry pick hardcode url and bug fix
  src/ui_ng/lib/package.json
  src/ui_ng/lib/pkg/package.json
  src/ui_ng/lib/src/create-edit-rule/create-edit-rule.component.html.ts
  src/ui_ng/lib/src/harbor-library.module.ts
  src/ui_ng/lib/src/repository-gridview/repository-gridview.component.html.ts
  src/ui_ng/lib/src/repository-gridview/repository-gridview.component.ts
  src/ui_ng/lib/src/service.config.ts
  src/ui_ng/lib/src/service/project.service.ts
  src/ui_ng/lib/src/service/tag.service.ts
  src/ui_ng/lib/src/utils.ts
  src/ui_ng/package.json
Labels: cla-not-required

#4815 Fix URL hardcode on replication service
  src/ui_ng/lib/package.json
  src/ui_ng/lib/pkg/package.json
  src/ui_ng/lib/src/harbor-library.module.ts
  src/ui_ng/lib/src/service.config.ts
  src/ui_ng/lib/src/service/replication.service.ts
  src/ui_ng/package.json
Labels: cla-not-required

#4820 Fix bug #4819: the scheduled rule can not be removed
  src/ui/api/replication_policy.go
Labels: cla-not-required

#4823 Cherry pick: Fix bug #4819: the scheduled rule can not be removed
  src/ui/api/replication_policy.go
Labels: cla-not-required

#4824 Collect log of redis
  make/docker-compose.tpl
  make/photon/redis/redis.conf
Labels: cla-not-required

#4825 Collect log of redis - cherrypick to 1.5 branch
  make/docker-compose.tpl
  make/photon/redis/redis.conf
Labels: cla-not-required
