Repository goharbor/harbor, pull requests merged in 2018-08, with the labels that each got.

#5438 Update README.md
  contrib/helm/harbor/README.md
Labels: cla-not-required

#5440 Add default value for creation time and update time trigger
  tools/migration/db/schema/registry_create_tables.pgsql
Labels: cla-not-required

#5435 Add scripts to verify Harbor DB migration
  tests/resources/Harbor-Pages/Verify.robot
  tests/resources/Util.robot
  tests/robot-cases/Group13-Upgrade/Verifydata.robot
  tests/robot-cases/Group13-Upgrade/data.json
  tests/robot-cases/Group13-Upgrade/prepare.py
  tests/robot-cases/Group13-Upgrade/sign_image.sh
  tests/robot-cases/Group13-Upgrade/testdata.json
  tests/robot-cases/Group13-Upgrade/testupgrade.py
  tests/robot-cases/Group13-Upgrade/verify.robot
Labels: cla-not-required

#5441 Add ldap admin DN
  src/ui_ng/src/app/config/auth/config-auth.component.html
  src/ui_ng/src/app/config/auth/config-auth.component.scss
  src/ui_ng/src/i18n/lang/en-us-lang.json
  src/ui_ng/src/i18n/lang/es-es-lang.json
  src/ui_ng/src/i18n/lang/fr-fr-lang.json
  src/ui_ng/src/i18n/lang/zh-cn-lang.json
  src/ui_ng/src/styles.css
Labels: cla-not-required, target/1.6.0

#5442 Remove the rewrite ingress rule
  contrib/helm/harbor/templates/ingress/ingress.yaml
Labels: cla-not-required

#5398 Add chartmuseum to Harbor chart
  contrib/helm/harbor/templates/adminserver/adminserver-cm.yaml
  contrib/helm/harbor/templates/chartmuseum/chartmuseum-cm.yaml
  contrib/helm/harbor/templates/chartmuseum/chartmuseum-secret.yaml
  contrib/helm/harbor/templates/chartmuseum/chartmuseum-ss.yaml
  contrib/helm/harbor/templates/chartmuseum/chartmuseum-svc.yaml
  contrib/helm/harbor/templates/ui/ui-dpl.yaml
  contrib/helm/harbor/values.yaml
Labels: cla-not-required

#5513 Hide the helmcharts tab when chart museum is not installed.
  src/ui_ng/lib/src/service/interface.ts
  src/ui_ng/src/app/app-config.ts
  src/ui_ng/src/app/project/project-detail/project-detail.component.html
  src/ui_ng/src/app/project/project-detail/project-detail.component.ts
Labels: kind/bug, target/1.6.0

#5402 Add harbor API test
  Makefile
  docs/swagger.yaml
  tests/apitests/python/test_assign_role_to_ldap_group.py
  tests/apitests/python/test_ldap_admin_role.py
  tests/apitests/python/test_user_group.py
  tests/apitests/python/testutils.py
  tests/ldap_test.ldif
  tests/resources/APITest-Util.robot
  tests/resources/Harbor-Util.robot
  tests/resources/Util.robot
  tests/robot-cases/Group0-BAT/BAT.robot
Labels: cla-not-required

#5281 Add testcase for define harbor admin by LDAP group DN
  tests/testcases/Group3-RBAC/3-08-LDAP-define-harbor-admin-by-dn.md
Labels: cla-not-required

#5549 Fix chart ui related issue
  src/ui_ng/lib/src/helm-chart/chart-detail/chart-detail-summary.component.html
  src/ui_ng/lib/src/helm-chart/chart-detail/chart-detail-summary.component.scss
  src/ui_ng/lib/src/helm-chart/chart-detail/chart-detail-summary.component.ts
  src/ui_ng/lib/src/helm-chart/helm-chart.component.ts
  src/ui_ng/src/app/project/member/add-group/add-group.component.html
  src/ui_ng/src/i18n/lang/en-us-lang.json
  src/ui_ng/src/i18n/lang/es-es-lang.json
  src/ui_ng/src/i18n/lang/fr-fr-lang.json
  src/ui_ng/src/i18n/lang/zh-cn-lang.json
Labels: target/1.6.0

#5508 Add mention of CNCF in README
  README.md
Labels: area/CNCF

#5556 UI changed after harbor moved to CNCF
  src/ui_ng/src/app/base/navigator/navigator.component.html
  src/ui_ng/src/app/shared/about-dialog/about-dialog.component.html
  src/ui_ng/src/app/shared/about-dialog/about-dialog.component.scss
  src/ui_ng/src/i18n/lang/en-us-lang.json
  src/ui_ng/src/i18n/lang/es-es-lang.json
  src/ui_ng/src/i18n/lang/fr-fr-lang.json
  src/ui_ng/src/i18n/lang/zh-cn-lang.json
  src/ui_ng/src/images/harbor-black-logo.png
Labels: 1.6.0-defer

#5648 Fix "gob: name not registered for interface" error
  src/ui/main.go
Labels: target/1.6.0

#5650 Cherry-pick the replication label filter E2E test cases to branch 1.6.0
  Makefile
  tests/apitests/python/library/Harbor.py
  tests/apitests/python/library/base.py
  tests/apitests/python/library/label.py
  tests/apitests/python/library/project.py
  tests/apitests/python/library/registry.py
  tests/apitests/python/library/replication.py
  tests/apitests/python/library/repository.py
  tests/resources/Docker-Util.robot
  tests/robot-cases/Group11-Nightly/Replication.robot
Labels: target/1.6.0

#5661 [Cherry-pick]Fix "gob: name not registered for interface" error
  src/ui/main.go
Labels: target/1.6.0

#5669 Add VOLUME definition in Dockerfile of chart museum
  make/photon/chartserver/Dockerfile
Labels: target/1.6.0

#5672 [Cherry-pick]Add VOLUME definition in Dockerfile of chart museum
  make/photon/chartserver/Dockerfile
Labels: target/1.6.0
