Repository goharbor/harbor, pull requests merged in 2019-10, with the labels that each got.

#9329 feat(replication): support for jfrog artifactory docker image replica…
  src/jobservice/job/impl/replication/replication.go
  src/replication/adapter/jfrog/adapter.go
  src/replication/adapter/jfrog/adapter_test.go
  src/replication/adapter/jfrog/types.go
  src/replication/model/registry.go
  src/replication/replication.go
Labels: target/1.10.0

#8556 Feat/image replication adapter for quay.io
  src/common/utils/registry/auth/apikey.go
  src/common/utils/registry/auth/apikey_test.go
  src/jobservice/job/impl/replication/replication.go
  src/replication/adapter/quayio/adapter.go
  src/replication/adapter/quayio/adapter_test.go
  src/replication/adapter/quayio/types.go
  src/replication/model/registry.go
  src/replication/replication.go
Labels: area/replication, target/1.10.0

#9343 Check the existence of project before the next action
  src/core/middlewares/util/util.go
  src/core/middlewares/util/util_test.go
Labels: target/1.10.0

#9189 Use external_url if exists on Add Repo Command chart details page
  src/portal/src/app/project/helm-chart/helm-chart-detail/chart-detail/chart-detail.component.ts
Labels: area/ui, target/1.10.0

#9419 [cherry-pick]ignore the duplicate error when to insert project_blobs on quota syncing
  src/core/api/quota/registry/registry.go
Labels: target/1.9.2

#9393 add immutable match
  src/core/api/immutabletagrule.go
  src/pkg/immutabletag/controller.go
  src/pkg/immutabletag/match/matcher.go
  src/pkg/immutabletag/match/rule/match.go
  src/pkg/immutabletag/match/rule/match_test.go
Labels: target/1.10.0

#8596 nginx: Remove TLSv1.1 support
  make/photon/prepare/templates/nginx/nginx.https.conf.jinja
Labels: candidate/1.10, doc-impact, kind/break-change

#9033 Added Gitlab Registry Support
  src/jobservice/job/impl/replication/replication.go
  src/replication/adapter/gitlab/adapter.go
  src/replication/adapter/gitlab/client.go
  src/replication/adapter/gitlab/client_test.go
  src/replication/adapter/gitlab/types.go
  src/replication/model/registry.go
  src/replication/replication.go
Labels: area/replication, target/1.10.0

#9273 Fix typos in core package
  src/core/api/chart_label.go
  src/core/api/chart_repository.go
  src/core/api/label.go
  src/core/api/quota/migrator.go
  src/core/api/repository.go
  src/core/api/systeminfo.go
  src/core/notifier/notification_handler.go
  src/core/promgr/metamgr/metamgr.go
  src/core/promgr/promgr.go
  src/core/service/notifications/admin/handler.go
  src/core/service/notifications/jobs/handler.go
  src/core/service/token/token.go
  src/core/utils/utils.go
Labels: target/1.10.0

#9415 do changes to let the vul policy check compatible with new framework
  make/migrations/postgresql/0015_1.10.0_schema.up.sql
  src/common/dao/clair.go
  src/common/dao/clair/base.go
  src/common/dao/dao_test.go
  src/common/dao/scan_job.go
  src/common/models/base.go
  src/common/models/scan_job.go
  src/common/models/sev.go
  src/common/utils/clair/client.go
  src/common/utils/clair/client_test.go
  src/common/utils/clair/test/notification.json
  src/common/utils/clair/test/ns.json
  src/common/utils/clair/test/server.go
  src/common/utils/clair/test/total-12.json
  src/common/utils/clair/utils.go
  src/common/utils/clair/utils_test.go
  src/core/api/config.go
  src/core/api/models/admin_job.go
  src/core/api/scan_test.go
  src/core/api/scanners_test.go
  src/core/api/systeminfo.go
  src/core/config/config.go
  src/core/config/config_test.go
  src/core/middlewares/util/util.go
  src/core/middlewares/util/util_test.go
  src/core/middlewares/vulnerable/handler.go
  src/core/notifier/event/event.go
  src/core/notifier/handler/notification/chart_handler_test.go
  src/core/notifier/handler/notification/processor.go
  src/core/notifier/handler/notification/scan_image_handler.go
  src/core/notifier/handler/notification/scan_image_handler_test.go
  src/core/notifier/model/event.go
  src/core/service/notifications/jobs/handler.go
  src/core/service/notifications/registry/handler.go
  src/core/utils/job.go
  src/core/utils/job_test.go
  src/jobservice/job/impl/scan/clair_job.go
  src/pkg/scan/api/scan/base_controller.go
  src/pkg/scan/api/scan/base_controller_test.go
  src/pkg/scan/api/scan/controller.go
  src/pkg/scan/api/scanner/base_controller.go
  src/pkg/scan/api/scanner/base_controller_test.go
  src/pkg/scan/api/scanner/controller.go
  src/pkg/scan/job.go
  src/pkg/scan/report/summary.go
  src/pkg/scan/report/summary_test.go
  src/pkg/scan/vuln.go
  src/pkg/scan/vuln/severity.go
  src/pkg/scan/vuln/summary.go
  src/pkg/scan/vuln_test.go
Labels: area/interrogation-service, target/1.10.0

#9497 Disable self registration by default (cherry-pick)
  src/common/config/metadata/metadatalist.go
Labels: doc-impact, kind/break-change

#9515 Modify the words of setting cli secret
  tests/resources/Harbor-Pages/OIDC_Auth.robot
Labels: target/1.10.0

#9522 Modify the permission when add Limited Guest
  src/portal/lib/src/create-edit-rule/create-edit-rule.component.ts
  src/portal/lib/src/replication/replication.component.html
  src/portal/lib/src/replication/replication.component.scss
  src/portal/lib/src/repository/repository.component.spec.ts
  src/portal/lib/src/tag/tag.component.spec.ts
  src/portal/lib/src/tag/tag.component.ts
Labels: target/1.10.0

#9478 Populate public metadata into the event
  src/core/api/chart_repository.go
  src/core/service/notifications/registry/handler.go
Labels: area/replication, target/1.10.0

#9479 [Cherry-pick]Populate public metadata into the event
  src/core/api/chart_repository.go
  src/core/service/notifications/registry/handler.go
Labels: area/replication, target/1.9.2

#9527 Cherry-pick the way of replication show label
  src/portal/lib/src/create-edit-rule/create-edit-rule.component.html
Labels: target/1.9.2

#9534 Adds Anchore logo in ADOPTERS.md
  ADOPTERS.md
  docs/img/anchore_logo.png
Labels: kind/process

#9520 Remove the health checker for Clair in health check API
  src/common/const.go
  src/core/api/health.go
  src/core/config/config.go
Labels: target/1.10.0

#9528 improve the scan controlling
  src/core/api/repository.go
  src/core/api/scan_all.go
  src/core/api/scan_all_test.go
  src/core/api/scan_test.go
  src/core/api/scanners_test.go
  src/core/main.go
  src/core/notifier/event/event.go
  src/core/notifier/handler/notification/scan_image_handler.go
  src/core/notifier/handler/notification/scan_image_handler_test.go
  src/core/service/notifications/jobs/handler.go
  src/core/service/notifications/registry/handler.go
  src/pkg/art/basic_controller.go
  src/pkg/art/basic_controller_test.go
  src/pkg/art/basic_manager.go
  src/pkg/art/basic_manager_test.go
  src/pkg/art/controller.go
  src/pkg/art/manager.go
  src/pkg/scan/api/scan/base_controller.go
  src/pkg/scan/api/scan/base_controller_test.go
  src/pkg/scan/api/scan/controller.go
  src/pkg/scan/api/scanner/base_controller.go
  src/pkg/scan/api/scanner/controller.go
  src/pkg/scan/dao/scan/report.go
  src/pkg/scan/dao/scanner/model.go
  src/pkg/scan/event/init.go
  src/pkg/scan/event/notification.go
  src/pkg/scan/job.go
  src/pkg/scan/report/base_manager.go
  src/pkg/scan/report/base_manager_test.go
  src/pkg/scan/report/manager.go
  src/pkg/scan/report/summary.go
  src/pkg/scan/rest/v1/models.go
  src/pkg/scan/vuln/summary.go
Labels: area/interrogation-service

#8174 refact replication info to support special endpoints and credential
  src/core/api/registry.go
  src/core/api/replication_adapter.go
  src/core/api/replication_adapter_test.go
  src/core/router.go
  src/replication/adapter/adapter.go
  src/replication/adapter/adapter_test.go
  src/replication/adapter/aliacr/adapter.go
  src/replication/adapter/aliacr/adapter_test.go
  src/replication/adapter/awsecr/adapter.go
  src/replication/adapter/awsecr/adapter_test.go
  src/replication/adapter/azurecr/adapter.go
  src/replication/adapter/dockerhub/adapter.go
  src/replication/adapter/dockerhub/adapter_test.go
  src/replication/adapter/gitlab/adapter.go
  src/replication/adapter/googlegcr/adapter.go
  src/replication/adapter/googlegcr/adapter_test.go
  src/replication/adapter/harbor/adapter.go
  src/replication/adapter/helmhub/adapter.go
  src/replication/adapter/huawei/huawei_adapter.go
  src/replication/adapter/huawei/huawei_adapter_test.go
  src/replication/adapter/huawei/image_registry_test.go
  src/replication/adapter/jfrog/adapter.go
  src/replication/adapter/jfrog/adapter_test.go
  src/replication/adapter/native/adapter.go
  src/replication/adapter/quayio/adapter.go
  src/replication/adapter/quayio/adapter_test.go
  src/replication/model/registry.go
  src/replication/operation/controller_test.go
  src/replication/operation/flow/stage.go
  src/replication/operation/flow/stage_test.go
  src/replication/registry/manager.go
  src/replication/transfer/chart/transfer.go
  src/replication/transfer/image/transfer.go
Labels: area/replication, enhancement, target/1.10.0

#9551 add gpg sign
  .drone.yml
  tests/integration.sh
Labels: doc-impact

#9571 support using internal registry addr to perform scan
  make/migrations/postgresql/0015_1.10.0_schema.up.sql
  src/core/api/scanners.go
  src/core/api/scanners_test.go
  src/pkg/scan/api/scan/base_controller.go
  src/pkg/scan/api/scanner/base_controller.go
  src/pkg/scan/dao/scanner/model.go
Labels: area/interrogation-service, target/1.10.0

#9524 Modiy the way of replication show label filter
  src/portal/lib/src/create-edit-rule/create-edit-rule.component.html
Labels: target/1.10.0

#9587 Add webhook nightly case
  src/portal/lib/src/confirmation-dialog/confirmation-dialog.component.html
  src/portal/src/app/project/webhook/add-webhook-form/add-webhook-form.component.html
  src/portal/src/app/project/webhook/webhook.component.html
  src/portal/src/app/shared/confirmation-dialog/confirmation-dialog.component.html
  tests/resources/Harbor-Pages/Project-Webhooks.robot
  tests/resources/Harbor-Pages/Project-Webhooks_Elements.robot
  tests/resources/Util.robot
  tests/robot-cases/Group1-Nightly/Common.robot
Labels: target/1.10.0

#9559 Improve Immutable tag UI
  src/portal/src/app/project/immutable-tag/add-rule/add-rule.component.html
  src/portal/src/app/project/immutable-tag/add-rule/add-rule.component.ts
  src/portal/src/app/project/immutable-tag/immutable-tag.component.html
  src/portal/src/app/project/immutable-tag/immutable-tag.component.scss
  src/portal/src/app/project/immutable-tag/immutable-tag.component.ts
  src/portal/src/app/project/immutable-tag/immutable-tag.service.ts
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
Labels: target/1.10.0

#9599 Fix quota sync crash on getting the unknown mainfest
  src/core/api/internal.go
  src/core/api/quota/migrator.go
  src/core/api/quota/registry/registry.go
Labels: target/1.10.0

#9618 permission grant for scanner related actions are not correctly
  src/common/rbac/const.go
  src/common/rbac/project/util.go
  src/common/rbac/project/visitor_role.go
  src/core/api/harborapi_test.go
  src/core/api/pro_scanner.go
  src/core/api/pro_scanner_test.go
  src/core/router.go
  src/pkg/scan/api/scanner/base_controller.go
  src/pkg/scan/dao/scanner/model.go
Labels: area/access-control, area/interrogation-service, target/1.10.0

#8610 change adapterInfo from by hardcode to by getting from backend API
  src/portal/lib/src/create-edit-endpoint/create-edit-endpoint.component.html
  src/portal/lib/src/create-edit-endpoint/create-edit-endpoint.component.scss
  src/portal/lib/src/create-edit-endpoint/create-edit-endpoint.component.spec.ts
  src/portal/lib/src/create-edit-endpoint/create-edit-endpoint.component.ts
  src/portal/lib/src/endpoint/endpoint.component.spec.ts
Labels: area/replication, target/1.10.0

#9634 fix bug found in the pluggable scanner
  src/jobservice/job/impl/scan/all.go
  src/pkg/scan/event/init.go
Labels: area/interrogation-service, target/1.10.0

#9637 fix the bug of returning errors when nothing is updated
  src/core/service/notifications/jobs/handler.go
  src/pkg/scan/dao/scan/report.go
  src/pkg/scan/dao/scan/report_test.go
Labels: area/interrogation-service, target/1.10.0

#9636 Make the username required when searching user
  docs/swagger.yaml
  src/core/api/user.go
Labels: target/1.8.5

#9656 [Cherry-pick-1.8]Populate public metadata into the event
  src/core/api/chart_repository.go
  src/core/service/notifications/registry/handler.go
Labels: target/1.8.5

#9682 [cherry-pick]add a switcher for quota sync on core launch
  make/photon/prepare/templates/core/env.jinja
  src/core/main.go
Labels: target/1.9.2
