Repository goharbor/harbor, pull requests merged in 2019-09, with the labels that each got.

#7923 [Cherry pick]Return account id when to issue a robot
  src/common/models/robot.go
  src/core/api/robot.go
Labels: target/1.8.3

#8837 Disable redis and db containers if external db enabled
  make/photon/prepare/templates/docker_compose/docker-compose.yml.jinja
  make/photon/prepare/utils/configs.py
  make/photon/prepare/utils/docker_compose.py
  make/photon/prepare/utils/jinja.py
Labels: candidate/1.9.0

#8890 fix UI bug for tag-retention and project-quota
  src/portal/lib/src/config/project-quotas/project-quotas.component.html
  src/portal/lib/src/config/project-quotas/project-quotas.component.scss
  src/portal/src/app/project/tag-retention/add-rule/add-rule.component.ts
  src/portal/src/app/project/tag-retention/tag-retention.component.html
  src/portal/src/app/project/tag-retention/tag-retention.component.ts
  src/portal/src/app/project/tag-retention/tag-retention.service.ts
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
Labels: target/1.9.0

#8907 Handle error on OIDC callback
  src/core/controllers/oidc.go
Labels: target/1.8.3, target/1.9.0

#8843 fix(chart,quota): fix path regexp of chart creation and deletion
  src/core/middlewares/chart/builder.go
  src/core/middlewares/chart/handler_test.go
Labels: target/1.9.0

#8891 Fix: prepare permission issue
  make/photon/prepare/g.py
  make/photon/prepare/utils/cert.py
  make/photon/prepare/utils/chart.py
  make/photon/prepare/utils/core.py
  make/photon/prepare/utils/db.py
  make/photon/prepare/utils/misc.py
  make/photon/prepare/utils/registry.py
Labels: target/1.9.0

#8917 Disallow creating an admin user when registration
  src/core/api/user.go
  src/core/api/user_test.go
Labels: target/1.8.3, target/1.9.0

#8910 fix(quota): correct size quota for image with foreign layers
  src/common/dao/blob.go
  src/common/dao/blob_test.go
  src/common/models/blob.go
  src/core/api/quota/registry/registry.go
  src/core/middlewares/sizequota/builder.go
  src/core/middlewares/sizequota/handler_test.go
  src/core/middlewares/sizequota/util.go
  src/core/middlewares/util/util.go
Labels: target/1.9.0

#8912 Add no-cache to index.html
  make/photon/portal/nginx.conf
Labels: target/1.9.0

#8948 The default item list should be empty list,not null
  src/pkg/scan/whitelist/manager.go
Labels: target/1.9.0

#8950 Disallow creating an admin user when registration -- cherry pick to 1.8
  src/core/api/user.go
  src/core/api/user_test.go
Labels: target/1.8.3

#8949 Handle error on OIDC callback -- cherry-pick to 1.8 branch
  src/core/controllers/oidc.go
Labels: target/1.8.3

#8953 The default item list should be empty list,not null - cherrypick to 1.9 branch
  src/pkg/scan/whitelist/manager.go
Labels: target/1.9.0

#8936 add swagger for tag retention
  docs/swagger.yaml
  src/core/api/retention.go
  src/pkg/retention/controller_test.go
  src/pkg/retention/manager.go
  src/pkg/retention/manager_test.go
  src/pkg/retention/models.go
  src/pkg/retention/policy/models.go
  src/pkg/retention/policy/rule/models.go
  src/portal/src/app/project/tag-retention/tag-retention.component.html
  src/portal/src/app/project/tag-retention/tag-retention.component.ts
  tests/apitests/python/library/base.py
  tests/apitests/python/library/docker_api.py
  tests/apitests/python/library/repository.py
  tests/apitests/python/library/retention.py
  tests/apitests/python/test_retention.py
  tests/apitests/python/testutils.py
  tests/robot-cases/Group0-BAT/API_DB.robot
Labels: area/tag-retention, target/1.9.0

#8927 Add logic to read clair and notary config
  make/photon/prepare/main.py
  make/photon/prepare/utils/configs.py
Labels: target/1.9.0

#9021 Check the status behind error when trying to update the scan schedule
  src/common/job/client.go
  src/common/job/client_test.go
  src/core/api/admin_job.go
  src/replication/operation/controller.go
  src/replication/operation/controller_test.go
Labels: target/1.9.0

#9025 [Cherry-pick 1.8.3]Check the status behind error when trying to update the scan schedule
  src/common/job/client.go
  src/common/job/client_test.go
  src/core/api/admin_job.go
  src/replication/operation/controller.go
  src/replication/operation/controller_test.go
Labels: target/1.8.3

#9022 [Cherry-pick 1.9]Check the status behind error when trying to update the scan schedule
  src/common/job/client.go
  src/common/job/client_test.go
  src/core/api/admin_job.go
  src/replication/operation/controller.go
  src/replication/operation/controller_test.go
Labels: target/1.9.0

#9039 change button text from "ADD SYSTEM" to "COPY FROM SYSTEM"
  src/portal/lib/src/project-policy-config/project-policy-config.component.html
  src/portal/lib/src/project-policy-config/project-policy-config.component.scss
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
Labels: target/1.9.0

#9050 Add the port 8080 to the default URL of portal to avoid the health check API failure
  src/common/const.go
Labels: target/1.9.0

#9051 [Cherry-pick]Add the port 8080 to the default URL of portal to avoid the health check API failure
  src/common/const.go
Labels: target/1.9.0

#9045 Updated upgrade and migration guide for 1.9
  docs/migration_guide.md
Labels: target/1.9.0

#8994 Documenting new registry providers as replication endpoints
  docs/img/replication-endpoint1.png
  docs/img/replication-endpoint2.png
  docs/user_guide.md
Labels: target/1.9.0

#9053 Quota e2e case
  docs/swagger.yaml
  tests/apitests/python/library/docker_api.py
  tests/apitests/python/library/system.py
  tests/apitests/python/test_project_quota.py
  tests/robot-cases/Group0-BAT/API_DB.robot
Labels: target/1.9.0

#9097 Promote version to v1.8.3
  VERSION
Labels: target/1.8.3

#9004 Documented that Robo accounts can push/pull helm charts
  docs/img/robotaccount/add_robot_account_2.png
  docs/user_guide.md
Labels: target/1.9.0

#9005 Documented how to configure Syslog and DB connection pool in harbor.yml
  docs/installation_guide.md
Labels: target/1.9.0

#8869 Adding docs about webhooks, tag retention, CVE whitelists and project quotas
  docs/img/cve-whitelist1.png
  docs/img/cve-whitelist2.png
  docs/img/cve-whitelist3.png
  docs/img/cve-whitelist4.png
  docs/img/cve-whitelist5.png
  docs/img/cve-whitelist6.png
  docs/img/project-quota1.png
  docs/img/project-quota2.png
  docs/img/project-quota3.png
  docs/img/project-quota4.png
  docs/img/project-quota5.png
  docs/img/tag-retention1.png
  docs/img/tag-retention2.png
  docs/img/tag-retention3.png
  docs/img/tag-retention4.png
  docs/img/tag-retention5.png
  docs/img/webhooks1.png
  docs/img/webhooks2.png
  docs/img/webhooks3.png
  docs/img/webhooks4.png
  docs/user_guide.md
Labels: target/1.9.0

#9104 Cherry pick upgrade doc updates into 1.9 branch
  docs/migration_guide.md
Labels: target/1.9.0

#9105 Cherry pick syslog doc updates into 1.9 branch
  docs/installation_guide.md
Labels: target/1.9.0

#9109 Cherry picking docs about webhooks, tag retention, CVE whitelists and project into 1.9 branch
  docs/img/cve-whitelist1.png
  docs/img/cve-whitelist2.png
  docs/img/cve-whitelist3.png
  docs/img/cve-whitelist4.png
  docs/img/cve-whitelist5.png
  docs/img/cve-whitelist6.png
  docs/img/project-quota1.png
  docs/img/project-quota2.png
  docs/img/project-quota3.png
  docs/img/project-quota4.png
  docs/img/project-quota5.png
  docs/img/tag-retention1.png
  docs/img/tag-retention2.png
  docs/img/tag-retention3.png
  docs/img/tag-retention4.png
  docs/img/tag-retention5.png
  docs/img/webhooks1.png
  docs/img/webhooks2.png
  docs/img/webhooks3.png
  docs/img/webhooks4.png
  docs/user_guide.md
Labels: target/1.9.0

#9134 support pluggable scanner
  make/migrations/postgresql/0011_1.10.0_schema.up.sql
  src/core/api/harborapi_test.go
  src/core/api/plug_scanners.go
  src/core/api/plug_scanners_test.go
  src/core/router.go
  src/go.mod
  src/go.sum
  src/pkg/q/query.go
  src/pkg/scan/scanner/api/controller.go
  src/pkg/scan/scanner/api/controller_test.go
  src/pkg/scan/scanner/api/registration.go
  src/pkg/scan/scanner/api/scan.go
  src/pkg/scan/scanner/dao/scan/report.go
  src/pkg/scan/scanner/dao/scanner/model.go
  src/pkg/scan/scanner/dao/scanner/model_test.go
  src/pkg/scan/scanner/dao/scanner/registration.go
  src/pkg/scan/scanner/dao/scanner/registration_test.go
  src/pkg/scan/scanner/manager.go
  src/pkg/scan/scanner/manager_test.go
  src/pkg/scan/scanner/scan/controller.go
  src/pkg/scan/scanner/scan/models.go
  src/vendor/github.com/google/uuid/.travis.yml
  src/vendor/github.com/google/uuid/CONTRIBUTING.md
  src/vendor/github.com/google/uuid/CONTRIBUTORS
  src/vendor/github.com/google/uuid/LICENSE
  src/vendor/github.com/google/uuid/README.md
  src/vendor/github.com/google/uuid/dce.go
  src/vendor/github.com/google/uuid/doc.go
  src/vendor/github.com/google/uuid/go.mod
  src/vendor/github.com/google/uuid/hash.go
  src/vendor/github.com/google/uuid/marshal.go
  src/vendor/github.com/google/uuid/node.go
  src/vendor/github.com/google/uuid/node_js.go
  src/vendor/github.com/google/uuid/node_net.go
  src/vendor/github.com/google/uuid/sql.go
  src/vendor/github.com/google/uuid/time.go
  src/vendor/github.com/google/uuid/util.go
  src/vendor/github.com/google/uuid/uuid.go
  src/vendor/github.com/google/uuid/version1.go
  src/vendor/github.com/google/uuid/version4.go
  src/vendor/modules.txt
Labels: area/API, area/interrogation-service

#9154 [stage2]support pluggable scanner
  make/migrations/postgresql/0011_1.10.0_schema.up.sql
  src/core/api/harborapi_test.go
  src/core/api/scanners.go
  src/core/api/scanners_test.go
  src/core/router.go
  src/pkg/q/query.go
  src/pkg/scan/api/scan/base_controller.go
  src/pkg/scan/api/scan/controller.go
  src/pkg/scan/api/scanner/base_controller.go
  src/pkg/scan/api/scanner/controller.go
  src/pkg/scan/api/scanner/controller_test.go
  src/pkg/scan/dao/scan/model.go
  src/pkg/scan/dao/scan/report.go
  src/pkg/scan/dao/scan/report_test.go
  src/pkg/scan/dao/scanner/model.go
  src/pkg/scan/dao/scanner/model_test.go
  src/pkg/scan/dao/scanner/registration.go
  src/pkg/scan/dao/scanner/registration_test.go
  src/pkg/scan/job.go
  src/pkg/scan/job_test.go
  src/pkg/scan/report/base_manager.go
  src/pkg/scan/report/base_manager_test.go
  src/pkg/scan/report/manager.go
  src/pkg/scan/report/supported_mime_test.go
  src/pkg/scan/report/supported_mimes.go
  src/pkg/scan/rest/auth/api_key_auth.go
  src/pkg/scan/rest/auth/auth.go
  src/pkg/scan/rest/auth/basic_auth.go
  src/pkg/scan/rest/auth/bearer_auth.go
  src/pkg/scan/rest/auth/no_auth.go
  src/pkg/scan/rest/v1/client.go
  src/pkg/scan/rest/v1/client_pool.go
  src/pkg/scan/rest/v1/client_pool_test.go
  src/pkg/scan/rest/v1/client_test.go
  src/pkg/scan/rest/v1/models.go
  src/pkg/scan/rest/v1/spec.go
  src/pkg/scan/scanner/manager.go
  src/pkg/scan/scanner/manager_test.go
  src/pkg/scan/scanner/scan/controller.go
  src/pkg/scan/scanner/scan/models.go
  src/pkg/scan/vuln/report.go
  src/pkg/scan/vuln/severity.go
Labels: area/API, area/interrogation-service

#9235 [cherry-pick]Add quota switcher swagger doc
  docs/swagger.yaml
Labels: target/1.9.1

#9221 patch registry fix of issue 2553
  Makefile
  make/photon/registry/builder
Labels: target/1.9.1

#9286 promote version to v1.9.1
  VERSION
Labels: target/1.9.1
