Repository goharbor/harbor, pull requests merged in 2019-05, with the labels that each got.

#7619 Fix a few bugs of replication
  make/migrations/postgresql/0004_1.8.0_schema.up.sql
  src/core/api/replication_policy.go
  src/replication/adapter/harbor/adapter.go
  src/replication/adapter/harbor/adapter_test.go
  src/replication/adapter/harbor/chart_registry.go
  src/replication/adapter/harbor/image_registry.go
  src/replication/dao/execution.go
  src/replication/model/policy.go
Labels: area/replication, target/1.8.0

#7602 Replicate just one image if the media type is manifest list
  src/replication/transfer/image/transfer.go
Labels: area/replication, target/1.8.0

#7660 Iterate all paginations when listing projects and repositories
  src/common/http/client.go
  src/replication/adapter/harbor/adapter.go
  src/replication/adapter/harbor/image_registry.go
Labels: area/replication, target/1.8.0

#7664 Rename the adapter name of docker registry
  src/replication/adapter/native/adapter.go
  src/replication/adapter/native/adapter_test.go
  src/replication/adapter/native/image_registry_test.go
  src/replication/model/registry.go
Labels: area/replication, target/1.8.0

#7667 Add more unit test cases for docker hub adapter
  src/replication/adapter/dockerhub/adapter_test.go
  src/replication/adapter/dockerhub/client.go
Labels: area/replication, target/1.8.0

#7585 add get jobs API to provide powerful job stats management
  src/jobservice/api/handler.go
  src/jobservice/api/handler_test.go
  src/jobservice/api/router.go
  src/jobservice/common/query/q.go
  src/jobservice/common/query/q_test.go
  src/jobservice/common/rds/keys.go
  src/jobservice/core/controller.go
  src/jobservice/core/controller_test.go
  src/jobservice/core/interface.go
  src/jobservice/errs/errors.go
  src/jobservice/job/tracker.go
  src/jobservice/job/tracker_test.go
  src/jobservice/main.go
  src/jobservice/mgt/manager.go
  src/jobservice/mgt/manager_test.go
  src/jobservice/runtime/bootstrap.go
  src/jobservice/worker/cworker/c_worker.go
  src/jobservice/worker/cworker/c_worker_test.go
  src/jobservice/worker/interface.go
  tests/robot-cases/Group0-BAT/API_DB.robot
Labels: area/job-services

#7721 Fix #7579: cannot stop the execution during the initialization stage
  src/replication/operation/controller.go
  src/replication/operation/flow/copy.go
  src/replication/operation/flow/stage.go
  src/replication/operation/flow/stage_test.go
Labels: area/replication, target/1.8.0

#7718 Fix issue: replication cannot work when Harbor is deployed on Kubernetes whose hairpin mode is disabled
  src/replication/adapter/harbor/adapter.go
  src/replication/adapter/harbor/chart_registry.go
  src/replication/adapter/harbor/image_registry.go
  src/replication/transfer/image/transfer.go
Labels: area/replication, target/1.8.0

#7739 Fixes #7693, the filters of replication policy is lost after upgrade
  make/migrations/postgresql/0004_1.8.0_schema.up.sql
  src/replication/policy/manager/manager.go
  src/replication/policy/manager/manager_test.go
Labels: area/replication, target/1.8.0

#7740 Rename the adapter name of huawei to huawei-SWR
  src/replication/adapter/huawei/huawei_adapter.go
  src/replication/model/registry.go
Labels: area/replication, target/1.8.0

#7738 Require output path for harbor.cfg->harbor.yml migration
  tools/migration/cfg/run.py
  tools/migration/migrator.py
Labels: priority/high, target/1.8.0

#7479 Add document for config user settings
  docs/configure_user_settings.md
  docs/installation_guide.md
Labels: target/1.8.0

#7612 Fix tls related issues
  make/harbor.yml
  make/photon/prepare/templates/docker_compose/docker-compose.yml.jinja
  make/photon/prepare/utils/cert.py
  make/photon/prepare/utils/nginx.py
  make/prepare
  tests/hostcfg.sh
Labels: priority/high

#7758 Fixes bug in replication
  src/replication/adapter/harbor/chart_registry.go
  src/replication/adapter/harbor/image_registry.go
Labels: target/1.8.0

#7760 Fix public url shoud not display port is it's default value
  make/photon/prepare/utils/configs.py
Labels: priority/high

#7761 Document how to use the external database in installation guide
  docs/installation_guide.md
  make/harbor.yml
Labels: target/1.8.0

#7746 Update the replication part in user guide
  docs/img/create_rule.png
  docs/img/delete_rule.png
  docs/img/list_stop_executions.png
  docs/img/list_stop_jobs.png
  docs/img/list_tasks.png
  docs/img/manage_endpoint.png
  docs/img/manage_registry.png
  docs/img/manage_replication.png
  docs/img/start_replicate.png
  docs/user_guide.md
Labels: area/replication, target/1.8.0

#7768 Fix_cron schedule bug when call api ' get/schedule ' error
  src/portal/lib/src/config/gc/gc.component.ts
  src/portal/lib/src/config/vulnerability/vulnerability-config.component.ts
  src/portal/lib/src/cron-schedule/cron-schedule.component.ts
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
Labels: target/1.8.0

#7769 Update the replication part in user guide (#7746)
  docs/img/create_rule.png
  docs/img/delete_rule.png
  docs/img/list_stop_executions.png
  docs/img/list_stop_jobs.png
  docs/img/list_tasks.png
  docs/img/manage_endpoint.png
  docs/img/manage_registry.png
  docs/img/manage_replication.png
  docs/img/start_replicate.png
  docs/user_guide.md
Labels: target/1.8.0

#7783 Fix issue caused by notary default_alias
  make/photon/prepare/templates/notary/signer-config.postgres.json.jinja
Labels: target/1.8.0

#7785 Fix issue caused by notary default_alias
  make/photon/prepare/templates/notary/signer-config.postgres.json.jinja
Labels: target/1.8.0

#7771 Typo in registry config - cherrypick to 1.8
  make/photon/prepare/templates/registry/config.yml.jinja
Labels: target/1.8.0

#7770 Typo in registry config
  make/photon/prepare/templates/registry/config.yml.jinja
Labels: target/1.8.0

#7719 Fix chart relative url issue
  make/harbor.yml
  make/photon/prepare/templates/chartserver/env.jinja
  make/photon/prepare/utils/chart.py
  make/photon/prepare/utils/configs.py
  src/chartserver/handler_repo.go
  src/chartserver/handler_utility.go
  src/core/api/chart_repository.go
  src/portal/src/app/project/helm-chart/helm-chart.service.ts
Labels: target/1.8.0

#7792 Cherry pick 180 fix chart url
  make/harbor.yml
  make/photon/prepare/templates/chartserver/env.jinja
  make/photon/prepare/utils/chart.py
  make/photon/prepare/utils/configs.py
  src/chartserver/handler_repo.go
  src/chartserver/handler_utility.go
  src/core/api/chart_repository.go
  src/portal/src/app/project/helm-chart/helm-chart.service.ts
Labels: target/1.8.0

#7799 Set the real name of OIDC user when onboarding
  src/core/controllers/oidc.go
Labels: target/1.8.0

#7800 Set the real name of OIDC user when onboarding -cherrypick to 1.8 branch
  src/core/controllers/oidc.go
Labels: target/1.8.0

#7802 Made logs in jobservice configurable
  make/harbor.yml
  make/photon/prepare/templates/jobservice/config.yml.jinja
  make/photon/prepare/utils/configs.py
  make/photon/prepare/utils/jobservice.py
Labels: target/1.8.0

#7815 Add "MaxMessageSize" to the config of rsyslogd
  make/photon/log/rsyslog.conf
Labels: target/1.8.0

#7814 Add "MaxMessageSize" to the config of rsyslogd
  make/photon/log/rsyslog.conf
Labels: target/1.8.0

#7816 fix typo of azure config
  make/photon/prepare/utils/chart.py
Labels: target/1.8.0

#7817 Fix typo in azure config
  make/photon/prepare/utils/chart.py
Labels: target/1.8.0

#7818 Update user guide for OIDC authentication
  docs/img/oidc_auth_setting.png
  docs/img/oidc_login.png
  docs/img/oidc_onboard_dlg.png
  docs/img/profile_dlg.png
  docs/img/user_profile.png
  docs/user_guide.md
Labels: target/1.8.0

#7819 Update user guide for OIDC authentication - cherrypick to 1.8 branch
  docs/img/oidc_auth_setting.png
  docs/img/oidc_login.png
  docs/img/oidc_onboard_dlg.png
  docs/img/profile_dlg.png
  docs/img/user_profile.png
  docs/user_guide.md
Labels: target/1.8.0

#7880 Add ensure settings when to search user in auth proxy
  src/core/auth/authproxy/auth.go
Labels: target/1.8.1

#7656 Minor documentation improvements for harbor
  CONTRIBUTING.md
  docs/kubernetes_deployment.md
Labels: area/doc
