Repository goharbor/harbor, pull requests merged in 2019-12, with the labels that each got.

#10022 Fix ca bundle path join issue
  make/photon/prepare/utils/configs.py
Labels: target/1.10.0

#9910 Use struct instead of pointer for the time to fix the timezone issue
  src/portal/lib/src/replication/replication-tasks/replication-tasks.component.html
  src/replication/dao/execution.go
  src/replication/dao/execution_test.go
  src/replication/dao/models/execution.go
  src/replication/operation/execution/execution_test.go
  src/replication/operation/flow/stage.go
Labels: target/1.9.4

#10073 [Cherry pick]perf(rbac): add permission evaluator to improve performance
  src/common/rbac/casbin.go
  src/common/rbac/casbin_test.go
  src/common/rbac/evaluator.go
  src/common/rbac/evaluator_test.go
  src/common/rbac/rbac.go
  src/common/rbac/rbac_test.go
  src/common/security/admiral/context.go
  src/common/security/local/context.go
  src/common/security/robot/context.go
Labels: target/1.9.4

#10028 Fix ca bundle path join issue
  make/photon/prepare/utils/configs.py
Labels: target/1.10.0

#10148 [Cherry pick]chore(scanner): upgrade clair scanner to 1.0.1
  Makefile
  make/photon/clair-adapter/Dockerfile.binary
Labels: target/1.10.0

#10152 improve pulling vulnerable images warning message
  src/core/middlewares/vulnerable/handler.go
Labels: target/1.10.0

#10165 Sort the tag before returning the list when calling API
  src/core/api/repository.go
Labels: target/1.10.0

#10208 doc[scanner]:clear scanner spec related
  API/scanner/scanner-adapter-openapi-v1.0.yaml
  README.md
Labels: area/doc

#10209 doc[api spec]:rename folder name to `api`
  api/harbor/swagger.yaml
Labels: area/doc

#10215 [Cherry pick]fix fatal error
  src/jobservice/job/impl/context.go
Labels: target/1.9.4

#10210 Chore/clear scanner specs 1.10
  API/scanner/scanner-adapter-openapi-v1.0.yaml
  Makefile
  README.md
  api/harbor/swagger.yaml
  docs/configure_swagger.md
  make/photon/portal/Dockerfile
  tests/swaggerchecker.sh
Labels: area/doc

#10232 chore[api]:rename API folder to api
  Makefile
  api/harbor/README
  docs/configure_swagger.md
  make/photon/portal/Dockerfile
  tests/swaggerchecker.sh
Labels: area/build, area/doc

#10229 fix[scan]:missing header in v1 client
  src/pkg/scan/rest/v1/client.go
Labels: area/interrogation-service

#9042 doc[compatibility]:provide compatibility doc
  docs/harbor_compatibility_list.md
  docs/img/OIDC/auth0.png
  docs/img/OIDC/dex.png
  docs/img/OIDC/google_identity.png
  docs/img/OIDC/keycloak.png
  docs/img/OIDC/ping.png
  docs/img/replication_adapters/acr.png
  docs/img/replication_adapters/ali-cr.png
  docs/img/replication_adapters/artifactory.png
  docs/img/replication_adapters/distribution.png
  docs/img/replication_adapters/docker_hub.png
  docs/img/replication_adapters/ecr-aws.png
  docs/img/replication_adapters/ecr.png
  docs/img/replication_adapters/gcr.png
  docs/img/replication_adapters/gitlab.png
  docs/img/replication_adapters/harbor_logo.png
  docs/img/replication_adapters/helm-hub.png
  docs/img/replication_adapters/hw.png
  docs/img/replication_adapters/quay.png
  docs/img/replication_adapters/right.png
  docs/img/scanners/anchore.png
  docs/img/scanners/aqua.png
  docs/img/scanners/clair.png
  docs/img/scanners/dosec.png
  docs/img/scanners/trivy.png
Labels: area/doc, area/oidc, area/replication, target/1.10.0

#10138 Create the models for OCI supporting
  make/migrations/postgresql/0030_1.11.0_schema.up.sql
  src/go.mod
  src/pkg/artifact/controller.go
  src/pkg/artifact/manager/dao/model.go
  src/pkg/artifact/manager/manager.go
  src/pkg/artifact/model/model.go
  src/pkg/artifact/model/model_test.go
Labels: area/OCI

#10212 [doc] Update doc for migration
  docs/migration_guide.md
Labels: target/1.10.0

#10245 doc[compatibility]:add doc ref in the README
  README.md
  api/harbor/README.md
Labels: area/doc

#10270 [CHERRY-PICK-1.10.0]:doc[compatibility]:add compatibility doc ref in the README
  README.md
  api/harbor/README.md
  docs/harbor_compatibility_list.md
  docs/img/OIDC/auth0.png
  docs/img/OIDC/dex.png
  docs/img/OIDC/google_identity.png
  docs/img/OIDC/keycloak.png
  docs/img/OIDC/ping.png
  docs/img/replication_adapters/acr.png
  docs/img/replication_adapters/ali-cr.png
  docs/img/replication_adapters/artifactory.png
  docs/img/replication_adapters/distribution.png
  docs/img/replication_adapters/docker_hub.png
  docs/img/replication_adapters/ecr-aws.png
  docs/img/replication_adapters/ecr.png
  docs/img/replication_adapters/gcr.png
  docs/img/replication_adapters/gitlab.png
  docs/img/replication_adapters/harbor_logo.png
  docs/img/replication_adapters/helm-hub.png
  docs/img/replication_adapters/hw.png
  docs/img/replication_adapters/quay.png
  docs/img/replication_adapters/right.png
  docs/img/scanners/anchore.png
  docs/img/scanners/aqua.png
  docs/img/scanners/clair.png
  docs/img/scanners/dosec.png
  docs/img/scanners/trivy.png
Labels: area/doc, area/interrogation-service

#10202 Add the registry handlers without the implementation detail
  src/server/middleware/middleware.go
  src/server/v2.0/registry/catalog/catalog.go
  src/server/v2.0/registry/handler.go
  src/server/v2.0/registry/manifest/manifest.go
  src/server/v2.0/registry/tag/tag.go
Labels: area/OCI, target/2.0.0

#10367 Remove the manifest list middleware
  src/core/middlewares/chain.go
  src/core/middlewares/config.go
  src/core/middlewares/multiplmanifest/handler.go
Labels: area/OCI

#10385 Remove the workaround for blocking manifest list in replication
  src/replication/transfer/image/transfer.go
Labels: area/replication, target/2.0.0

#10337 feat(orm): add orm support with context
  src/core/filter/orm.go
  src/core/main.go
  src/internal/orm/orm.go
  src/internal/orm/orm_test.go
  src/internal/orm/tx.go
Labels: target/2.0.0
