Repository goharbor/harbor, pull requests merged in 2020-08, with the labels that each got.

#11783 Add internal https 4 portal
  make/photon/portal/Dockerfile
  make/photon/prepare/commands/prepare.py
  make/photon/prepare/g.py
  make/photon/prepare/models.py
  make/photon/prepare/scripts/gencert.sh
  make/photon/prepare/templates/core/env.jinja
  make/photon/prepare/templates/docker_compose/docker-compose.yml.jinja
  make/photon/prepare/templates/nginx/nginx.http.conf.jinja
  make/photon/prepare/templates/nginx/nginx.https.conf.jinja
  make/photon/prepare/templates/portal/nginx.conf.jinja
  make/photon/prepare/utils/configs.py
  make/photon/prepare/utils/portal.py
Labels: target/2.1.0

#12622 fix[replicatioin] aliyun acr pull with repo filter
  src/replication/adapter/aliacr/adapter.go
Labels: area/replication, replication/adapters

#12650 update GC job
  src/jobservice/job/impl/gc/garbage_collection.go
  src/jobservice/job/impl/gc/garbage_collection_test.go
Labels: target/2.1.0

#12647 refactor(preheat): refactor policy schema serialize funcs
  src/controller/p2p/preheat/controller.go
  src/pkg/p2p/preheat/models/policy/policy.go
  src/pkg/p2p/preheat/models/policy/policy_test.go
  src/pkg/p2p/preheat/policy/manager.go
  src/pkg/p2p/preheat/policy/manager_test.go
Labels: area/P2P-Distribution, candidate/2.1.0

#12649 fix(preheat): fix preheat task log display
  api/v2.0/swagger.yaml
  src/server/v2.0/handler/preheat.go
Labels: area/P2P-Distribution, candidate/2.1.0

#10754 [CHERRY-PICK]fix(replication): huawei adapter multi authorization
  src/replication/adapter/huawei/huawei_adapter.go
  src/replication/adapter/huawei/image_registry.go
Labels: area/replication, target/1.10.5

#12646 Fix bug of update preheat instance default.
  src/pkg/p2p/preheat/dao/instance/dao.go
  src/pkg/p2p/preheat/dao/instance/dao_test.go
Labels: area/P2P-Distribution, target/2.1.0

#12656 fix(swagger): fix the definition of errors
  api/v2.0/swagger.yaml
Labels: area/API, target/2.1.0

#12610 Do some refine for the scheduler
  make/migrations/postgresql/0040_2.1.0_schema.up.sql
  src/controller/p2p/preheat/controller.go
  src/controller/p2p/preheat/controllor_test.go
  src/pkg/p2p/preheat/models/policy/policy.go
  src/pkg/retention/controller.go
  src/pkg/retention/controller_test.go
  src/pkg/retention/manager.go
  src/pkg/retention/policy/models.go
  src/pkg/scheduler/callback.go
  src/pkg/scheduler/dao.go
  src/pkg/scheduler/dao_test.go
  src/pkg/scheduler/scheduler.go
  src/pkg/scheduler/scheduler_test.go
  src/testing/pkg/scheduler/scheduler.go
Labels: area/task-execution, target/2.1.0

#12665 fix(preheat): provider more info about p2p provider instance
  api/v2.0/swagger.yaml
  src/server/v2.0/handler/preheat.go
Labels: area/P2P-Distribution, target/2.1.0, target/FC

#12034 disable tls v1.1
  make/common/templates/nginx/nginx.https.conf
  make/common/templates/nginx/notary.server.conf
  tests/travis/ut_install.sh
Labels: product/vic

#12652 Show the detail error message when failed to fetch the artifacts during replication
  src/common/utils/passports.go
  src/replication/adapter/aliacr/adapter.go
  src/replication/adapter/dockerhub/adapter.go
  src/replication/adapter/harbor/v1/adapter.go
  src/replication/adapter/harbor/v2/adapter.go
  src/replication/adapter/jfrog/adapter.go
  src/replication/adapter/native/adapter.go
Labels: area/replication, target/2.1.0

#12669 fix(preheat):leverage project settings
  src/controller/p2p/preheat/enforcer.go
  src/controller/p2p/preheat/enforcer_test.go
Labels: area/P2P-Distribution, target/2.1.0, target/FC

#12102 docs: Explain how to use Trivy in offline mode
  make/harbor.yml.tmpl
Labels: area/doc, target/2.1.0

#10455 fix(replication): refactor quay adapter to fix authorization and supp…
  make/migrations/postgresql/0040_2.1.0_schema.up.sql
  src/jobservice/job/impl/replication/replication.go
  src/replication/adapter/quay/adapter.go
  src/replication/adapter/quay/adapter_test.go
  src/replication/adapter/quay/apikey.go
  src/replication/adapter/quay/apikey_test.go
  src/replication/adapter/quay/types.go
  src/replication/adapter/quayio/types.go
  src/replication/model/registry.go
  src/replication/replication.go
Labels: area/replication, pending-for-more-info, target/2.1.0

#12518 Fix #12487: Proxy cache create duplicated operation log
  src/controller/proxy/controller.go
  src/controller/proxy/controller_test.go
  src/controller/proxy/local.go
  src/controller/proxy/local_test.go
  src/controller/proxy/remote.go
  src/server/middleware/repoproxy/proxy.go
Labels: target/2.1.0

#12690 fix(preheat): add precheck before disable instance
  src/controller/p2p/preheat/controller.go
  src/controller/p2p/preheat/controllor_test.go
  src/server/v2.0/handler/preheat.go
Labels: area/P2P-Distribution, target/2.1.0, target/FC

#12691 chore(clair): bump up clair adapter to v1.1.0
  Makefile
Labels: target/2.1.0

#12694 chore(images): install shadow package in base images
  make/photon/clair-adapter/Dockerfile.base
  make/photon/core/Dockerfile.base
  make/photon/jobservice/Dockerfile.base
  make/photon/nginx/Dockerfile.base
  make/photon/notary-server/Dockerfile.base
  make/photon/notary-signer/Dockerfile.base
  make/photon/portal/Dockerfile.base
  make/photon/registry/Dockerfile.base
  make/photon/registryctl/Dockerfile.base
  make/photon/trivy-adapter/Dockerfile.base
Labels: target/2.1.0

#12525 Feat: Enhance default processor to handle user-defined artifact like Machine Learning artifacts
  make/migrations/postgresql/0040_2.1.0_schema.up.sql
  src/controller/artifact/abstractor.go
  src/controller/artifact/abstractor_test.go
  src/controller/artifact/annotation/parser.go
  src/controller/artifact/annotation/parser_test.go
  src/controller/artifact/annotation/v1alpha1.go
  src/controller/artifact/annotation/v1alpha1_test.go
  src/controller/artifact/controller.go
  src/controller/artifact/processor/base/index.go
  src/controller/artifact/processor/base/manifest.go
  src/controller/artifact/processor/base/manifest_test.go
  src/controller/artifact/processor/chart/chart.go
  src/controller/artifact/processor/chart/chart_test.go
  src/controller/artifact/processor/cnab/cnab.go
  src/controller/artifact/processor/cnab/cnab_test.go
  src/controller/artifact/processor/default.go
  src/controller/artifact/processor/default_test.go
  src/controller/artifact/processor/image/index.go
  src/controller/artifact/processor/image/index_test.go
  src/controller/artifact/processor/image/manifest_v1.go
  src/controller/artifact/processor/image/manifest_v1_test.go
  src/controller/artifact/processor/image/manifest_v2.go
  src/controller/artifact/processor/image/manifest_v2_test.go
  src/controller/artifact/processor/processor.go
  src/controller/artifact/processor/processor_test.go
  src/pkg/artifact/dao/model.go
  src/pkg/artifact/model.go
  src/testing/pkg/parser/parser.go
  src/testing/pkg/processor/processor.go
Labels: area/OCI, target/2.1.0, target/FC

#12736 fix gc foreign layer issue
  src/jobservice/job/impl/gc/garbage_collection.go
Labels: target/2.1.0, target/FC

#12709 fix(replication): fix quay adapter authorization
  src/portal/src/lib/services/endpoint.service.ts
  src/replication/adapter/quay/adapter.go
Labels: target/2.1.0

#12755 fix(blob): make blob size in redis expired in 24 hours
  src/controller/blob/controller.go
  src/controller/blob/controller_test.go
  src/jobservice/job/impl/gc/garbage_collection.go
Labels: target/2.1.0, target/FC

#12748 fix gc remove manifest issue
  src/pkg/blob/models/blob.go
Labels: target/2.1.0, target/FC

#12767 fix(swagger): format the value of ResourceList as int64
  api/v2.0/legacy_swagger.yaml
Labels: target/2.1.0

#12751 Use a separated database table to store the data version
  make/migrations/postgresql/0040_2.1.0_schema.up.sql
  src/migration/artifact.go
  src/migration/migration.go
Labels: target/2.1.0, target/FC

#12683 Implement the icon API to get the icon of artifact
  api/v2.0/swagger.yaml
  icons/chart.png
  icons/cnab.png
  icons/default.png
  icons/image.png
  make/migrations/postgresql/0040_2.1.0_schema.up.sql
  make/photon/core/Dockerfile
  src/controller/artifact/processor/chart/chart.go
  src/controller/artifact/processor/chart/chart_test.go
  src/controller/artifact/processor/cnab/cnab.go
  src/controller/artifact/processor/cnab/cnab_test.go
  src/controller/artifact/processor/default.go
  src/controller/artifact/processor/default_test.go
  src/controller/artifact/processor/image/index.go
  src/controller/artifact/processor/image/index_test.go
  src/controller/artifact/processor/image/manifest_v1.go
  src/controller/artifact/processor/image/manifest_v1_test.go
  src/controller/artifact/processor/image/manifest_v2.go
  src/controller/artifact/processor/image/manifest_v2_test.go
  src/controller/icon/controller.go
  src/controller/icon/controller_test.go
  src/go.mod
  src/go.sum
  src/pkg/artifact/dao/model.go
  src/pkg/artifact/model.go
  src/server/v2.0/handler/handler.go
  src/server/v2.0/handler/icon.go
  src/server/v2.0/handler/model/artifact.go
  src/vendor/github.com/nfnt/resize/.travis.yml
  src/vendor/github.com/nfnt/resize/LICENSE
  src/vendor/github.com/nfnt/resize/README.md
  src/vendor/github.com/nfnt/resize/converter.go
  src/vendor/github.com/nfnt/resize/filters.go
  src/vendor/github.com/nfnt/resize/nearest.go
  src/vendor/github.com/nfnt/resize/resize.go
  src/vendor/github.com/nfnt/resize/thumbnail.go
  src/vendor/github.com/nfnt/resize/ycc.go
  src/vendor/modules.txt
Labels: target/2.1.0

#12762 remove reset password dialog from sign-in component
  src/portal/src/app/sign-in/sign-in.component.html
Labels: target/2.1.0

#12786 fix(scan): fix the permission checking for artifact scanning
  src/server/v2.0/handler/scan.go
  tests/apitests/python/library/base.py
  tests/apitests/python/library/scan.py
  tests/apitests/python/test_scan_image_artifact_in_public_project.py
  tests/apitests/python/testutils.py
  tests/robot-cases/Group0-BAT/API_DB.robot
Labels: target/2.1.0

#12698 [FIX] Delete executions of the P2P policy.
  src/controller/p2p/preheat/controller.go
  src/controller/p2p/preheat/controllor_test.go
  src/pkg/p2p/preheat/policy/manager.go
Labels: area/P2P-Distribution

#12701 get artifact icon from backend API
  src/portal/src/app/project/p2p-provider/add-p2p-policy/add-p2p-policy.component.ts
  src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
  src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.spec.ts
  src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
  src/portal/src/app/project/repository/artifact/artifact-summary.component.html
  src/portal/src/app/project/repository/artifact/artifact-summary.component.spec.ts
  src/portal/src/app/project/repository/artifact/artifact-summary.component.ts
  src/portal/src/app/project/repository/artifact/artifact.service.spec.ts
  src/portal/src/app/project/repository/artifact/artifact.service.ts
  src/portal/src/app/project/repository/artifact/artifact.ts
Labels: target/2.1.0

#12790 Token service handling invalid resource
  src/core/service/token/authutils.go
Labels: target/2.1.0

#12789 remove robot accounts when to delete a project
  src/pkg/robot/dao/robot.go
  src/pkg/robot/dao/robot_test.go
  src/pkg/robot/manager.go
  src/pkg/robot/manager_test.go
  src/server/v2.0/handler/project.go
  src/testing/pkg/pkg.go
  src/testing/pkg/robot/dao/robot_account_dao.go
Labels: target/2.1.0

#12793 Disable the tag creation for the artifact under a proxy cache project
  api/v2.0/swagger.yaml
  src/server/v2.0/handler/artifact.go
Labels: target/2.1.0

#12792 Return 403 when trying to push artifacts into the proxy cache project…
  src/server/middleware/repoproxy/proxy.go
  src/server/registry/route.go
Labels: target/2.1.0

#12803 add timeout for CI
  .github/workflows/CI.yml
Labels: target/2.1.0

#12749 Tag retention webhook support
  src/controller/event/handler/init.go
  src/controller/event/handler/webhook/artifact/replication.go
  src/controller/event/handler/webhook/artifact/retention.go
  src/controller/event/handler/webhook/artifact/retention_test.go
  src/controller/event/metadata/retention.go
  src/controller/event/metadata/retention_test.go
  src/controller/event/model/event.go
  src/controller/event/topic.go
  src/core/api/notification_policy.go
  src/core/api/retention.go
  src/core/service/notifications/jobs/handler.go
  src/pkg/notifier/model/event.go
  src/pkg/retention/controller.go
  src/pkg/retention/faked_controller.go
  src/pkg/retention/mocks/api_controller.go
  src/portal/src/app/project/webhook/webhook.service.ts
Labels: target/2.1.0, target/FC

#12801 refactor(scan): remove duplicate CVESet types
  src/common/models/cve_allowlist.go
  src/common/models/cve_allowlist_test.go
  src/controller/p2p/preheat/enforcer.go
  src/pkg/scan/report/summary.go
  src/pkg/scan/report/summary_test.go
  src/server/middleware/vulnerable/vulnerable.go
Labels: target/2.1.0

#12799 fix gc job submit issue
  src/core/api/admin_job.go
Labels: target/2.1.0

#12805 udpate resource list order
  src/common/dao/label.go
  src/common/dao/notification/notification_policy.go
  src/replication/dao/policy.go
  src/replication/dao/policy_test.go
Labels: target/2.1.0

#12670 Upload the harbor log icon as it's referenced by the released Harbor chart
  docs/img/README.md
  docs/img/harbor_logo.png
Labels: target/1.2.0

#12618 Refresh the status of execution for every status changing of task
  make/migrations/postgresql/0040_2.1.0_schema.up.sql
  src/pkg/task/dao/execution.go
  src/pkg/task/dao/execution_test.go
  src/pkg/task/dao/model.go
  src/pkg/task/execution.go
  src/pkg/task/execution_test.go
  src/pkg/task/hook.go
  src/pkg/task/hook_test.go
  src/pkg/task/mock_execution_dao_test.go
  src/pkg/task/model.go
  src/server/handler/job_status_hook.go
Labels: area/task-execution, target/2.1.0

#12809 Update to golang 1.14.7
  Makefile
  make/photon/chartserver/builder
  make/photon/clair-adapter/Dockerfile.binary
  make/photon/clair-adapter/builder.sh
  make/photon/clair/Dockerfile.binary
  make/photon/clair/builder
  make/photon/notary/binary.Dockerfile
  make/photon/registry/Dockerfile.binary
  make/photon/trivy-adapter/Dockerfile.binary
  make/photon/trivy-adapter/builder.sh
  tests/ci/distro_installer.sh
  tests/e2e-image/nightly/Dockerfile
  tools/swagger/Dockerfile
Labels: target/2.0.3, target/2.1.0

#12826 CSRF token cookie -> header
  src/portal/src/app/services/intercept-http.service.spec.ts
  src/portal/src/app/services/intercept-http.service.ts
  src/portal/src/lib/utils/shared/shared.module.ts
  src/server/middleware/csrf/csrf.go
  src/server/middleware/csrf/csrf_test.go
Labels: target/2.1.0, target/RC

#12729 Fix for duplicate webhook policy name
  make/migrations/postgresql/0040_2.1.0_schema.up.sql
  src/common/dao/notification/notification_policy.go
  src/core/api/notification_policy.go
Labels: target/2.1.0

#12831 chore(clair): bump up clair adapter to v1.1.1
  Makefile
Labels: target/2.1.0

#12788 upgrade robotframework in git action
  .github/workflows/CI.yml
  Makefile
  tests/apitests/python/library/artifact.py
  tests/apitests/python/library/configurations.py
  tests/apitests/python/library/project.py
  tests/apitests/python/library/system.py
  tests/apitests/python/library/user.py
  tests/apitests/python/test_add_member_to_private_project.py
  tests/apitests/python/test_add_sys_label_to_tag.py
  tests/apitests/python/test_assign_role_to_ldap_group.py
  tests/apitests/python/test_ldap_admin_role.py
  tests/apitests/python/test_manage_project_member.py
  tests/apitests/python/test_project_level_cve_allowlist.py
  tests/apitests/python/test_push_image_with_special_name.py
  tests/apitests/python/test_scan_image_artifact.py
  tests/apitests/python/test_sign_image.py
  tests/apitests/python/test_user_group.py
  tests/apitests/python/testutils.py
  tests/ci/api_common_install.sh
  tests/ci/api_run.sh
Labels: target/2.1.0

#12834 [Cherry pick]fix(scan): fix the permission checking for artifact scanning
  src/server/v2.0/handler/scan.go
  tests/apitests/python/library/base.py
  tests/apitests/python/library/scan.py
  tests/apitests/python/test_scan_image_artifact_in_public_project.py
  tests/apitests/python/testutils.py
  tests/robot-cases/Group0-BAT/API_DB.robot
Labels: target/2.0.3

#12835 Update all references of Golang to 1.14.7
  .github/workflows/CI.yml
  .github/workflows/conformance_test.yml
  CONTRIBUTING.md
Labels: target/2.1.0

#12840 chore(trivy): Bump up trivy adapter to v0.14.1
  Makefile
Labels: target/2.0.3, target/2.1.0

#12857 fix upgrade issue
  make/migrations/postgresql/0040_2.1.0_schema.up.sql
  src/pkg/blob/dao/dao.go
  src/pkg/blob/dao/dao_test.go
  src/pkg/blob/models/blob.go
Labels: target/2.1.0, target/RC

#12841 fix(jobservice) redis sentinel failover hang
  make/photon/prepare/templates/registry/config.yml.jinja
Labels: kind/helm-chart-impact

#12873 fix db migration issue
  make/migrations/postgresql/0031_2.0.3_schema.up.sql
Labels: target/2.1.0, target/RC

#12874 fix db migration issue
  VERSION
  make/migrations/postgresql/0031_2.0.3_schema.up.sql
Labels: target/2.0.3

#12881 refactor(event): change default operator to username of security
  src/controller/event/operator/operator.go
  src/controller/proxy/controller.go
  src/server/registry/manifest.go
Labels: target/2.1.0

#12886 Make the 2.1.0 migration SQL script idempotent
  make/migrations/postgresql/0040_2.1.0_schema.up.sql
Labels: target/2.1.0, target/RC

#12883 fix event log issue
  src/controller/event/handler/auditlog/auditlog.go
  src/controller/event/handler/auditlog/auditlog_test.go
  src/controller/event/handler/internal/artifact.go
  src/controller/event/handler/p2p/preheat.go
  src/controller/event/handler/p2p/preheat_test.go
  src/controller/event/handler/replication/replication.go
  src/controller/event/handler/webhook/artifact/artifact.go
  src/controller/event/handler/webhook/artifact/replication.go
  src/controller/event/handler/webhook/artifact/replication_test.go
  src/controller/event/handler/webhook/artifact/retention.go
  src/controller/event/handler/webhook/chart/chart.go
  src/controller/event/handler/webhook/chart/chart_test.go
  src/controller/event/handler/webhook/quota/quota.go
  src/controller/event/handler/webhook/quota/quota_test.go
  src/controller/event/handler/webhook/scan/delete.go
  src/controller/event/handler/webhook/scan/scan.go
  src/controller/event/handler/webhook/scan/scan_test.go
  src/controller/event/topic.go
  src/pkg/notifier/handler/notification/http_handler.go
  src/pkg/notifier/handler/notification/http_handler_test.go
  src/pkg/notifier/handler/notification/slack_handler.go
  src/pkg/notifier/handler/notification/slack_handler_test.go
  src/pkg/notifier/notification_handler.go
  src/pkg/notifier/notifier.go
  src/pkg/notifier/notifier_test.go
Labels: target/2.1.0

#12878 cherry-pick replication adapter's change for 2.0.3
  src/pkg/registry/client.go
  src/replication/adapter/aliacr/adapter.go
  src/replication/adapter/gitlab/adapter.go
  src/replication/adapter/gitlab/adapter_test.go
  src/replication/adapter/gitlab/client_test.go
  src/replication/adapter/gitlab/testdata/projects/-docker.json
  src/replication/adapter/gitlab/testdata/projects/all.json
  src/replication/adapter/gitlab/testdata/projects/dev-.json
  src/replication/adapter/gitlab/testdata/projects/dev-docker.json
  src/replication/adapter/gitlab/testdata/repositories/1.json
  src/replication/adapter/gitlab/testdata/repositories/2.json
  src/replication/adapter/gitlab/testdata/repositories/3.json
  src/replication/adapter/gitlab/testdata/repositories/4.json
  src/replication/adapter/gitlab/testdata/repositories/5.json
  src/replication/adapter/gitlab/testdata/tags/11.json
  src/replication/adapter/gitlab/testdata/tags/21.json
  src/replication/adapter/gitlab/testdata/tags/31.json
  src/replication/adapter/gitlab/testdata/tags/41.json
  src/replication/adapter/gitlab/testdata/tags/51.json
  src/replication/adapter/googlegcr/adapter.go
  src/replication/adapter/helmhub/adapter_test.go
  src/replication/adapter/helmhub/chart_registry_test.go
  src/replication/adapter/helmhub/client.go
  src/replication/adapter/jfrog/adapter.go
  src/replication/adapter/jfrog/adapter_test.go
  src/replication/adapter/jfrog/client.go
  src/replication/adapter/jfrog/client_test.go
  src/replication/adapter/jfrog/types.go
  src/testing/pkg/registry/client.go
Labels: target/2.0.3

#12897 Fill in the icon of known artifacts in artifact controller
  make/migrations/postgresql/0040_2.1.0_schema.up.sql
  src/controller/artifact/controller.go
  src/controller/artifact/controller_test.go
  src/controller/artifact/processor/chart/chart.go
  src/controller/artifact/processor/chart/chart_test.go
  src/controller/artifact/processor/cnab/cnab.go
  src/controller/artifact/processor/cnab/cnab_test.go
  src/controller/artifact/processor/default.go
  src/controller/artifact/processor/default_test.go
  src/controller/artifact/processor/image/index.go
  src/controller/artifact/processor/image/index_test.go
  src/controller/artifact/processor/image/manifest_v1.go
  src/controller/artifact/processor/image/manifest_v1_test.go
  src/controller/artifact/processor/image/manifest_v2.go
  src/controller/artifact/processor/image/manifest_v2_test.go
  src/controller/icon/controller.go
  src/controller/icon/controller_test.go
  src/lib/icon/const.go
Labels: target/2.1.0, target/RC

#12896 fix migration issue
  make/migrations/postgresql/0031_2.0.3_schema.up.sql
Labels: target/2.1.0, target/RC

#12894 Fallback to local repo on errors when proxy to remote repo
  src/server/middleware/repoproxy/proxy.go
Labels: target/2.1.0

#12906 fix(preheat):handle fail case of preheat in job
  src/pkg/p2p/preheat/job.go
Labels: area/P2P-Distribution, target/2.1.0

#12907 [CHERRY-PICK]fix(preheat):handle fail case of preheat in job
  src/pkg/p2p/preheat/job.go
Labels: area/P2P-Distribution, target/2.1.0

#12902 fix migration issue
  make/migrations/postgresql/0031_2.0.3_schema.up.sql
Labels: target/2.0.3
