Repository goharbor/harbor, pull requests merged in 2020-06, with the labels that each got.

#12044 Update Clair to v2.1.3
  Makefile
Labels: target/2.0.1

#10586 Fix typo (ODIC -> OIDC)
  docs/administration/configure-authentication/_index.md
Labels: area/doc

#11983 fix(trivy): Handle gracefully scratch and slim images
  Makefile
Labels: target/2.0.1

#12121 fix(jobservice):mismatch status issue when stopping job
  src/jobservice/hook/hook_agent_test.go
  src/jobservice/period/basic_scheduler.go
  src/jobservice/worker/cworker/c_worker.go
Labels: area/job-services, enhancement, target/2.0.1

#12128 fix(jobservice):mismatch status issue when stopping job
  src/jobservice/hook/hook_agent_test.go
  src/jobservice/period/basic_scheduler.go
  src/jobservice/worker/cworker/c_worker.go
Labels: area/job-services, target/2.0.1

#10389 Fixed search images in registry gitlab
  src/replication/adapter/gitlab/adapter.go
  src/replication/adapter/gitlab/adapter_test.go
  src/replication/adapter/gitlab/client_test.go
  src/replication/adapter/gitlab/testdata/projects/-docker.json
  src/replication/adapter/gitlab/testdata/projects/all.json
  src/replication/adapter/gitlab/testdata/projects/dev-.json
  src/replication/adapter/gitlab/testdata/projects/dev-docker.json
  src/replication/adapter/gitlab/testdata/repositories/1.json
  src/replication/adapter/gitlab/testdata/repositories/2.json
  src/replication/adapter/gitlab/testdata/repositories/3.json
  src/replication/adapter/gitlab/testdata/repositories/4.json
  src/replication/adapter/gitlab/testdata/repositories/5.json
  src/replication/adapter/gitlab/testdata/tags/11.json
  src/replication/adapter/gitlab/testdata/tags/21.json
  src/replication/adapter/gitlab/testdata/tags/31.json
  src/replication/adapter/gitlab/testdata/tags/41.json
  src/replication/adapter/gitlab/testdata/tags/51.json
Labels: target/2.1.0

#12164 Remove the API to test a webhook - Cherry pick to 2.0 branch
  src/server/v2.0/route/legacy.go
Labels: target/2.0.1

#12168 fix(trivy): Bump up Trivy adapter to v0.11.0
  Makefile
Labels: area/interrogation-service, target/2.0.1

#12159 [cherry-pick]: fix(trivy): Handle gracefully scratch and slim images
  Makefile
Labels: area/interrogation-service, target/2.0.1

#12127 Remove the label from artifacts when deleting a label
  src/core/api/label.go
  src/pkg/label/manager.go
  src/pkg/label/manager_test.go
  src/testing/pkg/label/manager.go
Labels: target/2.0.1

#12212 Makes api/users return 401 for request not authenticated - Cherrypick to 2.0
  src/core/api/user.go
  src/core/api/user_test.go
Labels: target/2.0.1

#12211 [Cherry-pick]Remove the label from artifacts when deleting a label
  src/core/api/label.go
  src/pkg/label/manager.go
  src/pkg/label/manager_test.go
  src/testing/pkg/label/manager.go
Labels: target/2.0.1

#12203 Update creating project API to support proxy cache project
  api/v2.0/legacy_swagger.yaml
  make/migrations/postgresql/0040_2.1.0_schema.up.sql
  src/common/dao/project.go
  src/common/models/project.go
  src/core/api/project.go
  src/core/api/registry.go
  src/core/promgr/pmsdriver/local/local.go
Labels: target/2.1.0

#12176 Define the task manager interface and data model
  make/migrations/postgresql/0040_2.1.0_schema.up.sql
  src/pkg/task/checkin.go
  src/pkg/task/checkin_test.go
  src/pkg/task/dao/model.go
  src/pkg/task/execution.go
  src/pkg/task/model.go
  src/pkg/task/task.go
Labels: target/2.1.0

#12179 [cherry-pick]: fix(trivy): Bump up Trivy adapter to v0.11.0
  Makefile
Labels: target/2.0.1

#12247 bump up clair v2.1.4
  Makefile
Labels: target/2.0.1

#12239 Implement execution/task DAO for task manager
  src/pkg/task/dao/execution.go
  src/pkg/task/dao/execution_test.go
  src/pkg/task/dao/model.go
  src/pkg/task/dao/task.go
  src/pkg/task/dao/task_test.go
Labels: target/2.1.0

#12268 fix(adopters):revise broken img paths
  ADOPTERS.md
  docs/img/adopters/360.png
  docs/img/adopters/Yanrong.jpg
  docs/img/adopters/anchore_logo.png
  docs/img/adopters/axatp.png
  docs/img/adopters/beyondsoft.png
  docs/img/adopters/bingocloud.png
  docs/img/adopters/bocoit.png
  docs/img/adopters/boer.png
  docs/img/adopters/caicloud.png
  docs/img/adopters/china-mobile.png
  docs/img/adopters/cloudchef.png
  docs/img/adopters/cloudstar.png
  docs/img/adopters/dataman.png
  docs/img/adopters/datayes.png
  docs/img/adopters/dianrong.png
  docs/img/adopters/hydsoft.png
  docs/img/adopters/ifre.png
  docs/img/adopters/jd.png
  docs/img/adopters/openedutainment.png
  docs/img/adopters/pivotal.png
  docs/img/adopters/rancher.png
  docs/img/adopters/slamtec.png
  docs/img/adopters/talkingdata.png
  docs/img/adopters/tenxcloud.png
  docs/img/adopters/trendmicro.png
  docs/img/adopters/wangyi.png
  docs/img/adopters/wise2c.png
Labels: area/doc

#12175 move send error to source lib
  src/common/api/base.go
  src/lib/http/error.go
  src/lib/http/error_test.go
  src/registryctl/api/base.go
  src/server/middleware/artifactinfo/artifact_info.go
  src/server/middleware/csrf/csrf.go
  src/server/middleware/immutable/pushmf.go
  src/server/middleware/middleware.go
  src/server/middleware/quota/quota.go
  src/server/middleware/readonly/readonly.go
  src/server/middleware/transaction/transaction.go
  src/server/middleware/v2auth/auth.go
  src/server/registry/catalog.go
  src/server/registry/manifest.go
  src/server/registry/tag.go
  src/server/v2.0/handler/base.go
  src/server/v2.0/handler/handler.go
  src/server/version.go
Labels: target/2.1.0

#12101 update blob controller & manager
  make/migrations/postgresql/0040_2.1.0_schema.up.sql
  src/common/models/base.go
  src/common/models/blob.go
  src/controller/blob/controller.go
  src/controller/blob/controller_test.go
  src/jobservice/job/impl/gc/garbage_collection_test.go
  src/pkg/blob/dao/dao.go
  src/pkg/blob/dao/dao_test.go
  src/pkg/blob/manager.go
  src/pkg/blob/manager_test.go
  src/pkg/blob/models/blob.go
  src/server/middleware/blob/head_blob.go
  src/server/middleware/blob/head_blob_test.go
  src/server/middleware/patterns.go
  src/server/registry/route.go
  src/testing/controller/blob/controller.go
  src/testing/pkg/blob/manager.go
Labels: target/2.1.0

#12280 Implement task and execution manager
  src/common/job/client.go
  src/core/config/config.go
  src/core/config/config_test.go
  src/core/main.go
  src/core/middlewares/middlewares.go
  src/core/middlewares/middlewares_test.go
  src/pkg/task/checkin.go
  src/pkg/task/dao/model.go
  src/pkg/task/dao/task.go
  src/pkg/task/dao/task_test.go
  src/pkg/task/execution.go
  src/pkg/task/execution_test.go
  src/pkg/task/hook.go
  src/pkg/task/hook_test.go
  src/pkg/task/mock.go
  src/pkg/task/mock_execution_dao_test.go
  src/pkg/task/mock_jobservice_client_test.go
  src/pkg/task/mock_task_dao_test.go
  src/pkg/task/mock_task_manager_test.go
  src/pkg/task/model.go
  src/pkg/task/task.go
  src/pkg/task/task_test.go
  src/replication/operation/controller.go
  src/server/handler/job_status_hook.go
  src/server/route.go
Labels: target/2.1.0

#12331 feat(preheat):add preheat drivers
  src/pkg/p2p/preheat/models/provider/instance.go
  src/pkg/p2p/preheat/provider/auth/basic_handler.go
  src/pkg/p2p/preheat/provider/auth/cred.go
  src/pkg/p2p/preheat/provider/auth/custom_handler.go
  src/pkg/p2p/preheat/provider/auth/handler.go
  src/pkg/p2p/preheat/provider/auth/handler_test.go
  src/pkg/p2p/preheat/provider/auth/known_handlers.go
  src/pkg/p2p/preheat/provider/auth/none_handler.go
  src/pkg/p2p/preheat/provider/auth/token_handler.go
  src/pkg/p2p/preheat/provider/client/http_client.go
  src/pkg/p2p/preheat/provider/client/http_client_test.go
  src/pkg/p2p/preheat/provider/dragonfly.go
  src/pkg/p2p/preheat/provider/dragonfly_test.go
  src/pkg/p2p/preheat/provider/driver.go
  src/pkg/p2p/preheat/provider/factory.go
  src/pkg/p2p/preheat/provider/known_drivers.go
  src/pkg/p2p/preheat/provider/known_drivers_test.go
  src/pkg/p2p/preheat/provider/kraken.go
  src/pkg/p2p/preheat/provider/kraken_test.go
Labels: area/P2P-Distribution, candidate/2.1.0

#11988 update for 2.0.0 documentation
  docs/administration/configure-project-quotas/_index.md
  docs/administration/configuring-replication/create-replication-rules.md
  docs/administration/garbage-collection/_index.md
  docs/administration/upgrade/_index.md
  docs/administration/vulnerability-scanning/_index.md
  docs/administration/vulnerability-scanning/deployment-security.md
  docs/administration/vulnerability-scanning/scan-all-artifacts.md
  docs/administration/vulnerability-scanning/scan-individual-artifact.md
  docs/install-config/configure-internal-tls.md
  docs/install-config/configure-yml-file.md
  docs/working-with-projects/project-configuration/configure-webhooks.md
  docs/working-with-projects/project-configuration/create-robot-accounts.md
  docs/working-with-projects/working-with-images/adding-tags.md
  docs/working-with-projects/working-with-images/create-labels.md
  docs/working-with-projects/working-with-images/create-tag-immutability-rules.md
  docs/working-with-projects/working-with-images/create-tag-retention-rules.md
  docs/working-with-projects/working-with-images/deleting-artifact.md
  docs/working-with-projects/working-with-images/deleting-tags.md
  docs/working-with-projects/working-with-images/managing-helm-charts.md
  docs/working-with-projects/working-with-images/pulling-pushing-images.md
  docs/working-with-projects/working-with-images/repositories.md
Labels: area/doc

#12337 feat: add p2p preheat policy model
  src/pkg/p2p/preheat/models/policy/policy.go
  src/pkg/p2p/preheat/models/policy/policy_test.go
Labels: area/P2P-Distribution, candidate/2.1.0

#12330 [Cherry pick]feat(certs): install internal tls ca from /etc/harbor/ssl dir
  make/photon/common/install_cert.sh
Labels: target/2.0.1

#12338 feat(preheat):add preheat job
  src/pkg/p2p/preheat/job.go
  src/pkg/p2p/preheat/job_test.go
  src/pkg/p2p/preheat/models/provider/instance.go
  src/pkg/p2p/preheat/provider/dragonfly_test.go
  src/pkg/p2p/preheat/provider/driver.go
  src/pkg/p2p/preheat/provider/known_drivers.go
  src/pkg/p2p/preheat/provider/kraken_test.go
  src/pkg/p2p/preheat/provider/mock.go
  src/pkg/p2p/preheat/provider/preheat_image.go
Labels: area/P2P-Distribution, candidate/2.1.0

#12315 handle blob status chanage in put blob middlware
  src/server/middleware/blob/put_blob_upload.go
  src/server/middleware/blob/put_blob_upload_test.go
Labels: target/2.1.0

#12345 chore(trivy): Bump up Trivy adapter to v0.12.0
  Makefile
Labels: area/interrogation-service, target/2.1.0

#12349 feat(preheat):add artifact filters for preheat policy
  src/controller/p2p/preheat/enforcer.go
  src/lib/selector/candidate.go
  src/lib/selector/selector.go
  src/lib/selector/selectors/doublestar/selector.go
  src/lib/selector/selectors/label/selector.go
  src/lib/selector/selectors/severity/selector.go
  src/lib/selector/selectors/severity/selector_test.go
  src/lib/selector/selectors/signature/selector.go
  src/lib/selector/selectors/signature/selector_test.go
  src/pkg/p2p/preheat/models/policy/policy.go
  src/pkg/p2p/preheat/policy/filter.go
  src/pkg/p2p/preheat/policy/filter_test.go
Labels: area/P2P-Distribution, candidate/2.1.0

#12342 feat: add p2p preheat policy dao and manager(#12286)
  make/migrations/postgresql/0040_2.1.0_schema.up.sql
  src/pkg/p2p/preheat/dao/policy/dao.go
  src/pkg/p2p/preheat/dao/policy/dao_test.go
  src/pkg/p2p/preheat/models/policy/policy.go
  src/pkg/p2p/preheat/models/policy/policy_test.go
  src/pkg/p2p/preheat/policy/manager.go
  src/pkg/p2p/preheat/policy/manager_test.go
Labels: area/P2P-Distribution, candidate/2.1.0

#12360 fix(codecov):add ignore configuration
  codecov.yml
Labels: area/ci

#12314 add get GC candidate
  src/pkg/blob/dao/dao.go
  src/pkg/blob/dao/dao_test.go
  src/pkg/blob/manager.go
  src/pkg/blob/manager_test.go
  src/testing/pkg/blob/manager.go
Labels: target/2.1.0
