Repository goharbor/harbor, pull requests merged in 2020-11, with the labels that each got.

#13411 Remove UT for helm hub adapter (#13255)
  src/replication/adapter/helmhub/adapter_test.go
  src/replication/adapter/helmhub/chart_registry_test.go
Labels: target/1.10.6

#13168 feature(tag) add a thread pool size for tags list
  src/core/api/repository.go
Labels: target/1.10.6

#13361 feature(replication) check namespace existing first for AWS adapter
  src/replication/adapter/awsecr/adapter.go
Labels: area/replication, replication/adapters

#13407 [Cherry pick]fix(db): set max open conns of sql.DB manually
  src/common/dao/pgsql.go
  src/common/dao/pgsql_test.go
  src/common/dao/testutils.go
Labels: target/1.10.6

#13406 fix chart replication issue of uppercase letters
  src/replication/adapter/harbor/base/chart_registry.go
Labels: area/replication, target/2.0.4, target/2.2.0

#13425 add robot name prefix
  src/common/config/metadata/metadatalist.go
  src/common/const.go
  src/common/utils/test/config.go
  src/common/utils/test/test.go
  src/core/config/config.go
  src/core/config/config_test.go
Labels: target/2.2.0

#13422 feat: skip middlewares require db for ping
  src/core/api/harborapi_test.go
  src/core/middlewares/middlewares.go
  src/server/middleware/security/security.go
Labels: target/2.2.0

#13435 [UI]add robot name prefix
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
  src/portal/src/lib/components/config/config.ts
  src/portal/src/lib/components/config/system/system-settings.component.html
  src/portal/src/lib/components/config/system/system-settings.component.ts
Labels: area/robot-account, area/ui, target/2.2.0

#13456 bump up base version to v2.0.4
  VERSION
Labels: target/2.0.4

#13450 fix chart replication issue of uppercase letters
  src/replication/adapter/harbor/base/chart_registry.go
Labels: target/2.0.4

#13451 fix chart replication issue of uppercase letters
  src/replication/adapter/harbor/base/chart_registry.go
Labels: target/2.1.2

#13439 add role permission manager for robot enhancement
  make/migrations/postgresql/0050_2.2.0_schema.up.sql
  src/pkg/rbac/dao/dao.go
  src/pkg/rbac/dao/dao_test.go
  src/pkg/rbac/manager.go
  src/pkg/rbac/manager_test.go
  src/pkg/rbac/model/model.go
  src/testing/pkg/pkg.go
  src/testing/pkg/rbac/dao/dao.go
  src/testing/pkg/rbac/manager.go
Labels: area/robot-account, target/2.2.0

#13408 refactor: remove core/promgr pkg
  src/common/api/base.go
  src/controller/event/handler/init.go
  src/controller/event/handler/webhook/chart/chart.go
  src/controller/event/handler/webhook/chart/chart_test.go
  src/controller/project/controller.go
  src/controller/scan/base_controller.go
  src/controller/scan/base_controller_test.go
  src/controller/scan/checker.go
  src/controller/scanner/base_controller.go
  src/controller/scanner/base_controller_test.go
  src/controller/scanner/controller.go
  src/core/api/base.go
  src/core/api/chart_label.go
  src/core/api/chart_repository.go
  src/core/api/chart_repository_test.go
  src/core/api/label.go
  src/core/api/metadata.go
  src/core/api/notification_job.go
  src/core/api/notification_policy.go
  src/core/api/pro_scanner.go
  src/core/api/pro_scanner_test.go
  src/core/api/projectmember.go
  src/core/api/registry.go
  src/core/api/retention.go
  src/core/api/robot.go
  src/core/api/search.go
  src/core/api/statistic.go
  src/core/api/user_test.go
  src/core/config/config.go
  src/core/promgr/metamgr/metamgr.go
  src/core/promgr/metamgr/metamgr_test.go
  src/core/promgr/mocks/project_manager.go
  src/core/promgr/pmsdriver/driver.go
  src/core/promgr/pmsdriver/local/local.go
  src/core/promgr/pmsdriver/local/local_test.go
  src/core/promgr/promgr.go
  src/core/promgr/promgr_test.go
  src/server/middleware/v2auth/auth.go
  src/server/middleware/v2auth/auth_test.go
  src/server/v2.0/handler/auditlog.go
  src/testing/controller/project/controller.go
  src/testing/controller/scanner/controller.go
Labels: kind/refactor, target/2.2.0

#13444 add robot mgr
  make/migrations/postgresql/0050_2.2.0_schema.up.sql
  src/pkg/robot2/dao/dao.go
  src/pkg/robot2/dao/dao_test.go
  src/pkg/robot2/manager.go
  src/pkg/robot2/manager_test.go
  src/pkg/robot2/model/model.go
  src/testing/pkg/pkg.go
  src/testing/pkg/robot2/dao/dao.go
  src/testing/pkg/robot2/manager.go
Labels: target/2.2.0

#13533 Don't escape the name when doing the exact matching for tag
  src/pkg/artifact/dao/dao.go
Labels: target/2.2.0

#13472 add robot account version 2 controller
  src/controller/robot/controller.go
  src/controller/robot/controller_test.go
  src/controller/robot/model.go
  src/controller/robot/model_test.go
Labels: target/2.2.0

#13394 [CHERRY_PICK] fix(preheat): add location when create instance and policy
  api/v2.0/swagger.yaml
  src/server/v2.0/handler/preheat.go
Labels: area/P2P-Distribution, target/2.1.2

#13381 [CHERRY_PICK] fix(preheat): disable preheat model bool type json omitempty option
  api/v2.0/swagger.yaml
Labels: area/P2P-Distribution, target/2.1.2

#13330 fix: fix scanner apikey type match error
  src/pkg/scan/rest/auth/api_key_auth.go
  src/pkg/scan/rest/auth/auth.go
Labels: area/interrogation-service, area/vulnerability-scan, target/2.2.0

#13571 [Cherry pick]fix: remove auto re-readable body in BeforeRequest
  src/server/middleware/blob/put_manifest.go
  src/server/middleware/middleware.go
Labels: target/2.1.2

#13591 fix(quota): ignore the fail when getting reference of quota
  make/migrations/postgresql/0050_2.2.0_schema.up.sql
  src/controller/quota/controller.go
Labels: area/quota, target/2.2.0

#13537 Add more registry type to proxy cache
  make/photon/prepare/templates/core/env.jinja
Labels: kind/helm-chart-impact

#13500 Fix api ldap group search by name
  src/common/utils/ldap/ldap.go
  src/common/utils/ldap/ldap_test.go
  src/core/api/harborapi_test.go
  src/core/api/ldap_test.go
  src/testing/apitests/apilib/ldap.go
Labels: area/ldap, target/2.2.0

#13548 add robot account 2 api handler
  api/v2.0/legacy_swagger.yaml
  api/v2.0/swagger.yaml
  src/common/security/robot/context.go
  src/common/security/robot/context_test.go
  src/controller/robot/controller.go
  src/controller/robot/model.go
  src/controller/scan/base_controller.go
  src/controller/scan/base_controller_test.go
  src/controller/scan/controller.go
  src/core/api/harborapi_test.go
  src/core/api/robot.go
  src/core/api/robot_test.go
  src/core/service/notifications/jobs/handler.go
  src/pkg/permission/types/types.go
  src/pkg/robot/controller.go
  src/pkg/robot/controller_test.go
  src/pkg/robot/dao/robot.go
  src/pkg/robot/dao/robot_test.go
  src/pkg/robot/manager.go
  src/pkg/robot/manager_test.go
  src/pkg/robot/model/robot.go
  src/pkg/robot2/model/model.go
  src/pkg/scan/job.go
  src/pkg/scan/job_test.go
  src/server/middleware/security/robot.go
  src/server/middleware/security/robot2.go
  src/server/middleware/security/robot2_test.go
  src/server/middleware/security/security.go
  src/server/v2.0/handler/handler.go
  src/server/v2.0/handler/model/robot.go
  src/server/v2.0/handler/project.go
  src/server/v2.0/handler/robot.go
  src/server/v2.0/handler/robotV1.go
  src/server/v2.0/route/legacy.go
  src/testing/controller/controller.go
  src/testing/controller/robot/controller.go
  src/testing/controller/scan/controller.go
  src/testing/pkg/pkg.go
  src/testing/pkg/robot/dao/robot_account_dao.go
  tests/apitests/python/library/base.py
  tests/apitests/python/library/project.py
  tests/apitests/python/library/robot.py
  tests/apitests/python/test_push_chart_by_helm2_helm3_with_robot_Account.py
  tests/apitests/python/test_robot_account.py
Labels: area/robot-account, target/2.2.0

#13601 [cherry-pick] fix(chartmuseum) compatible s3 cache fail for 2.1.2
  make/photon/prepare/templates/chartserver/env.jinja
Labels: target/2.1.2

#13634 add with details option for list project
  api/v2.0/swagger.yaml
  src/controller/project/controller.go
  src/controller/project/options.go
  src/server/v2.0/handler/project.go
Labels: target/2.2.0
