Repository goharbor/harbor, pull requests merged in 2020-02, with the labels that each got.

#10549 add Middleware policycheck into v2 handler
  src/internal/error/errors.go
  src/server/middleware/contenttrust/contenttrust.go
  src/server/middleware/contenttrust/contenttrust_test.go
  src/server/middleware/manifestinfo/manifest_info.go
  src/server/middleware/util.go
  src/server/middleware/vulnerable/vulnerable.go
  src/server/middleware/vulnerable/vulnerable_test.go
  src/server/registry/handler.go
Labels: area/OCI, target/2.0.0

#10588 Implement artifact/tag related API
  api/v2.0/swagger.yaml
  src/api/artifact/controller.go
  src/api/artifact/controller_test.go
  src/go.mod
  src/server/v2.0/handler/artifact.go
Labels: area/OCI, target/2.0.0

#10636 fix issue on listing robot accounts
  src/pkg/robot/controller_test.go
  src/pkg/robot/dao/robot.go
Labels: area/robot-account, target/1.10.1

#10627 Add child artifact digest in reference model
  api/v2.0/swagger.yaml
  src/api/artifact/model.go
  src/pkg/artifact/manager.go
  src/pkg/artifact/manager_test.go
  src/pkg/artifact/model.go
Labels: area/OCI, target/2.0.0

#10628 set the immutable status on getting/listting tag
  api/v2.0/swagger.yaml
  src/api/artifact/controller.go
  src/api/artifact/controller_test.go
  src/api/artifact/model.go
  src/core/api/repository.go
  src/core/middlewares/interceptor/immutable/deletemf.go
  src/core/middlewares/interceptor/immutable/pushmf.go
  src/pkg/immutabletag/match/matcher.go
  src/pkg/immutabletag/match/rule/match.go
  src/pkg/immutabletag/match/rule/match_test.go
  src/pkg/retention/policy/action/performer.go
  src/server/middleware/immutable/deletemf.go
  src/server/middleware/immutable/pushmf.go
  src/testing/pkg/immutabletag/matcher.go
Labels: area/OCI, target/2.0.0

#10649 [CHERRY-PICK] fix[jobservice]:job status is hung after restart
  src/jobservice/common/list/list.go
  src/jobservice/common/list/list_test.go
  src/jobservice/common/rds/keys.go
  src/jobservice/common/rds/scripts.go
  src/jobservice/common/rds/utils.go
  src/jobservice/hook/hook_agent.go
  src/jobservice/hook/hook_agent_test.go
  src/jobservice/hook/hook_client_test.go
  src/jobservice/job/impl/context_test.go
  src/jobservice/job/impl/sample/job.go
  src/jobservice/job/models.go
  src/jobservice/job/tracker.go
  src/jobservice/job/tracker_test.go
  src/jobservice/lcm/controller.go
  src/jobservice/lcm/controller_test.go
  src/jobservice/mgt/manager.go
  src/jobservice/mgt/manager_test.go
  src/jobservice/period/basic_scheduler.go
  src/jobservice/period/basic_scheduler_test.go
  src/jobservice/period/enqueuer.go
  src/jobservice/period/enqueuer_test.go
  src/jobservice/period/policy_store.go
  src/jobservice/period/policy_store_test.go
  src/jobservice/period/scheduler.go
  src/jobservice/runner/redis.go
  src/jobservice/runner/redis_test.go
  src/jobservice/runtime/bootstrap.go
  src/jobservice/worker/cworker/c_worker.go
  src/jobservice/worker/cworker/reaper.go
  src/jobservice/worker/cworker/reaper_test.go
Labels: target/1.10.1

#10651 Bump up version to v1.10.1
  VERSION
Labels: target/1.10.1

#10643 Add permission check for artifact related APIs
  api/v2.0/swagger.yaml
  src/common/rbac/const.go
  src/common/rbac/project/util.go
  src/common/rbac/project/visitor_role.go
  src/server/v2.0/handler/artifact.go
  src/server/v2.0/handler/base.go
Labels: area/OCI, target/2.0.0

#10662 Implement repository deletion API
  api/v2.0/swagger.yaml
  src/api/artifact/controller.go
  src/api/repository/controller.go
  src/api/repository/controller_test.go
  src/server/v2.0/handler/handler.go
  src/server/v2.0/handler/repository.go
  src/testing/api/repository/controller.go
Labels: area/OCI, target/2.0.0

#10652 Use controller rather than manager in the API handler and middleware
  src/server/middleware/immutable/deletemf.go
  src/server/middleware/immutable/pushmf.go
  src/server/middleware/util.go
Labels: area/OCI, target/2.0.0

#10626 Unify the method/style to handle error in handler/middleware
  api/v2.0/swagger.yaml
  src/common/api/base.go
  src/server/error/error.go
  src/server/error/error_test.go
  src/server/middleware/artifactinfo/artifact_info.go
  src/server/middleware/contenttrust/contenttrust.go
  src/server/middleware/immutable/deletemf.go
  src/server/middleware/immutable/pushmf.go
  src/server/middleware/manifestinfo/manifest_info.go
  src/server/middleware/readonly/readonly.go
  src/server/middleware/regtoken/regtoken.go
  src/server/middleware/transaction/transaction.go
  src/server/middleware/v2auth/auth.go
  src/server/middleware/vulnerable/vulnerable.go
  src/server/registry/catalog.go
  src/server/registry/error/error.go
  src/server/registry/manifest.go
  src/server/registry/tag.go
  src/server/v2.0/handler/handler.go
Labels: area/OCI, target/2.0.0

#10581 Add query string to listing artifact API to support specify only show the tagged artifacts
  api/v2.0/swagger.yaml
  src/pkg/artifact/dao/dao.go
  src/pkg/artifact/dao/dao_test.go
  src/pkg/q/query.go
  src/pkg/q/query_test.go
  src/server/v2.0/handler/artifact.go
Labels: area/OCI, target/2.0.0

#10681 Bump up the version of legacy APIs to v2.0
  Makefile
  api/v2.0/README.md
  api/v2.0/legacy_swagger.yaml
  make/photon/portal/Dockerfile
  src/server/route.go
  src/server/server.go
  src/server/v1.0/route/route.go
  src/server/v2.0/route/legacy.go
  src/server/v2.0/route/route.go
  tests/apitests/python/test_retention.py
  tests/apitests/python/testutils.py
  tests/configharbor.py
  tests/robot-cases/Group0-BAT/API_DB.robot
Labels: area/OCI, target/2.0.0

#10612 Do enhancement for the registry authorizer
  src/common/utils/registry/auth/authorizer.go
  src/common/utils/registry/auth/nullauthorizer.go
  src/replication/adapter/native/adapter.go
  tests/robot-cases/Group0-BAT/API_DB.robot
Labels: area/OCI, target/2.0.0

#10714 Fix bugs when pushing image(with index) and CNAB
  src/api/artifact/abstractor/resolver/image/index.go
  src/api/artifact/abstractor/resolver/image/index_test.go
  src/api/artifact/controller.go
  src/api/artifact/controller_test.go
  src/go.mod
  src/pkg/artifact/dao/dao.go
  src/pkg/artifact/dao/dao_test.go
  src/pkg/artifact/manager.go
  src/pkg/artifact/manager_test.go
  src/server/error/error.go
  src/server/error/error_test.go
  src/server/middleware/util.go
  src/server/middleware/v2auth/auth.go
  src/server/registry/proxy.go
  src/testing/pkg/artifact/manager.go
Labels: area/OCI, target/2.0.0

#10725 Improve swagger.yaml
  api/v2.0/swagger.yaml
Labels: area/OCI, target/2.0.0

#10682 Support add/remove label to/from artifact
  api/v2.0/swagger.yaml
  make/migrations/postgresql/0030_1.11.0_schema.up.sql
  src/api/artifact/controller.go
  src/api/artifact/controller_test.go
  src/api/artifact/model.go
  src/common/rbac/const.go
  src/common/rbac/project/visitor_role.go
  src/pkg/artifact/dao/dao.go
  src/pkg/label/dao.go
  src/pkg/label/dao_test.go
  src/pkg/label/manager.go
  src/pkg/label/manager_test.go
  src/pkg/label/model.go
  src/pkg/tag/dao/dao.go
  src/server/v2.0/handler/artifact.go
  src/testing/api/artifact/controller.go
  src/testing/pkg/label/manager.go
Labels: area/OCI, target/2.0.0

#10720 Get addition properties for chart
  src/api/artifact/abstractor/resolver/chart/chart.go
  src/api/artifact/abstractor/resolver/chart/chart_test.go
  src/go.mod
  src/go.sum
  src/pkg/chart/model.go
  src/pkg/chart/operator.go
  src/pkg/chart/opetator_test.go
  src/testing/pkg/chart/operator.go
  src/vendor/github.com/cyphar/filepath-securejoin/.travis.yml
  src/vendor/github.com/cyphar/filepath-securejoin/LICENSE
  src/vendor/github.com/cyphar/filepath-securejoin/README.md
  src/vendor/github.com/cyphar/filepath-securejoin/VERSION
  src/vendor/github.com/cyphar/filepath-securejoin/join.go
  src/vendor/github.com/cyphar/filepath-securejoin/vendor.conf
  src/vendor/github.com/cyphar/filepath-securejoin/vfs.go
  src/vendor/k8s.io/helm/LICENSE
  src/vendor/k8s.io/helm/cmd/helm/search/search.go
  src/vendor/k8s.io/helm/pkg/chartutil/capabilities.go
  src/vendor/k8s.io/helm/pkg/chartutil/capabilities_versions_generated.go
  src/vendor/k8s.io/helm/pkg/chartutil/chartfile.go
  src/vendor/k8s.io/helm/pkg/chartutil/create.go
  src/vendor/k8s.io/helm/pkg/chartutil/doc.go
  src/vendor/k8s.io/helm/pkg/chartutil/expand.go
  src/vendor/k8s.io/helm/pkg/chartutil/files.go
  src/vendor/k8s.io/helm/pkg/chartutil/load.go
  src/vendor/k8s.io/helm/pkg/chartutil/requirements.go
  src/vendor/k8s.io/helm/pkg/chartutil/save.go
  src/vendor/k8s.io/helm/pkg/chartutil/transform.go
  src/vendor/k8s.io/helm/pkg/chartutil/values.go
  src/vendor/k8s.io/helm/pkg/getter/doc.go
  src/vendor/k8s.io/helm/pkg/getter/getter.go
  src/vendor/k8s.io/helm/pkg/getter/httpgetter.go
  src/vendor/k8s.io/helm/pkg/getter/plugingetter.go
  src/vendor/k8s.io/helm/pkg/helm/environment/environment.go
  src/vendor/k8s.io/helm/pkg/helm/helmpath/helmhome.go
  src/vendor/k8s.io/helm/pkg/ignore/doc.go
  src/vendor/k8s.io/helm/pkg/ignore/rules.go
  src/vendor/k8s.io/helm/pkg/plugin/hooks.go
  src/vendor/k8s.io/helm/pkg/plugin/plugin.go
  src/vendor/k8s.io/helm/pkg/proto/hapi/chart/chart.pb.go
  src/vendor/k8s.io/helm/pkg/proto/hapi/chart/config.pb.go
  src/vendor/k8s.io/helm/pkg/proto/hapi/chart/metadata.pb.go
  src/vendor/k8s.io/helm/pkg/proto/hapi/chart/template.pb.go
  src/vendor/k8s.io/helm/pkg/proto/hapi/version/version.pb.go
  src/vendor/k8s.io/helm/pkg/provenance/doc.go
  src/vendor/k8s.io/helm/pkg/provenance/sign.go
  src/vendor/k8s.io/helm/pkg/repo/chartrepo.go
  src/vendor/k8s.io/helm/pkg/repo/doc.go
  src/vendor/k8s.io/helm/pkg/repo/index.go
  src/vendor/k8s.io/helm/pkg/repo/local.go
  src/vendor/k8s.io/helm/pkg/repo/repo.go
  src/vendor/k8s.io/helm/pkg/sympath/walk.go
  src/vendor/k8s.io/helm/pkg/tlsutil/cfg.go
  src/vendor/k8s.io/helm/pkg/tlsutil/tls.go
  src/vendor/k8s.io/helm/pkg/urlutil/urlutil.go
  src/vendor/k8s.io/helm/pkg/version/compatible.go
  src/vendor/k8s.io/helm/pkg/version/doc.go
  src/vendor/k8s.io/helm/pkg/version/version.go
  src/vendor/modules.txt
Labels: area/OCI, target/2.0.0

#10727 Bump up legacy api version to v2.0
  Makefile
  api/v2.0/README.md
  api/v2.0/legacy_swagger.yaml
  make/photon/portal/Dockerfile
  src/portal/src/app/app.module.ts
  src/portal/src/app/base-href-intercept.service.spec.ts
  src/portal/src/app/base-href-intercept.service.ts
  src/server/route.go
  src/server/server.go
  src/server/v1.0/route/route.go
  src/server/v2.0/route/legacy.go
  src/server/v2.0/route/route.go
  tests/apitests/python/test_retention.py
  tests/apitests/python/testutils.py
  tests/configharbor.py
  tests/robot-cases/Group0-BAT/API_DB.robot
Labels: area/OCI, target/2.0.0

#10746 Move the scan overview populating logic to API handler
  api/v2.0/swagger.yaml
  src/api/artifact/abstractor/resolver/image/manifest_v2.go
  src/api/artifact/abstractor/resolver/image/manifest_v2_test.go
  src/api/artifact/controller.go
  src/api/artifact/controller_test.go
  src/api/artifact/model.go
  src/server/v2.0/handler/artifact.go
  src/server/v2.0/handler/model/artifact.go
Labels: area/OCI, target/2.0.0

#10734 Refactor the logic of deleting artifact
  src/api/artifact/controller.go
  src/api/artifact/controller_test.go
  src/api/artifact/model.go
  src/pkg/artifact/dao/dao.go
  src/pkg/artifact/dao/dao_test.go
  src/pkg/artifact/manager.go
  src/pkg/artifact/manager_test.go
  src/pkg/artifact/model.go
  src/pkg/tag/dao/dao.go
  src/pkg/tag/dao/dao_test.go
  src/pkg/tag/manager.go
  src/pkg/tag/manager_test.go
  src/pkg/tag/model/tag/model.go
  src/testing/pkg/artifact/manager.go
  src/testing/pkg/tag/manager.go
Labels: area/OCI, target/2.0.0

#10752 update the enum value for chart on api get the addition
  api/v2.0/swagger.yaml
Labels: area/OCI, target/2.0.0

#10735 Scan reorganize
  src/api/scan/all_handler.go
  src/api/scan/base_controller.go
  src/api/scan/base_controller_test.go
  src/api/scan/controller.go
  src/api/scan/options.go
  src/api/scanner/base_controller.go
  src/api/scanner/base_controller_test.go
  src/api/scanner/controller.go
  src/core/api/admin_job.go
  src/core/api/pro_scanner.go
  src/core/api/pro_scanner_test.go
  src/core/api/repository.go
  src/core/api/scan.go
  src/core/api/scan_all.go
  src/core/api/scan_test.go
  src/core/api/scanners.go
  src/core/api/scanners_test.go
  src/core/middlewares/vulnerable/handler.go
  src/core/notifier/handler/notification/scan_image_handler.go
  src/core/notifier/handler/notification/scan_image_handler_test.go
  src/core/service/notifications/admin/handler.go
  src/core/service/notifications/jobs/handler.go
  src/core/service/notifications/registry/handler.go
  src/pkg/scan/all/checkin.go
  src/pkg/scan/all/job.go
  src/pkg/scan/api/scan/all_handler.go
  src/pkg/scan/event/notification.go
  src/server/middleware/vulnerable/vulnerable.go
Labels: area/vulnerability-scan, target/2.0.0

#10694 chore(install): Add --with-trivy arg to the installation script
  Makefile
  make/harbor.yml.tmpl
  make/install.sh
  make/photon/Makefile
  make/photon/clair-adapter/builder.sh
  make/photon/prepare/main.py
  make/photon/prepare/templates/core/env.jinja
  make/photon/prepare/templates/docker_compose/docker-compose.yml.jinja
  make/photon/prepare/templates/trivy-adapter/env.jinja
  make/photon/prepare/utils/configs.py
  make/photon/prepare/utils/core.py
  make/photon/prepare/utils/docker_compose.py
  make/photon/prepare/utils/trivy_adapter.py
  make/photon/trivy-adapter/Dockerfile
  make/photon/trivy-adapter/Dockerfile.base
  make/photon/trivy-adapter/Dockerfile.binary
  make/photon/trivy-adapter/builder.sh
  src/common/config/metadata/metadatalist.go
  src/common/const.go
  src/core/config/config.go
  src/core/main.go
  src/pkg/scan/init.go
  src/pkg/scan/init_test.go
Labels: area/interrogation-service, area/vulnerability-scan

#10753 add artifact trash manager
  make/migrations/postgresql/0030_1.11.0_schema.up.sql
  src/api/artifact/controller.go
  src/api/artifact/controller_test.go
  src/pkg/artifact/dao/dao.go
  src/pkg/artifactrash/dao/dao.go
  src/pkg/artifactrash/dao/dao_test.go
  src/pkg/artifactrash/manager.go
  src/pkg/artifactrash/manager_test.go
  src/pkg/artifactrash/model/model.go
  src/registryctl/api/registry.go
  src/testing/pkg/artifactrash/manager.go
Labels: area/OCI, target/2.0.0

#10756 Implement delete/update repository API
  api/v2.0/swagger.yaml
  src/api/artifact/controller.go
  src/api/artifact/controller_test.go
  src/api/repository/controller.go
  src/api/repository/controller_test.go
  src/api/scan/all_handler.go
  src/common/models/repo.go
  src/go.mod
  src/pkg/artifact/manager.go
  src/pkg/artifact/manager_test.go
  src/pkg/repository/manager.go
  src/pkg/repository/manager_test.go
  src/pkg/retention/launcher.go
  src/pkg/retention/launcher_test.go
  src/pkg/tag/manager.go
  src/pkg/tag/manager_test.go
  src/server/registry/catalog.go
  src/server/registry/catalog_test.go
  src/server/registry/tag.go
  src/server/registry/tag_test.go
  src/server/v2.0/handler/artifact.go
  src/server/v2.0/handler/repository.go
  src/testing/api/artifact/controller.go
  src/testing/api/repository/controller.go
  src/testing/pkg/artifact/manager.go
  src/testing/pkg/repository/manager.go
  src/testing/pkg/tag/manager.go
Labels: area/OCI, target/2.0.0

#10733 Implement copy artifact API
  api/v2.0/swagger.yaml
  src/api/artifact/controller.go
  src/api/artifact/controller_test.go
  src/common/rbac/project/visitor_role.go
  src/pkg/registry/client.go
  src/server/v2.0/handler/artifact.go
  src/server/v2.0/handler/artifact_test.go
  src/testing/api/artifact/controller.go
  src/testing/pkg/registry/client.go
Labels: area/OCI, target/2.0.0

#10710 feat(middleware): add blob middlewares
  Makefile
  src/api/artifact/controller.go
  src/api/artifact/controller_test.go
  src/api/blob/controller.go
  src/api/blob/controller_test.go
  src/api/blob/options.go
  src/api/project/controller.go
  src/api/project/controller_test.go
  src/api/repository/controller_test.go
  src/common/dao/artifact_blob_test.go
  src/internal/error/errors.go
  src/internal/orm/error.go
  src/internal/orm/query.go
  src/internal/request.go
  src/internal/request_test.go
  src/internal/response_buffer.go
  src/pkg/blob/dao/dao.go
  src/pkg/blob/dao/dao_test.go
  src/pkg/blob/manager.go
  src/pkg/blob/manager_test.go
  src/pkg/blob/models/blob.go
  src/pkg/distribution/distribution.go
  src/pkg/distribution/distribution_test.go
  src/pkg/q/query.go
  src/server/middleware/blob/controller.go
  src/server/middleware/blob/patch_blob_upload.go
  src/server/middleware/blob/patch_blob_upload_test.go
  src/server/middleware/blob/post_initiate_blob_upload.go
  src/server/middleware/blob/post_initiate_blob_upload_test.go
  src/server/middleware/blob/put_blob_upload.go
  src/server/middleware/blob/put_blob_upload_test.go
  src/server/middleware/blob/put_manifest.go
  src/server/middleware/blob/put_manifest_test.go
  src/server/middleware/middleware.go
  src/server/registry/route.go
  src/testing/pkg/blob/manager.go
  src/testing/pkg/pkg.go
  src/testing/pkg/project/manager.go
  src/testing/suite.go
  tests/apitests/python/testutils.py
Labels: area/quota, target/2.0.0

#10781 refactor(scan,auth): remove bearer token auth support for scan job
  src/api/scan/base_controller.go
Labels: area/vulnerability-scan, target/2.0.0

#10789 Upgrade the artifact table
  make/migrations/postgresql/0030_1.11.0_schema.up.sql
  make/migrations/postgresql/0030_2.0.0_schema.up.sql
  src/common/dao/artifact.go
  src/common/dao/blob.go
  src/common/dao/project_blob.go
  src/common/models/artifact.go
  src/pkg/artifact/dao/dao.go
  src/pkg/artifact/dao/model.go
  src/pkg/artifactrash/dao/dao.go
  src/pkg/blob/dao/dao.go
  src/pkg/blob/dao/dao_test.go
  src/pkg/blob/manager_test.go
Labels: area/OCI, target/2.0.0

#10736 Implement the resolver for CNAB
  src/api/artifact/abstractor/abstractor.go
  src/api/artifact/abstractor/abstractor_test.go
  src/api/artifact/abstractor/resolver/cnab/cnab.go
  src/api/artifact/abstractor/resolver/cnab/cnab_test.go
  src/api/artifact/controller.go
  src/api/artifact/descriptor/descriptor.go
  src/api/artifact/descriptor/descriptor_test.go
  src/pkg/distribution/distribution.go
  src/server/router/router.go
  src/vendor/github.com/docker/distribution/manifest/ocischema/builder.go
  src/vendor/github.com/docker/distribution/manifest/ocischema/manifest.go
  src/vendor/modules.txt
Labels: area/OCI, target/2.0.0

#10751 Remove dead code
  api/v2.0/legacy_swagger.yaml
  make/photon/prepare/templates/core/env.jinja
  src/common/dao/dao_test.go
  src/common/dao/repository.go
  src/common/dao/repository_test.go
  src/common/models/retag.go
  src/common/models/retag_test.go
  src/core/api/harborapi_test.go
  src/core/api/internal.go
  src/core/api/repository.go
  src/core/api/repository_label.go
  src/core/api/repository_label_test.go
  src/core/api/repository_test.go
  src/core/api/utils.go
  src/core/controllers/controllers_test.go
  src/core/main.go
  src/core/middlewares/chain.go
  src/core/middlewares/config.go
  src/core/middlewares/contenttrust/handler.go
  src/core/middlewares/contenttrust/handler_test.go
  src/core/middlewares/countquota/builder.go
  src/core/middlewares/countquota/handler.go
  src/core/middlewares/countquota/handler_test.go
  src/core/middlewares/countquota/util.go
  src/core/middlewares/immutable/builder.go
  src/core/middlewares/immutable/handler.go
  src/core/middlewares/immutable/handler_test.go
  src/core/middlewares/inlet.go
  src/core/middlewares/interceptor/immutable/deletemf.go
  src/core/middlewares/interceptor/immutable/pushmf.go
  src/core/middlewares/listrepo/handler.go
  src/core/middlewares/listrepo/handler_test.go
  src/core/middlewares/readonly/hanlder.go
  src/core/middlewares/registryproxy/handler.go
  src/core/middlewares/regtoken/handler.go
  src/core/middlewares/regtoken/handler_test.go
  src/core/middlewares/sizequota/builder.go
  src/core/middlewares/sizequota/handler.go
  src/core/middlewares/sizequota/handler_test.go
  src/core/middlewares/sizequota/util.go
  src/core/middlewares/sizequota/util_test.go
  src/core/middlewares/url/handler.go
  src/core/middlewares/url/handler_test.go
  src/core/middlewares/util/error/immutable.go
  src/core/middlewares/vulnerable/handler.go
  src/core/service/notifications/registry/handler.go
  src/core/utils/retag.go
  src/core/utils/utils.go
  src/core/utils/utils_test.go
  src/server/route.go
  src/server/v2.0/route/legacy.go
  tests/robot-cases/Group0-BAT/API_DB.robot
  tests/robot-cases/Group0-BAT/API_LDAP.robot
Labels: area/OCI, target/2.0.0

#10803 Revise the GC job flow
  api/v2.0/legacy_swagger.yaml
  make/migrations/postgresql/0030_2.0.0_schema.up.sql
  src/common/dao/admin_job.go
  src/common/dao/admin_job_test.go
  src/common/models/adminjob.go
  src/core/api/admin_job.go
  src/core/api/models/admin_job.go
  src/core/api/models/admin_job_test.go
  src/core/api/reg_gc.go
  src/core/api/reg_gc_test.go
  src/jobservice/job/impl/default_context.go
  src/jobservice/job/impl/gc/garbage_collection.go
  src/jobservice/job/impl/gc/garbage_collection_test.go
  src/jobservice/job/impl/gc/util.go
  src/jobservice/runner/redis_test.go
  src/jobservice/worker/cworker/c_worker_test.go
  src/pkg/artifactrash/dao/dao.go
  src/pkg/artifactrash/dao/dao_test.go
  src/pkg/artifactrash/manager.go
  src/pkg/artifactrash/manager_test.go
  src/testing/apitests/apilib/admin_job_req.go
  src/testing/pkg/artifactrash/manager.go
Labels: area/OCI, target/2.0.0

#10802 Upgrade repository API tests to V2.0
  Makefile
  tests/apitests/python/library/artifact.py
  tests/apitests/python/library/base.py
  tests/apitests/python/library/repository.py
  tests/apitests/python/test_add_sys_label_to_tag.py
  tests/apitests/python/test_copy_artifact_outside_project.py
  tests/apitests/python/test_del_repo.py
  tests/apitests/python/test_garbage_collection.py
  tests/apitests/python/test_manage_project_member.py
  tests/apitests/python/test_project_level_policy_content_trust.py
  tests/apitests/python/test_retention.py
  tests/apitests/python/test_robot_account.py
  tests/apitests/python/test_sign_image.py
  tests/robot-cases/Group0-BAT/API_DB.robot
Labels: target/2.0.0

#10834 Implement the API to get the specified repository
  api/v2.0/swagger.yaml
  src/server/v2.0/handler/repository.go
Labels: area/OCI, target/2.0.0

#10831 add readonly to beego middleware
  src/core/middlewares/middlewares.go
  src/core/middlewares/middlewares_test.go
  src/server/middleware/readonly/readonly.go
  src/server/registry/route.go
Labels: area/OCI, target/2.0.0

#10842 Fix some detail function
  src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
  src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.spec.ts
  src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
  src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list.component.spec.ts
  src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list.component.ts
  src/portal/src/app/project/repository/artifact/artifact-common-properties/artifact-common-properties.component.html
  src/portal/src/app/project/repository/artifact/artifact-common-properties/artifact-common-properties.component.ts
  src/portal/src/app/project/repository/artifact/artifact-summary.component.html
  src/portal/src/app/project/repository/artifact/artifact-tag/artifact-tag.component.html
  src/portal/src/app/project/repository/artifact/artifact-tag/artifact-tag.component.ts
  src/portal/src/app/project/repository/artifact/artifact.service.ts
  src/portal/src/app/project/repository/artifact/artifact.ts
  src/portal/src/app/project/repository/repository-gridview.component.ts
  src/portal/src/app/project/repository/vulnerability-scanning/result-bar-chart.component.ts
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/images/artifact-cnab.svg
  src/portal/src/lib/services/channel.service.ts
Labels: target/2.0.0

#10844 Use the repository name of artifact model
  make/migrations/postgresql/0030_2.0.0_schema.up.sql
  src/api/artifact/abstractor/abstractor.go
  src/api/artifact/abstractor/abstractor_test.go
  src/api/artifact/abstractor/resolver/chart/chart.go
  src/api/artifact/abstractor/resolver/chart/chart_test.go
  src/api/artifact/abstractor/resolver/cnab/cnab.go
  src/api/artifact/abstractor/resolver/cnab/cnab_test.go
  src/api/artifact/abstractor/resolver/image/index.go
  src/api/artifact/abstractor/resolver/image/manifest_v2.go
  src/api/artifact/abstractor/resolver/image/manifest_v2_test.go
  src/api/artifact/controller.go
  src/api/artifact/controller_test.go
  src/pkg/artifact/dao/dao.go
  src/pkg/artifact/dao/dao_test.go
  src/pkg/artifact/dao/model.go
  src/pkg/artifact/manager.go
  src/pkg/artifact/manager_test.go
  src/pkg/artifact/model.go
  src/pkg/blob/dao/dao_test.go
  src/pkg/blob/manager_test.go
  src/server/middleware/immutable/pushmf_test.go
  src/server/registry/manifest.go
  src/server/v2.0/handler/artifact.go
  src/testing/api/artifact/controller.go
  src/testing/pkg/artifact/manager.go
Labels: area/OCI, target/2.0.0

#10792 Fix URL issue introduced by api version
  src/chartserver/handler_manipulation.go
  src/chartserver/handler_proxy_traffic_test.go
  src/chartserver/reverse_proxy.go
  src/chartserver/reverse_proxy_test.go
  src/common/api/base.go
  src/core/api/chart_label_test.go
  src/core/api/chart_repository.go
  src/core/api/chart_repository_test.go
  src/core/api/harborapi_test.go
  src/core/filter/security.go
  src/core/middlewares/chart/builder.go
  src/core/middlewares/chart/handler_test.go
  src/pkg/clients/core/chart.go
  src/replication/adapter/harbor/adapter.go
  src/replication/adapter/harbor/chart_registry.go
  src/replication/adapter/harbor/chart_registry_test.go
Labels: target/2.0.0

#10833 Update existing API tests for API V2.0
  tests/apitests/python/library/artifact.py
  tests/apitests/python/test_add_member_to_private_project.py
  tests/apitests/python/test_add_replication_rule.py
  tests/apitests/python/test_add_sys_label_to_tag.py
  tests/apitests/python/test_assign_role_to_ldap_group.py
  tests/apitests/python/test_assign_sys_admin.py
  tests/apitests/python/test_copy_artifact_outside_project.py
  tests/apitests/python/test_del_repo.py
  tests/apitests/python/test_garbage_collection.py
  tests/apitests/python/test_manage_project_member.py
  tests/apitests/python/test_project_level_policy_content_trust.py
  tests/apitests/python/test_project_quota.py
  tests/apitests/python/test_retention.py
  tests/apitests/python/test_robot_account.py
  tests/apitests/python/test_scan_all_images.py
  tests/apitests/python/test_scan_image.py
  tests/apitests/python/test_sign_image.py
  tests/apitests/python/testutils.py
  tests/robot-cases/Group0-BAT/API_DB.robot
Labels: target/2.0.0

#10868 Add "Docker-Distribution-Api-Version" header for the 401 response of registry API
  src/server/middleware/v2auth/auth.go
Labels: area/OCI, target/2.0.0

#10882 add tag controller
  src/api/artifact/controller.go
  src/api/artifact/controller_test.go
  src/api/artifact/model.go
  src/api/tag/controller.go
  src/api/tag/controller_test.go
  src/api/tag/model.go
  src/pkg/retention/dep/client_test.go
  src/server/middleware/immutable/deletemf.go
  src/server/middleware/immutable/pushmf.go
  src/server/registry/tag.go
  src/server/registry/tag_test.go
  src/server/v2.0/handler/artifact.go
  src/testing/api/artifact/controller.go
  src/testing/api/tag/controller.go
  tests/apitests/python/test_sign_image.py
Labels: area/OCI, target/2.0.0

#10864 Set the "Link" and "location" header
  api/v2.0/swagger.yaml
  src/server/v2.0/handler/artifact.go
  src/server/v2.0/handler/base.go
  src/server/v2.0/handler/base_test.go
  src/server/v2.0/handler/repository.go
Labels: area/OCI, target/2.0.0

#10841 Migrate artifact data in 2.0
  make/migrations/postgresql/0030_2.0.0_schema.up.sql
  src/api/artifact/controller.go
  src/api/artifact/controller_test.go
  src/common/dao/base.go
  src/common/dao/pgsql.go
  src/common/dao/project.go
  src/common/utils/test/database.go
  src/core/main.go
  src/migration/artifact.go
  src/migration/migration.go
  src/pkg/artifact/manager.go
  src/pkg/artifact/manager_test.go
  src/testing/pkg/artifact/manager.go
Labels: target/2.0.0
