Repository goharbor/harbor, pull requests merged in 2020-03, with the labels that each got.

#10857 feat(oci) remove dead code pkg/art
  src/api/tag/controller.go
  src/pkg/art/basic_controller_test.go
  src/pkg/art/basic_manager.go
  src/pkg/art/basic_manager_test.go
  src/pkg/art/controller.go
  src/pkg/art/manager.go
  src/pkg/art/result.go
  src/pkg/artifactselector/candidate.go
  src/pkg/artifactselector/result.go
  src/pkg/artifactselector/selector.go
  src/pkg/artifactselector/selectors/doublestar/selector.go
  src/pkg/artifactselector/selectors/doublestar/selector_test.go
  src/pkg/artifactselector/selectors/index/index.go
  src/pkg/artifactselector/selectors/label/selector.go
  src/pkg/artifactselector/selectors/label/selector_test.go
  src/pkg/immutabletag/match/matcher.go
  src/pkg/immutabletag/match/rule/match.go
  src/pkg/immutabletag/match/rule/match_test.go
  src/pkg/retention/dep/client.go
  src/pkg/retention/dep/client_test.go
  src/pkg/retention/job.go
  src/pkg/retention/job_test.go
  src/pkg/retention/launcher.go
  src/pkg/retention/launcher_test.go
  src/pkg/retention/policy/action/index/index_test.go
  src/pkg/retention/policy/action/performer.go
  src/pkg/retention/policy/action/performer_test.go
  src/pkg/retention/policy/alg/or/processor.go
  src/pkg/retention/policy/alg/or/processor_test.go
  src/pkg/retention/policy/alg/processor.go
  src/pkg/retention/policy/builder.go
  src/pkg/retention/policy/builder_test.go
  src/pkg/retention/policy/rule/always/evaluator.go
  src/pkg/retention/policy/rule/always/evaluator_test.go
  src/pkg/retention/policy/rule/dayspl/evaluator.go
  src/pkg/retention/policy/rule/dayspl/evaluator_test.go
  src/pkg/retention/policy/rule/daysps/evaluator.go
  src/pkg/retention/policy/rule/daysps/evaluator_test.go
  src/pkg/retention/policy/rule/evaluator.go
  src/pkg/retention/policy/rule/index/index_test.go
  src/pkg/retention/policy/rule/lastx/evaluator.go
  src/pkg/retention/policy/rule/lastx/evaluator_test.go
  src/pkg/retention/policy/rule/latestk/evaluator.go
  src/pkg/retention/policy/rule/latestk/evaluator_test.go
  src/pkg/retention/policy/rule/latestpl/evaluator.go
  src/pkg/retention/policy/rule/latestpl/evaluator_test.go
  src/pkg/retention/policy/rule/latestps/evaluator.go
  src/pkg/retention/policy/rule/latestps/evaluator_test.go
  src/pkg/retention/policy/rule/nothing/evaluator.go
  src/pkg/retention/policy/rule/nothing/evaluator_test.go
  src/pkg/scan/event/notification.go
  src/testing/pkg/immutabletag/matcher.go
Labels: target/2.0.0

#10815 Set redis idle timeout for core
  make/harbor.yml.tmpl
  make/photon/prepare/templates/core/env.jinja
  make/photon/prepare/utils/configs.py
Labels: target/2.0.0

#10892 feat(addition-link): only set vuls addition link when artifact scanable
  src/api/artifact/controller.go
  src/api/repository/controller_test.go
  src/api/scan/base_controller_test.go
  src/api/scan/checker.go
  src/api/scan/checker_test.go
  src/api/scanner/base_controller.go
  src/api/scanner/controller.go
  src/api/scanner/options.go
  src/core/api/pro_scanner_test.go
  src/core/api/scanners_test.go
  src/pkg/scan/dao/scanner/model.go
  src/pkg/scan/rest/v1/models.go
  src/server/registry/manifest_test.go
  src/server/v2.0/handler/assembler/vul.go
  src/server/v2.0/handler/assembler/vul_test.go
  src/testing/api/api.go
  src/testing/api/artifact/controller.go
  src/testing/api/scan/checker.go
  src/testing/api/scanner/controller.go
  src/testing/mock/mock.go
Labels: area/vulnerability-scan, target/2.0.0

#10886 Fix transaction issue
  src/api/artifact/controller.go
  src/api/artifact/controller_test.go
  src/api/repository/controller.go
  src/api/repository/controller_test.go
  src/api/tag/controller.go
  src/api/tag/controller_test.go
  src/testing/lib/orm/orm.go
Labels: area/OCI, target/2.0.0

#10908 add delete manifest middleware
  src/server/middleware/contenttrust/contenttrust.go
  src/server/middleware/immutable/deletemf.go
  src/server/middleware/immutable/deletemf_test.go
  src/server/middleware/immutable/pushmf.go
  src/server/middleware/immutable/pushmf_test.go
  src/server/registry/route.go
Labels: target/2.0.0, target/FC

#10939 add audit logs API
  api/v2.0/swagger.yaml
  make/migrations/postgresql/0030_2.0.0_schema.up.sql
  src/pkg/audit/dao/dao.go
  src/pkg/audit/dao/dao_test.go
  src/pkg/audit/manager.go
  src/pkg/audit/manager_test.go
  src/pkg/audit/model/model.go
  src/server/v2.0/handler/auditlog.go
  src/server/v2.0/handler/auditlog_test.go
  src/server/v2.0/handler/handler.go
Labels: target/2.0.0, target/FC

#10923 Make sure replication work with OCI artifacts(phase 1)
  src/replication/adapter/adapter.go
  src/replication/adapter/aliacr/adapter.go
  src/replication/adapter/harbor/adapter.go
  src/replication/adapter/harbor/chart_registry.go
  src/replication/adapter/harbor/chart_registry_test.go
  src/replication/adapter/harbor/image_registry.go
  src/replication/adapter/harbor/image_registry_test.go
  src/replication/adapter/helmhub/chart_registry.go
  src/replication/adapter/helmhub/chart_registry_test.go
  src/replication/adapter/huawei/huawei_adapter.go
  src/replication/adapter/huawei/image_registry.go
  src/replication/adapter/native/adapter.go
  src/replication/adapter/native/adapter_test.go
  src/replication/event/handler.go
  src/replication/event/handler_test.go
  src/replication/filter/artifact.go
  src/replication/filter/filter.go
  src/replication/filter/filter_test.go
  src/replication/filter/repository.go
  src/replication/filter/resource.go
  src/replication/model/policy.go
  src/replication/model/resource.go
  src/replication/model/resource_test.go
  src/replication/operation/flow/deletion_test.go
  src/replication/operation/flow/stage.go
  src/replication/operation/flow/stage_test.go
  src/replication/operation/scheduler/scheduler_test.go
  src/replication/transfer/chart/transfer.go
  src/replication/transfer/image/transfer.go
Labels: target/2.0.0

#10946 Use project controller rather than the manager in API handlers
  src/server/v2.0/handler/artifact.go
  src/server/v2.0/handler/repository.go
Labels: area/OCI, target/2.0.0

#10944 Remove the readonly filter
  src/core/filter/readonly.go
  src/core/filter/readonly_test.go
  src/core/filter/security.go
  src/core/main.go
Labels: target/2.0.0

#10941 Implement query string builder
  api/v2.0/swagger.yaml
  src/internal/orm/query.go
  src/internal/orm/query_test.go
  src/pkg/blob/dao/dao.go
  src/pkg/blob/dao/dao_test.go
  src/pkg/blob/manager.go
  src/pkg/q/builder.go
  src/pkg/q/builder_test.go
  src/pkg/q/query.go
  src/server/v2.0/handler/repository.go
Labels: area/OCI, target/2.0.0

#10954 Fix gc issue on clean the artifact trash
  make/photon/prepare/templates/jobservice/env.jinja
  src/core/api/reg_gc.go
  src/jobservice/job/impl/context.go
  src/jobservice/job/impl/context_test.go
  src/jobservice/job/impl/gc/garbage_collection.go
  src/pkg/artifactrash/dao/dao.go
  src/pkg/artifactrash/dao/dao_test.go
Labels: target/2.0.0, target/FC

#10951 skip configuration update in readonly mode
  src/core/middlewares/middlewares.go
Labels: target/2.0.0, target/FC

#10899 fix[js]:fix ut case faulure
  src/jobservice/runner/redis.go
  src/jobservice/runner/redis_test.go
  src/jobservice/runtime/bootstrap.go
  src/jobservice/worker/cworker/c_worker_test.go
Labels: area/job-services

#10970 remove middleware regtoken
  src/server/middleware/contenttrust/contenttrust.go
  src/server/middleware/regtoken/regtoken.go
  src/server/middleware/regtoken/regtoken_test.go
  src/server/middleware/util.go
  src/server/middleware/vulnerable/vulnerable.go
  src/server/registry/route.go
Labels: target/2.0.0, target/FC

#10955 add sql for migrating access log
  make/migrations/postgresql/0030_2.0.0_schema.up.sql
Labels: target/2.0.0, target/FC

#10972 fix Conformance testing failure
  src/internal/error/errors.go
  src/server/error/error.go
  src/server/middleware/immutable/pushmf.go
  src/server/registry/catalog.go
  src/server/registry/manifest.go
  src/server/registry/manifest_test.go
  src/server/registry/tag.go
  src/server/router/router.go
  src/server/router/router_test.go
Labels: target/2.0.0, target/FC

#10973 add no expriation limited robot account
  src/pkg/robot/controller.go
  src/pkg/robot/controller_test.go
  src/pkg/robot/model/robot.go
Labels: target/2.0.0, target/FC

#10967 Only set "Www-Authenticate" header for registry API
  src/server/error/error.go
  src/server/error/error_test.go
  src/server/middleware/v2auth/auth.go
Labels: target/2.0.0

#10961 Make replication work with new artifact(phase 2)
  src/replication/adapter/harbor/adapter.go
  src/replication/adapter/harbor/adapter_test.go
  src/replication/filter/artifact.go
  src/replication/model/policy.go
  src/replication/model/resource.go
  src/replication/operation/flow/stage.go
  src/replication/transfer/image/transfer.go
Labels: area/replication, target/2.0.0

#10969 Remove dependency on travis-ci
  .github/workflows/CI.yml
  .travis.yml
  README.md
  src/common/utils/email/mail_test.go
  tests/ci/api_common_install.sh
  tests/ci/api_run.sh
  tests/ci/distro_installer.sh
  tests/ci/ui_ut_run.sh
  tests/ci/ut_install.sh
  tests/ci/ut_run.sh
Labels: target/2.0.0, target/FC

#10971 add scanner pull check in policy checker middleware
  src/server/middleware/contenttrust/contenttrust.go
  src/server/middleware/vulnerable/vulnerable.go
Labels: target/2.0.0, target/FC

#10968 Add support for querying artifact by labels and tags
  api/v2.0/swagger.yaml
  src/internal/orm/query.go
  src/pkg/artifact/dao/dao.go
  src/pkg/q/query.go
  src/pkg/q/query_test.go
  src/server/v2.0/handler/artifact.go
  src/server/v2.0/handler/base.go
  src/server/v2.0/handler/base_test.go
  src/server/v2.0/handler/repository.go
Labels: area/OCI, target/2.0.0

#10987 add trivy into offline/online package
  Makefile
  tests/resources/Harbor-Util.robot
Labels: target/FC

#10991 Accept the pagination information in the separated query string
  api/v2.0/swagger.yaml
  src/pkg/q/builder.go
  src/pkg/q/builder_test.go
  src/server/v2.0/handler/artifact.go
  src/server/v2.0/handler/base.go
  src/server/v2.0/handler/base_test.go
  src/server/v2.0/handler/repository.go
Labels: area/OCI, target/2.0.0

#11000 enable garbage colloection api test case
  api/v2.0/legacy_swagger.yaml
  tests/apitests/python/library/system.py
  tests/robot-cases/Group0-BAT/API_DB.robot
Labels: target/2.0.0, target/FC

#11006 upgrade golang version to v1.13.8
  .github/workflows/CI.yml
  CONTRIBUTING.md
  Makefile
  docs/1.10/build-customize-contribute/use-make.md
  make/photon/chartserver/builder
  make/photon/clair-adapter/Dockerfile.binary
  make/photon/clair-adapter/builder.sh
  make/photon/clair/Dockerfile.binary
  make/photon/clair/builder
  make/photon/notary/binary.Dockerfile
  make/photon/registry/Dockerfile.binary
  make/photon/trivy-adapter/Dockerfile.binary
  make/photon/trivy-adapter/builder.sh
  tests/ci/api_common_install.sh
  tests/ci/distro_installer.sh
  tools/swagger/Dockerfile
Labels: target/2.0.0, target/FC

#10986 Bump up base version to v2.0.0
  VERSION
Labels: target/2.0.0, target/FC

#11010 Fire event when create/delete resources
  src/api/artifact/controller.go
  src/api/event/artifact.go
  src/api/event/artifact_test.go
  src/api/event/handler/replication.go
  src/api/event/project.go
  src/api/event/project_test.go
  src/api/event/repository.go
  src/api/event/repository_test.go
  src/api/event/tag.go
  src/api/event/tag_test.go
  src/api/event/topic.go
  src/core/api/project.go
  src/core/main.go
  src/internal/response_recorder.go
  src/internal/response_recorder_test.go
  src/pkg/notifier/event/event.go
  src/replication/adapter/harbor/image_registry.go
  src/replication/adapter/harbor/image_registry_test.go
  src/replication/event/event.go
  src/replication/event/handler.go
  src/replication/event/handler_test.go
  src/replication/transfer/image/transfer.go
  src/server/registry/manifest.go
  src/server/v2.0/handler/artifact.go
  src/server/v2.0/handler/repository.go
Labels: target/2.0.0

#10370 FIX: AliACR Provider.
  src/replication/adapter/aliacr/adapter.go
  src/replication/adapter/aliacr/types.go
Labels: candidate/1.10, candidate/2.0

#10942 Persistent the URLs and annotations of artifact references in database
  make/migrations/postgresql/0030_2.0.0_schema.up.sql
  src/api/artifact/abstractor/resolver/cnab/cnab.go
  src/api/artifact/abstractor/resolver/image/index.go
  src/pkg/artifact/dao/model.go
  src/pkg/artifact/manager.go
  src/pkg/artifact/manager_test.go
  src/pkg/artifact/model.go
Labels: area/OCI, target/2.0.0

#10945 Remove the "x-go-type" for artifact definition in swagger
  api/v2.0/swagger.yaml
  src/api/artifact/model.go
  src/api/tag/model.go
  src/common/models/label.go
  src/pkg/artifact/model.go
  src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.spec.ts
  src/server/v2.0/handler/artifact.go
  src/server/v2.0/handler/model/artifact.go
Labels: area/OCI, target/2.0.0

#11045 Updating the redirects in the old page stubs to point to new site.
  docs/compile_guide.md
  docs/configure_https.md
  docs/configure_swagger.md
  docs/configure_user_settings.md
  docs/customize_look&feel_guide.md
  docs/customize_token_service.md
  docs/demo_server.md
  docs/developer_guide_i18n.md
  docs/harbor_compatibility_list.md
  docs/import_vulnerability_data.md
  docs/installation_guide.md
  docs/kubernetes_deployment.md
  docs/manage_role_by_ldap_group.md
  docs/migration_guide.md
  docs/permissions.md
  docs/registry_landscape.md
  docs/ui_contribution_get_started.md
  docs/upgradetest.md
  docs/use_make.md
  docs/use_notary.md
  docs/user_guide.md
Labels: DONT MERGE

#11009 Implement pagination and query for preheat list apis
  api/v2.0/swagger.yaml
  src/pkg/p2p/preheat/dao/history/storage_redis.go
  src/server/v2.0/handler/preheat.go
  tests/robot-cases/Group0-BAT/API_DB.robot
Labels: area/P2P-Distribution

#10922 [OCI] add checkbox for user to control whether remove untagged image
  src/internal/selector/selector.go
  src/internal/selector/selectors/doublestar/selector.go
  src/internal/selector/selectors/doublestar/selector_test.go
  src/internal/selector/selectors/index/index.go
  src/internal/selector/selectors/label/selector.go
  src/pkg/immutabletag/match/rule/match.go
  src/pkg/retention/launcher.go
  src/pkg/retention/policy/alg/or/processor_test.go
  src/pkg/retention/policy/builder.go
  src/pkg/retention/policy/rule/models.go
  src/portal/src/app/project/project-detail/project-detail.component.ts
  src/portal/src/app/project/tag-feature-integration/tag-retention/add-rule/add-rule.component.html
  src/portal/src/app/project/tag-feature-integration/tag-retention/add-rule/add-rule.component.scss
  src/portal/src/app/project/tag-feature-integration/tag-retention/add-rule/add-rule.component.ts
  src/portal/src/app/project/tag-feature-integration/tag-retention/retention.ts
  src/portal/src/app/project/tag-feature-integration/tag-retention/tag-retention.component.html
  src/portal/src/app/project/tag-feature-integration/tag-retention/tag-retention.component.ts
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
Labels: target/2.0.0, target/FC

#11055 Middleware ctx
  src/api/artifact/controller_test.go
  src/internal/context.go
  src/internal/context_test.go
  src/server/middleware/apiversion/api_version.go
  src/server/middleware/artifactinfo/artifact_info.go
  src/server/middleware/artifactinfo/artifact_info_test.go
  src/server/middleware/contenttrust/contenttrust.go
  src/server/middleware/immutable/pushmf.go
  src/server/middleware/immutable/pushmf_test.go
  src/server/middleware/util.go
  src/server/middleware/v2auth/auth.go
  src/server/middleware/v2auth/auth_test.go
  src/server/middleware/vulnerable/vulnerable.go
Labels: target/2.0.0

#11038 Repair the count usage during the upgrading
  make/migrations/postgresql/0030_2.0.0_schema.up.sql
  src/migration/migration.go
Labels: target/2.0.0

#10806 feat: add p2p preheat models and managers
  api/v2.0/swagger.yaml
  make/migrations/postgresql/0030_2.0.0_schema.up.sql
  src/api/preheat/base.go
  src/api/preheat/controller.go
  src/api/preheat/controllor_test.go
  src/pkg/p2p/preheat/dao/history.go
  src/pkg/p2p/preheat/dao/history/storage.go
  src/pkg/p2p/preheat/dao/history/storage_redis.go
  src/pkg/p2p/preheat/dao/history/storage_redis_test.go
  src/pkg/p2p/preheat/dao/history_test.go
  src/pkg/p2p/preheat/dao/instance.go
  src/pkg/p2p/preheat/dao/instance/storage.go
  src/pkg/p2p/preheat/dao/instance/storage_redis.go
  src/pkg/p2p/preheat/dao/instance/storage_redis_test.go
  src/pkg/p2p/preheat/dao/instance_test.go
  src/pkg/p2p/preheat/dao/models/base.go
  src/pkg/p2p/preheat/dao/models/history.go
  src/pkg/p2p/preheat/dao/models/instance.go
  src/pkg/p2p/preheat/dao/redis_base.go
  src/pkg/p2p/preheat/dao/setup_test.go
  src/pkg/p2p/preheat/dao/utils.go
  src/pkg/p2p/preheat/dao/utils/redis.go
  src/pkg/p2p/preheat/dao/utils/redis_test.go
  src/pkg/p2p/preheat/history/base.go
  src/pkg/p2p/preheat/history/base_test.go
  src/pkg/p2p/preheat/history/manager.go
  src/pkg/p2p/preheat/history/manager_test.go
  src/pkg/p2p/preheat/history/mocks/Manager.go
  src/pkg/p2p/preheat/instance/manager.go
  src/pkg/p2p/preheat/instance/manager_test.go
  src/pkg/p2p/preheat/instance/mocks/Manager.go
  src/pkg/p2p/preheat/models/extensions.go
  src/pkg/p2p/preheat/models/extensions_test.go
  src/pkg/p2p/preheat/models/models.go
  src/pkg/p2p/preheat/provider/dragonfly.go
  src/pkg/p2p/preheat/provider/factory.go
  src/pkg/p2p/preheat/tests/utils.go
  src/server/v2.0/handler/preheat.go
  src/testing/pkg/p2p/preheat/dao/storage.go
Labels: area/P2P-Distribution

#11070 United error response format for management APIs (legacy and v2.0 APIs)
  src/common/api/base.go
  src/server/error/error.go
  src/server/error/error_test.go
  tests/apitests/python/test_edit_project_creation.py
Labels: target/2.0.0

#11075 Implement total in preheat list apis
  api/v2.0/swagger.yaml
  src/api/preheat/base.go
  src/api/preheat/controller.go
  src/api/preheat/controllor_test.go
  src/pkg/p2p/preheat/dao/history.go
  src/pkg/p2p/preheat/dao/history_test.go
  src/pkg/p2p/preheat/dao/instance.go
  src/pkg/p2p/preheat/dao/instance_test.go
  src/pkg/p2p/preheat/history/manager.go
  src/pkg/p2p/preheat/history/manager_test.go
  src/pkg/p2p/preheat/history/mocks/Manager.go
  src/pkg/p2p/preheat/instance/manager.go
  src/pkg/p2p/preheat/instance/manager_test.go
  src/pkg/p2p/preheat/instance/mocks/Manager.go
  src/server/v2.0/handler/preheat.go
Labels: area/P2P-Distribution

#11071 fix(blob,quota): process blobs already in registry no but associated with project
  src/api/blob/controller.go
  src/api/blob/controller_test.go
  src/server/middleware/blob/put_manifest.go
  src/server/middleware/blob/put_manifest_test.go
  src/server/middleware/quota/put_manifest.go
  src/server/middleware/quota/put_manifest_test.go
  src/testing/pkg/distribution/manifest.go
  src/testing/pkg/pkg.go
Labels: target/2.0.0

#11072 add notification middleware
  src/core/middlewares/middlewares.go
  src/pkg/notification/notification.go
  src/server/middleware/notification/notification.go
  src/server/middleware/notification/notification_test.go
Labels: target/FC

#11058 refactor(quota): implement internal quota APIs by quota controller
  src/api/quota/controller.go
  src/api/quota/controller_test.go
  src/api/quota/driver/project/project.go
  src/api/quota/driver/project/util.go
  src/api/quota/options.go
  src/common/models/project.go
  src/core/api/harborapi_test.go
  src/core/api/internal.go
  src/core/api/project.go
  src/core/api/quota/chart/chart.go
  src/core/api/quota/migrator.go
  src/core/api/quota/registry/registry.go
  src/core/main.go
  src/pkg/quota/dao/dao.go
  src/pkg/quota/dao/dao_test.go
  src/pkg/quota/manager.go
  src/pkg/quota/util.go
  src/pkg/quota/util_test.go
  src/portal/src/app/project/summary/summary.component.html
  src/testing/api/quota/controller.go
  src/testing/pkg/quota/manager.go
Labels: target/2.0.0

#11076 make Secure flag of CSRF cookie adapt to config
  src/server/middleware/csrf/csrf.go
  src/server/middleware/csrf/csrf_test.go
Labels: target/2.0.0

#11059 Fix bug when reading the readme.md of helm chart
  src/pkg/chart/operator.go
Labels: target/2.0.0

#11068 Change tag count to artifact count in search result
  api/v2.0/legacy_swagger.yaml
  src/core/api/search.go
Labels: target/2.0.0

#11064 Check expired or not when getting token from cache
  src/pkg/registry/auth/bearer/cache.go
  src/pkg/registry/auth/bearer/cache_test.go
Labels: target/2.0.0

#11085 move notification handles and events metadata into api
  src/api/artifact/controller.go
  src/api/event/handler/auditlog/auditlog.go
  src/api/event/handler/auditlog/auditlog_test.go
  src/api/event/handler/init.go
  src/api/event/handler/replication/replication.go
  src/api/event/handler/util/util.go
  src/api/event/handler/webhook/artifact/artifact.go
  src/api/event/handler/webhook/artifact/artifact_test.go
  src/api/event/handler/webhook/chart/chart.go
  src/api/event/handler/webhook/chart/chart_test.go
  src/api/event/handler/webhook/quota/quota.go
  src/api/event/handler/webhook/quota/quota_test.go
  src/api/event/handler/webhook/scan/delete.go
  src/api/event/handler/webhook/scan/scan.go
  src/api/event/handler/webhook/scan/scan_test.go
  src/api/event/metadata/artifact.go
  src/api/event/metadata/artifact_test.go
  src/api/event/metadata/chart.go
  src/api/event/metadata/chart_test.go
  src/api/event/metadata/project.go
  src/api/event/metadata/project_test.go
  src/api/event/metadata/quota.go
  src/api/event/metadata/quota_test.go
  src/api/event/metadata/repository.go
  src/api/event/metadata/repository_test.go
  src/api/event/metadata/scan.go
  src/api/event/metadata/scan_test.go
  src/api/event/metadata/tag.go
  src/api/event/metadata/tag_test.go
  src/api/event/topic.go
  src/chartserver/reverse_proxy.go
  src/core/api/chart_repository.go
  src/core/api/notification_job_test.go
  src/core/api/notification_policy.go
  src/core/api/notification_policy_test.go
  src/core/api/project.go
  src/core/main.go
  src/core/service/notifications/jobs/handler.go
  src/pkg/notification/notification.go
  src/pkg/notification/policy/manager/manager.go
  src/pkg/notifier/event/event.go
  src/pkg/notifier/event/event_test.go
  src/pkg/notifier/handler/auditlog/handler.go
  src/pkg/notifier/handler/notification/http_handler_test.go
  src/pkg/notifier/handler/notification/image_handler.go
  src/pkg/notifier/handler/notification/image_handler_test.go
  src/pkg/notifier/handler/notification/processor.go
  src/pkg/notifier/handler/notification/slack_handler_test.go
  src/pkg/notifier/model/const.go
  src/pkg/notifier/model/event.go
  src/pkg/notifier/model/topic.go
  src/pkg/notifier/topic/topics.go
  src/pkg/scan/event/notification.go
  src/server/middleware/notification/notification_test.go
  src/server/registry/manifest.go
  src/server/v2.0/handler/artifact.go
  src/server/v2.0/handler/repository.go
  src/testing/pkg/notification/manager.go
Labels: target/FC

#11046 Replicate tag deletion between Harbor instances
  src/api/event/handler/init.go
  src/api/event/handler/replication/replication.go
  src/replication/adapter/adapter.go
  src/replication/adapter/aliacr/adapter.go
  src/replication/adapter/aliacr/adapter_test.go
  src/replication/adapter/awsecr/adapter.go
  src/replication/adapter/awsecr/adapter_test.go
  src/replication/adapter/azurecr/adapter.go
  src/replication/adapter/dockerhub/adapter.go
  src/replication/adapter/dockerhub/adapter_test.go
  src/replication/adapter/gitlab/adapter.go
  src/replication/adapter/googlegcr/adapter.go
  src/replication/adapter/googlegcr/adapter_test.go
  src/replication/adapter/harbor/adapter.go
  src/replication/adapter/harbor/image_registry.go
  src/replication/adapter/harbor/image_registry_test.go
  src/replication/adapter/helmhub/adapter.go
  src/replication/adapter/huawei/huawei_adapter.go
  src/replication/adapter/huawei/image_registry.go
  src/replication/adapter/huawei/image_registry_test.go
  src/replication/adapter/jfrog/adapter.go
  src/replication/adapter/native/adapter.go
  src/replication/adapter/native/adapter_test.go
  src/replication/adapter/quayio/adapter.go
  src/replication/event/event.go
  src/replication/event/handler.go
  src/replication/filter/resource.go
  src/replication/model/resource.go
  src/replication/operation/flow/stage.go
  src/replication/operation/flow/stage_test.go
  src/replication/transfer/image/transfer.go
  src/replication/transfer/image/transfer_test.go
Labels: target/2.0.0

#11073 Swith to new API for recent log page
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/lib/components/log/recent-log.component.html
  src/portal/src/lib/components/log/recent-log.component.spec.ts
  src/portal/src/lib/components/log/recent-log.component.ts
  src/portal/src/lib/services/permission.service.ts
Labels: target/2.0.0, target/FC

#11097 update project logs api to v2.0
  api/v2.0/swagger.yaml
  src/server/v2.0/handler/handler.go
  src/server/v2.0/handler/project.go
Labels: target/2.0.0, target/FC

#11091 Add create/delete tag API test case
  tests/apitests/python/library/artifact.py
  tests/apitests/python/test_create_delete_tag.py
  tests/robot-cases/Group0-BAT/API_DB.robot
Labels: target/2.0.0

#10909 add support kraken preheat
  src/api/preheat/controller.go
  src/api/preheat/controllor_test.go
  src/pkg/p2p/preheat/provider/driver.go
  src/pkg/p2p/preheat/provider/factory.go
  src/pkg/p2p/preheat/provider/known_drivers.go
  src/pkg/p2p/preheat/provider/known_drivers_test.go
  src/pkg/p2p/preheat/provider/kraken.go
Labels: area/P2P-Distribution

#11109 fix(scan): assign repository pull access policy to robot account when scan artifact
  src/api/scan/base_controller.go
  src/api/scan/base_controller_test.go
Labels: target/FC

#11111 Clean up some TODO items
  src/api/artifact/abstractor.go
  src/api/artifact/abstractor_test.go
  src/api/artifact/processor/base/index.go
  src/api/artifact/processor/base/manifest.go
  src/api/artifact/processor/base/manifest_test.go
  src/api/artifact/processor/blob/cache.go
  src/api/artifact/processor/blob/fetcher.go
  src/api/artifact/processor/chart/chart.go
  src/api/artifact/processor/chart/chart_test.go
  src/api/artifact/processor/cnab/cnab.go
  src/api/artifact/processor/cnab/cnab_test.go
  src/api/artifact/processor/image/manifest_v2.go
  src/api/artifact/processor/image/manifest_v2_test.go
  src/api/repository/controller.go
  src/pkg/registry/client.go
  src/testing/api/artifact/processor/blob/fetcher.go
  src/testing/pkg/registry/client.go
  tests/robot-cases/Group0-BAT/API_LDAP.robot
Labels: target/2.0.0

#11102 Fix delete scan report on deleting artifact
  src/api/event/handler/webhook/scan/delete.go
Labels: target/2.0.0

#11113 Use new query model to get audit logs
  api/v2.0/swagger.yaml
  src/api/event/metadata/artifact.go
  src/portal/src/app/log/audit-log.component.html
  src/portal/src/app/log/audit-log.component.spec.ts
  src/portal/src/app/log/audit-log.component.ts
  src/portal/src/app/log/audit-log.service.spec.ts
  src/portal/src/app/log/audit-log.service.ts
  src/portal/src/app/log/audit-log.ts
  src/portal/src/app/log/log.module.ts
  src/portal/src/lib/components/datetime-picker/datetime-picker.component.ts
  src/portal/src/lib/components/log/recent-log.component.html
  src/portal/src/lib/components/log/recent-log.component.spec.ts
  src/portal/src/lib/components/log/recent-log.component.ts
  src/server/v2.0/handler/auditlog.go
  src/server/v2.0/handler/repository.go
Labels: target/2.0.0

#11112 fix: remove old artifact model
  make/migrations/postgresql/0030_2.0.0_schema.up.sql
  src/common/dao/artifact.go
  src/common/dao/artifact_blob.go
  src/common/dao/artifact_blob_test.go
  src/common/dao/artifact_test.go
  src/common/dao/blob.go
  src/common/dao/blob_test.go
  src/common/dao/project_blob.go
  src/common/dao/project_blob_test.go
  src/common/models/artifact.go
  src/common/models/base.go
Labels: target/2.0.0

#11037 Escapse the repository name in the link header returned in response
  src/pkg/q/builder.go
  src/pkg/q/builder_test.go
  src/server/v2.0/handler/base.go
  src/server/v2.0/handler/base_test.go
Labels: target/2.0.0

#11107 Filter the pulling manifest request from replication service
  src/pkg/registry/client.go
  src/server/registry/manifest.go
Labels: target/2.0.0

#11120 Remove the project manager from context
  src/core/api/base.go
  src/core/api/retention.go
  src/core/filter/security.go
  src/core/filter/security_test.go
  src/core/service/token/creator.go
Labels: target/2.0.0

#11040 Update the swagger
  api/v2.0/swagger.yaml
Labels: target/2.0.0

#11110 Enable pull time on getting manifest
  src/api/artifact/controller.go
  src/api/artifact/controller_test.go
  src/api/event/handler/init.go
  src/api/event/handler/internal/artifact.go
  src/api/event/handler/internal/artifact_test.go
  src/api/repository/controller.go
  src/api/repository/controller_test.go
  src/pkg/repository/dao/dao.go
  src/pkg/repository/dao/dao_test.go
  src/pkg/repository/manager.go
  src/pkg/repository/manager_test.go
  src/server/registry/manifest.go
  src/testing/api/repository/controller.go
  src/testing/pkg/repository/manager.go
Labels: target/2.0.0

#11118 drop table access log in migration
  make/migrations/postgresql/0030_2.0.0_schema.up.sql
  src/common/dao/accesslog.go
  src/common/dao/dao_test.go
  src/common/dao/project_test.go
  src/common/models/accesslog.go
  src/common/models/base.go
  src/core/api/harborapi_test.go
  src/core/api/log.go
  src/core/api/log_test.go
  src/core/api/project.go
  src/core/api/project_test.go
  src/core/auth/uaa/uaa_test.go
  src/server/v2.0/route/legacy.go
  src/testing/apitests/apilib/access_log.go
  src/testing/apitests/apilib/access_log_filter.go
  tests/apitests/python/test_assign_role_to_ldap_group.py
  tests/apitests/python/test_ldap_admin_role.py
Labels: target/2.0.0

#11123 feat(quota,notification): notification for quota exceeded and warning
  src/api/event/metadata/quota.go
  src/api/event/topic.go
  src/api/quota/controller.go
  src/core/api/notification_policy.go
  src/pkg/distribution/distribution.go
  src/pkg/distribution/distribution_test.go
  src/pkg/notification/notification.go
  src/pkg/quota/errors.go
  src/pkg/quota/models/quota.go
  src/pkg/quota/models/quota_test.go
  src/server/middleware/notification/notification.go
  src/server/middleware/notification/notification_test.go
  src/server/middleware/quota/copy_artifact.go
  src/server/middleware/quota/copy_artifact_test.go
  src/server/middleware/quota/put_manifest.go
  src/server/middleware/quota/put_manifest_test.go
  src/server/middleware/quota/quota.go
  src/server/middleware/quota/quota_test.go
Labels: target/2.0.0, target/FC

#11126 Remove the API to listing the resources that added with the specific label
  api/v2.0/legacy_swagger.yaml
  src/core/api/harborapi_test.go
  src/core/api/label.go
  src/server/v2.0/route/legacy.go
Labels: target/2.0.0

#11128 simplify query string when to list artifact
  src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
Labels: target/2.0.0

#11069 Remove the useless definitions in lagacy swagger.yaml
  api/v2.0/legacy_swagger.yaml
Labels: target/2.0.0

#10994 update common error
  src/internal/error/errors.go
Labels: target/2.0.0, target/FC

#11084 feat(middleware,vulnerable): add image index checking for vulnerability prevention
  src/api/artifact/const.go
  src/api/project/controller.go
  src/api/project/controller_test.go
  src/api/project/options.go
  src/api/scan/base_controller.go
  src/api/scan/base_controller_test.go
  src/api/scan/checker.go
  src/api/scan/checker_test.go
  src/pkg/artifact/manager.go
  src/pkg/artifact/model.go
  src/pkg/artifact/model_test.go
  src/server/middleware/util.go
  src/server/middleware/vulnerable/controller.go
  src/server/middleware/vulnerable/vulnerable.go
  src/server/middleware/vulnerable/vulnerable_test.go
  src/testing/api/project/controller.go
Labels: target/2.0.0, target/FC

#11122 Increase the length the columns (src_resource, dst_resource)of replication_task
  make/migrations/postgresql/0030_2.0.0_schema.up.sql
Labels: target/2.0.0

#11127 Move the webhook event API definition to legacy_swagger.yaml
  api/v2.0/legacy_swagger.yaml
  api/v2.0/swagger.yaml
Labels: target/2.0.0

#11142 Enable API logs test case
  src/server/v2.0/handler/base.go
  src/server/v2.0/handler/project.go
  tests/apitests/python/library/base.py
  tests/apitests/python/library/projectV2.py
  tests/apitests/python/test_user_view_logs.py
  tests/robot-cases/Group0-BAT/API_DB.robot
Labels: target/2.0.0

#11004 fix[js_ut]:update stop job case of js
  src/jobservice/worker/cworker/c_worker_test.go
Labels: area/job-services

#11148 Unescape tags query when to list artifact
  src/pkg/q/builder.go
  src/pkg/q/builder_test.go
  src/server/v2.0/handler/base_test.go
Labels: target/2.0.0

#11162 Remove route entry to reset password
  src/core/controllers/controllers_test.go
  src/portal/src/app/sign-in/sign-in.component.html
  src/portal/src/app/sign-in/sign-in.component.ts
  src/server/route.go
Labels: target/2.0.0

#11163 feat(gc,quota): refersh quotas for projects after gc
  src/api/chartmuseum/controller.go
  src/api/project/controller.go
  src/api/quota/util.go
  src/api/quota/util_test.go
  src/core/api/internal.go
  src/core/service/notifications/admin/handler.go
  src/testing/api/project/controller.go
Labels: target/2.0.0, target/FC

#11144 Rewrite the filters with middleware mechinism
  src/common/utils/test/test.go
  src/core/api/api_test.go
  src/core/api/harborapi_test.go
  src/core/api/user.go
  src/core/auth/authenticator.go
  src/core/controllers/base.go
  src/core/controllers/controllers_test.go
  src/core/filter/mediatype.go
  src/core/filter/mediatype_test.go
  src/core/filter/security.go
  src/core/filter/security_test.go
  src/core/filter/sessionchecker.go
  src/core/filter/sessionchecker_test.go
  src/core/main.go
  src/core/middlewares/middlewares.go
  src/internal/context.go
  src/server/middleware/csrf/csrf.go
  src/server/middleware/security/auth_proxy.go
  src/server/middleware/security/auth_proxy_test.go
  src/server/middleware/security/basic_auth.go
  src/server/middleware/security/basic_auth_test.go
  src/server/middleware/security/idtoken.go
  src/server/middleware/security/idtoken_test.go
  src/server/middleware/security/oidc_cli.go
  src/server/middleware/security/oidc_cli_test.go
  src/server/middleware/security/robot.go
  src/server/middleware/security/robot_test.go
  src/server/middleware/security/secret.go
  src/server/middleware/security/secret_test.go
  src/server/middleware/security/security.go
  src/server/middleware/security/security_test.go
  src/server/middleware/security/session.go
  src/server/middleware/security/session_test.go
  src/server/middleware/security/unauthorized.go
  src/server/middleware/security/unauthorized_test.go
  src/server/middleware/session/session.go
  src/server/middleware/session/session_test.go
Labels: target/2.0.0

#11121 Fix bug when deleting the repository
  src/api/repository/controller.go
  src/api/repository/controller_test.go
Labels: target/2.0.0

#11158 Add "_self" suffix for repository API to avoid conflict
  api/v2.0/swagger.yaml
  src/server/middleware/path/path.go
  src/server/middleware/path/path_test.go
Labels: target/2.0.0

#11154 Add permission check for audit logs API
  src/pkg/audit/dao/dao.go
  src/pkg/audit/dao/dao_test.go
  src/server/v2.0/handler/auditlog.go
  src/server/v2.0/handler/base.go
Labels: target/2.0.0

#10859 Trigger a new Netlify build when new docs are merged
  .github/workflows/netlify.yml
Labels: area/ci

#11180 Update the URL checking logic of auth proxy security generator
  src/server/middleware/security/auth_proxy.go
  src/server/middleware/security/auth_proxy_test.go
Labels: target/2.0.0

#11270 Handle empty orlist in orm query
  src/lib/orm/query.go
Labels: target/2.0.0

#11285 feat(trivy): Return Trivy DB update timestamp in /api/v1/metadata response
  Makefile
  docs/1.10/build-customize-contribute/compile-guide.md
  src/portal/src/app/config/scanner/scanner-metadata/scanner-metadata.component.ts
  src/portal/src/lib/utils/utils.ts
Labels: target/2.0.0

#11306 give the username to anonymous when to pull public resource without a…
  src/controller/event/topic.go
Labels: target/2.0.0

#11309 Fix bugs of replication
  src/common/api/base.go
  src/core/api/registry.go
  src/jobservice/job/impl/replication/scheduler.go
  src/replication/policy/scheduler/scheduler.go
Labels: area/replication, target/2.0.0

#11320 Use the same logic to parse the registry URL
  src/core/api/registry.go
Labels: area/replication, target/2.0.0

#11314 fix(quota): allowed to put blob which size is zero
  src/controller/blob/controller.go
  src/controller/blob/controller_test.go
  src/server/middleware/quota/put_blob_upload.go
  src/server/middleware/quota/put_blob_upload_test.go
  src/server/middleware/quota/quota.go
Labels: area/quota

#11303 append pull permission for push policy
  src/common/security/robot/robot.go
  src/common/security/robot/robot_test.go
  tests/apitests/python/library/artifact.py
Labels: target/2.0.0

#11318 Iterate the link header when listing artifact
  src/replication/adapter/harbor/image_registry.go
  src/server/v2.0/handler/base.go
Labels: area/replication, target/2.0.0

#11296 Support replicate images with media type application/vnd.docker.distribution.manifest.v1+json
  src/pkg/registry/client.go
  src/replication/transfer/image/transfer.go
Labels: area/replication, target/2.0.0

#11336 Add API to list tags under the specific repository
  api/v2.0/swagger.yaml
  src/common/rbac/const.go
  src/common/rbac/project_rbac_role.go
  src/common/rbac/project_rbac_util.go
  src/server/v2.0/handler/handler.go
  src/server/v2.0/handler/tag.go
Labels: area/OCI

#11348 Make sure the tag filter have the same behavior for empty value and *
  src/replication/filter/artifact.go
Labels: target/2.0.0

#11339 Add "order by" clause to avoid the duplicat rows
  src/pkg/artifact/dao/dao.go
  src/pkg/repository/dao/dao.go
  src/pkg/tag/dao/dao.go
  tests/apitests/python/test_create_delete_tag.py
Labels: target/2.0.0

#11351 fix[logger]:update log ID validation logic
  src/jobservice/logger/getter/file_getter.go
Labels: area/job-services, target/2.0.0

#11358 fix[UT]:improve the UT cases of enqueuer
  src/jobservice/period/enqueuer_test.go
Labels: area/job-services

#11321 fix content trust middleware bypass scanner pull
  src/server/middleware/contenttrust/contenttrust.go
  src/server/middleware/contenttrust/contenttrust_test.go
  src/server/middleware/util.go
Labels: target/2.0.0

#11363 Does not throw err in the notification job
  src/jobservice/job/impl/notification/webhook_job.go
  src/jobservice/job/impl/notification/webhook_job_test.go
  src/pkg/scan/job_test.go
  src/testing/jobservice/context.go
Labels: target/2.0.0
