Repository goharbor/harbor, pull requests merged in 2020-12, with the labels that each got.

#13638 fix(redis) redis sentinel for chart cache
  src/chartserver/cache.go
  src/chartserver/handler_utility.go
  src/chartserver/utils.go
Labels: target/2.1.2

#13623 updates on robot accounts
  api/v2.0/swagger.yaml
  make/migrations/postgresql/0050_2.2.0_schema.up.sql
  src/controller/robot/controller.go
  src/controller/robot/controller_test.go
  src/controller/robot/model.go
  src/controller/robot/model_test.go
  src/controller/scan/base_controller.go
  src/controller/scan/base_controller_test.go
  src/pkg/robot2/manager.go
  src/pkg/robot2/model/model.go
  src/server/v2.0/handler/model/robot.go
  src/server/v2.0/handler/robot.go
  src/server/v2.0/handler/robotV1.go
  src/testing/pkg/robot2/manager.go
  tests/apitests/python/library/robot.py
  tests/apitests/python/test_push_chart_by_helm2_helm3_with_robot_Account.py
  tests/apitests/python/test_robot_account.py
Labels: area/robot-account, target/2.2.0

#13651 fix(quota): ignore the fail when getting reference of quota
  src/controller/quota/controller.go
Labels: area/quota, target/2.1.2

#13511 [i18n] added support for German
  src/portal/src/app/base/navigator/navigator.component.html
  src/portal/src/app/shared/shared.const.ts
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/lib/utils/utils.ts
Labels: help wanted

#13661 Set timezone as UTC for database connection
  src/common/dao/pgsql.go
Labels: target/2.2.0

#13663 [cherry-pick]Set timezone as UTC for database connection
  src/common/dao/pgsql.go
Labels: target/2.1.2

#13676 Fix the pattern to match v2 catalog URI
  src/lib/patterns.go
  src/lib/patterns_test.go
Labels: target/2.1.2

#13677 Fix the pattern to match v2 catalog URI
  src/server/middleware/pattern_test.go
  src/server/middleware/patterns.go
Labels: target/2.0.5

#13675 Fix the pattern to match v2 catalog URI
  src/lib/patterns.go
  src/lib/patterns_test.go
Labels: target/2.2.0

#13654 update robot secret
  api/v2.0/swagger.yaml
  make/migrations/postgresql/0050_2.2.0_schema.up.sql
  src/controller/robot/controller.go
  src/controller/robot/controller_test.go
  src/controller/scan/base_controller.go
  src/controller/scan/base_controller_test.go
  src/pkg/robot2/model/model.go
  src/server/middleware/security/robot2.go
  src/server/v2.0/handler/robot.go
  src/server/v2.0/handler/robotV1.go
  src/testing/controller/robot/controller.go
Labels: area/robot-account, target/2.2.0

#13686 Move security/readonly middleware ahead of transaction middleware
  src/core/middlewares/middlewares.go
Labels: target/2.1.2

#13618 Support replicate from artifact hub
  src/jobservice/job/impl/replication/replication.go
  src/replication/adapter/artifacthub/adapter.go
  src/replication/adapter/artifacthub/adapter_test.go
  src/replication/adapter/artifacthub/chart_registry.go
  src/replication/adapter/artifacthub/client.go
  src/replication/adapter/artifacthub/consts.go
  src/replication/adapter/artifacthub/model.go
  src/replication/model/registry.go
  src/replication/replication.go
Labels: target/2.2.0

#13685 fix robot name conflicate issue
  src/controller/robot/controller.go
  src/controller/robot/controller_test.go
  src/server/middleware/security/robot2.go
  src/server/middleware/security/robot2_test.go
  src/server/v2.0/handler/robot.go
Labels: target/2.2.0

#11470 Tecent TCR Provider
  src/go.mod
  src/go.sum
  src/jobservice/job/impl/replication/replication.go
  src/replication/adapter/tencentcr/adapter.go
  src/replication/adapter/tencentcr/adapter_test.go
  src/replication/adapter/tencentcr/artifact_registry.go
  src/replication/adapter/tencentcr/artifact_registry_test.go
  src/replication/adapter/tencentcr/auth.go
  src/replication/adapter/tencentcr/chart_registry.go
  src/replication/adapter/tencentcr/sdk.go
  src/replication/adapter/tencentcr/sdk_test.go
  src/replication/model/registry.go
  src/replication/replication.go
  src/vendor/github.com/tencentcloud/tencentcloud-sdk-go/LICENSE
  src/vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/client.go
  src/vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/credentials.go
  src/vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/errors/errors.go
  src/vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/request.go
  src/vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/response.go
  src/vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/profile/client_profile.go
  src/vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/profile/http_profile.go
  src/vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/regions/regions.go
  src/vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/sign.go
  src/vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/types.go
  src/vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tcr/v20190924/client.go
  src/vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tcr/v20190924/models.go
  src/vendor/modules.txt
Labels: area/replication, replication/adapters

#13658 Cherry Pick: Tencent TCR Provider
  src/go.mod
  src/go.sum
  src/jobservice/job/impl/replication/replication.go
  src/replication/adapter/tencentcr/adapter.go
  src/replication/adapter/tencentcr/adapter_test.go
  src/replication/adapter/tencentcr/artifact_registry.go
  src/replication/adapter/tencentcr/artifact_registry_test.go
  src/replication/adapter/tencentcr/auth.go
  src/replication/adapter/tencentcr/chart_registry.go
  src/replication/adapter/tencentcr/sdk.go
  src/replication/adapter/tencentcr/sdk_test.go
  src/replication/model/registry.go
  src/replication/replication.go
  src/vendor/github.com/tencentcloud/tencentcloud-sdk-go/LICENSE
  src/vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/client.go
  src/vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/credentials.go
  src/vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/errors/errors.go
  src/vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/request.go
  src/vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/response.go
  src/vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/profile/client_profile.go
  src/vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/profile/http_profile.go
  src/vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/regions/regions.go
  src/vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/sign.go
  src/vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/types.go
  src/vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tcr/v20190924/client.go
  src/vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tcr/v20190924/models.go
  src/vendor/modules.txt
Labels: area/replication, replication/adapters

#13711 fix(api):update stop job api
  src/jobservice/job/tracker.go
  src/jobservice/lcm/controller.go
  src/jobservice/period/basic_scheduler.go
  src/jobservice/period/basic_scheduler_test.go
  src/jobservice/period/policy_store.go
  src/jobservice/period/policy_store_test.go
  src/jobservice/runner/redis.go
  src/jobservice/worker/cworker/c_worker.go
Labels: target/2.1.2

#13694 GHCR Provider
  src/jobservice/job/impl/replication/replication.go
  src/replication/adapter/githubcr/adapter.go
  src/replication/adapter/githubcr/adapter_test.go
  src/replication/model/registry.go
  src/replication/replication.go
Labels: area/replication, replication/adapters

#13139 Migrate gc to task manager
  api/v2.0/legacy_swagger.yaml
  api/v2.0/swagger.yaml
  make/migrations/postgresql/0050_2.2.0_schema.up.sql
  src/controller/gc/callback.go
  src/controller/gc/controller.go
  src/controller/gc/controller_test.go
  src/controller/gc/model.go
  src/controller/p2p/preheat/controller.go
  src/controller/p2p/preheat/controllor_test.go
  src/core/api/harborapi_test.go
  src/core/api/reg_gc.go
  src/core/api/reg_gc_test.go
  src/pkg/retention/controller.go
  src/pkg/retention/controller_test.go
  src/pkg/scheduler/dao.go
  src/pkg/scheduler/dao_test.go
  src/pkg/scheduler/scheduler.go
  src/pkg/scheduler/scheduler_test.go
  src/pkg/task/model.go
  src/portal/src/lib/components/config/gc/gc-history/gc-history.component.html
  src/replication/policy/controller/controller.go
  src/replication/policy/controller/controller_test.go
  src/server/v2.0/handler/gc.go
  src/server/v2.0/handler/handler.go
  src/server/v2.0/handler/model/gc.go
  src/server/v2.0/handler/util.go
  src/server/v2.0/route/legacy.go
  src/testing/pkg/scheduler/scheduler.go
  tests/apitests/python/library/base.py
  tests/apitests/python/library/gc.py
  tests/apitests/python/library/system.py
  tests/apitests/python/test_garbage_collection.py
Labels: target/2.2.0

#13684 refactor(scan): refactor scan/scan all job to task manager
  make/migrations/postgresql/0050_2.2.0_schema.up.sql
  src/controller/artifact/helper.go
  src/controller/artifact/helper_test.go
  src/controller/event/handler/init.go
  src/controller/event/handler/webhook/scan/delete.go
  src/controller/event/handler/webhook/scan/delete_test.go
  src/controller/event/metadata/scan.go
  src/controller/event/metadata/scan_test.go
  src/controller/scan/all_handler.go
  src/controller/scan/base_controller.go
  src/controller/scan/base_controller_test.go
  src/controller/scan/callback.go
  src/controller/scan/callback_test.go
  src/controller/scan/controller.go
  src/controller/scan/options.go
  src/core/api/admin_job.go
  src/core/api/scan_all.go
  src/core/api/scan_all_test.go
  src/core/service/notifications/admin/handler.go
  src/core/service/notifications/jobs/handler.go
  src/lib/log/logger.go
  src/lib/q/query.go
  src/pkg/artifact/model.go
  src/pkg/scan/dao/scan/model.go
  src/pkg/scan/dao/scan/report.go
  src/pkg/scan/dao/scan/report_test.go
  src/pkg/scan/job.go
  src/pkg/scan/report/base_manager.go
  src/pkg/scan/report/base_manager_test.go
  src/pkg/scan/report/manager.go
  src/pkg/scan/report/manager_test.go
  src/pkg/scan/report/summary_test.go
  src/pkg/task/model.go
  src/server/v2.0/handler/scan.go
  src/testing/controller/scan/controller.go
  src/testing/pkg/scan/report/manager.go
Labels: target/2.2.0

#13744 feat(api): support project name in the path of apis
  api/v2.0/swagger.yaml
  src/server/v2.0/handler/project.go
  src/server/v2.0/handler/robotV1.go
  src/server/v2.0/handler/util.go
Labels: target/2.2.0

#13759 fix_tencenttcr_getAdapterInfo
  src/replication/adapter/tencentcr/adapter.go
Labels: target/2.2.0

#13729 Tiny fixes for task manager
  api/v2.0/swagger.yaml
  make/migrations/postgresql/0050_2.2.0_schema.up.sql
  src/pkg/scheduler/dao.go
  src/pkg/scheduler/dao_test.go
  src/pkg/task/dao/execution.go
  src/pkg/task/dao/model.go
  src/pkg/task/execution.go
  src/pkg/task/execution_test.go
  src/pkg/task/model.go
  src/server/route.go
Labels: target/2.2.0

#13756 add permission checking for gc operation
  src/server/v2.0/handler/gc.go
  src/server/v2.0/handler/replication.go
  tests/apitests/python/library/base.py
Labels: target/2.2.0

#13774 Escape the values to `contains` operator in dao packages
  src/common/dao/label.go
  src/lib/orm/query.go
  src/pkg/scan/dao/scanner/registration.go
  src/replication/dao/policy.go
Labels: target/2.2.0

#13770 Add default CVE allowlist to project library
  make/migrations/postgresql/0050_2.2.0_schema.up.sql
Labels: target/2.2.0

#13777 build: add cleanbaseimage target in Makefile
  Makefile
Labels: target/2.2.0

#13785 fix(scan): returns 400 when artifact not support by scanner
  api/v2.0/swagger.yaml
  src/controller/scan/base_controller.go
Labels: target/2.2.0

#13792 fixes robot account list permission issue
  src/controller/robot/controller.go
Labels: target/2.2.0

#13751 Add content type and length in header
  src/controller/proxy/controller.go
  src/controller/proxy/controller_test.go
  src/controller/proxy/remote.go
  src/controller/replication/flow/mock_adapter_test.go
  src/pkg/registry/client.go
  src/pkg/registry/client_test.go
  src/replication/adapter/adapter.go
  src/replication/adapter/huawei/image_registry.go
  src/replication/adapter/huawei/image_registry_test.go
  src/replication/transfer/image/transfer.go
  src/replication/transfer/image/transfer_test.go
  src/server/middleware/repoproxy/proxy.go
  src/testing/controller/controller.go
  src/testing/controller/proxy/remote_interface.go
  src/testing/pkg/registry/client.go
Labels: target/2.2.0

#13790 fix gc log not found issue
  src/controller/gc/controller.go
  src/controller/gc/controller_test.go
  src/server/v2.0/handler/gc.go
Labels: target/2.2.0

#13766 migration admin job data
  make/migrations/postgresql/0050_2.2.0_schema.up.sql
  src/controller/gc/model.go
Labels: target/2.2.0

#13741 fix robot account update issue
  make/migrations/postgresql/0050_2.2.0_schema.up.sql
  src/common/config/metadata/metadatalist.go
  src/core/config/config_test.go
  src/server/v2.0/handler/robot.go
  src/server/v2.0/handler/robot_test.go
Labels: target/2.2.0

#13813 refactor(api): move scan all apis to go-swagger
  Makefile
  api/v2.0/legacy_swagger.yaml
  api/v2.0/swagger.yaml
  src/core/api/harborapi_test.go
  src/core/api/scan_all.go
  src/core/api/scan_all_test.go
  src/pkg/scheduler/scheduler.go
  src/server/v2.0/handler/gc.go
  src/server/v2.0/handler/handler.go
  src/server/v2.0/handler/model/gc.go
  src/server/v2.0/handler/model/schedule.go
  src/server/v2.0/handler/scan_all.go
  src/server/v2.0/handler/scan_all_test.go
  src/server/v2.0/route/legacy.go
  src/testing/server/v2.0/handler/handler.go
  tests/apitests/python/library/base.py
  tests/apitests/python/library/scan_all.py
  tests/apitests/python/library/system.py
  tests/apitests/python/test_system_level_scan_all.py
Labels: target/2.2.0

#13821 refactor: remove code of scan all job
  src/jobservice/runtime/bootstrap.go
  src/pkg/scan/all/job.go
  src/pkg/scan/all/stats.go
Labels: target/2.2.0

#13819 refactor: remove code of admin job
  make/migrations/postgresql/0050_2.2.0_schema.up.sql
  src/common/dao/admin_job.go
  src/common/dao/admin_job_test.go
  src/common/models/adminjob.go
  src/common/models/base.go
  src/controller/gc/callback.go
  src/core/api/admin_job.go
  src/core/api/config.go
  src/core/api/harborapi_test.go
  src/core/api/models/admin_job.go
  src/core/api/models/admin_job_test.go
  src/core/api/models/execution.go
  src/core/middlewares/middlewares_test.go
  src/core/service/notifications/admin/handler.go
  src/core/service/notifications/jobs/handler.go
  src/server/route.go
  src/testing/apitests/apilib/admin_job.go
  src/testing/apitests/apilib/admin_job_req.go
Labels: target/2.2.0

#13791 Add extra parms when forming redirect URI for OIDC
  src/common/config/metadata/metadatalist.go
  src/common/config/metadata/type.go
  src/common/config/metadata/type_test.go
  src/common/const.go
  src/common/models/config.go
  src/common/utils/oidc/helper.go
  src/common/utils/oidc/helper_test.go
  src/core/config/config.go
Labels: target/2.2.0

#13800 Add handler to handle redirect via authproxy
  src/common/const.go
  src/core/api/base.go
  src/core/auth/authproxy/auth.go
  src/core/controllers/authproxy_redirect.go
  src/server/route.go
Labels: target/2.2.0

#13820 Use the same transaction to remove the schedule to avoid dead lock in database
  src/pkg/scheduler/scheduler.go
Labels: target/2.2.0

#13836 upgrade go version to v1.15.6
  .github/workflows/CI.yml
  .github/workflows/build-package.yml
  .github/workflows/conformance_test.yml
  CONTRIBUTING.md
  Makefile
  make/photon/chartserver/builder
  make/photon/notary/binary.Dockerfile
  make/photon/registry/Dockerfile.binary
  make/photon/trivy-adapter/Dockerfile.binary
  make/photon/trivy-adapter/builder.sh
  tests/ci/distro_installer.sh
  tools/swagger/Dockerfile
Labels: target/2.2.0

#13838 feat: add trigger to the metrics of the scan all job
  api/v2.0/swagger.yaml
  src/server/v2.0/handler/scan_all.go
Labels: target/2.2.0

#13839 Provide the function to update extra attributes in the task manager
  src/pkg/scheduler/scheduler.go
  src/pkg/task/mock_task_manager_test.go
  src/pkg/task/task.go
  src/pkg/task/task_test.go
  src/testing/pkg/scheduler/scheduler.go
  src/testing/pkg/task/manager.go
Labels: target/2.2.0

#13844 fix quota cannot be updated after gc
  src/controller/gc/callback.go
Labels: target/2.2.0

#13616 Store vulnerability data from scanner into a relational format
  .gitignore
  make/migrations/postgresql/0050_2.2.0_schema.up.sql
  src/controller/event/handler/webhook/scan/scan.go
  src/controller/p2p/preheat/enforcer.go
  src/controller/p2p/preheat/enforcer_test.go
  src/controller/scan/base_controller.go
  src/controller/scan/base_controller_test.go
  src/controller/scan/callback_test.go
  src/controller/scanner/base_controller.go
  src/controller/scanner/base_controller_test.go
  src/pkg/scan/dao/scan/model.go
  src/pkg/scan/dao/scan/report_test.go
  src/pkg/scan/dao/scan/vulnerability.go
  src/pkg/scan/dao/scan/vulnerability_test.go
  src/pkg/scan/job_test.go
  src/pkg/scan/postprocessors/report_converters.go
  src/pkg/scan/postprocessors/report_converters_test.go
  src/pkg/scan/report/manager.go
  src/pkg/scan/report/report.go
  src/pkg/scan/report/summary.go
  src/pkg/scan/report/supported_mime_test.go
  src/pkg/scan/report/supported_mimes.go
  src/pkg/scan/rest/v1/client_test.go
  src/pkg/scan/rest/v1/spec.go
  src/pkg/scan/vuln/report.go
  src/pkg/scan/vuln/summary.go
  src/server/middleware/vulnerable/vulnerable.go
  src/server/v2.0/handler/assembler/vul.go
  src/server/v2.0/handler/util.go
  src/testing/pkg/scan/postprocessors/report_converters.go
Labels: area/interrogation-service, target/2.2.0

#13823 Replace tilde in install_cert.sh
  make/photon/common/install_cert.sh
  make/photon/core/Dockerfile
  make/photon/jobservice/Dockerfile
Labels: target/2.2.0

#13639 chore(trivy): Bump up Trivy scanner adapter to v0.17.0
  Makefile
Labels: area/interrogation-service, area/vulnerability-scan
