Repository goharbor/harbor, pull requests merged in 2020-07, with the labels that each got.

#12378 feat(preheat):implement policy enforcer
  src/controller/p2p/preheat/enforcer.go
  src/controller/p2p/preheat/enforcer_test.go
  src/jobservice/job/known_jobs.go
  src/jobservice/runtime/bootstrap.go
  src/pkg/p2p/preheat/job.go
  src/pkg/p2p/preheat/job_test.go
  src/pkg/p2p/preheat/provider/preheat_image.go
  src/testing/pkg/p2p/preheat/policy/manager.go
  src/testing/pkg/task/execution_manager.go
  src/testing/pkg/task/manager.go
Labels: area/P2P-Distribution, candidate/2.1.0

#12382 feat(code):enable code security scanning
  .github/workflows/codeql-analysis.yml
Labels: area/ci, enhancement

#12381 fix delete manifest route issue
  src/registryctl/handlers/router.go
Labels: target/2.1.0

#12356 add middlware for put manifest
  src/go.mod
  src/go.sum
  src/server/middleware/blob/put_blob_upload.go
  src/server/middleware/blob/put_manifest.go
  src/server/middleware/blob/put_manifest_test.go
  src/server/middleware/blob/util.go
  src/vendor/github.com/justinas/alice/.travis.yml
  src/vendor/github.com/justinas/alice/LICENSE
  src/vendor/github.com/justinas/alice/README.md
  src/vendor/github.com/justinas/alice/chain.go
  src/vendor/modules.txt
Labels: target/2.1.0

#12386 fix return value for blob & manifest not found
  src/registryctl/api/base.go
  src/registryctl/api/base_test.go
Labels: target/2.1.0

#12385 support list blobs by update time
  src/pkg/blob/dao/dao.go
  src/pkg/blob/dao/dao_test.go
  src/pkg/blob/manager_test.go
  src/pkg/blob/models/blob.go
Labels: target/2.1.0

#12389 fix: add count method of policy manager to replace list method return…
  src/controller/p2p/preheat/enforcer.go
  src/controller/p2p/preheat/enforcer_test.go
  src/pkg/p2p/preheat/dao/policy/dao.go
  src/pkg/p2p/preheat/dao/policy/dao_test.go
  src/pkg/p2p/preheat/policy/manager.go
  src/pkg/p2p/preheat/policy/manager_test.go
  src/testing/pkg/p2p/preheat/policy/manager.go
Labels: area/P2P-Distribution, candidate/2.1.0

#12392 fix(p2p):remove the provider manager related to
  src/controller/p2p/preheat/controllor_test.go
  src/controller/p2p/preheat/enforcer.go
  src/controller/p2p/preheat/enforcer_test.go
  src/pkg/p2p/preheat/job_test.go
  src/pkg/p2p/preheat/provider/factory.go
  src/pkg/p2p/preheat/provider/kraken.go
  src/pkg/p2p/preheat/provider/kraken_test.go
  src/testing/pkg/p2p/preheat/instance/manager.go
Labels: area/P2P-Distribution, candidate/2.1.0

#12395 Feat/preheat controller policy part
  api/v2.0/swagger.yaml
  src/controller/p2p/preheat/controller.go
  src/controller/p2p/preheat/controllor_test.go
  src/pkg/p2p/preheat/dao/policy/dao.go
  src/pkg/p2p/preheat/dao/policy/dao_test.go
  src/pkg/p2p/preheat/policy/manager.go
  src/pkg/p2p/preheat/policy/manager_test.go
  src/server/v2.0/handler/preheat.go
  src/server/v2.0/handler/preheat_test.go
  src/testing/pkg/p2p/preheat/policy/manager.go
Labels: area/P2P-Distribution, candidate/2.1.0

#12407 fix: adjust p2p preheat policy swagger yaml definitions
  api/v2.0/swagger.yaml
Labels: area/P2P-Distribution, candidate/2.1.0

#12400 add time windows support in artifact trash
  src/jobservice/job/impl/gc/garbage_collection.go
  src/pkg/artifactrash/dao/dao.go
  src/pkg/artifactrash/dao/dao_test.go
  src/pkg/artifactrash/manager.go
  src/pkg/artifactrash/manager_test.go
  src/testing/pkg/artifactrash/manager.go
Labels: target/2.1.0

#12411 Get instance by name.
  api/v2.0/swagger.yaml
  src/controller/p2p/preheat/controller.go
  src/pkg/p2p/preheat/dao/instance/dao.go
  src/pkg/p2p/preheat/dao/instance/dao_test.go
  src/pkg/p2p/preheat/instance/manager.go
  src/pkg/p2p/preheat/instance/manager_test.go
  src/testing/pkg/p2p/preheat/instance/manager.go
Labels: area/P2P-Distribution

#12414 chore(preheat):add mock policy enforcer
  src/testing/controller/p2p/preheat/enforcer.go
Labels: area/P2P-Distribution, candidate/2.1.0

#12424 fix(quota): fix internal server error when delete project
  src/common/quota/driver/project/driver.go
  src/core/api/project.go
Labels: target/1.10.4

#12419 feat(preheat): add healthcheck methods for p2p preheat controller
  src/controller/p2p/preheat/controller.go
  src/controller/p2p/preheat/controllor_test.go
Labels: area/P2P-Distribution, candidate/2.1.0

#12415 Instance handler.
  src/server/v2.0/handler/preheat.go
  src/server/v2.0/handler/preheat_test.go
Labels: area/P2P-Distribution, candidate/2.1.0

#12428 Add P2P trigger event and handler
  src/controller/artifact/controller.go
  src/controller/artifact/controller_test.go
  src/controller/event/handler/init.go
  src/controller/event/handler/p2p/preheat.go
  src/controller/event/handler/p2p/preheat_test.go
  src/controller/event/metadata/label.go
  src/controller/event/topic.go
  src/controller/p2p/preheat/enforcer.go
Labels: area/P2P-Distribution, candidate/2.1.0

#12447 bump up version to v1.10.4
  VERSION
Labels: target/1.10.4

#12430 Preheat and healthcheck
  api/v2.0/swagger.yaml
  src/server/v2.0/handler/preheat.go
Labels: area/P2P-Distribution, candidate/2.1.0

#12344 Add P2p preheat distribution instance UI
  src/portal/scripts/convert-yaml-to-json.js
  src/portal/src/app/app.module.ts
  src/portal/src/app/base/harbor-shell/harbor-shell.component.html
  src/portal/src/app/distribution/base.scss
  src/portal/src/app/distribution/distribution-instances/distribution-instances.component.html
  src/portal/src/app/distribution/distribution-instances/distribution-instances.component.scss
  src/portal/src/app/distribution/distribution-instances/distribution-instances.component.spec.ts
  src/portal/src/app/distribution/distribution-instances/distribution-instances.component.ts
  src/portal/src/app/distribution/distribution-interface.ts
  src/portal/src/app/distribution/distribution-setup-modal/distribution-setup-modal.component.html
  src/portal/src/app/distribution/distribution-setup-modal/distribution-setup-modal.component.scss
  src/portal/src/app/distribution/distribution-setup-modal/distribution-setup-modal.component.spec.ts
  src/portal/src/app/distribution/distribution-setup-modal/distribution-setup-modal.component.ts
  src/portal/src/app/distribution/distribution.module.ts
  src/portal/src/app/harbor-routing.module.ts
  src/portal/src/app/shared/shared.const.ts
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
  src/portal/src/images/kraken-logo-color.svg
Labels: area/P2P-Distribution, candidate/2.1.0

#12438 [Cherry pick]fix(db): set max open conns of sql.DB manually
  src/common/dao/pgsql.go
  src/common/dao/pgsql_test.go
  src/common/dao/testutils.go
Labels: target/2.0.2

#12459 Query preheat instance by name
  src/portal/src/app/distribution/distribution-instances/distribution-instances.component.ts
  src/portal/src/app/distribution/distribution-setup-modal/distribution-setup-modal.component.ts
Labels: area/P2P-Distribution, candidate/2.1.0

#12458 Enable RBAC control in the preheat API
  src/common/rbac/const.go
  src/common/rbac/project_rbac_role.go
  src/server/v2.0/handler/preheat.go
Labels: area/P2P-Distribution, candidate/2.1.0

#12432 Rename "reuse_sys_cve_whitelist" to "reuse_sys_cve_allowlist"
  make/migrations/postgresql/0040_2.1.0_schema.up.sql
Labels: target/2.1.0

#12462 Feat/preheat execution api
  api/v2.0/swagger.yaml
  src/controller/task/controller.go
  src/controller/task/controller_test.go
  src/controller/task/execution_controller.go
  src/controller/task/execution_controller_test.go
  src/server/v2.0/handler/preheat.go
  src/server/v2.0/handler/preheat_test.go
Labels: area/P2P-Distribution, candidate/2.1.0

#12274 Add proxy cache feature
  src/controller/proxy/controller.go
  src/controller/proxy/controller_test.go
  src/controller/proxy/inflight.go
  src/controller/proxy/inflight_test.go
  src/controller/proxy/local.go
  src/controller/proxy/local_test.go
  src/controller/proxy/remote.go
  src/server/middleware/repoproxy/proxy.go
  src/server/registry/route.go
Labels: target/2.1.0

#12454 feat(preheat): add list providers under project level handler
  api/v2.0/swagger.yaml
  src/server/v2.0/handler/preheat.go
Labels: area/P2P-Distribution, candidate/2.1.0

#12440 refactor: remove initialization of clair db
  make/photon/prepare/templates/core/env.jinja
  src/common/config/manager_test.go
  src/common/config/metadata/metadatalist.go
  src/common/const.go
  src/common/dao/base.go
  src/common/utils/test/config.go
  src/common/utils/test/test.go
  src/core/config/config.go
  src/core/config/config_test.go
  src/core/main.go
Labels: target/2.1.0

#12477 [Cherry pick]chore(db): change max_connections of postgres to 1024
  make/harbor.yml.tmpl
  make/photon/db/docker-entrypoint.sh
Labels: target/2.0.2

#12480 refactor(quota): move pkg/types to pkg/quota/types
  src/common/models/project.go
  src/controller/quota/controller.go
  src/controller/quota/controller_test.go
  src/controller/quota/driver/project/project.go
  src/controller/quota/driver/project/project_test.go
  src/controller/quota/util_test.go
  src/core/api/project.go
  src/core/api/quota.go
  src/core/api/quota_test.go
  src/pkg/quota/dao/dao.go
  src/pkg/quota/dao/dao_test.go
  src/pkg/quota/dao/util.go
  src/pkg/quota/driver/driver.go
  src/pkg/quota/errors.go
  src/pkg/quota/manager.go
  src/pkg/quota/manager_test.go
  src/pkg/quota/models/quota.go
  src/pkg/quota/models/quota_test.go
  src/pkg/quota/types/format.go
  src/pkg/quota/types/format_test.go
  src/pkg/quota/types/resources.go
  src/pkg/quota/types/resources_test.go
  src/pkg/quota/util.go
  src/pkg/quota/util_test.go
  src/pkg/scan/dao/scanner/registration.go
  src/pkg/types/error.go
  src/server/middleware/quota/copy_artifact.go
  src/server/middleware/quota/copy_artifact_test.go
  src/server/middleware/quota/post_initiate_blob_upload.go
  src/server/middleware/quota/post_initiate_blob_upload_test.go
  src/server/middleware/quota/put_blob_upload.go
  src/server/middleware/quota/put_blob_upload_test.go
  src/server/middleware/quota/put_manifest.go
  src/server/middleware/quota/put_manifest_test.go
  src/server/middleware/quota/quota.go
  src/server/middleware/quota/quota_test.go
  src/testing/controller/quota/controller.go
  src/testing/pkg/quota/driver/driver.go
  src/testing/pkg/quota/manager.go
Labels: target/2.1.0

#12478 feat(p2p):enhance policy enforcer
  src/controller/p2p/preheat/enforcer.go
  src/controller/p2p/preheat/enforcer_test.go
Labels: area/P2P-Distribution, candidate/2.1.0

#12439 revise gc job to align non blocking gc
  src/jobservice/job/impl/gc/garbage_collection.go
  src/jobservice/job/impl/gc/garbage_collection_test.go
  src/jobservice/job/impl/gc/util.go
  src/pkg/artifactrash/dao/dao.go
  src/pkg/blob/models/blob.go
  tests/apitests/python/library/system.py
Labels: target/2.1.0

#12489 upgrade golang to v1.14.5
  .github/workflows/CI.yml
  .github/workflows/conformance_test.yml
  CONTRIBUTING.md
  Makefile
  docs/build-customize-contribute/use-make.md
  make/photon/chartserver/builder
  make/photon/clair-adapter/Dockerfile.binary
  make/photon/clair-adapter/builder.sh
  make/photon/clair/Dockerfile.binary
  make/photon/clair/builder
  make/photon/notary/binary.Dockerfile
  make/photon/registry/Dockerfile.binary
  make/photon/trivy-adapter/Dockerfile.binary
  make/photon/trivy-adapter/builder.sh
  src/go.mod
  src/jobservice/hook/hook_client.go
  src/vendor/modules.txt
  tests/ci/distro_installer.sh
  tools/swagger/Dockerfile
Labels: target/2.1.0

#12505 [Cherry-pick]Fix replication bugs #11974, #11939
  src/pkg/registry/auth/authorizer.go
  src/pkg/registry/auth/bearer/authorizer.go
Labels: target/2.0.2

#12494 fix get manifest return code
  src/server/middleware/repoproxy/proxy.go
Labels: target/2.1.0

#12513 fix(jobservice):add job id in log getting error
  src/jobservice/core/controller.go
Labels: area/job-services, target/2.1.0

#12519 [cherry-pick]: chore(trivy): Bump up Trivy adapter to v0.12.0
  Makefile
Labels: target/2.0.2

#9311 Add options for automatic onboarding and username claim
  src/common/config/metadata/metadatalist.go
  src/common/const.go
  src/common/models/config.go
  src/common/utils/oidc/helper.go
  src/common/utils/oidc/helper_test.go
  src/core/config/config.go
  src/core/config/config_test.go
  src/core/controllers/oidc.go
  src/portal/src/app/config/auth/config-auth.component.html
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/lib/components/config/config.ts
Labels: area/oidc, target/2.1.0

#12506 Don't return the error detail back to the client when adding registry
  src/core/api/registry.go
Labels: target/2.1.0

#12509 [Cherry-pick]Don't return the error detail back to the client when adding registry
  src/core/api/registry.go
Labels: target/2.0.2

#12510 Prevent copying artifact to a proxy cache project
  api/v2.0/swagger.yaml
  src/server/v2.0/handler/artifact.go
Labels: target/2.1.0

#12481 fix blob deleting status issue
  src/controller/blob/controller.go
  src/controller/blob/controller_test.go
  src/pkg/blob/dao/dao.go
  src/pkg/blob/dao/dao_test.go
  src/pkg/blob/manager.go
  src/pkg/blob/manager_test.go
  src/server/middleware/blob/head_blob.go
  src/server/middleware/blob/util.go
  src/testing/controller/blob/controller.go
  src/testing/pkg/blob/manager.go
Labels: target/2.1.0

#12530 [cherry-pick] fix SWR replication adapter pull-based
  src/replication/adapter/huawei/huawei_adapter.go
Labels: target/2.0.2

#12507 fix(preheat): fix preheat handler PingInstance and UpdateInstance
  api/v2.0/swagger.yaml
  make/migrations/postgresql/0040_2.1.0_schema.up.sql
  src/controller/p2p/preheat/controller.go
  src/controller/p2p/preheat/controllor_test.go
  src/portal/src/app/distribution/distribution-instances/distribution-instances.component.ts
  src/portal/src/app/distribution/distribution-setup-modal/distribution-setup-modal.component.ts
  src/server/v2.0/handler/preheat.go
Labels: area/P2P-Distribution, candidate/2.1.0

#12511 fix(preheat):remove health property check when saving instance
  src/controller/p2p/preheat/controller.go
  src/controller/p2p/preheat/controllor_test.go
  src/controller/p2p/preheat/enforcer.go
Labels: area/P2P-Distribution, candidate/2.1.0

#12496 Provide secret manager for proxy cache project
  src/pkg/proxy/secret/manager.go
  src/pkg/proxy/secret/manager_test.go
Labels: target/2.1.0

#12528 add debugging env for GC time window
  src/common/const.go
  src/core/api/reg_gc.go
  src/core/config/config.go
  src/core/config/config_test.go
  src/jobservice/job/impl/gc/garbage_collection.go
  src/pkg/blob/dao/dao.go
  src/server/middleware/blob/head_blob.go
  src/server/middleware/blob/util.go
  tests/apitests/python/library/system.py
  tests/ci/api_common_install.sh
Labels: target/2.1.0

#12556 handle path not found when to delete manifest
  src/registryctl/api/registry/manifest/manifest.go
Labels: target/2.1.0

#12499 Add p2p-preheat policy UI
  src/portal/src/app/distribution/distribution-instances/distribution-instances.component.html
  src/portal/src/app/distribution/distribution-instances/distribution-instances.component.spec.ts
  src/portal/src/app/distribution/distribution-instances/distribution-instances.component.ts
  src/portal/src/app/distribution/distribution-interface.ts
  src/portal/src/app/distribution/distribution-setup-modal/distribution-setup-modal.component.html
  src/portal/src/app/distribution/distribution-setup-modal/distribution-setup-modal.component.scss
  src/portal/src/app/distribution/distribution-setup-modal/distribution-setup-modal.component.ts
  src/portal/src/app/harbor-routing.module.ts
  src/portal/src/app/project/p2p-provider/add-p2p-policy/add-p2p-policy.component.html
  src/portal/src/app/project/p2p-provider/add-p2p-policy/add-p2p-policy.component.scss
  src/portal/src/app/project/p2p-provider/add-p2p-policy/add-p2p-policy.component.spec.ts
  src/portal/src/app/project/p2p-provider/add-p2p-policy/add-p2p-policy.component.ts
  src/portal/src/app/project/p2p-provider/p2p-provider.component.html
  src/portal/src/app/project/p2p-provider/p2p-provider.component.scss
  src/portal/src/app/project/p2p-provider/p2p-provider.component.spec.ts
  src/portal/src/app/project/p2p-provider/p2p-provider.component.ts
  src/portal/src/app/project/p2p-provider/p2p-provider.service.spec.ts
  src/portal/src/app/project/p2p-provider/p2p-provider.service.ts
  src/portal/src/app/project/p2p-provider/policy/policy.component.html
  src/portal/src/app/project/p2p-provider/policy/policy.component.scss
  src/portal/src/app/project/p2p-provider/policy/policy.component.spec.ts
  src/portal/src/app/project/p2p-provider/policy/policy.component.ts
  src/portal/src/app/project/p2p-provider/task-list/task-list.component.html
  src/portal/src/app/project/p2p-provider/task-list/task-list.component.scss
  src/portal/src/app/project/p2p-provider/task-list/task-list.component.spec.ts
  src/portal/src/app/project/p2p-provider/task-list/task-list.component.ts
  src/portal/src/app/project/project-detail/project-detail.component.ts
  src/portal/src/app/project/project.module.ts
  src/portal/src/app/shared/shared.const.ts
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
  src/portal/src/lib/components/cron-schedule/cron-schedule.component.html
  src/portal/src/lib/components/cron-schedule/cron-schedule.component.scss
  src/portal/src/lib/components/cron-schedule/cron-schedule.component.ts
  src/portal/src/lib/services/permission-static.ts
  src/portal/src/lib/utils/utils.ts
Labels: area/P2P-Distribution, target/2.1.0, target/FC

#12547 Fix: preheat install update transaction.
  src/pkg/p2p/preheat/dao/instance/dao.go
Labels: area/P2P-Distribution, candidate/2.1.0

#12549 fix(replication): fix jfrog replication when filter includes multi im…
  src/replication/adapter/jfrog/adapter.go
  src/replication/adapter/jfrog/adapter_test.go
  src/replication/adapter/jfrog/client.go
  src/replication/adapter/jfrog/client_test.go
  src/replication/adapter/jfrog/types.go
Labels: replication/adapters, target/2.0.2

#12582 fix(p2p-preheat):fix issues of triggering preheat
  src/controller/p2p/preheat/enforcer.go
  src/pkg/p2p/preheat/job.go
  src/pkg/p2p/preheat/policy/filter.go
  src/pkg/p2p/preheat/policy/filter_test.go
  src/pkg/p2p/preheat/policy/manager.go
Labels: area/P2P-Distribution, candidate/2.1.0

#12539 Fix: beego app config port hardcode
  make/photon/prepare/templates/core/app.conf.jinja
  make/photon/prepare/templates/core/env.jinja
  make/photon/prepare/utils/core.py
Labels: kind/helm-chart-impact

#12597 Fix for project metadata
  src/controller/event/handler/replication/replication.go
  src/controller/event/handler/webhook/artifact/artifact.go
  src/controller/event/handler/webhook/artifact/replication.go
  src/controller/event/handler/webhook/artifact/replication_test.go
  src/controller/event/handler/webhook/chart/chart.go
  src/controller/event/handler/webhook/quota/quota.go
  src/controller/event/handler/webhook/scan/scan.go
Labels: target/2.0.2

#12599 fix(preheat):improve preheat job logs
  src/pkg/p2p/preheat/job.go
  src/pkg/p2p/preheat/provider/driver.go
Labels: area/P2P-Distribution, candidate/2.1.0

#12603 fix update pull time issue
  src/controller/event/handler/internal/artifact.go
Labels: target/2.0.2

#12609 fix(preheat):fix issues of event-based preheat
  src/controller/event/handler/p2p/preheat.go
  src/controller/p2p/preheat/enforcer.go
Labels: area/P2P-Distribution, candidate/2.1.0

#12612 fix(preheat):enhance preheat job
  src/controller/p2p/preheat/enforcer.go
  src/pkg/p2p/preheat/job.go
  src/pkg/p2p/preheat/job_test.go
Labels: area/P2P-Distribution, candidate/2.1.0

#12602 Modify column name for preheat task list UI
  src/portal/src/app/project/p2p-provider/add-p2p-policy/add-p2p-policy.component.html
  src/portal/src/app/project/p2p-provider/task-list/task-list.component.html
  src/portal/src/app/project/p2p-provider/task-list/task-list.component.ts
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: area/P2P-Distribution, area/ui, candidate/2.1.0

#12595 remove limitation of artifact in the GC job
  src/jobservice/job/impl/gc/garbage_collection.go
  src/jobservice/job/impl/gc/garbage_collection_test.go
Labels: target/2.1.0

#12567 Schedule preheat policy.
  src/controller/p2p/preheat/controller.go
  src/controller/p2p/preheat/controllor_test.go
  src/core/api/base.go
  src/pkg/p2p/preheat/models/policy/policy.go
  src/pkg/retention/controller.go
  src/server/v2.0/handler/preheat.go
Labels: area/P2P-Distribution, candidate/2.1.0

#12512 Include the registry info in the project summary API for proxy cache project
  api/v2.0/legacy_swagger.yaml
  src/common/models/project.go
  src/core/api/project.go
  src/core/api/replication_policy.go
  src/replication/dao/policy_test.go
  src/replication/model/policy.go
Labels: target/2.1.0

#12617 fix(preheat): fix npe issues
  src/controller/p2p/preheat/controller.go
  src/controller/p2p/preheat/controllor_test.go
  src/pkg/p2p/preheat/policy/manager.go
  src/pkg/p2p/preheat/policy/manager_test.go
  src/pkg/p2p/preheat/provider/client/http_client.go
Labels: area/P2P-Distribution, candidate/2.1.0

#12615 revise the blob logs
  src/jobservice/job/impl/gc/garbage_collection.go
  src/pkg/blob/dao/dao.go
  src/server/middleware/blob/head_blob.go
  src/server/middleware/blob/util.go
Labels: target/2.1.0

#12571 Limit the permission of secret used by proxy cache service
  src/common/secret/store.go
  src/common/security/proxycachesecret/context.go
  src/common/security/proxycachesecret/context_test.go
  src/common/security/secret/context.go
  src/controller/proxy/local.go
  src/core/config/config.go
  src/core/middlewares/middlewares.go
  src/lib/patterns.go
  src/lib/patterns_test.go
  src/pkg/proxy/secret/authorizer.go
  src/pkg/proxy/secret/authorizer_test.go
  src/server/middleware/artifactinfo/artifact_info.go
  src/server/middleware/artifactinfo/artifact_info_test.go
  src/server/middleware/repoproxy/proxy.go
  src/server/middleware/repoproxy/proxy_test.go
  src/server/middleware/security/proxy_cache_secret.go
  src/server/middleware/security/proxy_cache_secret_test.go
  src/server/middleware/security/security.go
  src/server/middleware/v2auth/access.go
  src/server/registry/route.go
Labels: area/proxy, target/2.1.0

#12591 add gc read only job
  src/common/job/const.go
  src/core/api/reg_gc.go
  src/jobservice/job/impl/gcreadonly/garbage_collection.go
  src/jobservice/job/impl/gcreadonly/garbage_collection_test.go
  src/jobservice/job/impl/gcreadonly/util.go
  src/jobservice/job/known_jobs.go
  src/jobservice/runtime/bootstrap.go
Labels: target/2.1.0

#12629 update time format of audit log
  api/v2.0/swagger.yaml
  src/server/v2.0/handler/auditlog.go
  src/server/v2.0/handler/project.go
Labels: target/2.1.0
