Repository goharbor/harbor, pull requests merged in 2021-02, with the labels that each got.

#14116 Reduce warning logs in OIDC middleware
  src/server/middleware/security/idtoken.go
  src/server/middleware/security/idtoken_test.go
Labels: target/2.2.0, target/RC

#14131 bump up base to v2.0.6
  VERSION
Labels: target/2.0.6

#14155 Ignore the not found error in some cases
  src/pkg/task/execution.go
Labels: target/2.2.0

#14150 rename permission of robot account
  api/v2.0/swagger.yaml
  src/portal/src/app/system-robot-accounts/list-all-projects/list-all-projects.component.ts
  src/portal/src/app/system-robot-accounts/projects-modal/projects-modal.component.spec.ts
  src/portal/src/app/system-robot-accounts/projects-modal/projects-modal.component.ts
  src/portal/src/app/system-robot-accounts/system-robot-accounts.component.ts
  src/server/v2.0/handler/model/robot.go
  src/server/v2.0/handler/robot.go
  tests/apitests/python/library/robot.py
  tests/apitests/python/test_robot_account.py
Labels: area/robot-account, target/2.2.0

#14168 fix: remove default execution sweeper count
  src/controller/gc/controller.go
  src/controller/p2p/preheat/enforcer.go
  src/controller/replication/controller.go
  src/controller/retention/controller.go
  src/pkg/task/execution.go
  src/pkg/task/execution_test.go
Labels: target/2.2.0

#14176 fix: wrap report vuls record creating in transaction
  src/lib/orm/error.go
  src/lib/orm/orm.go
  src/lib/orm/orm_test.go
  src/pkg/scan/dao/scan/model.go
  src/pkg/scan/dao/scan/vulnerability.go
  src/pkg/scan/dao/scan/vulnerability_test.go
Labels: target/2.2.0

#14115 [Cherry-Pick 2.0.0] Reschedule docker login policy in base image build process
  Makefile
  make/pushimage.sh
Labels: target/2.0.0

#14179 [Cherry pick]fix: remove default execution sweeper count
  src/controller/gc/controller.go
  src/controller/p2p/preheat/enforcer.go
  src/controller/replication/controller.go
  src/controller/retention/controller.go
  src/pkg/task/execution.go
  src/pkg/task/execution_test.go
Labels: target/2.2.0

#14180 [Cherry pick]fix: wrap report vuls record creating in transaction
  src/lib/orm/error.go
  src/lib/orm/orm.go
  src/lib/orm/orm_test.go
  src/pkg/scan/dao/scan/model.go
  src/pkg/scan/dao/scan/vulnerability.go
  src/pkg/scan/dao/scan/vulnerability_test.go
Labels: target/2.2.0

#14181 [cherry-pick] fix gc migration issue
  make/migrations/postgresql/0050_2.2.0_schema.up.sql
Labels: target/2.2.0

#14182 [cherry-pick] Fix retention migrate 2.2.0
  make/migrations/postgresql/0050_2.2.0_schema.up.sql
  src/controller/retention/controller.go
  src/pkg/retention/dao/retention.go
  src/pkg/retention/dao/retention_test.go
  src/pkg/retention/launcher_test.go
  src/pkg/retention/manager.go
  src/pkg/retention/manager_test.go
Labels: target/2.2.0

#14169 Recover the panic of the process of replication adapter and fix bug of gitlab adapter
  src/controller/replication/controller.go
  src/replication/adapter/gitlab/adapter.go
  src/replication/adapter/gitlab/adapter_test.go
  src/replication/adapter/gitlab/client.go
Labels: target/2.2.0

#14178 [cherry-pick] rename permission of robot account (#14150)
  api/v2.0/swagger.yaml
  src/portal/src/app/system-robot-accounts/list-all-projects/list-all-projects.component.ts
  src/portal/src/app/system-robot-accounts/projects-modal/projects-modal.component.spec.ts
  src/portal/src/app/system-robot-accounts/projects-modal/projects-modal.component.ts
  src/portal/src/app/system-robot-accounts/system-robot-accounts.component.ts
  src/server/v2.0/handler/model/robot.go
  src/server/v2.0/handler/robot.go
  tests/apitests/python/library/robot.py
  tests/apitests/python/test_robot_account.py
Labels: target/2.2.0

#14202 fix(jobservice):wrong depth of job logging
  src/jobservice/logger/base.go
  src/jobservice/logger/known_loggers.go
  src/jobservice/logger/known_loggers_test.go
Labels: area/job-services, target/2.2.0

#14203 Fix metrics template for http mode
  make/photon/prepare/templates/nginx/nginx.http.conf.jinja
Labels: area/metrics, target/2.2.0

#14210 test: fix the TestRetryUntil
  src/lib/retry_test.go
Labels: target/2.2.0

#14214 [CP - v2.2]: Use the Email address from DB instead of request
  src/core/controllers/base.go
Labels: target/2.2.0

#14213 [Cherry pick]test: fix the TestRetryUntil
  src/lib/retry_test.go
Labels: target/2.2.0

#14211 [CP - v2.2]: Escape the service passed via request
  src/core/service/token/token.go
Labels: target/2.2.0

#14195 update blob list query
  src/controller/artifact/abstractor.go
  src/controller/artifact/controller.go
  src/controller/blob/controller.go
  src/jobservice/job/impl/gc/garbage_collection.go
  src/jobservice/job/impl/gcreadonly/garbage_collection.go
  src/pkg/blob/dao/dao.go
  src/pkg/blob/dao/dao_test.go
  src/pkg/blob/manager.go
  src/pkg/blob/manager_test.go
  src/pkg/blob/models/blob.go
  src/server/middleware/blob/copy_artifact.go
  src/server/middleware/quota/copy_artifact.go
  src/testing/controller/blob/controller.go
  src/testing/pkg/blob/manager.go
Labels: target/2.2.0

#14219 [cherry-pick]Release 2.2.0 14195
  src/controller/artifact/abstractor.go
  src/controller/artifact/controller.go
  src/controller/blob/controller.go
  src/jobservice/job/impl/gc/garbage_collection.go
  src/jobservice/job/impl/gcreadonly/garbage_collection.go
  src/pkg/blob/dao/dao.go
  src/pkg/blob/dao/dao_test.go
  src/pkg/blob/manager.go
  src/pkg/blob/manager_test.go
  src/pkg/blob/models/blob.go
  src/server/middleware/blob/copy_artifact.go
  src/server/middleware/quota/copy_artifact.go
  src/testing/controller/blob/controller.go
  src/testing/pkg/blob/manager.go
Labels: target/2.2.0

#14208 Fix sql issue for querying tasks
  src/lib/orm/orm.go
  src/pkg/artifact/dao/dao.go
  src/pkg/task/dao/execution.go
  src/pkg/task/dao/task.go
Labels: target/2.2.0

#14222 [cherry-pick]Fix sql issue for querying tasks
  src/lib/orm/orm.go
  src/pkg/artifact/dao/dao.go
  src/pkg/task/dao/execution.go
  src/pkg/task/dao/task.go
Labels: target/2.2.0

#14220 fix quota dao sql injection
  src/pkg/quota/dao/util.go
Labels: target/2.2.0

#14224 [cherry-pick 2.2]fix quota dao sql injection
  src/pkg/quota/dao/util.go
Labels: target/2.2.0

#14240 chore: Bump up Trivy scanner adapter from v0.17.0 to v0.18.0
  Makefile
Labels: area/interrogation-service, scanner/trivy

#14262 [Cherry pick]chore: Bump up Trivy scanner adapter from v0.17.0 to v0.18.0 (#14240)
  Makefile
Labels: target/2.2.0

#14283 fix: use clone query in loop of artifact.Iterator func
  src/controller/artifact/helper.go
  src/controller/artifact/helper_test.go
  src/testing/pkg/artifact/fake_manager.go
  src/testing/pkg/artifact/manager.go
  src/testing/pkg/pkg.go
Labels: target/2.2.0

#14285 [Cherry pick]fix: use clone query in loop of artifact.Iterator func (#14283)
  src/controller/artifact/helper.go
  src/controller/artifact/helper_test.go
  src/testing/pkg/artifact/fake_manager.go
  src/testing/pkg/artifact/manager.go
  src/testing/pkg/pkg.go
Labels: target/2.2.0

#14100 [Cherry-pick 2.1.0] Fix nightly issues caused by docker upgrade to 20
  tests/apitests/python/library/artifact.py
  tests/apitests/python/library/base.py
  tests/apitests/python/library/chart.py
  tests/apitests/python/library/docker_api.py
  tests/apitests/python/library/helm.py
  tests/apitests/python/library/label.py
  tests/apitests/python/library/repository.py
  tests/apitests/python/sign_image.sh
  tests/apitests/python/test_add_sys_label_to_tag.py
  tests/apitests/python/test_assign_role_to_ldap_group.py
  tests/apitests/python/test_copy_artifact_outside_project.py
  tests/apitests/python/test_del_repo.py
  tests/apitests/python/test_garbage_collection.py
  tests/apitests/python/test_manage_project_member.py
  tests/apitests/python/test_project_level_policy_content_trust.py
  tests/apitests/python/test_project_quota.py
  tests/apitests/python/test_push_chart_by_helm3_chart_cli.py
  tests/apitests/python/test_push_cnab_bundle.py
  tests/apitests/python/test_push_image_with_special_name.py
  tests/apitests/python/test_push_index_by_docker_manifest.py
  tests/apitests/python/test_registry_api.py
  tests/apitests/python/test_replication_from_dockerhub.py
  tests/apitests/python/test_retention.py
  tests/apitests/python/test_robot_account.py
  tests/apitests/python/test_scan_image_artifact.py
  tests/apitests/python/test_scan_image_artifact_in_public_project.py
  tests/apitests/python/test_sign_image.py
  tests/apitests/python/test_system_level_scan_all.py
  tests/apitests/python/test_tag_crud.py
  tests/apitests/python/test_tag_immutability.py
  tests/apitests/python/test_user_view_logs.py
  tests/apitests/python/testutils.py
  tests/ci/api_run.sh
  tests/e2e-image/nightly/Dockerfile
  tests/resources/Docker-Util.robot
  tests/resources/Harbor-Pages/Project-Members.robot
  tests/resources/Harbor-Pages/Project-Tag-Retention.robot
  tests/resources/Harbor-Pages/Project-Tag-Retention_Elements.robot
  tests/resources/Harbor-Pages/Project.robot
  tests/resources/Harbor-Pages/Project_Elements.robot
  tests/resources/Harbor-Pages/Replication.robot
  tests/resources/Nightly-Util.robot
  tests/resources/TestCaseBody.robot
  tests/resources/Util.robot
  tests/robot-cases/Group0-BAT/API_DB.robot
  tests/robot-cases/Group1-Nightly/Common.robot
  tests/robot-cases/Group1-Nightly/Common_GC.robot
  tests/robot-cases/Group1-Nightly/Replication.robot
  tests/robot-cases/Group1-Nightly/Schedule.robot
  tests/robot-cases/Group1-Nightly/Trivy.robot
  tests/robot-cases/Group3-Upgrade/run.sh
Labels: target/2.1.0

#14227 [Cherry-pick 2.2.0] Reschedule docker login policy in base image build process
  Makefile
  make/pushimage.sh
Labels: target/2.2.0

#14273 [Cherry pick 2.2.0] fix nightly issues and upgrade docker and containerd
  tests/apitests/python/library/base.py
  tests/apitests/python/library/docker_api.py
  tests/apitests/python/library/project.py
  tests/apitests/python/library/repository.py
  tests/apitests/python/library/robot.py
  tests/apitests/python/library/sign.py
  tests/apitests/python/test_add_sys_label_to_tag.py
  tests/apitests/python/test_assign_role_to_ldap_group.py
  tests/apitests/python/test_copy_artifact_outside_project.py
  tests/apitests/python/test_del_repo.py
  tests/apitests/python/test_manage_project_member.py
  tests/apitests/python/test_project_level_policy_content_trust.py
  tests/apitests/python/test_project_quota.py
  tests/apitests/python/test_push_cnab_bundle.py
  tests/apitests/python/test_push_image_with_special_name.py
  tests/apitests/python/test_registry_api.py
  tests/apitests/python/test_robot_account.py
  tests/apitests/python/test_scan_image_artifact.py
  tests/apitests/python/test_tag_crud.py
  tests/apitests/python/testutils.py
  tests/ci/api_run.sh
  tests/e2e-image/Dockerfile
  tests/resources/Docker-Util.robot
  tests/resources/Harbor-Pages/Configuration.robot
  tests/resources/Harbor-Pages/OIDC_Auth.robot
  tests/resources/Harbor-Pages/OIDC_Auth_Elements.robot
  tests/resources/Harbor-Pages/Project-Config.robot
  tests/resources/Harbor-Pages/Project-Members.robot
  tests/resources/Harbor-Pages/Project-P2P-Preheat-Elements.robot
  tests/resources/Harbor-Pages/Project-P2P-Preheat.robot
  tests/resources/Harbor-Pages/Project-Tag-Retention.robot
  tests/resources/Harbor-Pages/Project-Tag-Retention_Elements.robot
  tests/resources/Harbor-Pages/Project.robot
  tests/resources/Harbor-Pages/Replication_Elements.robot
  tests/resources/Nightly-Util.robot
  tests/resources/Util.robot
  tests/robot-cases/Group0-BAT/API_DB.robot
  tests/robot-cases/Group1-Nightly/Common.robot
  tests/robot-cases/Group1-Nightly/Notary.robot
  tests/robot-cases/Group1-Nightly/OIDC.robot
  tests/robot-cases/Group1-Nightly/Schedule.robot
  tests/robot-cases/Group3-Upgrade/data.json
  tests/robot-cases/Group3-Upgrade/verify.robot
Labels: target/2.2.0

#14123 [Cherry-pick 2.1.0] Reschedule docker login policy in base image build process
  Makefile
  make/pushimage.sh
  tests/apitests/python/library/base.py
  tests/apitests/python/library/docker_api.py
  tests/apitests/python/library/repository.py
  tests/apitests/python/library/sign.py
  tests/apitests/python/testutils.py
  tests/ci/api_run.sh
  tests/resources/Docker-Util.robot
  tests/resources/Harbor-Pages/Configuration.robot
  tests/resources/Harbor-Pages/OIDC_Auth.robot
  tests/resources/Harbor-Pages/OIDC_Auth_Elements.robot
  tests/resources/Harbor-Pages/Project-Tag-Retention.robot
  tests/resources/Harbor-Pages/Project-Tag-Retention_Elements.robot
  tests/resources/Nightly-Util.robot
  tests/robot-cases/Group0-BAT/API_DB.robot
  tests/robot-cases/Group1-Nightly/Common.robot
  tests/robot-cases/Group1-Nightly/Notary.robot
  tests/robot-cases/Group1-Nightly/OIDC.robot
Labels: target/2.1.0

#14300 refactor: generate quota APIs by go-swagger
  api/v2.0/legacy_swagger.yaml
  api/v2.0/swagger.yaml
  src/common/config/metadata/metadatalist.go
  src/common/const.go
  src/common/models/project.go
  src/core/api/harborapi_test.go
  src/core/api/quota.go
  src/core/api/quota_test.go
  src/pkg/quota/types/resources.go
  src/server/v2.0/handler/handler.go
  src/server/v2.0/handler/model/quota.go
  src/server/v2.0/handler/project.go
  src/server/v2.0/handler/quota.go
  src/server/v2.0/handler/quota_test.go
  src/server/v2.0/route/legacy.go
  src/testing/apitests/apilib/quota.go
  tests/apitests/python/library/base.py
  tests/apitests/python/library/system.py
Labels: target/2.3.0

#14319 add sorting for list blobs
  src/pkg/blob/dao/dao.go
Labels: target/2.1.4, target/2.2.1
