Repository goharbor/harbor, pull requests merged in 2021-11, with the labels that each got.

#15879 Add test cases helm3.7 CLI push in python test
  tests/apitests/python/library/helm.py
  tests/apitests/python/test_push_chart_by_helm3.7_chart_cli.py
  tests/apitests/python/test_push_chart_by_helm3_chart_cli.py
  tests/apitests/python/testutils.py
  tests/ci/api_run.sh
  tests/robot-cases/Group0-BAT/API_DB.robot
  tests/test-engine-image/Dockerfile.api_test
  tests/test-engine-image/Dockerfile.common
Labels: area/test automation/pytest-e2e

#15905 Add wasm-to-oci test cases for harbor push and pull
  tests/robot-cases/Group1-Nightly/Common.robot
  tests/test-engine-image/Dockerfile.common
  tests/test-engine-image/Dockerfile.ui_test
Labels: area/test automation/nightly-testing

#15734 （cherry-pick) Allow empty email attribute for ldap/oidc user
  make/migrations/postgresql/0061_2.3.4_schema.up.sql
  src/common/dao/base.go
  src/common/dao/testutils.go
  src/common/models/base.go
  src/common/models/user.go
  src/controller/project/controller_test.go
  src/controller/user/controller.go
  src/core/auth/ldap/ldap_test.go
  src/core/auth/uaa/uaa_test.go
  src/core/main.go
  src/pkg/member/dao/dao_test.go
  src/pkg/user/dao/dao.go
  src/pkg/user/dao/dao_test.go
  src/pkg/user/dao/user.go
  src/pkg/user/manager.go
  src/pkg/user/models/model.go
  src/server/v2.0/handler/model/user.go
  src/server/v2.0/handler/user.go
  src/testing/pkg/user/dao/dao.go
  src/testing/pkg/user/manager.go
Labels: target/2.3.4

#15934 fix(replication): list projects before replicate
  src/common/http/client.go
  src/pkg/reg/adapter/harbor/base/adapter.go
  src/pkg/reg/adapter/harbor/base/adapter_test.go
  src/pkg/reg/adapter/harbor/base/client.go
Labels: area/replication

#15956 Modify ci script
  tests/ci/api_common_install.sh
  tests/ci/api_run.sh
  tests/ci/distro_installer.sh
  tests/hostcfg.sh
Labels: area/ci

#15985 fix(replication): enhance the replication rule validation
  src/pkg/project/manager.go
  src/pkg/reg/adapter/harbor/base/adapter.go
  src/pkg/reg/adapter/harbor/base/adapter_test.go
Labels: area/replication, target/2.5.0

#16061 add pull update control env
  src/common/const.go
  src/controller/event/handler/auditlog/auditlog.go
  src/controller/event/handler/internal/artifact.go
  src/lib/config/metadata/metadatalist.go
  src/lib/config/userconfig.go
Labels: target/2.3.5

#16051 add pull update control env
  src/common/const.go
  src/controller/event/handler/auditlog/auditlog.go
  src/controller/event/handler/internal/artifact.go
  src/lib/config/metadata/metadatalist.go
  src/lib/config/userconfig.go
Labels: target/2.4.1, target/2.3.5

#16033 Add replication testcase for exclude and bandwidth
  tests/resources/Harbor-Pages/Replication.robot
  tests/resources/Harbor-Pages/Replication_Elements.robot
  tests/robot-cases/Group1-Nightly/Replication.robot
Labels: area/test automation/nightly-testing

#16044 Add robot account do replication test case
  tests/resources/Harbor-Pages/Robot_Account.robot
  tests/resources/Harbor-Pages/Robot_Account_Elements.robot
  tests/robot-cases/Group1-Nightly/Common.robot
  tests/robot-cases/Group1-Nightly/Replication.robot
Labels: area/test automation/nightly-testing
