Repository goharbor/harbor, pull requests merged in 2021-04, with the labels that each got.

#14344 [Cherrypick - 1.10] Add "*" to the claim set in the token for /v2 apis
  src/core/service/token/creator.go
  src/core/service/token/token_test.go
Labels: target/1.10.7

#14591 fix(js): webhook infinitely resending issue
  src/go.mod
  src/go.sum
  src/jobservice/common/rds/keys.go
  src/jobservice/common/rds/scripts.go
  src/jobservice/common/rds/utils.go
  src/jobservice/common/rds/utils_test.go
  src/jobservice/hook/hook_agent.go
  src/jobservice/hook/hook_agent_test.go
  src/jobservice/runtime/bootstrap.go
  src/jobservice/worker/cworker/reaper.go
  src/vendor/github.com/cenkalti/backoff/v4/.gitignore
  src/vendor/github.com/cenkalti/backoff/v4/.travis.yml
  src/vendor/github.com/cenkalti/backoff/v4/LICENSE
  src/vendor/github.com/cenkalti/backoff/v4/README.md
  src/vendor/github.com/cenkalti/backoff/v4/backoff.go
  src/vendor/github.com/cenkalti/backoff/v4/context.go
  src/vendor/github.com/cenkalti/backoff/v4/exponential.go
  src/vendor/github.com/cenkalti/backoff/v4/go.mod
  src/vendor/github.com/cenkalti/backoff/v4/retry.go
  src/vendor/github.com/cenkalti/backoff/v4/ticker.go
  src/vendor/github.com/cenkalti/backoff/v4/timer.go
  src/vendor/github.com/cenkalti/backoff/v4/tries.go
  src/vendor/modules.txt
Labels: target/2.1.5, target/2.2.2, target/2.3.0

#14601 fix(js): webhook infinitely resending issue
  src/go.mod
  src/go.sum
  src/jobservice/common/rds/keys.go
  src/jobservice/common/rds/scripts.go
  src/jobservice/common/rds/utils.go
  src/jobservice/common/rds/utils_test.go
  src/jobservice/hook/hook_agent.go
  src/jobservice/hook/hook_agent_test.go
  src/jobservice/runtime/bootstrap.go
  src/jobservice/worker/cworker/reaper.go
  src/vendor/github.com/cenkalti/backoff/v4/.gitignore
  src/vendor/github.com/cenkalti/backoff/v4/.travis.yml
  src/vendor/github.com/cenkalti/backoff/v4/LICENSE
  src/vendor/github.com/cenkalti/backoff/v4/README.md
  src/vendor/github.com/cenkalti/backoff/v4/backoff.go
  src/vendor/github.com/cenkalti/backoff/v4/context.go
  src/vendor/github.com/cenkalti/backoff/v4/exponential.go
  src/vendor/github.com/cenkalti/backoff/v4/go.mod
  src/vendor/github.com/cenkalti/backoff/v4/retry.go
  src/vendor/github.com/cenkalti/backoff/v4/ticker.go
  src/vendor/github.com/cenkalti/backoff/v4/timer.go
  src/vendor/github.com/cenkalti/backoff/v4/tries.go
  src/vendor/modules.txt
Labels: target/2.1.5

#14602 fix(js): webhook infinitely resending issue
  src/go.mod
  src/go.sum
  src/jobservice/common/rds/keys.go
  src/jobservice/common/rds/scripts.go
  src/jobservice/common/rds/utils.go
  src/jobservice/common/rds/utils_test.go
  src/jobservice/hook/hook_agent.go
  src/jobservice/hook/hook_agent_test.go
  src/jobservice/runtime/bootstrap.go
  src/jobservice/worker/cworker/reaper.go
  src/vendor/github.com/cenkalti/backoff/v4/.gitignore
  src/vendor/github.com/cenkalti/backoff/v4/.travis.yml
  src/vendor/github.com/cenkalti/backoff/v4/LICENSE
  src/vendor/github.com/cenkalti/backoff/v4/README.md
  src/vendor/github.com/cenkalti/backoff/v4/backoff.go
  src/vendor/github.com/cenkalti/backoff/v4/context.go
  src/vendor/github.com/cenkalti/backoff/v4/exponential.go
  src/vendor/github.com/cenkalti/backoff/v4/go.mod
  src/vendor/github.com/cenkalti/backoff/v4/retry.go
  src/vendor/github.com/cenkalti/backoff/v4/ticker.go
  src/vendor/github.com/cenkalti/backoff/v4/timer.go
  src/vendor/github.com/cenkalti/backoff/v4/tries.go
  src/vendor/modules.txt
Labels: target/2.2.2

#14597 Ignore the not found error when trying to delete scheduled policies
  src/core/api/admin_job.go
  src/replication/policy/scheduler/scheduler.go
Labels: target/2.1.5

#14578 Improve the performance of replication
  api/v2.0/swagger.yaml
  src/common/models/repo.go
  src/controller/replication/flow/mock_adapter_test.go
  src/controller/replication/transfer/image/transfer.go
  src/controller/replication/transfer/image/transfer_test.go
  src/lib/q/query.go
  src/pkg/reg/adapter/adapter.go
  src/pkg/reg/adapter/harbor/v2/adapter.go
  src/pkg/reg/adapter/harbor/v2/client.go
  src/pkg/reg/adapter/native/adapter.go
  src/server/v2.0/handler/repository.go
Labels: target/2.3.0

#14499 remove the autobuild step
  .github/workflows/codeql-analysis.yml
Labels: area/ci

#14619 Add --no-cache and --pull flag to image builds
  make/photon/Makefile
Labels: target/2.3.0

#14630 fix(js):job log not found issue
  src/jobservice/core/controller.go
  src/jobservice/logger/getter/db_getter.go
Labels: target/2.1.5

#14628 fix(js):job log not found issue
  src/jobservice/core/controller.go
  src/jobservice/logger/getter/db_getter.go
Labels: target/2.3.0

#14629 fix(js):job log not found issue
  src/jobservice/core/controller.go
  src/jobservice/logger/getter/db_getter.go
Labels: target/2.2.0

#14604 API for users to new model
  api/v2.0/legacy_swagger.yaml
  api/v2.0/swagger.yaml
  src/common/security/local/context.go
  src/controller/project/controller.go
  src/controller/user/controller.go
  src/core/api/harborapi_test.go
  src/core/api/user.go
  src/core/api/user_test.go
  src/lib/orm/error.go
  src/pkg/oidc/dao/meta.go
  src/pkg/oidc/dao/meta_test.go
  src/pkg/oidc/metamanager.go
  src/pkg/oidc/metamanager_test.go
  src/pkg/oidc/secret.go
  src/pkg/oidc/secret_test.go
  src/pkg/repository/manager_test.go
  src/pkg/user/dao/dao.go
  src/pkg/user/dao/dao_test.go
  src/pkg/user/manager.go
  src/pkg/user/manager_test.go
  src/pkg/user/models/user.go
  src/server/v2.0/handler/handler.go
  src/server/v2.0/handler/model/user.go
  src/server/v2.0/handler/user.go
  src/server/v2.0/handler/user_test.go
  src/server/v2.0/route/legacy.go
  src/testing/controller/config/controller.go
  src/testing/controller/controller.go
  src/testing/controller/user/controller.go
  src/testing/pkg/oidc/dao/meta_dao.go
  src/testing/pkg/pkg.go
  src/testing/pkg/user/dao/dao.go
  src/testing/pkg/user/manager.go
  tests/apitests/python/library/base.py
  tests/apitests/python/library/user.py
Labels: target/2.3.0

#14625 Fix bug of ping registry
  src/server/v2.0/handler/registry.go
Labels: target/2.3.0

#14643 fix immutable issue
  src/pkg/immutabletag/match/rule/match.go
Labels: target/2.1.5

#14644 [cherry-pick] fix immutable issue
  src/pkg/immutabletag/match/rule/match.go
Labels: target/2.2.2

#14647 CHERRY-PICK: fix(jobservice): value out of range (#14634)
  src/jobservice/mgt/manager.go
Labels: target/2.2.2

#14646 CHERRY-PICK: fix(jobservice): value out of range (#14634)
  src/jobservice/mgt/manager.go
Labels: target/2.1.5

#14660 bump up base version to v2.1.5
  VERSION
Labels: target/2.1.5

#14611 Refactor health check API
  api/v2.0/legacy_swagger.yaml
  api/v2.0/swagger.yaml
  src/controller/health/checker.go
  src/controller/health/checker_test.go
  src/controller/health/controller.go
  src/controller/health/controller_test.go
  src/controller/health/model.go
  src/core/api/base.go
  src/core/api/harborapi_test.go
  src/core/main.go
  src/server/v2.0/handler/handler.go
  src/server/v2.0/handler/health.go
  src/server/v2.0/route/legacy.go
  tests/apitests/python/library/base.py
  tests/apitests/python/test_health_check.py
Labels: target/2.3.0

#14663 Remove local goharbor images after building
  .github/workflows/build-package.yml
  make/pushimage.sh
Labels: target/2.1.0

#14661 Refactor the statistics API
  api/v2.0/legacy_swagger.yaml
  api/v2.0/swagger.yaml
  src/core/api/harborapi_test.go
  src/core/api/statistic.go
  src/core/api/statistic_test.go
  src/server/v2.0/handler/handler.go
  src/server/v2.0/handler/statistic.go
  src/server/v2.0/route/legacy.go
Labels: target/2.3.0

#14677 fix(replication) aws adapter checkRepository
  src/pkg/reg/adapter/awsecr/adapter.go
Labels: target/2.3.0

#14676 update aliyun and aws region
  src/pkg/reg/adapter/aliacr/adapter.go
  src/pkg/reg/adapter/awsecr/adapter.go
Labels: target/2.3.0

#14680 [cherry-pick] fix(replication) aws adapter checkRepository 2.2.2
  src/replication/adapter/awsecr/adapter.go
Labels: target/2.2.2

#14695 Refine the "not support" error when searching user
  src/core/api/projectmember.go
  src/core/api/projectmember_test.go
  src/core/auth/authenticator.go
Labels: target/2.2.2

#14696 Refine the "not support" error when searching user
  src/core/auth/authenticator.go
Labels: target/2.3.0

#14652 [ 2.1.0 ] Add build base step to UT test in CI
  .github/workflows/build-package.yml
  Makefile
  tests/ci/ut_install.sh
  tests/robot-cases/Group1-Nightly/Setup_Nightly.robot
Labels: target/2.1.0

#14671 [ Cherry-pick 2.0.0 ]Add build base image step in build package git action workflow
  .github/workflows/build-package.yml
  .gitignore
  Makefile
  make/pushimage.sh
  tests/ci/build_util.sh
  tests/ci/ut_install.sh
  tests/robot-cases/Group1-Nightly/Setup_Nightly.robot
Labels: target/2.0.0

#14670 [ Cherry-pick 2.2.0 ] Add build base image step in build package git action workflow
  .github/workflows/build-package.yml
  .gitignore
  Makefile
  make/pushimage.sh
  tests/ci/ut_install.sh
  tests/robot-cases/Group1-Nightly/Setup_Nightly.robot
Labels: target/2.2.0

#14735 bump up to v1.10.7
  VERSION
Labels: target/1.10.7

#14744 fix registry token issue
  src/core/service/token/creator.go
Labels: target/1.10.7

#14702 Refactor project metadata API
  api/v2.0/legacy_swagger.yaml
  api/v2.0/swagger.yaml
  src/controller/project/metadata/controller.go
  src/core/api/harborapi_test.go
  src/core/api/metadata.go
  src/core/api/metadata_test.go
  src/pkg/project/metadata/dao/dao.go
  src/server/v2.0/handler/handler.go
  src/server/v2.0/handler/project_metadata.go
  src/server/v2.0/route/legacy.go
Labels: target/2.3.0

#14761 Read upstream job ID as ID when it isn't null
  src/pkg/task/hook.go
Labels: target/2.2.2

#14756 Fix the failure of event based chart replication
  src/controller/replication/transfer/chart/transfer.go
Labels: target/2.3.0

#14755 Fix the failure of event based chart replication
  src/replication/transfer/chart/transfer.go
Labels: target/2.2.2

#14762 Read upstream job ID as ID when it isn't null
  src/pkg/task/hook.go
Labels: target/2.3.0

#14662 Refactor the replication policy destination namespace logic
  api/v2.0/swagger.yaml
  make/migrations/postgresql/0060_2.3.0_schema.up.sql
  src/controller/replication/flow/copy.go
  src/controller/replication/flow/deletion.go
  src/controller/replication/flow/stage.go
  src/controller/replication/flow/stage_test.go
  src/controller/replication/model/model.go
  src/controller/replication/policy.go
  src/pkg/replication/model/model.go
  src/server/v2.0/handler/registry.go
  src/server/v2.0/handler/replication.go
Labels: target/2.3.0

#14776 move blob models
  src/common/models/artifact_blob.go
  src/common/models/base.go
  src/common/models/project_blob.go
  src/pkg/blob/models/blob.go
Labels: target/2.3.0

#14772 add storage consumption support
  api/v2.0/swagger.yaml
  src/controller/blob/controller.go
  src/controller/blob/controller_test.go
  src/pkg/blob/dao/dao.go
  src/pkg/blob/dao/dao_test.go
  src/pkg/blob/manager.go
  src/pkg/blob/manager_test.go
  src/server/v2.0/handler/statistic.go
  src/testing/controller/blob/controller.go
  src/testing/pkg/blob/manager.go
Labels: target/2.3.0

#14700 Fix: Move pyyaml to system package
  make/photon/prepare/Dockerfile.base
  make/photon/prepare/Pipfile
  make/photon/prepare/Pipfile.lock
Labels: target/2.2.2
