Repository goharbor/harbor, pull requests merged in 2021-08, with the labels that each got.

#15373 replace jwt model
  src/core/service/token/authutils.go
  src/core/service/token/token_test.go
  src/go.mod
  src/go.sum
  src/pkg/token/claims/robot/robot.go
  src/pkg/token/claims/v2/claims.go
  src/pkg/token/claims/v2/claims_test.go
  src/pkg/token/option_test.go
  src/pkg/token/options.go
  src/pkg/token/token.go
  src/pkg/token/token_test.go
  src/vendor/github.com/golang-jwt/jwt/.gitignore
  src/vendor/github.com/golang-jwt/jwt/.travis.yml
  src/vendor/github.com/golang-jwt/jwt/LICENSE
  src/vendor/github.com/golang-jwt/jwt/MIGRATION_GUIDE.md
  src/vendor/github.com/golang-jwt/jwt/README.md
  src/vendor/github.com/golang-jwt/jwt/VERSION_HISTORY.md
  src/vendor/github.com/golang-jwt/jwt/claims.go
  src/vendor/github.com/golang-jwt/jwt/doc.go
  src/vendor/github.com/golang-jwt/jwt/ecdsa.go
  src/vendor/github.com/golang-jwt/jwt/ecdsa_utils.go
  src/vendor/github.com/golang-jwt/jwt/errors.go
  src/vendor/github.com/golang-jwt/jwt/hmac.go
  src/vendor/github.com/golang-jwt/jwt/map_claims.go
  src/vendor/github.com/golang-jwt/jwt/none.go
  src/vendor/github.com/golang-jwt/jwt/parser.go
  src/vendor/github.com/golang-jwt/jwt/rsa.go
  src/vendor/github.com/golang-jwt/jwt/rsa_pss.go
  src/vendor/github.com/golang-jwt/jwt/rsa_utils.go
  src/vendor/github.com/golang-jwt/jwt/signing_method.go
  src/vendor/github.com/golang-jwt/jwt/token.go
  src/vendor/modules.txt
Labels: target/2.3.2

#15397 Support IPv6 when connecting to LDAP server
  src/pkg/ldap/ldap.go
  src/pkg/ldap/ldap_test.go
Labels: target/2.3.2

#15374 fixes the broken pipe connection error with postgres. Similar as PR: …
  src/common/dao/pgsql.go
Labels: target/2.3.2

#15431 support robot to list project
  src/common/security/robot/context.go
  src/common/security/robot/context_test.go
  src/pkg/project/models/project.go
  src/server/middleware/security/robot.go
  src/server/v2.0/handler/project.go
  src/server/v2.0/handler/repository.go
Labels: area/robot-account, target/2.4.0

#15291 if username is not available in remote, fall back to username from token
  src/pkg/oidc/helper.go
  src/pkg/oidc/helper_test.go
Labels: target/2.3.2

#15443 [CP-v2.3]: if username is not available in remote, fall back to username from token
  src/pkg/oidc/helper.go
  src/pkg/oidc/helper_test.go
Labels: target/2.3.2

#15344 feat(replication) add exclude decoration in policy
  api/v2.0/swagger.yaml
  src/controller/replication/model/model.go
  src/pkg/reg/adapter/aliacr/adapter.go
  src/pkg/reg/adapter/dockerhub/adapter.go
  src/pkg/reg/filter/artifact.go
  src/pkg/reg/filter/resource_test.go
  src/pkg/reg/model/policy.go
  src/pkg/reg/util/pattern_test.go
  src/server/v2.0/handler/replication.go
Labels: area/replication, target/2.4.0

#15368 Support excluding rule for adding a replication rule
  src/portal/src/app/base/left-side-nav/replication/replication.ts
  src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.html
  src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.scss
  src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.ts
  src/portal/src/app/shared/services/interface.ts
Labels: area/ui, target/2.4.0

#15461 enable robot to support create project
  src/controller/robot/model.go
  src/controller/robot/model_test.go
  src/controller/user/controller.go
  src/pkg/user/manager.go
  src/pkg/user/models/user.go
  src/server/v2.0/handler/project.go
  src/testing/controller/user/controller.go
  src/testing/pkg/user/manager.go
Labels: area/robot-account, target/2.4.0

#15509 [Cherry pick]fix: avoid panic in the RetryUntil (#15501)
  src/controller/replication/execution.go
  src/controller/scan/base_controller.go
  src/go.mod
  src/go.sum
  src/jobservice/job/impl/gc/garbage_collection.go
  src/jobservice/job/impl/gc/util.go
  src/lib/cache/cache.go
  src/lib/retry/retry.go
  src/lib/retry/retry_test.go
  src/vendor/github.com/dgrijalva/jwt-go/.gitignore
  src/vendor/github.com/dgrijalva/jwt-go/.travis.yml
  src/vendor/github.com/dgrijalva/jwt-go/LICENSE
  src/vendor/github.com/dgrijalva/jwt-go/MIGRATION_GUIDE.md
  src/vendor/github.com/dgrijalva/jwt-go/README.md
  src/vendor/github.com/dgrijalva/jwt-go/VERSION_HISTORY.md
  src/vendor/github.com/dgrijalva/jwt-go/claims.go
  src/vendor/github.com/dgrijalva/jwt-go/doc.go
  src/vendor/github.com/dgrijalva/jwt-go/ecdsa.go
  src/vendor/github.com/dgrijalva/jwt-go/ecdsa_utils.go
  src/vendor/github.com/dgrijalva/jwt-go/errors.go
  src/vendor/github.com/dgrijalva/jwt-go/hmac.go
  src/vendor/github.com/dgrijalva/jwt-go/map_claims.go
  src/vendor/github.com/dgrijalva/jwt-go/none.go
  src/vendor/github.com/dgrijalva/jwt-go/parser.go
  src/vendor/github.com/dgrijalva/jwt-go/rsa.go
  src/vendor/github.com/dgrijalva/jwt-go/rsa_pss.go
  src/vendor/github.com/dgrijalva/jwt-go/rsa_utils.go
  src/vendor/github.com/dgrijalva/jwt-go/signing_method.go
  src/vendor/github.com/dgrijalva/jwt-go/token.go
  src/vendor/github.com/jpillora/backoff/LICENSE
  src/vendor/github.com/jpillora/backoff/README.md
  src/vendor/github.com/jpillora/backoff/backoff.go
  src/vendor/github.com/jpillora/backoff/go.mod
  src/vendor/modules.txt
Labels: target/2.3.3

#15495 fix gc delete manifest log issue
  src/jobservice/job/impl/gc/garbage_collection.go
  src/jobservice/job/impl/gc/util.go
Labels: area/gc

#15455 Provides full translation for Brazilian Portuguese.
  src/portal/src/i18n/lang/pt-br-lang.json
Labels: help wanted, area/i18n
