Repository goharbor/harbor, pull requests merged in 2021-05, with the labels that each got.

#14788 Support specifying multiple fields for default sorting
  src/common/models/repo.go
  src/lib/orm/metadata.go
  src/lib/orm/metadata_test.go
  src/lib/orm/query.go
  src/pkg/artifact/dao/model.go
  src/pkg/p2p/preheat/models/policy/policy.go
  src/pkg/tag/model/tag/model.go
  src/pkg/task/dao/model.go
Labels: target/2.3.0

#14837 perf: skip db tx for get, head and options api requests
  src/core/middlewares/middlewares.go
Labels: target/2.3.0

#14849 fixes immutable rule issue
  src/pkg/immutable/match/rule/match.go
Labels: target/2.3.0

#14842 [Cherry pick]fix: change art_size to bigint in migrations
  make/migrations/postgresql/0050_2.2.0_schema.up.sql
Labels: target/2.2.2

#14781 Add SAN for internal tls
  make/photon/prepare/scripts/gencert.sh
Labels: area/installation, target/2.1.6

#14724 [Cherrypick to v2.2]: Add attribute admin username for authproxy
  src/common/config/metadata/metadatalist.go
  src/common/const.go
  src/common/models/config.go
  src/core/auth/authproxy/auth.go
  src/core/config/config.go
  src/core/config/config_test.go
  src/pkg/authproxy/http.go
  src/pkg/authproxy/http_test.go
  src/server/middleware/security/auth_proxy.go
  src/server/middleware/security/auth_proxy_test.go
Labels: target/2.2.2

#14852 Fix duplicate execution record issue
  make/migrations/postgresql/0052_2.2.2_schema.up.sql
  src/controller/scan/callback.go
  src/controller/scan/callback_test.go
  src/pkg/retention/callback.go
  src/pkg/scheduler/callback.go
  src/pkg/scheduler/dao.go
  src/pkg/scheduler/mock_dao_test.go
  src/pkg/task/hook.go
  src/pkg/task/hook_test.go
  src/pkg/task/registry.go
Labels: target/2.2.2

#14860 [cherry-pick]Fix duplicate execution record issue
  make/migrations/postgresql/0052_2.2.2_schema.up.sql
  src/controller/scan/callback.go
  src/controller/scan/callback_test.go
  src/pkg/retention/callback.go
  src/pkg/scheduler/callback.go
  src/pkg/scheduler/dao.go
  src/pkg/scheduler/mock_dao_test.go
  src/pkg/task/hook.go
  src/pkg/task/hook_test.go
  src/pkg/task/registry.go
Labels: target/2.3.0

#14858 refactor preheat model
  src/pkg/p2p/preheat/models/notification/notification.go
  src/pkg/p2p/preheat/provider/kraken.go
  src/pkg/p2p/preheat/provider/mock.go
Labels: target/2.3.0

#14797 chore(trivy): Bump up Trivy scanner adapter to v0.19.0
  Makefile
Labels: area/interrogation-service, scanner/trivy

#14875 fix: using new ctx to scan artifact when scanAll
  src/controller/scan/base_controller.go
  src/controller/scan/base_controller_test.go
Labels: target/2.3.0

#14504 Add grafana example for metrics
  contrib/grafana-dashborad/metrics-example.json
Labels: doc-impact

#14879 perf: cache the metadata of the scanner
  src/controller/scanner/base_controller.go
  src/lib/cache/cache.go
  src/lib/cache/memory/memory.go
  src/lib/cache/redis/redis.go
  src/pkg/scan/rest/v1/client.go
  src/pkg/scan/rest/v1/models.go
Labels: area/performance, target/2.3.0

#14867 Check permission for user group api
  src/core/api/usergroup.go
Labels: target/2.2.2

#14884 [Cherry pick]fix: using new ctx to scan artifact when scanAll
  src/controller/scan/base_controller.go
  src/controller/scan/base_controller_test.go
Labels: target/2.2.2

#14883 [Cherry pick]perf: cache the metadata of the scanner
  src/controller/scanner/base_controller.go
  src/lib/cache/cache.go
  src/lib/cache/memory/memory.go
  src/lib/cache/redis/redis.go
  src/pkg/scan/rest/v1/client.go
  src/pkg/scan/rest/v1/models.go
Labels: target/2.2.2

#14885 bump up base to v2.2.2
  VERSION
Labels: target/2.2.2

#14895 fix: disable x-omitempty for repo_count and chart_count
  api/v2.0/swagger.yaml
Labels: target/2.3.0

#14887 bump up go to v1.15.12
  .github/workflows/CI.yml
  .github/workflows/build-package.yml
  .github/workflows/conformance_test.yml
  CONTRIBUTING.md
  Makefile
  make/photon/chartserver/builder
  make/photon/notary/binary.Dockerfile
  make/photon/registry/Dockerfile.binary
  make/photon/trivy-adapter/Dockerfile.binary
  make/photon/trivy-adapter/builder.sh
  src/go.mod
  tests/ci/distro_installer.sh
Labels: target/2.3.0

#14871 Fix replication filter bug in branch 2.1
  src/replication/event/handler.go
  src/replication/event/handler_test.go
  src/replication/filter/resource.go
  src/replication/operation/flow/copy.go
  src/replication/operation/flow/deletion.go
  src/replication/operation/flow/stage.go
  src/replication/operation/flow/stage_test.go
Labels: target/2.1.6

#14825 Fix tencentcr adapter.
  src/go.mod
  src/go.sum
  src/replication/adapter/tencentcr/adapter.go
  src/replication/adapter/tencentcr/artifact_registry.go
  src/replication/adapter/tencentcr/ratelimiter.go
  src/replication/adapter/tencentcr/ratelimiter_test.go
  src/replication/adapter/tencentcr/sdk.go
  src/vendor/github.com/andres-erbsen/clock/.travis.yml
  src/vendor/github.com/andres-erbsen/clock/LICENSE
  src/vendor/github.com/andres-erbsen/clock/README.md
  src/vendor/github.com/andres-erbsen/clock/clock.go
  src/vendor/go.uber.org/ratelimit/.gitignore
  src/vendor/go.uber.org/ratelimit/CHANGELOG.md
  src/vendor/go.uber.org/ratelimit/LICENSE
  src/vendor/go.uber.org/ratelimit/Makefile
  src/vendor/go.uber.org/ratelimit/README.md
  src/vendor/go.uber.org/ratelimit/go.mod
  src/vendor/go.uber.org/ratelimit/go.sum
  src/vendor/go.uber.org/ratelimit/limiter_atomic.go
  src/vendor/go.uber.org/ratelimit/limiter_mutexbased.go
  src/vendor/go.uber.org/ratelimit/ratelimit.go
  src/vendor/modules.txt
Labels: target/2.1.6

#14906 Provide detailed output about missing RBAC permissions in debug mode.
  src/pkg/permission/evaluator/rbac/casbin.go
Labels: target/2.3.0

#14836 refactor: remove allowlist in GetSummary of scan controller
  src/controller/p2p/preheat/enforcer.go
  src/controller/p2p/preheat/enforcer_test.go
  src/controller/scan/base_controller.go
  src/controller/scan/controller.go
  src/pkg/scan/report/report.go
  src/pkg/scan/report/summary.go
  src/pkg/scan/report/summary_test.go
  src/pkg/scan/vuln/report.go
  src/pkg/scan/vuln/report_test.go
  src/pkg/scan/vuln/summary.go
  src/pkg/scan/vuln/summary_test.go
  src/pkg/scan/vuln/util.go
  src/pkg/scan/vuln/util_test.go
  src/server/middleware/vulnerable/vulnerable.go
  src/server/middleware/vulnerable/vulnerable_test.go
  src/server/v2.0/handler/artifact.go
  src/testing/controller/scan/controller.go
Labels: target/2.3.0

#14910 Check user in security context before getting the ID
  .github/workflows/CI.yml
  src/controller/user/controller.go
Labels: target/2.3.0

#14916 ci: lint the swagger file
  .dockerignore
  .spectral.yaml
  Makefile
  api/v2.0/swagger.yaml
  src/portal/src/app/base/left-side-nav/gc-page/gc/gc.component.ts
  src/portal/src/app/base/left-side-nav/replication/replication/replication-tasks/replication-tasks.component.ts
  src/portal/src/app/services/routing-resolvers/replication-tasks-routing-resolver.service.ts
  src/portal/src/app/shared/components/label/create-edit-label/create-edit-label.component.ts
  src/portal/src/app/shared/components/label/label.component.ts
  tools/spectral/Dockerfile
  tools/spectral/functions/requireRequestId.js
Labels: target/2.3.0

#14900 Remove GetUser and Onboard from common/dao
  src/common/dao/dao_test.go
  src/common/dao/testutils.go
  src/common/dao/user.go
  src/common/dao/user_test.go
  src/common/utils/test/database.go
  src/core/auth/authenticator.go
  src/core/auth/authproxy/auth.go
  src/core/auth/authproxy/auth_test.go
  src/core/auth/db/db.go
  src/core/auth/db/db_test.go
  src/core/auth/ldap/ldap.go
  src/core/auth/ldap/ldap_test.go
  src/core/auth/uaa/uaa.go
  src/core/auth/uaa/uaa_test.go
  src/core/main.go
  src/pkg/user/manager.go
  src/pkg/user/manager_test.go
  src/server/middleware/security/auth_proxy.go
  src/server/middleware/security/auth_proxy_test.go
  src/testing/pkg/user/manager.go
Labels: kind/refactor, target/2.3.0

#14914 Update the field name of registry model
  src/pkg/reg/dao/dao_test.go
  src/pkg/reg/dao/model.go
  src/pkg/reg/manager.go
Labels: target/2.3.0

#14912 Truncate the string when deletinng the resources when the length exceeds the limit
  api/v2.0/swagger.yaml
  src/lib/truncate.go
  src/lib/truncate_test.go
  src/pkg/project/dao/dao.go
  src/pkg/user/manager.go
Labels: target/2.3.0

#14921 Clean up tech debt codes
  src/common/dao/dao_test.go
  src/common/dao/pro_meta.go
  src/common/dao/pro_meta_test.go
  src/common/dao/repository.go
  src/common/dao/repository_test.go
  src/common/dao/version.go
  src/common/dao/version_test.go
  src/common/models/base.go
  src/common/models/pro_meta.go
  src/common/models/version.go
  src/controller/artifact/controller_test.go
  src/controller/repository/controller.go
  src/controller/repository/controller_test.go
  src/controller/retention/controller_test.go
  src/controller/tag/controller_test.go
  src/pkg/exporter/project_collector_test.go
  src/pkg/project/metadata/models/metadata.go
  src/pkg/reg/adapter/harbor/v1/client.go
  src/pkg/reg/adapter/harbor/v2/client.go
  src/pkg/repository/dao/dao.go
  src/pkg/repository/dao/dao_test.go
  src/pkg/repository/manager.go
  src/pkg/repository/manager_test.go
  src/pkg/repository/model/model.go
  src/pkg/retention/launcher_test.go
  src/server/middleware/immutable/pushmf_test.go
  src/server/registry/catalog_test.go
  src/server/registry/manifest_test.go
  src/server/registry/tag_test.go
  src/server/v2.0/handler/model/repository.go
  src/server/v2.0/handler/repository.go
  src/testing/controller/controller.go
  src/testing/controller/repository/controller.go
  src/testing/pkg/pkg.go
  src/testing/pkg/project/metadata/manager.go
  src/testing/pkg/repository/dao/dao.go
  src/testing/pkg/repository/manager.go
Labels: target/2.3.0

#14828 Fix tencentcr adapter.
  src/go.mod
  src/go.sum
  src/replication/adapter/tencentcr/adapter.go
  src/replication/adapter/tencentcr/artifact_registry.go
  src/replication/adapter/tencentcr/ratelimiter.go
  src/replication/adapter/tencentcr/ratelimiter_test.go
  src/replication/adapter/tencentcr/sdk.go
  src/vendor/github.com/andres-erbsen/clock/.travis.yml
  src/vendor/github.com/andres-erbsen/clock/LICENSE
  src/vendor/github.com/andres-erbsen/clock/README.md
  src/vendor/github.com/andres-erbsen/clock/clock.go
  src/vendor/go.uber.org/ratelimit/.gitignore
  src/vendor/go.uber.org/ratelimit/CHANGELOG.md
  src/vendor/go.uber.org/ratelimit/LICENSE
  src/vendor/go.uber.org/ratelimit/Makefile
  src/vendor/go.uber.org/ratelimit/README.md
  src/vendor/go.uber.org/ratelimit/go.mod
  src/vendor/go.uber.org/ratelimit/go.sum
  src/vendor/go.uber.org/ratelimit/limiter_atomic.go
  src/vendor/go.uber.org/ratelimit/limiter_mutexbased.go
  src/vendor/go.uber.org/ratelimit/ratelimit.go
  src/vendor/modules.txt
Labels: target/2.2.3

#14923 Fail with 401 for GET .../users/current/permissions
  src/server/v2.0/handler/user.go
Labels: target/2.3.0

#14911 Use system configuration resource for permission checking
  src/common/rbac/const.go
  src/common/rbac/system/policies.go
  src/server/v2.0/handler/oidc.go
  src/server/v2.0/handler/sys_cve_allowlist.go
Labels: target/2.3.0

#14925 Improve the performance of artifact related APIs
  make/migrations/postgresql/0060_2.3.0_schema.up.sql
  src/pkg/artifact/dao/dao.go
Labels: target/2.3.0

#14820 fix: change sql to improve the performance of catalog api
  src/pkg/repository/dao/dao.go
Labels: area/performance, target/2.3.0

#14846 support pg upgrade
  Makefile
  make/photon/db/Dockerfile
  make/photon/db/Dockerfile.base
  make/photon/db/docker-entrypoint.sh
  make/photon/db/initdb.sh
  make/photon/db/postgres.spec
  make/photon/db/rpm_builder.sh
  make/photon/db/upgrade.sh
Labels: target/2.3.0

#14926 Remove the onboard and update funcs for OIDC user from common/dao
  src/common/dao/oidc_user.go
  src/common/dao/oidc_user_test.go
  src/controller/user/controller.go
  src/core/controllers/oidc.go
  src/pkg/oidc/metamanager.go
  src/testing/controller/user/controller.go
  src/testing/pkg/oidc/dao/meta_dao.go
  src/testing/pkg/oidc/meta_manager.go
  src/testing/pkg/pkg.go
Labels: target/2.3.0

#14934 pg upgrade failure handling
  make/photon/db/docker-entrypoint.sh
Labels: target/2.3.0

#14951 fix: delete robots by project id using raw sql
  src/pkg/robot/dao/dao.go
Labels: target/2.3.0

#14827 Fix tencentcr adapter.
  src/go.mod
  src/go.sum
  src/pkg/reg/adapter/tencentcr/adapter.go
  src/pkg/reg/adapter/tencentcr/adapter_test.go
  src/pkg/reg/adapter/tencentcr/artifact_registry.go
  src/pkg/reg/adapter/tencentcr/ratelimiter.go
  src/pkg/reg/adapter/tencentcr/ratelimiter_test.go
  src/pkg/reg/adapter/tencentcr/sdk.go
  src/vendor/github.com/andres-erbsen/clock/.travis.yml
  src/vendor/github.com/andres-erbsen/clock/LICENSE
  src/vendor/github.com/andres-erbsen/clock/README.md
  src/vendor/github.com/andres-erbsen/clock/clock.go
  src/vendor/go.uber.org/ratelimit/.gitignore
  src/vendor/go.uber.org/ratelimit/CHANGELOG.md
  src/vendor/go.uber.org/ratelimit/LICENSE
  src/vendor/go.uber.org/ratelimit/Makefile
  src/vendor/go.uber.org/ratelimit/README.md
  src/vendor/go.uber.org/ratelimit/go.mod
  src/vendor/go.uber.org/ratelimit/go.sum
  src/vendor/go.uber.org/ratelimit/limiter_atomic.go
  src/vendor/go.uber.org/ratelimit/limiter_mutexbased.go
  src/vendor/go.uber.org/ratelimit/ratelimit.go
  src/vendor/modules.txt
Labels: target/2.3.0

#14941 Set null list when or list is nil in query
  src/lib/orm/query.go
Labels: target/2.3.0

#14918 fix nil map assignment in gc handler
  src/server/v2.0/handler/gc.go
Labels: target/2.3.0

#14985 Fix bug of migration sql for replication policy
  make/migrations/postgresql/0060_2.3.0_schema.up.sql
Labels: target/2.3.0

#14949 Fall back to local registry when upstream registry is not working
  src/server/middleware/repoproxy/proxy.go
Labels: target/2.3.0

#15011 Add merge slash middleware
  src/core/middlewares/middlewares.go
  src/server/middleware/mergeslash/mergeslash.go
  src/server/middleware/mergeslash/mergeslash_test.go
Labels: target/2.3.0

#15010 Make v2auth more strict
  src/server/middleware/v2auth/auth.go
  src/server/middleware/v2auth/auth_test.go
Labels: target/2.3.0

#15005 Declare the capability of supported repository path component for registries
  src/controller/replication/flow/copy.go
  src/controller/replication/flow/deletion.go
  src/controller/replication/flow/deletion_test.go
  src/controller/replication/flow/stage.go
  src/controller/replication/flow/stage_test.go
  src/pkg/reg/adapter/dockerhub/adapter.go
  src/pkg/reg/adapter/dockerhub/adapter_test.go
  src/pkg/reg/adapter/harbor/base/adapter.go
  src/pkg/reg/adapter/harbor/base/adapter_test.go
  src/pkg/reg/model/registry.go
Labels: target/2.3.0

#15014 refactor: convert scan report in scan job
  src/controller/scan/base_controller.go
  src/controller/scan/base_controller_test.go
  src/controller/scan/callback.go
  src/controller/scan/callback_test.go
  src/controller/scan/controller.go
  src/lib/set.go
  src/lib/set_test.go
  src/pkg/scan/dao/scan/model.go
  src/pkg/scan/dao/scan/vulnerability.go
  src/pkg/scan/dao/scan/vulnerability_test.go
  src/pkg/scan/job.go
  src/pkg/scan/job_test.go
  src/pkg/scan/postprocessors/report_converters.go
  src/pkg/scan/report/manager.go
  src/pkg/scan/vuln/report.go
  src/testing/controller/scan/controller.go
Labels: area/vulnerability-scan, target/2.3.0

#15015 Fix ui issues found in testing day
  src/portal/src/app/base/account-settings/account-settings-modal.component.html
  src/portal/src/app/base/account-settings/account-settings-modal.component.scss
  src/portal/src/app/base/left-side-nav/config/auth/config-auth.component.html
  src/portal/src/app/base/left-side-nav/config/email/config-email.component.html
  src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.html
  src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.scss
  src/portal/src/app/base/project/project-config/project-policy-config/project-policy-config.component.ts
  src/portal/src/app/base/project/project-detail/project-detail.component.ts
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
  src/portal/src/app/base/project/repository/repository-gridview.component.ts
  src/portal/src/app/services/event-service/event.service.ts
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: target/2.3.0

#14740 [ 1.10 ] Fix OIDC tests issue for new dex service
  tests/apitests/python/library/docker_api.py
  tests/apitests/python/library/user.py
  tests/apitests/python/test_project_quota.py
  tests/apitests/python/testutils.py
  tests/resources/Admiral-Util.robot
  tests/resources/Drone-Util.robot
  tests/resources/Github-Util.robot
  tests/resources/Harbor-Pages/Configuration.robot
  tests/resources/Harbor-Pages/OIDC_Auth.robot
  tests/resources/Harbor-Pages/OIDC_Auth_Elements.robot
  tests/resources/Nimbus-Util.robot
  tests/resources/OVA-Util.robot
  tests/resources/Util.robot
  tests/resources/VCH-Util.robot
  tests/resources/Vsphere-Util.robot
  tests/robot-cases/Group0-BAT/BAT.robot
  tests/robot-cases/Group1-Nightly/Chartmuseum.robot
  tests/robot-cases/Group1-Nightly/Clair.robot
  tests/robot-cases/Group1-Nightly/Common.robot
  tests/robot-cases/Group1-Nightly/Common_GC.robot
  tests/robot-cases/Group1-Nightly/DB.robot
  tests/robot-cases/Group1-Nightly/Nightly.robot
  tests/robot-cases/Group1-Nightly/Notary.robot
  tests/robot-cases/Group1-Nightly/OIDC.robot
  tests/robot-cases/Group1-Nightly/Replication.robot
  tests/robot-cases/Group1-Nightly/Upgrade.robot
  tests/robot-cases/Group2-Longevity/Longevity.robot
  tests/robot-cases/Group3-Upgrade/prepare.py
  tests/robot-cases/Group3-Upgrade/prepare_v17.py
Labels: target/1.10.0
