Repository goharbor/harbor, pull requests merged in 2021-07, with the labels that each got.

#15235 add retry for blob & manifest deletion in GC
  src/jobservice/job/impl/gc/garbage_collection.go
  src/jobservice/job/impl/gc/util.go
Labels: area/gc

#15248 bump up version to v2.2.3
  VERSION
Labels: target/2.2.3

#15249 fix(p2p): fix p2p create policy permission
  src/server/v2.0/handler/preheat.go
Labels: area/P2P-Distribution, target/2.1.6

#15243 fix(p2p): fix p2p create policy permission
  src/server/v2.0/handler/preheat.go
Labels: area/P2P-Distribution, target/2.2.3

#15244 fix(p2p): fix p2p create policy permission
  src/server/v2.0/handler/preheat.go
Labels: area/P2P-Distribution, target/2.3.1

#15238 fix(p2p): fix p2p create policy permission
  src/server/v2.0/handler/preheat.go
Labels: area/P2P-Distribution

#15286 bump up go version to 1.16
  .github/workflows/CI.yml
  .github/workflows/build-package.yml
  .github/workflows/conformance_test.yml
  CONTRIBUTING.md
  Makefile
  make/photon/chartserver/builder
  make/photon/registry/Dockerfile.binary
  make/photon/trivy-adapter/Dockerfile.binary
  make/photon/trivy-adapter/builder.sh
  src/go.mod
  tests/ci/distro_installer.sh
  tests/ci/ut_run.sh
  tools/mockery/Dockerfile
Labels: target/2.4.0

#15280 fix(p2p): adjust task time format
  src/server/v2.0/handler/preheat.go
  src/server/v2.0/handler/preheat_test.go
Labels: area/P2P-Distribution

#15281 [cherry-pick] fix(p2p): adjust task time format
  src/server/v2.0/handler/preheat.go
  src/server/v2.0/handler/preheat_test.go
Labels: area/P2P-Distribution, target/2.3.1

#15296 deprecate version 1 robot account
  src/server/middleware/security/robot.go
  src/server/middleware/security/robot2.go
  src/server/middleware/security/robot2_test.go
  src/server/middleware/security/robot_test.go
  src/server/middleware/security/security.go
Labels: area/robot-account, target/2.4.0

#14857 [ V2.0.0 ] Adapt OIDC sevice change of more login provider
  tests/apitests/python/library/user.py
  tests/resources/Docker-Util.robot
  tests/resources/Drone-Util.robot
  tests/resources/Github-Util.robot
  tests/resources/Harbor-Pages/Configuration.robot
  tests/resources/Harbor-Pages/OIDC_Auth.robot
  tests/resources/Harbor-Pages/OIDC_Auth_Elements.robot
  tests/resources/Nimbus-Util.robot
  tests/resources/OVA-Util.robot
  tests/resources/Util.robot
  tests/resources/VCH-Util.robot
  tests/resources/Vsphere-Util.robot
  tests/robot-cases/Group0-BAT/BAT.robot
  tests/robot-cases/Group1-Nightly/Chartmuseum.robot
  tests/robot-cases/Group1-Nightly/Clair.robot
  tests/robot-cases/Group1-Nightly/Common.robot
  tests/robot-cases/Group1-Nightly/Common_GC.robot
  tests/robot-cases/Group1-Nightly/DB.robot
  tests/robot-cases/Group1-Nightly/Nightly.robot
  tests/robot-cases/Group1-Nightly/Notary.robot
  tests/robot-cases/Group1-Nightly/Schedule.robot
  tests/robot-cases/Group1-Nightly/Trivy.robot
  tests/robot-cases/Group1-Nightly/Upgrade.robot
  tests/robot-cases/Group1-Nightly/multi_scanners.robot
  tests/robot-cases/Group2-Longevity/Longevity.robot
  tests/robot-cases/Group3-Upgrade/prepare.py
Labels: target/2.0.6

#15242 Fix refreshing oidc access token breaks users subiss in database
  src/pkg/oidc/dao/meta.go
  src/pkg/oidc/dao/meta_test.go
Labels: needs/crossport

#15303 Remediate the empty subiss problem
  src/core/main.go
  src/pkg/oidc/fix.go
  src/pkg/oidc/fix_test.go
  src/pkg/oidc/secret.go
Labels: needs/crossport

#15324 [cherry pick]add retry for blob & manifest deletion in GC
  src/jobservice/job/impl/gc/garbage_collection.go
  src/jobservice/job/impl/gc/util.go
Labels: target/2.3.1

#15329 [CP-v2.3]:Remediate the empty subiss problem
  src/core/main.go
  src/pkg/oidc/dao/meta.go
  src/pkg/oidc/fix.go
  src/pkg/oidc/fix_test.go
  src/pkg/oidc/secret.go
  src/testing/pkg/oidc/dao/meta_dao.go
Labels: target/2.3.1

#15330 [CP - v2.3]subiss needs to be part of selected fields, otherwise this attribute …
  src/pkg/oidc/dao/meta.go
  src/pkg/oidc/dao/meta_test.go
Labels: target/2.3.1
