Repository goharbor/harbor, pull requests merged in 2021-01, with the labels that each got.

#13840 enable visible when to list/create robot
  src/common/security/robot/context.go
  src/common/security/robot/context_test.go
  src/controller/robot/controller.go
  src/controller/robot/controller_test.go
  src/controller/robot/model.go
  src/controller/robot/model_test.go
  src/controller/scan/base_controller.go
  src/controller/scan/base_controller_test.go
  src/pkg/robot/dao/dao.go
  src/pkg/robot/dao/dao_test.go
  src/pkg/robot/manager.go
  src/pkg/robot/manager_test.go
  src/pkg/robot/model/model.go
  src/pkg/scan/job.go
  src/pkg/scan/job_test.go
  src/server/middleware/security/robot2.go
  src/server/v2.0/handler/project.go
  src/server/v2.0/handler/robot.go
  src/server/v2.0/handler/robotV1.go
  src/testing/pkg/pkg.go
  src/testing/pkg/robot/dao/dao.go
  src/testing/pkg/robot/manager.go
Labels: target/2.2.0

#13872 Refine the token scope generation
  src/common/security/v2token/context.go
  src/core/service/token/authutils.go
  src/core/service/token/creator.go
  src/core/service/token/token_test.go
Labels: target/2.2.0

#13828 (cherry-pick) Add content type and length in header
  src/controller/proxy/controller.go
  src/controller/proxy/controller_test.go
  src/controller/proxy/local.go
  src/controller/proxy/remote.go
  src/controller/replication/flow/mock_adapter_test.go
  src/pkg/registry/client.go
  src/pkg/registry/client_test.go
  src/replication/adapter/adapter.go
  src/replication/adapter/huawei/image_registry.go
  src/replication/adapter/huawei/image_registry_test.go
  src/replication/operation/flow/stage_test.go
  src/replication/transfer/image/transfer.go
  src/replication/transfer/image/transfer_test.go
  src/server/middleware/repoproxy/proxy.go
  src/testing/controller/controller.go
  src/testing/controller/proxy/remote_interface.go
  src/testing/pkg/registry/client.go
Labels: target/2.1.3

#13893 bump version to v2.1.3
  VERSION
Labels: target/2.1.3

#13853 feat(retention) refactor task manager
  make/migrations/postgresql/0050_2.2.0_schema.up.sql
  src/core/api/base.go
  src/core/api/retention.go
  src/core/service/notifications/jobs/handler.go
  src/pkg/retention/callback.go
  src/pkg/retention/controller.go
  src/pkg/retention/controller_test.go
  src/pkg/retention/faked_controller.go
  src/pkg/retention/launcher.go
  src/pkg/retention/launcher_test.go
  src/pkg/retention/manager.go
  src/pkg/retention/manager_test.go
  src/pkg/retention/mocks/api_controller.go
  src/pkg/task/model.go
  src/server/route.go
Labels: area/tag-retention, target/2.2.0

#13903 Remove scanner-pull from system admin's permission -- Cherrypick-2.1 branch
  src/common/security/local/context_test.go
  src/pkg/permission/evaluator/admin/admin.go
Labels: target/2.1.3

#13805 Add content type and length in header
  src/controller/proxy/controller.go
  src/controller/proxy/controller_test.go
  src/controller/proxy/local.go
  src/controller/proxy/local_test.go
  src/controller/proxy/manifestcache.go
  src/controller/proxy/manifestcache_test.go
  src/controller/proxy/remote.go
  src/controller/replication/flow/mock_adapter_test.go
  src/pkg/registry/client.go
  src/pkg/registry/client_test.go
  src/replication/adapter/adapter.go
  src/replication/adapter/huawei/image_registry.go
  src/replication/adapter/huawei/image_registry_test.go
  src/replication/transfer/image/transfer.go
  src/replication/transfer/image/transfer_test.go
  src/server/middleware/repoproxy/proxy.go
  src/testing/controller/controller.go
  src/testing/controller/proxy/remote_interface.go
  src/testing/pkg/registry/client.go
Labels: target/2.2.0

#13904 Remove scanner-pull from system admin's permission - cherrypick to 2.0 branch
  src/common/security/local/context_test.go
  src/pkg/permission/evaluator/admin/admin.go
Labels: target/2.0.6

#13899 test: fix the data race in the test of scan controller
  src/controller/scan/callback.go
  src/controller/scan/callback_test.go
Labels: target/2.2.0

#13898 feat: return scan report and summary by header
  api/v2.0/swagger.yaml
  src/server/v2.0/handler/artifact.go
  src/server/v2.0/handler/artifact_test.go
  src/server/v2.0/handler/assembler/vul.go
  src/server/v2.0/handler/assembler/vul_test.go
  src/server/v2.0/handler/base.go
  src/server/v2.0/handler/base_test.go
  src/server/v2.0/handler/util.go
  src/testing/server/v2.0/handler/handler.go
Labels: target/2.2.0

#13874 Refine the token scope generation - cherrypick to 2.0
  src/common/security/v2token/context.go
  src/core/service/token/authutils.go
  src/core/service/token/creator.go
  src/core/service/token/token_test.go
Labels: target/2.0.6

#13909 Provide a mechanism to sweep the execution/task records in task manager
  src/controller/scan/base_controller.go
  src/pkg/task/execution.go
  src/pkg/task/execution_test.go
Labels: target/2.2.0

#13896 Fix replication filter bug
  src/controller/replication/flow/copy.go
  src/controller/replication/flow/deletion.go
  src/controller/replication/flow/stage.go
  src/controller/replication/flow/stage_test.go
  src/replication/event/handler.go
  src/replication/event/handler_test.go
  src/replication/filter/resource.go
Labels: target/2.2.0

#13826 add system resource
  src/common/rbac/const.go
  src/common/rbac/system/evaluator.go
  src/common/rbac/system/namespace.go
  src/common/rbac/system/policies.go
  src/common/rbac/system/rbac_user.go
  src/common/security/robot/context.go
  src/controller/robot/model.go
  src/core/api/label.go
  src/core/api/notification_job.go
  src/core/api/quota.go
  src/core/api/registry.go
  src/core/api/replication_adapter.go
  src/core/api/replication_policy.go
  src/core/api/retention.go
  src/core/api/scanners.go
  src/core/api/user.go
  src/core/api/user_test.go
  src/core/api/usergroup.go
  src/server/middleware/v2auth/auth.go
  src/server/v2.0/handler/auditlog.go
  src/server/v2.0/handler/base.go
  src/server/v2.0/handler/gc.go
  src/server/v2.0/handler/preheat.go
  src/server/v2.0/handler/project.go
  src/server/v2.0/handler/replication.go
  src/server/v2.0/handler/robot.go
  src/server/v2.0/handler/scan_all.go
  src/server/v2.0/handler/scan_all_test.go
  src/server/v2.0/handler/systeminfo.go
Labels: area/robot-account, target/2.2.0

#13931 feat: save summary for the scan all execution
  src/controller/scan/base_controller.go
  src/controller/scan/base_controller_test.go
  src/controller/scan/callback_test.go
  src/pkg/task/execution.go
  src/pkg/task/execution_test.go
  src/testing/pkg/task/execution_manager.go
Labels: target/2.2.0, target/FC

#13910 Support artifact hub replication using new API
  src/replication/adapter/adapter.go
  src/replication/adapter/artifacthub/adapter_test.go
  src/replication/adapter/artifacthub/chart_registry.go
  src/replication/adapter/artifacthub/client.go
  src/replication/adapter/artifacthub/consts.go
  src/replication/adapter/artifacthub/model.go
  src/replication/adapter/harbor/base/chart_registry.go
  src/replication/adapter/harbor/base/chart_registry_test.go
  src/replication/adapter/helmhub/chart_registry.go
  src/replication/adapter/tencentcr/chart_registry.go
  src/replication/transfer/chart/transfer.go
  src/replication/transfer/chart/transfer_test.go
Labels: target/2.2.0, target/FC

#13918 feat: remove duplicate CVE in scan report and summary
  api/v2.0/swagger.yaml
  src/common/models/cve_allowlist.go
  src/pkg/scan/postprocessors/report_converters.go
  src/pkg/scan/report/summary.go
  src/pkg/scan/vuln/report.go
  src/pkg/scan/vuln/report_test.go
  src/pkg/scan/vuln/summary.go
  src/pkg/scan/vuln/summary_test.go
Labels: target/2.2.0, target/FC

#13554 reform job status compare method
  src/jobservice/job/status.go
  src/jobservice/period/basic_scheduler.go
  src/jobservice/worker/cworker/c_worker.go
  src/jobservice/worker/cworker/reaper.go
  src/pkg/scan/vuln/util.go
Labels: area/job-services, target/2.2.0

#13781 Add py test for system robot account
  tests/apitests/python/library/artifact.py
  tests/apitests/python/library/base.py
  tests/apitests/python/library/chart.py
  tests/apitests/python/library/helm.py
  tests/apitests/python/library/label.py
  tests/apitests/python/library/repository.py
  tests/apitests/python/library/robot.py
  tests/apitests/python/test_robot_account.py
  tests/apitests/python/testutils.py
  tests/resources/Harbor-Pages/Robot_Account.robot
  tests/robot-cases/Group1-Nightly/Common.robot
Labels: target/2.2.0

#13935 chore: delete records of scan_report
  make/migrations/postgresql/0050_2.2.0_schema.up.sql
Labels: target/2.2.0, target/FC

#13930 Refactor retention beego api to go-swagger
  api/v2.0/legacy_swagger.yaml
  api/v2.0/swagger.yaml
  src/common/dao/testutils.go
  src/controller/event/handler/init.go
  src/controller/event/handler/webhook/artifact/retention.go
  src/controller/event/handler/webhook/artifact/retention_test.go
  src/controller/retention/callback.go
  src/controller/retention/controller.go
  src/controller/retention/controller_test.go
  src/core/api/base.go
  src/core/api/harborapi_test.go
  src/core/api/retention.go
  src/core/api/retention_test.go
  src/pkg/retention/faked_controller.go
  src/pkg/retention/launcher.go
  src/pkg/retention/launcher_test.go
  src/pkg/retention/mocks/api_controller.go
  src/server/v2.0/handler/handler.go
  src/server/v2.0/handler/model/retention.go
  src/server/v2.0/handler/project.go
  src/server/v2.0/handler/retention.go
  src/server/v2.0/route/legacy.go
  src/testing/controller/controller.go
  src/testing/controller/retention/controller.go
  tests/robot-cases/Group0-BAT/API_DB.robot
Labels: target/2.2.0, target/FC

#13945 Check the stop error during the replication process
  src/replication/transfer/chart/transfer.go
  src/replication/transfer/image/transfer.go
Labels: target/2.2.0

#13938 update go version to 1.14.13
  .github/workflows/CI.yml
  .github/workflows/build-package.yml
  .github/workflows/conformance_test.yml
  CONTRIBUTING.md
  Makefile
  make/photon/Makefile
  make/photon/chartserver/builder
  make/photon/clair-adapter/Dockerfile.binary
  make/photon/clair-adapter/builder.sh
  make/photon/clair/Dockerfile.binary
  make/photon/clair/builder
  make/photon/notary/binary.Dockerfile
  make/photon/registry/Dockerfile.binary
  make/photon/trivy-adapter/Dockerfile.binary
  make/photon/trivy-adapter/builder.sh
  tests/ci/api_common_install.sh
  tests/ci/distro_installer.sh
  tools/swagger/Dockerfile
Labels: target/2.1.3

#13943 Update the reg-exp to match v2/catalog api -- Cherry pick to 2.1
  src/lib/patterns.go
  src/lib/patterns_test.go
  src/server/middleware/v2auth/access.go
  src/server/middleware/v2auth/auth.go
Labels: target/2.1.3

#13941 Update the reg-exp to match v2/catalog api
  src/lib/patterns.go
  src/lib/patterns_test.go
  src/server/middleware/v2auth/access.go
  src/server/middleware/v2auth/auth.go
Labels: target/2.2.0

#13944 fix robot cannot update expiresat
  src/controller/robot/controller.go
  src/controller/robot/controller_test.go
Labels: target/2.2.0

#13924 refractor project rbac
  src/common/rbac/project/evaluator.go
  src/common/rbac/project/evaluator_test.go
  src/common/rbac/project/namespace.go
  src/common/rbac/project/rbac_role.go
  src/common/rbac/project/rbac_user.go
  src/common/rbac/project/rbac_util.go
  src/common/rbac/project_rbac_role.go
  src/common/security/local/context.go
  src/common/security/local/context_test.go
  src/common/security/proxycachesecret/context.go
  src/common/security/proxycachesecret/context_test.go
  src/common/security/robot/context.go
  src/common/security/robot/context_test.go
  src/common/security/v2token/context.go
  src/common/security/v2token/context_test.go
  src/controller/robot/controller.go
  src/core/api/base.go
  src/core/service/token/creator.go
  src/core/service/token/token_test.go
  src/server/middleware/util/util.go
  src/server/middleware/v2auth/auth.go
  src/server/v2.0/handler/base.go
  src/server/v2.0/handler/robotV1.go
Labels: target/2.2.0

#13939 Add san for notary cert - cherrypick 1.10
  make/photon/prepare/utils/cert.py
  make/photon/prepare/utils/notary.py
Labels: target/1.10.7

#13914 Bump up the go-migrate
  Makefile
  make/photon/notary/binary.Dockerfile
Labels: target/2.2.0

#13871 Refine the token scope generation -- cherrypick to 1.10
  src/core/service/token/authutils.go
  src/core/service/token/creator.go
  src/core/service/token/token_test.go
  src/pkg/scan/api/scan/base_controller.go
  src/pkg/scan/api/scan/base_controller_test.go
Labels: target/1.10.7

#13966 do not add prefix for the legacy robots
  src/controller/robot/controller.go
Labels: target/2.2.0

#13967 fix(retention) retained/total empty when 0
  api/v2.0/swagger.yaml
Labels: area/tag-retention

#13998 fix(retention) execution status for zero repo
  src/controller/retention/controller.go
  src/controller/retention/controller_test.go
Labels: target/2.2.0

#13989 fix robot issues
  src/server/middleware/security/robot2.go
  src/server/v2.0/handler/robot.go
  src/server/v2.0/handler/robot_test.go
Labels: area/robot-account, target/2.2.0

#14009 Remove raw token from header in token review reuqest - 1.10.x
  src/pkg/authproxy/http.go
Labels: target/1.10.7

#14011 Remove raw token from header in token review reuqest
  src/pkg/authproxy/http.go
Labels: target/2.2.0

#14010 Remove raw token from header in token review reuqest - 2.1.x
  src/pkg/authproxy/http.go
Labels: target/2.1.4

#14003 fix: correct completed in the metrics of the scan all
  src/server/v2.0/handler/scan_all.go
Labels: target/2.2.0

#14014 fix robot list issue
  src/pkg/robot/dao/dao.go
  src/pkg/robot/manager.go
Labels: area/robot-account, target/2.2.0

#13794 Fix repoitory -> repository typo
  tests/apitests/python/library/repository.py
  tests/apitests/python/test_add_sys_label_to_tag.py
  tests/apitests/python/test_assign_role_to_ldap_group.py
  tests/apitests/python/test_copy_artifact_outside_project.py
  tests/apitests/python/test_del_repo.py
  tests/apitests/python/test_garbage_collection.py
  tests/apitests/python/test_manage_project_member.py
  tests/apitests/python/test_project_level_policy_content_trust.py
  tests/apitests/python/test_project_quota.py
  tests/apitests/python/test_push_chart_by_helm3_chart_cli.py
  tests/apitests/python/test_push_cnab_bundle.py
  tests/apitests/python/test_push_image_with_special_name.py
  tests/apitests/python/test_push_index_by_docker_manifest.py
  tests/apitests/python/test_registry_api.py
  tests/apitests/python/test_replication_from_dockerhub.py
  tests/apitests/python/test_retention.py
  tests/apitests/python/test_robot_account.py
  tests/apitests/python/test_scan_image_artifact.py
  tests/apitests/python/test_scan_image_artifact_in_public_project.py
  tests/apitests/python/test_sign_image.py
  tests/apitests/python/test_system_level_scan_all.py
  tests/apitests/python/test_tag_crud.py
  tests/apitests/python/test_tag_immutability.py
  tests/apitests/python/test_user_view_logs.py
Labels: target/2.3.0

#14012 Query executions with both vendor type and ID when sweep the execution records
  src/controller/replication/controller.go
  src/pkg/task/execution.go
Labels: target/2.2.0

#14023 Fix the legacy scheduled job issue for GC/scan all
  make/migrations/postgresql/0050_2.2.0_schema.up.sql
  src/controller/gc/controller.go
  src/controller/scan/base_controller.go
  src/controller/scan/base_controller_test.go
  src/controller/scan/callback.go
  src/controller/scan/callback_test.go
  src/jobservice/job/impl/legacy/legacy.go
  src/jobservice/job/impl/replication/scheduler.go
  src/jobservice/job/known_jobs.go
  src/jobservice/migration/manager_test.go
  src/jobservice/migration/migrator_v180.go
  src/jobservice/runtime/bootstrap.go
  src/server/v2.0/handler/scan_all.go
Labels: target/2.2.0

#14028 fix: always remove the robot after scan job finished
  src/controller/scan/callback.go
Labels: target/2.2.0, target/FC

#14036 fix: correct Authorize of basic and berer authorizer
  src/pkg/scan/rest/auth/api_key_auth_test.go
  src/pkg/scan/rest/auth/basic_auth.go
  src/pkg/scan/rest/auth/basic_auth_test.go
  src/pkg/scan/rest/auth/bearer_auth.go
  src/pkg/scan/rest/auth/bearer_auth_test.go
Labels: target/2.2.0

#14022 Add exporter to offline and online
  Makefile
Labels: target/2.2.0, target/FC

#14027 Don't ignore the NotFoundErr when handling the status hook of tasks to avoid the status out of sync
  src/controller/replication/controller.go
  src/controller/replication/controller_test.go
  src/jobservice/common/rds/scripts.go
  src/pkg/task/task.go
  src/server/handler/job_status_hook.go
Labels: target/2.2.0, target/FC

#14048 feat: add BeforePrepare for operation of swagger API
  src/server/v2.0/handler/handler.go
  tools/swagger/templates/server/builder.gotmpl
  tools/swagger/templates/server/configureapi.gotmpl
Labels: target/2.2.0

#14013 Harbor upgrading for 2.2
  make/harbor.yml.tmpl
  make/photon/prepare/commands/migrate.py
  make/photon/prepare/migrations/__init__.py
  make/photon/prepare/migrations/version_2_2_0/__init__.py
  make/photon/prepare/migrations/version_2_2_0/harbor.yml.jinja
  make/photon/prepare/utils/cert.py
  make/photon/prepare/utils/notary.py
Labels: target/2.2.0

#14050 fix robot v1 api update issue
  src/server/v2.0/handler/robotV1.go
Labels: target/2.2.0

#14058 Fix a potential nil pointer issue
  src/common/utils/oidc/helper.go
  src/core/controllers/oidc.go
Labels: target/2.2.0

#14059 feat: add health checker for trivy when it's enabled
  src/core/api/health.go
Labels: target/2.2.0, target/FC

#14085 Make sure the revision of execution isn't null during the upgrade
  make/migrations/postgresql/0050_2.2.0_schema.up.sql
Labels: target/2.2.0

#14076 build third parties in CI
  .github/workflows/build-package.yml
  make/photon/chartserver/builder
  tests/apitests/python/library/docker_api.py
  tests/ci/api_common_install.sh
  tests/ci/distro_installer.sh
Labels: target/2.0.6

#14088 [Cherry-pick 2.1.0] Upgrade python to v3 in git action CI host
  tests/ci/api_common_install.sh
Labels: target/2.1.0

#14084 Support multiple artifact type in metric
  src/pkg/exporter/project_collector.go
  src/pkg/exporter/project_collector_test.go
Labels: target/2.2.0

#14078 Fix metric label related things
  src/pkg/exporter/project_collector.go
  src/pkg/exporter/system_collector.go
  tests/apitests/python/test_verify_metrics_enabled.py
Labels: target/2.2.0

#14112 Add sen existed check for internal cert
  make/photon/prepare/models.py
  make/photon/prepare/utils/cert.py
Labels: target/2.2.0

#14101 fix: make a new ctx when start scan all in async
  src/controller/scan/base_controller.go
Labels: target/2.2.0

#14008 Remove raw token from header in token review request -- 2.0.x
  src/pkg/authproxy/http.go
Labels: target/2.0.6

#14120 fix catalog performance issue
  src/core/middlewares/middlewares.go
  src/pkg/repository/dao/dao.go
  src/pkg/repository/dao/dao_test.go
  src/pkg/repository/manager.go
  src/pkg/repository/manager_test.go
  src/server/registry/catalog.go
  src/server/registry/catalog_test.go
  src/testing/pkg/pkg.go
  src/testing/pkg/repository/dao/dao.go
  src/testing/pkg/repository/manager.go
Labels: area/performance, target/2.2.0
