Repository goharbor/harbor, pull requests merged in 2021-12, with the labels that each got.

#16077 Fix core private key
  tests/ci/api_common_install.sh
Labels: area/ci

#16045 add accessory dao service
  make/migrations/postgresql/0080_2.5.0_schema.up.sql
  src/lib/icon/const.go
  src/pkg/accessory/dao/dao.go
  src/pkg/accessory/dao/dao_test.go
  src/pkg/accessory/dao/model.go
  src/pkg/accessory/manager.go
  src/pkg/accessory/manager_test.go
  src/pkg/accessory/model/accessory.go
  src/pkg/accessory/model/accessory_test.go
  src/pkg/accessory/model/base/base.go
  src/pkg/accessory/model/base/base_test.go
  src/pkg/accessory/model/cosign/cosign.go
  src/pkg/accessory/model/cosign/cosign_test.go
  src/testing/pkg/accessory/dao/dao.go
  src/testing/pkg/accessory/model/accessory.go
  src/testing/pkg/pkg.go
Labels: target/2.5.0, area/cosign

#16066 Bump up version to v2.3.5
  VERSION
  tests/ci/api_common_install.sh
Labels: target/2.3.5

#16078 add cosign middleware
  src/server/middleware/cosign/cosign.go
  src/server/middleware/cosign/cosign_test.go
  src/server/registry/route.go
Labels: target/2.5.0

#16086 modify build-package branch master to main
  .github/workflows/build-package.yml
Labels: area/ci

#16087 Modify build-package branch master to main
  tests/ci/build_util.sh
Labels: area/ci

#16088 Modify push_index and push_sif case to be compatible arm
  tests/apitests/python/test_push_index_by_docker_manifest.py
  tests/apitests/python/test_push_sif_by_singularity.py
  tests/ci/api_run.sh
  tests/test-engine-image/Dockerfile.api_test
  tests/test-engine-image/Dockerfile.common
Labels: area/test automation/pytest-e2e

#16127 (CHERRY-PICK) fix: resolve the codeql alerts
  src/jobservice/logger/service.go
Labels: target/2.4.1

#16119 add scan report v1.1 to default X-Accept-Vulnerabilities
  api/v2.0/swagger.yaml
  src/server/v2.0/handler/artifact_test.go
Labels: target/2.4.1

#16063 add pull update control env
  src/common/const.go
  src/controller/event/handler/auditlog/auditlog.go
  src/controller/event/handler/internal/artifact.go
  src/lib/config/metadata/metadatalist.go
  src/lib/config/userconfig.go
Labels: target/2.4.1

#16091 Fix unescaped url issue
  src/portal/src/app/shared/components/list-repository-ro/list-repository-ro.component.ts
Labels: target/2.4.1

#15921 Improvements for Brazilian Portuguese (pt-br) translation.
  src/portal/src/i18n/lang/pt-br-lang.json
Labels: help wanted

#16165 Temp disable test cases that rely on notary
  tests/ci/api_run.sh
Labels: area/ci
