Repository goharbor/harbor, pull requests merged in 2021-06, with the labels that each got.

#14886 (cherry-pick) Check permission for user group api
  src/core/api/usergroup.go
Labels: target/2.1.6

#15019 [Cherrypick v2.1] Make v2auth more strict
  src/server/middleware/v2auth/auth.go
Labels: target/2.1.6

#15018 [Cherrypick - v2.2]: Make v2auth more strict
  src/server/middleware/v2auth/auth.go
  src/server/middleware/v2auth/auth_test.go
Labels: target/2.2.3

#15017 [Cherrypick - v2.1] Add merge slash middleware
  src/core/middlewares/middlewares.go
  src/server/middleware/mergeslash/mergeslash.go
  src/server/middleware/mergeslash/mergeslash_test.go
Labels: target/2.1.6

#15016 [Cherrypick - 2.2]: Add merge slash middleware
  src/core/middlewares/middlewares.go
  src/server/middleware/mergeslash/mergeslash.go
  src/server/middleware/mergeslash/mergeslash_test.go
Labels: target/2.2.3

#14976 (cherry-pick)fix: change sql to improve the performance of catalog api
  src/pkg/repository/dao/dao.go
Labels: target/2.2.3

#15029 test: use mockery generated artifact Manager in tests
  src/controller/artifact/abstractor_test.go
  src/controller/artifact/controller_test.go
  src/controller/icon/controller_test.go
  src/controller/repository/controller_test.go
  src/controller/tag/controller_test.go
  src/testing/pkg/artifact/fake_manager.go
Labels: target/2.3.0

#15028 fix db issue on helm upgrade
  make/photon/db/docker-entrypoint.sh
Labels: target/2.3.0

#14869 [ Cherry pick 2.1] replace email domain name in test
  .drone.yml
  .github/workflows/build-package.yml
  make/pushimage.sh
  tests/apitests/python/library/user.py
  tests/resources/Drone-Util.robot
  tests/resources/Github-Util.robot
  tests/resources/Harbor-Pages/Configuration.robot
  tests/resources/Nimbus-Util.robot
  tests/resources/OVA-Util.robot
  tests/resources/Util.robot
  tests/resources/VCH-Util.robot
  tests/resources/Vsphere-Util.robot
  tests/robot-cases/Group0-BAT/BAT.robot
  tests/robot-cases/Group1-Nightly/Chartmuseum.robot
  tests/robot-cases/Group1-Nightly/Clair.robot
  tests/robot-cases/Group1-Nightly/Common.robot
  tests/robot-cases/Group1-Nightly/Common_GC.robot
  tests/robot-cases/Group1-Nightly/DB.robot
  tests/robot-cases/Group1-Nightly/Nightly.robot
  tests/robot-cases/Group1-Nightly/Notary.robot
  tests/robot-cases/Group1-Nightly/Schedule.robot
  tests/robot-cases/Group1-Nightly/Trivy.robot
  tests/robot-cases/Group1-Nightly/Upgrade.robot
  tests/robot-cases/Group1-Nightly/multi_scanners.robot
  tests/robot-cases/Group2-Longevity/Longevity.robot
  tests/robot-cases/Group3-Upgrade/prepare.py
Labels: target/2.1.6

#15032 bump up clair version
  Makefile
  VERSION
Labels: target/2.1.6

#15037 update the log level of robot v1 context
  src/server/middleware/security/robot.go
Labels: target/2.3.0

#14977 (cherry-pick)Improve the performance of artifact related APIs
  make/migrations/postgresql/0053_2.2.3_schema.up.sql
  src/pkg/artifact/dao/dao.go
Labels: target/2.2.3

#15049 set shm size of postgres
  make/photon/prepare/templates/docker_compose/docker-compose.yml.jinja
Labels: target/2.3.0

#14919 Fix dragonfly preheat error.
  src/pkg/p2p/preheat/provider/client/http_client.go
  src/pkg/p2p/preheat/provider/client/http_client_test.go
  src/pkg/p2p/preheat/provider/dragonfly.go
  src/pkg/p2p/preheat/provider/dragonfly_test.go
  src/pkg/p2p/preheat/provider/mock.go
Labels: area/P2P-Distribution, target/2.3.0

#15056 enable policy checker for head manifest request
  src/server/registry/route.go
Labels: target/2.3.0

#15047 fixes 13976
  src/jobservice/job/impl/gc/garbage_collection.go
  src/jobservice/job/impl/gc/garbage_collection_test.go
  src/pkg/blob/manager.go
  src/pkg/blob/manager_test.go
  src/testing/pkg/blob/manager.go
Labels: target/2.3.0

#15076 Fix: Remove v6 format of harbor
  make/photon/prepare/templates/docker_compose/docker-compose.yml.jinja
Labels: target/2.3.0

#15082 fix: listen to 5443 when clean unexpected status of db
  make/photon/db/docker-entrypoint.sh
Labels: target/2.3.0

#15091 [Cherry pick]fix: listen to 5443 when clean unexpected status of db
  make/photon/db/docker-entrypoint.sh
Labels: target/2.3.0

#15046 Refind build base process in Makefile
  .github/workflows/build-package.yml
  Makefile
  make/photon/Makefile
  make/pushimage.sh
  tests/ci/api_common_install.sh
  tests/ci/ut_install.sh
Labels: target/2.3.0

#15084 Flattening repository path components excepting the last one
  src/controller/replication/flow/stage.go
  src/controller/replication/flow/stage_test.go
Labels: area/replication, target/2.3.0

#15087 Flattening repository path components excepting the last one
  src/controller/replication/flow/stage.go
  src/controller/replication/flow/stage_test.go
Labels: target/2.3.0

#15090 fix: supply the latest tag of artifact to scan request
  src/controller/event/handler/internal/artifact.go
  src/controller/event/handler/internal/util.go
  src/controller/event/handler/internal/util_test.go
  src/controller/event/handler/webhook/scan/scan.go
  src/controller/scan/base_controller.go
  src/controller/scan/base_controller_test.go
  src/controller/scan/callback.go
  src/controller/scan/options.go
  src/server/v2.0/handler/scan.go
Labels: target/2.3.0

#14998 Fix replication namespace level issue
  tests/resources/Harbor-Pages/Replication.robot
  tests/resources/Harbor-Pages/Replication_Elements.robot
  tests/resources/TestCaseBody.robot
  tests/robot-cases/Group1-Nightly/Common.robot
  tests/robot-cases/Group1-Nightly/Replication.robot
Labels: target/2.3.0

#15101 Set "x-omitempty" as "false" for the pull count and artifact count of repository
  api/v2.0/swagger.yaml
Labels: target/2.3.0

#15083 Remove workround for docker20 adaptation
  tests/resources/Docker-Util.robot
  tests/resources/Harbor-Pages/OIDC_Auth_Elements.robot
  tests/resources/Nightly-Util.robot
  tests/resources/TestCaseBody.robot
  tests/robot-cases/Group1-Nightly/Common.robot
Labels: target/2.3.0

#15102 [Cherry pick]fix: supply the latest tag of artifact to scan request
  src/controller/event/handler/internal/artifact.go
  src/controller/event/handler/internal/util.go
  src/controller/event/handler/internal/util_test.go
  src/controller/event/handler/webhook/scan/scan.go
  src/controller/scan/base_controller.go
  src/controller/scan/base_controller_test.go
  src/controller/scan/callback.go
  src/controller/scan/options.go
  src/server/v2.0/handler/scan.go
Labels: target/2.3.0

#15089 [ Cherry-pick 2.2.0 ] Refind build base process in Makefile
  .github/workflows/build-package.yml
  Makefile
  make/photon/Makefile
  make/pushimage.sh
  tests/ci/api_common_install.sh
  tests/ci/ut_install.sh
Labels: target/2.2.0

#15104 Fix the concurrent pushing the same image issue
  src/controller/artifact/controller.go
  src/controller/repository/controller.go
Labels: target/2.3.0

#15106 [ Cherry pick 2.3 ]Remove workaround for docker20 adaptation
  tests/resources/Docker-Util.robot
  tests/resources/Harbor-Pages/OIDC_Auth_Elements.robot
  tests/resources/Nightly-Util.robot
  tests/resources/TestCaseBody.robot
  tests/robot-cases/Group1-Nightly/Common.robot
Labels: target/2.3.0

#15114 [ Cherry pick 2.3 ] Add UI test for replicaiton flattening
  tests/resources/Harbor-Pages/Replication.robot
  tests/resources/Harbor-Pages/Replication_Elements.robot
  tests/resources/TestCaseBody.robot
  tests/robot-cases/Group1-Nightly/Common.robot
  tests/robot-cases/Group1-Nightly/Replication.robot
Labels: target/2.3.0

#15130 [ Cherry pick 2.3 ] - Refine build base process in Makefile
  .github/workflows/build-package.yml
  Makefile
  VERSION
  make/photon/Makefile
  make/pushimage.sh
  tests/ci/api_common_install.sh
  tests/ci/ut_install.sh
Labels: target/2.3.0

#15126 Fix the concurrent pushing the same image issue
  src/controller/artifact/controller.go
  src/controller/repository/controller.go
Labels: target/2.2.3

#15125 [cherry-pick]Add validation for destination namespace when creating/updating replication policy
  src/controller/replication/model/model.go
  src/lib/patterns.go
  src/lib/patterns_test.go
Labels: target/2.3.0

#15124 Add validation for destination namespace when creating/updating replication policy
  src/controller/replication/model/model.go
  src/lib/patterns.go
  src/lib/patterns_test.go
Labels: target/2.3.0

#15122 [cherry-pick]Fix the concurrent pushing the same image issue
  src/controller/artifact/controller.go
  src/controller/repository/controller.go
Labels: target/2.3.0

#15142 perf: configurations for perf improvement
  make/harbor.yml.tmpl
  make/photon/prepare/migrations/version_2_3_0/__init__.py
  make/photon/prepare/migrations/version_2_3_0/harbor.yml.jinja
  make/photon/prepare/templates/nginx/nginx.http.conf.jinja
  make/photon/prepare/templates/nginx/nginx.https.conf.jinja
  make/photon/prepare/templates/registry/config.yml.jinja
Labels: target/2.3.0

#15143 [Cherry pick]perf: configurations for perf improvement
  make/harbor.yml.tmpl
  make/photon/prepare/migrations/version_2_3_0/__init__.py
  make/photon/prepare/migrations/version_2_3_0/harbor.yml.jinja
  make/photon/prepare/templates/nginx/nginx.http.conf.jinja
  make/photon/prepare/templates/nginx/nginx.https.conf.jinja
  make/photon/prepare/templates/registry/config.yml.jinja
Labels: target/2.3.0

#15156 Trigger full build package process
  VERSION
Labels: target/2.3.0

#15147 bump up to v2.4.0
  VERSION
Labels: target/2.4.0

#15036 [ 2.1.0 ] Refine build base login in Makefile
  .github/workflows/build-package.yml
  Makefile
  VERSION
  make/photon/Makefile
  make/pushimage.sh
  tests/ci/api_common_install.sh
  tests/ci/ut_install.sh
Labels: target/2.1.0

#15205 remove migrator from offline install
  .github/workflows/build-package.yml
Labels: target/1.10.8

#15201 Add TiB support for display, fix unit to correct one
  src/portal/src/app/shared/units/utils.spec.ts
  src/portal/src/app/shared/units/utils.ts
Labels: target/2.4.0

#15223 roll back go for notary binary
  make/photon/notary/binary.Dockerfile
Labels: area/notary, target/2.2.3, target/2.3.1, target/2.4.0

#15224 [cherry pick]roll back go for notary binary
  make/photon/notary/binary.Dockerfile
Labels: target/2.2.3

#15225 [cherry pick]roll back go for notary binary
  make/photon/notary/binary.Dockerfile
Labels: target/2.3.1
