Repository goharbor/harbor, pull requests merged in 2021-03, with the labels that each got.

#14313 refactor: use ormer from the ctx for scanner ctl mgr and dao
  src/controller/scanner/base_controller.go
  src/controller/scanner/base_controller_test.go
  src/controller/scanner/controller.go
  src/core/api/pro_scanner.go
  src/core/api/pro_scanner_test.go
  src/core/api/scanners.go
  src/core/api/scanners_test.go
  src/core/main.go
  src/lib/orm/error.go
  src/pkg/scan/dao/scan/vulnerability_test.go
  src/pkg/scan/dao/scanner/registration.go
  src/pkg/scan/dao/scanner/registration_test.go
  src/pkg/scan/init.go
  src/pkg/scan/init_test.go
  src/pkg/scan/postprocessors/report_converters_test.go
  src/pkg/scan/scanner/manager.go
  src/pkg/scan/scanner/manager_test.go
  src/pkg/scan/scanner/mocks/manager.go
  src/server/v2.0/handler/scan_all.go
  src/testing/controller/scanner/controller.go
  src/testing/pkg/scan/scanner/manager.go
Labels: target/2.3.0

#14295 [cherry-pick]fix quota dao codeQL issue
  src/pkg/quota/dao/util.go
Labels: target/2.1.4

#14342 [Cherry Pick - 2.1] Add "*" to the claim set in the token for /v2 apis
  src/core/service/token/creator.go
  src/core/service/token/token_test.go
Labels: target/2.1.4

#14294 [cherry-pick] update blob list query
  src/controller/artifact/controller.go
  src/controller/blob/controller.go
  src/jobservice/job/impl/gc/garbage_collection.go
  src/jobservice/job/impl/gcreadonly/garbage_collection.go
  src/pkg/blob/dao/dao.go
  src/pkg/blob/dao/dao_test.go
  src/pkg/blob/manager.go
  src/pkg/blob/manager_test.go
  src/pkg/blob/models/blob.go
  src/server/middleware/blob/copy_artifact.go
  src/server/middleware/quota/copy_artifact.go
  src/testing/controller/blob/controller.go
  src/testing/pkg/blob/manager.go
Labels: target/2.1.4

#14296 [cherry-pick-2.1]Fix sql issue in artifact dao
  src/lib/orm/orm.go
  src/pkg/artifact/dao/dao.go
Labels: target/2.1.4

#14291 fix: handle project not found when creating token
  src/core/service/token/creator.go
Labels: target/2.1.4

#14322 [cherry-pick]add sorting for list blobs
  src/pkg/blob/dao/dao.go
Labels: target/2.2.1

#14356 patch upstream fix for io reader
  make/photon/registry/builder
Labels: target/2.1.4, target/2.2.1, target/2.3.0

#14341 refactor: generate scanner APIs by go-swagger
  api/v2.0/legacy_swagger.yaml
  api/v2.0/swagger.yaml
  src/controller/scanner/base_controller.go
  src/controller/scanner/controller.go
  src/core/api/harborapi_test.go
  src/core/api/pro_scanner.go
  src/core/api/pro_scanner_test.go
  src/core/api/scanners.go
  src/core/api/scanners_test.go
  src/pkg/scan/dao/scanner/registration.go
  src/pkg/scan/dao/scanner/registration_test.go
  src/pkg/scan/init.go
  src/pkg/scan/init_test.go
  src/pkg/scan/scanner/manager.go
  src/server/v2.0/handler/base.go
  src/server/v2.0/handler/handler.go
  src/server/v2.0/handler/model/scanner.go
  src/server/v2.0/handler/project.go
  src/server/v2.0/handler/project_test.go
  src/server/v2.0/handler/scanner.go
  src/server/v2.0/handler/scanner_test.go
  src/server/v2.0/route/legacy.go
  src/testing/controller/scanner/controller.go
  src/testing/pkg/scan/scanner/manager.go
  tests/apitests/python/library/base.py
  tests/apitests/python/library/scanner.py
  tests/apitests/python/test_assign_role_to_ldap_group.py
  tests/apitests/python/test_registry_api.py
  tests/apitests/python/test_scan_image_artifact.py
Labels: target/2.3.0

#14365 [cherry-pick]patch upstream fix for io reader
  make/photon/registry/builder
Labels: target/2.1.4

#14363 [cherry-pick]patch upstream fix for io reader
  make/photon/registry/builder
Labels: target/2.2.1

#14364 [cherry-pick 2.1.0] Remove python3.7 deployment in CI installtion phase.
  tests/ci/api_common_install.sh
Labels: target/2.1.4

#14366 [cherry-pick 2.0.0] Remove python3.7 deployment in CI installtion phase
  tests/ci/api_common_install.sh
Labels: target/2.0.0

#14374 Replace pybot to robot and upgrade python to v3.6
  tests/ci/api_common_install.sh
  tests/ci/api_run.sh
Labels: target/1.10.0

#14362 [cherry-pick 2.2.0] Replace python3.7 by 3.6 in CI installtion phase
  .github/workflows/CI.yml
  tests/ci/api_common_install.sh
Labels: target/2.2.1

#14371 Immu refactor
  api/v2.0/legacy_swagger.yaml
  api/v2.0/swagger.yaml
  src/controller/artifact/controller.go
  src/controller/artifact/controller_test.go
  src/controller/immutable/controller.go
  src/controller/immutable/controller_test.go
  src/controller/tag/controller.go
  src/controller/tag/controller_test.go
  src/core/api/harborapi_test.go
  src/core/api/immutabletagrule.go
  src/core/api/immutabletagrule_test.go
  src/pkg/immutable/dao/dao.go
  src/pkg/immutable/dao/dao_test.go
  src/pkg/immutable/dao/model/rule.go
  src/pkg/immutable/manager.go
  src/pkg/immutable/manager_test.go
  src/pkg/immutable/match/matcher.go
  src/pkg/immutable/match/rule/match.go
  src/pkg/immutable/match/rule/match_test.go
  src/pkg/immutable/model/rule.go
  src/pkg/immutabletag/controller.go
  src/pkg/immutabletag/dao/immutable.go
  src/pkg/immutabletag/manager.go
  src/pkg/retention/job.go
  src/pkg/retention/policy/action/index/index_test.go
  src/pkg/retention/policy/action/performer.go
  src/pkg/retention/policy/action/performer_test.go
  src/pkg/retention/policy/alg/or/processor.go
  src/pkg/retention/policy/alg/or/processor_test.go
  src/pkg/retention/policy/alg/processor.go
  src/pkg/retention/policy/builder_test.go
  src/server/middleware/immutable/pushmf_test.go
  src/server/v2.0/handler/handler.go
  src/server/v2.0/handler/immutable.go
  src/server/v2.0/handler/model/immutable.go
  src/server/v2.0/route/legacy.go
  src/testing/pkg/immutable/dao/dao.go
  src/testing/pkg/immutable/matcher.go
  src/testing/pkg/pkg.go
  tests/apitests/python/library/base.py
  tests/apitests/python/library/tag_immutability.py
Labels: target/2.3.0

#14399 bump version to v2.1.4
  VERSION
Labels: target/2.1.4

#14369 Introduce "sort" in query to provide a general solution for sorting
  api/v2.0/swagger.yaml
  src/common/models/project.go
  src/common/models/repo.go
  src/common/models/user.go
  src/core/api/registry.go
  src/core/api/search.go
  src/jobservice/job/impl/gc/garbage_collection.go
  src/lib/orm/metadata.go
  src/lib/orm/metadata_test.go
  src/lib/orm/orm.go
  src/lib/orm/query.go
  src/lib/orm/query_test.go
  src/lib/q/builder.go
  src/lib/q/builder_test.go
  src/lib/q/query.go
  src/pkg/artifact/dao/dao.go
  src/pkg/artifact/dao/model.go
  src/pkg/audit/dao/dao.go
  src/pkg/audit/model/model.go
  src/pkg/blob/dao/dao.go
  src/pkg/immutable/dao/dao.go
  src/pkg/p2p/preheat/dao/instance/dao.go
  src/pkg/p2p/preheat/dao/policy/dao.go
  src/pkg/p2p/preheat/models/policy/policy.go
  src/pkg/project/dao/dao.go
  src/pkg/repository/dao/dao.go
  src/pkg/robot/dao/dao.go
  src/pkg/robot/manager.go
  src/pkg/robot/model/model.go
  src/pkg/scan/dao/scanner/registration.go
  src/pkg/tag/dao/dao.go
  src/pkg/tag/model/tag/model.go
  src/pkg/task/dao/execution.go
  src/pkg/task/dao/model.go
  src/pkg/task/dao/task.go
  src/pkg/user/dao/dao.go
  src/pkg/user/manager.go
  src/server/v2.0/handler/artifact.go
  src/server/v2.0/handler/auditlog.go
  src/server/v2.0/handler/base.go
  src/server/v2.0/handler/base_test.go
  src/server/v2.0/handler/gc.go
  src/server/v2.0/handler/immutable.go
  src/server/v2.0/handler/preheat.go
  src/server/v2.0/handler/project.go
  src/server/v2.0/handler/quota.go
  src/server/v2.0/handler/replication.go
  src/server/v2.0/handler/repository.go
  src/server/v2.0/handler/retention.go
  src/server/v2.0/handler/robot.go
  src/server/v2.0/handler/robotV1.go
  src/server/v2.0/handler/scan_all.go
  src/server/v2.0/handler/scanner.go
Labels: target/2.3.0

#14412 API for system CVE allowlist to new model
  api/v2.0/swagger.yaml
  src/common/dao/cve_allowlist.go
  src/common/dao/cve_allowlist_test.go
  src/common/models/base.go
  src/common/models/project.go
  src/common/rbac/const.go
  src/common/rbac/system/policies.go
  src/controller/p2p/preheat/enforcer_test.go
  src/controller/project/controller.go
  src/controller/project/controller_test.go
  src/core/api/harborapi_test.go
  src/core/api/sys_cve_allowlist.go
  src/core/api/sys_cve_allowlist_test.go
  src/pkg/allowlist/dao/dao.go
  src/pkg/allowlist/dao/dao_test.go
  src/pkg/allowlist/manager.go
  src/pkg/allowlist/manager_test.go
  src/pkg/allowlist/models/cve_allowlist.go
  src/pkg/allowlist/models/cve_allowlist_test.go
  src/pkg/allowlist/validator.go
  src/pkg/allowlist/validator_test.go
  src/pkg/scan/allowlist/manager_test.go
  src/pkg/scan/report/summary.go
  src/pkg/scan/report/summary_test.go
  src/pkg/scan/vuln/report.go
  src/pkg/scan/vuln/report_test.go
  src/pkg/scan/vuln/summary.go
  src/server/v2.0/handler/handler.go
  src/server/v2.0/handler/model/cve_allowlist.go
  src/server/v2.0/handler/sys_cve_allowlist.go
  src/server/v2.0/route/legacy.go
  src/testing/pkg/allowlist/dao/dao.go
  src/testing/pkg/allowlist/manager.go
  src/testing/pkg/pkg.go
  src/testing/pkg/scan/allowlist/manager.go
  tests/apitests/python/library/base.py
  tests/apitests/python/library/system_cve_allowlist.py
  tests/apitests/python/test_sys_cve_allowlists.py
Labels: target/2.3.0

#14343 [ CherryPick 2.2 ] Add "*" to the claim set in the token for /v2 apis
  src/core/service/token/creator.go
  src/core/service/token/token_test.go
Labels: target/2.2.1

#14423 Update the execution status of retention schedule
  make/migrations/postgresql/0041_2.1.4_schema.up.sql
  src/pkg/task/execution.go
  src/pkg/task/execution_test.go
  src/pkg/task/task.go
  src/pkg/task/task_test.go
Labels: target/2.1.4

#14434 Add upgrade sql file introduced in 2.1.4
  make/migrations/postgresql/0041_2.1.4_schema.up.sql
  src/pkg/task/execution.go
  src/pkg/task/execution_test.go
  src/pkg/task/task.go
  src/pkg/task/task_test.go
Labels: target/2.2.1

#14447 Add upgrade sql file introduced in 2.1.4
  make/migrations/postgresql/0041_2.1.4_schema.up.sql
  src/pkg/task/execution.go
  src/pkg/task/execution_test.go
  src/pkg/task/task.go
  src/pkg/task/task_test.go
Labels: target/2.3.0

#14455 fix catalog duplicate result
  src/pkg/repository/dao/dao.go
  src/pkg/repository/dao/dao_test.go
Labels: target/2.2.1

#14452 Add order by ID when listing tasks to avoid duplicated records
  src/pkg/task/dao/task.go
Labels: target/2.2.1

#14451 Fix the consume too much CPU issue
  make/migrations/postgresql/0051_2.2.1_schema.up.sql
  src/pkg/task/execution.go
Labels: target/2.2.1

#14456 [cherry-pick] fix catalog duplicate result
  src/pkg/repository/dao/dao.go
  src/pkg/repository/dao/dao_test.go
Labels: target/2.2.1

#14428 fix: search charts in the projects the user owned
  src/core/api/search.go
Labels: target/2.2.1

#14471 Update the index name
  make/migrations/postgresql/0051_2.2.1_schema.up.sql
Labels: target/2.2.1

#14457 [cherry-pick]Fix the consume too much CPU issue
  make/migrations/postgresql/0051_2.2.1_schema.up.sql
  src/pkg/task/execution.go
Labels: target/2.3.0

#14478 bump up base to v2.2.1
  VERSION
Labels: target/2.2.1

#14422 refactor: generate search API by go-swagger
  api/v2.0/legacy_swagger.yaml
  api/v2.0/swagger.yaml
  src/common/dao/repository.go
  src/common/dao/repository_test.go
  src/core/api/harborapi_test.go
  src/core/api/search.go
  src/core/api/search_test.go
  src/server/v2.0/handler/handler.go
  src/server/v2.0/handler/search.go
  src/server/v2.0/route/legacy.go
Labels: target/2.3.0

#14329 Before fetching the GitLab repository check if the project has container registry enabled to avoid 403 error
  src/replication/adapter/gitlab/adapter.go
Labels: area/replication

#14503 Base image for exporter
  Makefile
  make/photon/Makefile
  make/photon/exporter/Dockerfile
  make/photon/exporter/Dockerfile.base
Labels: target/2.2.1

#14546 Update web UI start guideline
  CONTRIBUTING.md
Labels: area/doc
