Repository goharbor/harbor, pull requests merged in 2022-03, with the labels that each got.

#16453 Create index on task with job_id
  make/migrations/postgresql/0080_2.5.0_schema.up.sql
Labels: target/2.5.0

#16466 Add replication test cases triggered by events
  tests/resources/Harbor-Pages/Project.robot
  tests/robot-cases/Group1-Nightly/Replication.robot
Labels: area/test automation/nightly-testing

#16484 [cherry-pick]Bump TRIVYVERSION to v0.24.2 and bump TRIVYADAPTERVERSION to v0.26.0
  Makefile
Labels: target/2.4.2

#16485 [cherry-pick]Bump TRIVYVERSION to v0.24.2 and bump TRIVYADAPTERVERSION to v0.26.0
  Makefile
Labels: target/2.5.0

#16487 Add a new robot permission and sort permissions
  src/portal/src/app/base/left-side-nav/system-robot-accounts/system-robot-util.ts
Labels: target/2.5.0

#16498 Improve style and correct typos
  src/portal/src/app/base/left-side-nav/project-quotas/project-quotas/edit-project-quotas/edit-project-quotas.component.scss
  src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.html
  src/portal/src/app/base/left-side-nav/system-robot-accounts/list-all-projects/list-all-projects.component.html
  src/portal/src/app/base/left-side-nav/system-robot-accounts/new-robot/new-robot.component.html
  src/portal/src/app/base/left-side-nav/system-robot-accounts/new-robot/new-robot.component.ts
  src/portal/src/app/base/project/robot-account/add-robot/add-robot.component.html
  src/portal/src/app/base/project/robot-account/add-robot/add-robot.component.ts
  src/portal/src/i18n/lang/en-us-lang.json
Labels: target/2.6.0

#16148 Add online latest installer package
  .github/workflows/build-package.yml
Labels: area/ci

#16501 Update readme
  README.md
Labels: target/2.6.0

#16499 [Cherry-pick]Improve style and correct typos
  src/portal/src/app/base/left-side-nav/project-quotas/project-quotas/edit-project-quotas/edit-project-quotas.component.scss
  src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.html
  src/portal/src/app/base/left-side-nav/system-robot-accounts/list-all-projects/list-all-projects.component.html
  src/portal/src/app/base/left-side-nav/system-robot-accounts/new-robot/new-robot.component.html
  src/portal/src/app/base/left-side-nav/system-robot-accounts/new-robot/new-robot.component.ts
  src/portal/src/app/base/project/robot-account/add-robot/add-robot.component.html
  src/portal/src/app/base/project/robot-account/add-robot/add-robot.component.ts
  src/portal/src/i18n/lang/en-us-lang.json
Labels: target/2.5.0

#16511 [cherry-pick]add transaction for artifact delete
  src/controller/artifact/controller.go
Labels: target/2.5.0

#16512 [cherry-pick]add transaction for artifact delete
  src/controller/artifact/controller.go
Labels: target/2.4.2

#16545 add cosign signature icon
  icons/cosign.png
  src/controller/icon/controller.go
  src/lib/icon/const.go
  src/pkg/accessory/manager.go
  src/pkg/accessory/manager_test.go
  src/pkg/accessory/model/accessory.go
  src/server/v2.0/handler/model/accessory.go
Labels: area/cosign

#16551 enhance health validataion
  src/lib/endpoint.go
  src/lib/endpoint_test.go
  src/pkg/p2p/preheat/provider/dragonfly.go
  src/pkg/p2p/preheat/provider/kraken.go
  src/pkg/scan/dao/scanner/model.go
  src/pkg/scan/dao/scanner/model_test.go
Labels: target/2.5.0

#16552 Update push and pull command for helm
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
  src/portal/src/app/base/project/repository/artifact/artifact-tag/artifact-tag.component.ts
  src/portal/src/app/base/project/repository/artifact/artifact.ts
  src/portal/src/app/shared/components/push-image/push-image.component.ts
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: target/2.6.0

#16553 [Cherry-pick]Update push and pull command for helm
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
  src/portal/src/app/base/project/repository/artifact/artifact-tag/artifact-tag.component.ts
  src/portal/src/app/base/project/repository/artifact/artifact.ts
  src/portal/src/app/shared/components/push-image/push-image.component.ts
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: target/2.5.0

#16573 [cherry-pick]Modify setup-gcloud from master to v0
  .github/workflows/build-package.yml
Labels: area/build

#16572 [cherry-pick]Modify setup-gcloud from master to v0
  .github/workflows/build-package.yml
Labels: area/build

#16571 Modify setup-gcloud from master to v0
  .github/workflows/build-package.yml
Labels: area/build

#16546 feat: implement beego session provider
  src/controller/proxy/controller.go
  src/core/main.go
  src/core/session/codec.go
  src/core/session/codec_test.go
  src/core/session/session.go
  src/core/session/session_test.go
  src/lib/cache/codec.go
  src/lib/cache/redis/redis.go
Labels: area/performance

#16579 Update webhook testcase xpath from disable to deactivate
  tests/resources/Harbor-Pages/Project-Webhooks.robot
  tests/robot-cases/Group1-Nightly/Common.robot
Labels: area/test automation/nightly-testing

#16597 migrations: correct project metadata public value
  make/migrations/postgresql/0090_2.6.0_schema.up.sql
Labels: kind/bug, area/metrics

#16596 fix: validate project metadata public value
  src/server/v2.0/handler/project.go
Labels: kind/bug, area/metrics

#16580 Update usergroups API to support search by group_name
  api/v2.0/swagger.yaml
  src/server/v2.0/handler/usergroup.go
Labels: target/2.6.0
