Repository goharbor/harbor, pull requests merged in 2022-06, with the labels that each got.

#16322 fix: add patch for registry layers larger than 10G with S3 backend
  make/photon/registry/builder
Labels: area/registry, env/storage/s3, release-note/enhancement

#16925 Add NextScheduledTime in schedule object
  api/v2.0/swagger.yaml
  src/common/utils/utils.go
  src/common/utils/utils_test.go
  src/controller/replication/model/model.go
  src/go.mod
  src/go.sum
  src/jobservice/core/controller.go
  src/jobservice/period/enqueuer.go
  src/jobservice/period/policy_store.go
  src/pkg/p2p/preheat/models/policy/policy.go
  src/pkg/p2p/preheat/models/policy/policy_test.go
  src/pkg/scheduler/scheduler.go
  src/server/v2.0/handler/gc.go
  src/server/v2.0/handler/model/gc.go
  src/server/v2.0/handler/model/jobservice.go
  src/server/v2.0/handler/purge.go
  src/vendor/github.com/robfig/cron/v3/.gitignore
  src/vendor/github.com/robfig/cron/v3/.travis.yml
  src/vendor/github.com/robfig/cron/v3/LICENSE
  src/vendor/github.com/robfig/cron/v3/README.md
  src/vendor/github.com/robfig/cron/v3/chain.go
  src/vendor/github.com/robfig/cron/v3/constantdelay.go
  src/vendor/github.com/robfig/cron/v3/cron.go
  src/vendor/github.com/robfig/cron/v3/doc.go
  src/vendor/github.com/robfig/cron/v3/logger.go
  src/vendor/github.com/robfig/cron/v3/option.go
  src/vendor/github.com/robfig/cron/v3/parser.go
  src/vendor/github.com/robfig/cron/v3/spec.go
  src/vendor/modules.txt
Labels: target/2.6.0, release-note/enhancement

#16953 fix(prepare): validate expire hours when enable cache (#16949)
  make/photon/prepare/models.py
Labels: area/cache, release-note/update

#16956 Add Publish Release workflow
  .github/release.tpl
  .github/workflows/publish_release.yml
  tools/release/release_utils.sh
Labels: target/2.6.0, release-note/infra, area/release

#16920 fix: golangci-lint errcheck
  src/.golangci.yaml
  src/chartserver/chart_operator.go
  src/chartserver/redis_sentinel.go
  src/common/job/test/server.go
  src/controller/blob/controller.go
  src/controller/event/handler/init.go
  src/controller/gc/callback.go
  src/controller/replication/policy.go
  src/controller/scan/base_controller.go
  src/controller/scanner/options.go
  src/core/api/base.go
  src/core/api/internal.go
  src/core/controllers/base.go
  src/core/main.go
  src/core/session/session.go
  src/jobservice/job/impl/context.go
  src/jobservice/job/impl/sample/job.go
  src/jobservice/main.go
  src/lib/cache/memory/memory.go
  src/lib/config/config.go
  src/lib/log/logger.go
  src/lib/orm/error.go
  src/lib/request.go
  src/pkg/config/manager.go
  src/pkg/config/store/store.go
  src/pkg/exporter/exporter.go
  src/pkg/exporter/health_collector.go
  src/pkg/exporter/project_collector.go
  src/pkg/exporter/system_collector.go
  src/pkg/member/dao/dao.go
  src/pkg/p2p/preheat/models/policy/policy.go
  src/pkg/quota/dao/util.go
  src/pkg/reg/adapter/aliacr/adapter.go
  src/pkg/reg/adapter/aliacr/auth.go
  src/pkg/reg/adapter/artifacthub/client.go
  src/pkg/reg/adapter/helmhub/client.go
  src/pkg/scan/job.go
  src/server/middleware/middleware.go
  src/server/middleware/quota/quota.go
  src/server/middleware/repoproxy/proxy.go
  src/server/registry/manifest.go
  src/server/v2.0/handler/artifact.go
  src/server/v2.0/handler/immutable.go
  src/server/v2.0/handler/label.go
  src/server/v2.0/handler/model/project.go
  src/server/v2.0/handler/model/retention.go
  src/server/v2.0/handler/model/robot.go
  src/server/v2.0/handler/notification_policy.go
  src/server/v2.0/handler/project.go
  src/server/v2.0/handler/robot.go
  src/server/v2.0/handler/robotV1.go
Labels: release-note/update

#16944 Add webhook functionality test case
  tests/resources/Harbor-Pages/Project-Tag-Retention.robot
  tests/resources/Harbor-Pages/Project-Webhooks.robot
  tests/resources/Harbor-Pages/ToolKit.robot
  tests/resources/TestCaseBody.robot
  tests/resources/Util.robot
  tests/resources/Webhook-Util.robot
  tests/robot-cases/Group1-Nightly/Common.robot
  tests/robot-cases/Group1-Nightly/Webhook.robot
Labels: area/test automation/nightly-testing, target/2.6.0, release-note/infra

#16943 The purge job update time is wrong
  src/server/v2.0/handler/purge.go
Labels: release-note/ignore-for-release

#16957 bump up golang version to v1.18.3
  .github/workflows/CI.yml
  .github/workflows/build-package.yml
  .github/workflows/conformance_test.yml
  CONTRIBUTING.md
  Makefile
  make/photon/chartserver/builder
  make/photon/registry/Dockerfile.binary
  make/photon/trivy-adapter/Dockerfile.binary
  make/photon/trivy-adapter/builder.sh
  src/go.mod
  tests/ci/distro_installer.sh
  tests/ci/ut_install.sh
Labels: release-note/update

#16879 Introduce system artifact manager cleanup job
  src/controller/systemartifact/callback.go
  src/controller/systemartifact/callback_test.go
  src/controller/systemartifact/execution.go
  src/controller/systemartifact/execution_test.go
  src/core/main.go
  src/jobservice/job/impl/systemartifact/cleanup.go
  src/jobservice/job/impl/systemartifact/cleanup_test.go
  src/jobservice/job/known_jobs.go
  src/jobservice/runtime/bootstrap.go
  src/testing/controller/controller.go
Labels: target/2.6.0, release-note/new-feature, area/system-artifact

#16914 Add audit_log forward endpoint
  api/v2.0/swagger.yaml
  src/common/const.go
  src/controller/config/controller.go
  src/controller/config/controller_test.go
  src/controller/event/handler/auditlog/auditlog_test.go
  src/core/main.go
  src/lib/config/metadata/metadatalist.go
  src/lib/config/userconfig.go
  src/lib/log/logger.go
  src/lib/log/logger_test.go
  src/pkg/audit/forward.go
  src/pkg/audit/manager.go
  src/pkg/audit/manager_test.go
  src/testing/lib/config/manager.go
  src/testing/lib/lib.go
Labels: release-note/new-feature

#16965 fix(swagger): append scan report version 1.1 to swagger docs
  api/v2.0/swagger.yaml
  src/server/v2.0/handler/artifact_test.go
Labels: release-note/update

#16947 fix(replication): azurecr replication with token (#16888)
  src/pkg/reg/adapter/azurecr/adapter.go
  src/pkg/reg/adapter/azurecr/adapter_test.go
  src/pkg/reg/adapter/azurecr/auth.go
  src/pkg/reg/adapter/azurecr/auth_test.go
Labels: area/replication, release-note/update

#16981 Update Web Routing test case
  tests/robot-cases/Group1-Nightly/Routing.robot
Labels: area/test automation/nightly-testing, target/2.6.0, release-note/infra

#16979 Fix some UI issues
  src/portal/.stylelintrc.json
  src/portal/src/app/base/left-side-nav/clearing-job/audit-log-purge/set-job/set-job.component.html
  src/portal/src/app/base/left-side-nav/clearing-job/audit-log-purge/set-job/set-job.component.ts
  src/portal/src/app/base/left-side-nav/clearing-job/gc-page/gc/gc.component.ts
  src/portal/src/app/base/left-side-nav/config/security/security.component.ts
  src/portal/src/app/base/left-side-nav/projects/create-project/create-project.component.ts
  src/portal/src/app/base/project/tag-feature-integration/tag-retention/tag-retention.component.ts
  src/portal/src/app/shared/services/interface.ts
Labels: release-note/enhancement

#16987 fixes 16940
  src/common/rbac/project/rbac_util.go
Labels: release-note/enhancement

#16980 Update CVE allowlist UI test case
  tests/resources/Harbor-Pages/Configuration.robot
  tests/resources/Harbor-Pages/Configuration_Elements.robot
  tests/resources/Harbor-Pages/Verify.robot
  tests/resources/TestCaseBody.robot
Labels: area/test automation/nightly-testing, target/2.6.0, release-note/infra

#16975 Update GC UI Testcase
  tests/resources/Harbor-Pages/Configuration.robot
  tests/resources/Harbor-Pages/Configuration_Elements.robot
  tests/resources/Harbor-Pages/GC.robot
  tests/resources/Harbor-Pages/GC_Elements.robot
  tests/resources/Util.robot
  tests/robot-cases/Group1-Nightly/Common_GC.robot
  tests/robot-cases/Group1-Nightly/Schedule.robot
Labels: area/test automation/nightly-testing, target/2.6.0, release-note/infra

#16974 fix: update code for golangci-lint gosimple
  src/.golangci.yaml
  src/chartserver/chart_operator.go
  src/chartserver/handler_repo.go
  src/chartserver/handler_utility.go
  src/chartserver/utils.go
  src/common/job/test/server.go
  src/common/rbac/system/namespace.go
  src/common/utils/utils.go
  src/controller/config/controller.go
  src/controller/event/handler/p2p/preheat.go
  src/controller/user/controller.go
  src/core/api/email.go
  src/core/api/internal.go
  src/core/auth/authproxy/auth.go
  src/core/auth/lock.go
  src/core/controllers/authproxy_redirect.go
  src/core/controllers/oidc.go
  src/core/utils/response_handlers.go
  src/jobservice/api/handler.go
  src/jobservice/job/tracker.go
  src/jobservice/migration/migrator_v180.go
  src/jobservice/runner/redis.go
  src/jobservice/worker/cworker/c_worker.go
  src/lib/q/builder.go
  src/pkg/chart/operator.go
  src/pkg/config/rest/manager.go
  src/pkg/notification/notification.go
  src/pkg/oidc/helper.go
  src/pkg/p2p/preheat/models/policy/policy.go
  src/pkg/p2p/preheat/policy/filter.go
  src/pkg/project/metadata/manager.go
  src/pkg/reg/adapter/aliacr/adapter.go
  src/pkg/reg/adapter/harbor/v2/client.go
  src/pkg/reg/adapter/huawei/image_registry.go
  src/pkg/reg/adapter/jfrog/adapter.go
  src/pkg/registry/auth/bearer/authorizer.go
  src/pkg/registry/client.go
  src/pkg/retention/launcher.go
  src/pkg/scan/postprocessors/report_converters.go
  src/pkg/signature/notary/helper.go
  src/pkg/task/dao/execution.go
  src/pkg/user/manager.go
  src/registryctl/client/client.go
  src/registryctl/handlers/handler.go
  src/server/middleware/csrf/csrf.go
  src/server/middleware/repoproxy/proxy.go
  src/server/registry/catalog.go
  src/server/v2.0/handler/notification_policy.go
  src/server/v2.0/handler/repository.go
  src/server/v2.0/handler/retention.go
  src/server/v2.0/handler/scan_all.go
Labels: release-note/update

#16994 fixes 16940
  src/common/rbac/project/rbac_util.go
Labels: release-note/update, target/2.5.2

#17025 clean up unused mock file&& regenerate mocks
  src/testing/controller/jobservice/execution_controller.go
  src/testing/controller/jobservice/task_controller.go
  src/testing/controller/systemartifact/controller.go
Labels: release-note/ignore-for-release

#17004 Support stop GC execution
  api/v2.0/swagger.yaml
  src/jobservice/job/impl/gc/garbage_collection.go
  src/jobservice/job/impl/gc/garbage_collection_test.go
  src/server/v2.0/handler/gc.go
Labels: target/2.6.0, release-note/enhancement

#17024 fix: update the jobservice hook retry concurrency
  src/jobservice/hook/hook_agent.go
  src/jobservice/hook/hook_client.go
  src/jobservice/runtime/bootstrap.go
Labels: release-note/update

#17026 fix: update the jobservice hook retry concurrency
  src/jobservice/hook/hook_agent.go
  src/jobservice/hook/hook_client.go
  src/jobservice/runtime/bootstrap.go
Labels: release-note/update, target/2.5.2

#17009 Remove style-lint package and upgrade @angular-devkit/build-angular
  src/portal/package-lock.json
  src/portal/package.json
Labels: release-note/update

#17023 Skip to refresh execution status when unchanged
  src/pkg/task/dao/execution.go
Labels: target/2.6.0, release-note/update

#17032 Update harbor-e2e-engine image
  tests/test-engine-image/Dockerfile.common
  tests/test-engine-image/Dockerfile.ui_test
Labels: area/test automation/nightly-testing, release-note/infra

#17034 (cherry-pick) Skip to refresh execution status when unchanged
  src/pkg/task/dao/execution.go
Labels: release-note/update

#17036 migrate: add db index on artifact repository name
  make/migrations/postgresql/0081_2.5.2_schema.up.sql
Labels: release-note/update

#17035 migrate: add db index on artifact repository name
  make/migrations/postgresql/0090_2.6.0_schema.up.sql
Labels: release-note/update

#17019 In SECURITY.md, fix broken link to RELEASES.md
  SECURITY.md
Labels: release-note/community

#17037 Add stop button for GC
  src/portal/src/app/base/left-side-nav/clearing-job/gc-page/gc/gc-history/gc-history.component.html
  src/portal/src/app/base/left-side-nav/clearing-job/gc-page/gc/gc-history/gc-history.component.ts
  src/portal/src/app/shared/entities/shared.const.ts
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: target/2.6.0, release-note/new-feature, release-note/docs

#17042 Bump up version to v2.5.2
  VERSION
Labels: release-note/ignore-for-release

#17027 golangci-lint fix ineffassign
  src/.golangci.yaml
  src/controller/replication/policy.go
  src/jobservice/job/impl/replication/replication.go
  src/jobservice/migration/migrator_v180.go
  src/lib/redis/helper.go
  src/lib/redis/helper_test.go
  src/pkg/reg/adapter/aliacr/adapter.go
  src/pkg/reg/adapter/aliacr/auth.go
  src/pkg/reg/adapter/tencentcr/adapter.go
  src/pkg/reg/adapter/tencentcr/sdk.go
  src/pkg/replication/dao/dao.go
  src/pkg/task/dao/task.go
  src/server/registry/catalog.go
  src/server/v2.0/handler/config.go
Labels: release-note/ignore-for-release

#17029 Project name validation to prevent system artifact reserved project names
  src/pkg/systemartifact/manager.go
  src/pkg/systemartifact/manager_test.go
  src/server/v2.0/handler/statistic.go
  src/server/v2.0/handler/statistic_test.go
  src/testing/pkg/systemartifact/manager.go
Labels: release-note/new-feature

#17031 Enhance webhook testcase
  tests/resources/Harbor-Pages/Project-Webhooks.robot
  tests/resources/TestCaseBody.robot
  tests/robot-cases/Group1-Nightly/Webhook.robot
Labels: area/test automation/nightly-testing, release-note/ignore-for-release

#17039 update support for docker compose v2
  make/common.sh
  make/install.sh
Labels: release-note/update

#17045 fix: update code for golangci-lint varcheck
  src/.golangci.yaml
  src/pkg/reg/adapter/aliacr/types.go
  src/pkg/reg/adapter/tencentcr/adapter.go
Labels: release-note/ignore-for-release

#17047 fix: enable structcheck/typecheck/unused for golangci-lint
  src/.golangci.yaml
Labels: release-note/ignore-for-release

#17057 (cherry-pick) Unify the process of jobservice execution/task retrieve and update
  src/server/v2.0/handler/notification_policy.go
  src/server/v2.0/handler/preheat.go
  src/server/v2.0/handler/robot.go
Labels: release-note/update

#17060 removing httpd on prepare base DockerFile
  make/photon/prepare/Dockerfile.base
Labels: release-note/ignore-for-release

#17056 update install htpasswd in prepare dockerfile
  make/photon/prepare/Dockerfile.base
Labels: release-note/ignore-for-release

#17065 fix: fix the update of retention policy
  src/server/v2.0/handler/retention.go
Labels: release-note/update, target/2.5.2

#17064 fix: fix the update of retention policy
  src/server/v2.0/handler/retention.go
Labels: release-note/update

#17066 Update publish release workflow dockerhub account
  .github/workflows/publish_release.yml
Labels: release-note/ignore-for-release

#17067 Update publish release workflow dockerhub account
  .github/workflows/publish_release.yml
Labels: release-note/ignore-for-release

#17072 [Cherry-Pick] fix: bump trivy version to v0.29.2 and bump trivyadapter version to v0.30.0
  Makefile
Labels: release-note/update

#17071 fix: bump trivy version to v0.29.2 and bump trivyadapter version to v0.30.0
  Makefile
Labels: release-note/update

#17073 [cherry-pick]add url raw query check middleware
  src/core/middlewares/middlewares.go
  src/server/middleware/url/parse.go
  src/server/middleware/url/parse_test.go
Labels: release-note/update, target/2.5.2

#17033 Support stop purge audit log job
  api/v2.0/swagger.yaml
  src/controller/purge/controller.go
  src/jobservice/job/impl/purge/purge.go
  src/jobservice/job/impl/purge/purge_test.go
  src/server/v2.0/handler/purge.go
  src/testing/controller/purge/controller.go
Labels: release-note/update

#17068 Improve copy command component
  src/portal/src/app/services/event-service/event.service.spec.ts
  src/portal/src/app/services/event-service/event.service.ts
  src/portal/src/app/shared/components/push-image/copy-input.component.ts
  src/portal/src/app/shared/components/third-party/ngx-clipboard/clipboard.service.ts
Labels: release-note/enhancement

#17069 Improve cron validator for replication rule
  src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.html
  src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.ts
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: release-note/enhancement

#17054 Add stop button for audit log rotation
  src/portal/src/app/base/left-side-nav/clearing-job/audit-log-purge/history/purge-history.component.html
  src/portal/src/app/base/left-side-nav/clearing-job/audit-log-purge/history/purge-history.component.spec.ts
  src/portal/src/app/base/left-side-nav/clearing-job/audit-log-purge/history/purge-history.component.ts
  src/portal/src/app/base/left-side-nav/clearing-job/audit-log-purge/set-job/set-job.component.html
  src/portal/src/app/base/left-side-nav/clearing-job/gc-page/gc/gc-history/gc-history.component.html
  src/portal/src/app/base/left-side-nav/clearing-job/gc-page/gc/gc-history/gc-history.component.spec.ts
  src/portal/src/app/shared/entities/shared.const.ts
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: target/2.6.0, release-note/new-feature, release-note/docs

#17085 Fix scan log mismatch issue
  src/common/rbac/project/rbac_role.go
  src/controller/scan/base_controller.go
  src/controller/scan/base_controller_test.go
  src/controller/scan/controller.go
  src/core/api/chart_label.go
  src/server/v2.0/handler/artifact.go
  src/server/v2.0/handler/scan.go
  src/testing/controller/scan/controller.go
Labels: release-note/update

#17079 fix: update preheat api handler and DAO
  src/pkg/p2p/preheat/dao/instance/dao.go
  src/pkg/p2p/preheat/dao/instance/dao_test.go
  src/server/v2.0/handler/preheat.go
Labels: release-note/update

#17080 fix: update preheat api handler and DAO
  src/pkg/p2p/preheat/dao/instance/dao.go
  src/pkg/p2p/preheat/dao/instance/dao_test.go
  src/server/v2.0/handler/preheat.go
Labels: release-note/update, target/2.5.2

#17093 Upgrade pipenv to 2022.1.8
  make/photon/prepare/Dockerfile.base
Labels: release-note/update

#17092 [cherry-pick]Upgrade pipenv to 2022.1.8
  make/photon/prepare/Dockerfile.base
Labels: release-note/update, target/2.5.2

#17088 Unify retention schedule/task retrieve and update
  src/controller/retention/controller.go
  src/pkg/retention/models.go
  src/server/v2.0/handler/retention.go
Labels: release-note/ignore-for-release, target/2.5.2

#17055 Enhance the read-only API to avoid deleting operations during the job running
  src/common/registryctl/client.go
  src/jobservice/job/impl/gc/garbage_collection.go
  src/jobservice/job/impl/gc/util.go
  src/jobservice/logger/entry_test.go
  src/jobservice/logger/sweeper_controller.go
  src/jobservice/runtime/bootstrap_test.go
  src/lib/cache/memory/memory.go
  src/pkg/registry/client.go
  src/pkg/registry/interceptor/interceptor.go
  src/pkg/registry/interceptor/readonly/interceptor.go
  src/pkg/registry/interceptor/readonly/interceptor_test.go
  src/registryctl/client/client.go
Labels: target/2.6.0, release-note/enhancement

#16984 Update ROADMAP.md
  ROADMAP.md
Labels: area/doc, kind/note, release-note/ignore-for-release

#17105 Enhancement Stop Scan Testcase
  tests/resources/Harbor-Pages/Project.robot
  tests/resources/Harbor-Pages/Project_Elements.robot
  tests/resources/TestCaseBody.robot
Labels: area/test automation/nightly-testing, release-note/infra

#17083 Unify retention schedule/task retrieve and update
  src/controller/retention/controller.go
  src/pkg/retention/models.go
  src/server/v2.0/handler/retention.go
Labels: target/2.6.0, release-note/ignore-for-release

#17106 Modify Build Package Workflow trigger condition
  .github/workflows/build-package.yml
Labels: area/build, release-note/infra
