Repository goharbor/harbor, pull requests merged in 2022-10, with the labels that each got.

#17635 Refresh base images
  .buildbaselog
Labels: release-note/infra

#17620 Add dependabot.yaml to enable PRs
  .github/dependabot.yml
Labels: release-note/infra

#17603 Add scan data export API test case
  tests/apitests/python/library/base.py
  tests/apitests/python/library/scan_data_export.py
  tests/apitests/python/test_scan_data_export.py
  tests/robot-cases/Group0-BAT/API_DB.robot
Labels: area/test automation/pytest-e2e, release-note/infra

#17581 test: add GetRedisURL to tests redis pkg and fix hardcoded redis url
  src/jobservice/job/impl/gc/garbage_collection_test.go
  src/jobservice/tests/utils.go
Labels: release-note/ignore-for-release

#17537 Add default project when pulling from dockerhub without project name
  src/server/middleware/repoproxy/proxy.go
Labels: release-note/enhancement, target/2.7.0

#17645 Fix ecr authorization token issue
  src/pkg/reg/adapter/awsecr/auth.go
Labels: release-note/ignore-for-release

#17665 [cherry-pick] Remove singularity testcase
  tests/apitests/python/test_push_sif_by_singularity.py
  tests/robot-cases/Group0-BAT/API_DB.robot
Labels: area/test automation/nightly-testing, release-note/infra

#17666 [cherry-pick] Remove singularity testcase
  tests/apitests/python/test_push_sif_by_singularity.py
  tests/robot-cases/Group0-BAT/API_DB.robot
Labels: area/test automation/nightly-testing, release-note/infra

#17662 Add labeling for dependa bot PRs
  .github/dependabot.yml
Labels: release-note/infra

#17663 Remove validator for username claim input
  src/portal/src/app/base/left-side-nav/config/auth/config-auth.component.html
Labels: release-note/update

#17628 Fix redirect url redirect_url when OIDC auth mode is enabled
  src/core/controllers/oidc.go
  src/portal/src/app/account/sign-in/sign-in.component.html
  src/portal/src/app/oidc-onboard/oidc-onboard.component.ts
Labels: release-note/enhancement

#17655 feat: optimize return value in pkg modifier
  src/common/http/modifier/auth/auth.go
  src/common/http/tls.go
Labels: release-note/ignore-for-release

#17675 [cherry-pick]Add export CVE UI testcase
  tests/resources/Harbor-Pages/HomePage_Elements.robot
  tests/resources/Harbor-Pages/Project.robot
  tests/resources/Harbor-Pages/Public_Elements.robot
  tests/resources/Harbor-Pages/Replication.robot
  tests/resources/Util.robot
  tests/robot-cases/Group1-Nightly/Common.robot
Labels: area/test automation/nightly-testing, release-note/infra

#17672 Add export CVE UI testcase
  tests/resources/Harbor-Pages/HomePage_Elements.robot
  tests/resources/Harbor-Pages/Project.robot
  tests/resources/Harbor-Pages/Public_Elements.robot
  tests/resources/Harbor-Pages/Replication.robot
  tests/resources/Util.robot
  tests/robot-cases/Group1-Nightly/Common.robot
Labels: area/test automation/nightly-testing, release-note/infra

#17681 feat: bump TRIVYVERSION to v0.32.1 and bump TRIVYADAPTERVERSION to v0.30.2
  Makefile
  make/harbor.yml.tmpl
  make/photon/prepare/templates/trivy-adapter/env.jinja
  make/photon/prepare/utils/configs.py
Labels: release-note/update, target/2.7.0

#17685 [cherry-pick] feat: bump TRIVYVERSION to v0.32.1 and bump TRIVYADAPTERVERSION to v0.30.2 (#17681)
  Makefile
  make/harbor.yml.tmpl
  make/photon/prepare/templates/trivy-adapter/env.jinja
  make/photon/prepare/utils/configs.py
Labels: release-note/update, target/2.6.2

#17690 bump up golang.org/x/text to v0.4.0
  src/go.mod
  src/go.sum
  src/vendor/golang.org/x/text/AUTHORS
  src/vendor/golang.org/x/text/CONTRIBUTORS
  src/vendor/golang.org/x/text/cases/trieval.go
  src/vendor/golang.org/x/text/encoding/internal/identifier/mib.go
  src/vendor/golang.org/x/text/internal/language/compact/tables.go
  src/vendor/golang.org/x/text/internal/language/lookup.go
  src/vendor/golang.org/x/text/internal/language/parse.go
  src/vendor/golang.org/x/text/internal/language/tables.go
  src/vendor/golang.org/x/text/internal/utf8internal/utf8internal.go
  src/vendor/golang.org/x/text/language/doc.go
  src/vendor/golang.org/x/text/language/go1_1.go
  src/vendor/golang.org/x/text/language/go1_2.go
  src/vendor/golang.org/x/text/language/match.go
  src/vendor/golang.org/x/text/language/parse.go
  src/vendor/golang.org/x/text/language/tables.go
  src/vendor/golang.org/x/text/runes/runes.go
  src/vendor/golang.org/x/text/secure/precis/profile.go
  src/vendor/golang.org/x/text/unicode/bidi/core.go
  src/vendor/golang.org/x/text/unicode/norm/forminfo.go
  src/vendor/golang.org/x/text/unicode/norm/normalize.go
  src/vendor/golang.org/x/text/unicode/norm/tables13.0.0.go
  src/vendor/golang.org/x/text/width/tables10.0.0.go
  src/vendor/golang.org/x/text/width/tables11.0.0.go
  src/vendor/golang.org/x/text/width/tables12.0.0.go
  src/vendor/golang.org/x/text/width/tables13.0.0.go
  src/vendor/golang.org/x/text/width/tables9.0.0.go
  src/vendor/modules.txt
Labels: release-note/update

#17693 bump up golang to 1.18.7
  .github/workflows/CI.yml
  .github/workflows/build-package.yml
  .github/workflows/conformance_test.yml
  CONTRIBUTING.md
  Makefile
  make/photon/chartserver/builder
  make/photon/registry/Dockerfile.binary
  make/photon/trivy-adapter/Dockerfile.binary
  make/photon/trivy-adapter/builder.sh
  tests/ci/distro_installer.sh
Labels: release-note/update

#17694 bump up golang to 1.19.2
  .github/workflows/CI.yml
  .github/workflows/build-package.yml
  .github/workflows/conformance_test.yml
  CONTRIBUTING.md
  Makefile
  make/photon/chartserver/builder
  make/photon/registry/Dockerfile.binary
  make/photon/trivy-adapter/Dockerfile.binary
  make/photon/trivy-adapter/builder.sh
  tests/ci/distro_installer.sh
Labels: release-note/update

#17689 bump up golang.org/x/text to v0.4.0
  src/go.mod
  src/go.sum
  src/vendor/golang.org/x/text/AUTHORS
  src/vendor/golang.org/x/text/CONTRIBUTORS
  src/vendor/golang.org/x/text/cases/trieval.go
  src/vendor/golang.org/x/text/encoding/internal/identifier/mib.go
  src/vendor/golang.org/x/text/internal/language/compact/tables.go
  src/vendor/golang.org/x/text/internal/language/lookup.go
  src/vendor/golang.org/x/text/internal/language/parse.go
  src/vendor/golang.org/x/text/internal/language/tables.go
  src/vendor/golang.org/x/text/internal/utf8internal/utf8internal.go
  src/vendor/golang.org/x/text/language/doc.go
  src/vendor/golang.org/x/text/language/go1_1.go
  src/vendor/golang.org/x/text/language/go1_2.go
  src/vendor/golang.org/x/text/language/match.go
  src/vendor/golang.org/x/text/language/parse.go
  src/vendor/golang.org/x/text/language/tables.go
  src/vendor/golang.org/x/text/runes/runes.go
  src/vendor/golang.org/x/text/secure/precis/profile.go
  src/vendor/golang.org/x/text/unicode/bidi/core.go
  src/vendor/golang.org/x/text/unicode/norm/forminfo.go
  src/vendor/golang.org/x/text/unicode/norm/normalize.go
  src/vendor/golang.org/x/text/unicode/norm/tables13.0.0.go
  src/vendor/golang.org/x/text/width/tables10.0.0.go
  src/vendor/golang.org/x/text/width/tables11.0.0.go
  src/vendor/golang.org/x/text/width/tables12.0.0.go
  src/vendor/golang.org/x/text/width/tables13.0.0.go
  src/vendor/golang.org/x/text/width/tables9.0.0.go
  src/vendor/modules.txt
Labels: release-note/update

#17687 Bump up version to v2.6.2
  VERSION
Labels: release-note/infra, target/2.6.2

#17701 Add check when adding project member
  src/controller/member/controller.go
  src/controller/member/controller_test.go
  src/testing/pkg/member/fake_member_manager.go
  src/testing/pkg/pkg.go
  src/testing/pkg/usergroup/fake_usergroup_manager.go
Labels: release-note/update, target/2.6.2

#17684 feat: log completion message when database migrated
  src/core/main.go
Labels: release-note/update, target/2.7.0

#17720 Refresh base images
  .buildbaselog
Labels: release-note/infra

#17721 (cherry-pick)Add check when adding project member
  src/controller/member/controller.go
  src/controller/member/controller_test.go
  src/testing/pkg/member/fake_member_manager.go
  src/testing/pkg/pkg.go
  src/testing/pkg/usergroup/fake_usergroup_manager.go
Labels: release-note/update

#17718 Fix broken links in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: release-note/ignore-for-release
