Repository goharbor/harbor, pull requests merged in 2022-08, with the labels that each got.

#16206 feature: Use RegisteredClaims instead of deprecated staruct StandardClaims
  src/core/service/token/authutils.go
  src/core/service/token/token_test.go
  src/pkg/token/claims/robot/robot.go
  src/pkg/token/claims/v2/claims.go
  src/pkg/token/claims/v2/claims_test.go
  src/pkg/token/token_test.go
Labels: release-note/update

#17284 Refresh base images
  .buildbaselog
Labels: release-note/ignore-for-release

#17175 Add purge audit log API test cases
  tests/apitests/python/library/base.py
  tests/apitests/python/library/purge.py
  tests/apitests/python/test_log_rotation.py
  tests/robot-cases/Group0-BAT/API_DB.robot
Labels: area/test automation/pytest-e2e, release-note/infra

#17286 Enable staticcheck
  src/.golangci.yaml
Labels: release-note/ignore-for-release

#17287 Upgrade Angular dev-tool package
  src/portal/package-lock.json
  src/portal/package.json
Labels: release-note/update

#17288 [cherry-pick]Add purge audit log API test cases
  tests/apitests/python/library/base.py
  tests/apitests/python/library/purge.py
  tests/apitests/python/test_log_rotation.py
  tests/robot-cases/Group0-BAT/API_DB.robot
Labels: area/test automation/pytest-e2e, target/2.6.0, release-note/infra

#17289 Return time.Time{} when cron string is empty
  src/common/utils/utils.go
Labels: release-note/update

#17290 (cherry-pick) Return time.Time{} when cron string is empty
  src/common/utils/utils.go
Labels: release-note/update

#17291 update image extra attributes author in labels
  src/controller/artifact/processor/image/manifest_v2.go
Labels: release-note/update

#17300 update session log level
  src/core/session/session.go
Labels: release-note/ignore-for-release

#17304 [cherry-pick] update session log level
  src/core/session/session.go
Labels: target/2.6.0, release-note/ignore-for-release

#17294 update image extra attributes author in labels
  src/controller/artifact/processor/image/manifest_v2.go
Labels: target/2.6.0, release-note/update

#17306 fix: distribution v2.8.0 tag does not match checksum
  src/go.mod
  src/go.sum
  src/vendor/github.com/docker/distribution/.mailmap
  src/vendor/github.com/docker/distribution/Dockerfile
  src/vendor/github.com/docker/distribution/README.md
  src/vendor/github.com/docker/distribution/docker-bake.hcl
  src/vendor/github.com/docker/distribution/version/version.go
  src/vendor/modules.txt
Labels: release-note/ignore-for-release

#17307 bumpup golang to v1.18.5
  .github/workflows/CI.yml
  .github/workflows/build-package.yml
  .github/workflows/conformance_test.yml
  CONTRIBUTING.md
  Makefile
  make/photon/chartserver/builder
  make/photon/registry/Dockerfile.binary
  make/photon/trivy-adapter/Dockerfile.binary
  make/photon/trivy-adapter/builder.sh
  tests/ci/distro_installer.sh
Labels: release-note/update

#17308 bumpup golang to v1.18.5 on release-2.6.0
  .github/workflows/CI.yml
  .github/workflows/build-package.yml
  .github/workflows/conformance_test.yml
  CONTRIBUTING.md
  Makefile
  make/photon/chartserver/builder
  make/photon/registry/Dockerfile.binary
  make/photon/trivy-adapter/Dockerfile.binary
  make/photon/trivy-adapter/builder.sh
  tests/ci/distro_installer.sh
Labels: target/2.6.0, release-note/update

#17309 bumpup golang to v1.17.13
  .github/workflows/CI.yml
  .github/workflows/build-package.yml
  .github/workflows/conformance_test.yml
  CONTRIBUTING.md
  Makefile
  make/photon/chartserver/builder
  make/photon/registry/Dockerfile.binary
  make/photon/trivy-adapter/Dockerfile.binary
  make/photon/trivy-adapter/builder.sh
  tests/ci/distro_installer.sh
Labels: release-note/update

#17313 [cherry-pick] fix: reduce the high db cpu usage for tag retention
  make/migrations/postgresql/0090_2.6.0_schema.up.sql
  src/controller/quota/controller.go
  src/controller/quota/options.go
  src/pkg/clients/core/client.go
  src/pkg/retention/dep/client.go
  src/pkg/retention/dep/client_test.go
  src/pkg/retention/job.go
  src/server/middleware/quota/quota.go
  src/server/middleware/security/utils.go
  src/server/middleware/security/utils_test.go
Labels: target/2.6.0, release-note/update

#17293 fix copy artifact accessory quota issue
  src/controller/artifact/controller.go
  src/server/middleware/quota/copy_artifact.go
Labels: release-note/update

#17296 fix: reduce the high db cpu usage for tag retention
  make/migrations/postgresql/0090_2.6.0_schema.up.sql
  src/controller/quota/controller.go
  src/controller/quota/options.go
  src/pkg/clients/core/client.go
  src/pkg/retention/dep/client.go
  src/pkg/retention/dep/client_test.go
  src/pkg/retention/job.go
  src/server/middleware/quota/quota.go
  src/server/middleware/security/utils.go
  src/server/middleware/security/utils_test.go
Labels: area/performance, area/tag-retention, release-note/update

#17315 fix copy artifact accessory quota issue
  src/controller/artifact/controller.go
  src/server/middleware/quota/copy_artifact.go
Labels: target/2.6.0, release-note/update

#17311 bump up distribution to v2.8.1+incompatible
  src/go.mod
  src/go.sum
  src/vendor/github.com/docker/distribution/.mailmap
  src/vendor/github.com/docker/distribution/Dockerfile
  src/vendor/github.com/docker/distribution/README.md
  src/vendor/github.com/docker/distribution/docker-bake.hcl
  src/vendor/github.com/docker/distribution/version/version.go
  src/vendor/modules.txt
Labels: target/2.6.0, release-note/update

#17312 fix: replication webhook lost when src namespace different with dest
  src/controller/event/handler/webhook/artifact/replication.go
  src/controller/event/handler/webhook/artifact/replication_test.go
Labels: area/webhook, release-note/update

#17317 docs: add helpful description for cache layer configurations
  make/harbor.yml.tmpl
Labels: release-note/ignore-for-release

#17319 [cherry-pick] docs: add helpful description for cache layer configurations
  make/harbor.yml.tmpl
Labels: target/2.6.0, release-note/ignore-for-release

#17318 [cherry-pick] fix: replication webhook lost when src namespace different with dest
  src/controller/event/handler/webhook/artifact/replication.go
  src/controller/event/handler/webhook/artifact/replication_test.go
Labels: target/2.6.0, release-note/update

#17321 Export CVE data Score column empty values
  src/jobservice/job/impl/scandataexport/scan_data_export_test.go
  src/pkg/scan/export/export_data_selector.go
  src/pkg/scan/export/export_data_selector_test.go
  src/pkg/scan/export/manager.go
  src/pkg/scan/export/manager_test.go
  src/pkg/scan/export/model.go
Labels: target/2.6.0, release-note/ignore-for-release

#17325 [cherry-pick] Export CVE data Score column empty values (#17321)
  src/jobservice/job/impl/scandataexport/scan_data_export_test.go
  src/pkg/scan/export/export_data_selector.go
  src/pkg/scan/export/export_data_selector_test.go
  src/pkg/scan/export/manager.go
  src/pkg/scan/export/manager_test.go
  src/pkg/scan/export/model.go
Labels: target/2.6.0, release-note/ignore-for-release, area/cve-export

#17328 _version:2.6.0 correction in migration yml jinja
  make/photon/prepare/migrations/version_2_6_0/harbor.yml.jinja
Labels: release-note/update

#17329 [cherry-pick]_version:2.6.0 correction in migration yml jinja
  make/photon/prepare/migrations/version_2_6_0/harbor.yml.jinja
Labels: release-note/ignore-for-release

#17336 [cherry-pick] fix: export cve for image manifest list
  api/v2.0/swagger.yaml
  src/jobservice/job/impl/scandataexport/scan_data_export.go
  src/jobservice/job/impl/scandataexport/scan_data_export_test.go
  src/pkg/scan/export/export_data_selector_test.go
  src/pkg/scan/export/filter_processor.go
  src/pkg/scan/export/manager.go
  src/pkg/scan/export/model.go
Labels: target/2.6.0, release-note/ignore-for-release, area/cve-export

#17333 fix: export cve for image manifest list
  api/v2.0/swagger.yaml
  src/jobservice/job/impl/scandataexport/scan_data_export.go
  src/jobservice/job/impl/scandataexport/scan_data_export_test.go
  src/pkg/scan/export/export_data_selector_test.go
  src/pkg/scan/export/filter_processor.go
  src/pkg/scan/export/manager.go
  src/pkg/scan/export/model.go
Labels: release-note/ignore-for-release, area/cve-export

#17341 fix: validate export cve request params
  src/jobservice/job/impl/scandataexport/scan_data_export.go
  src/jobservice/job/impl/scandataexport/scan_data_export_test.go
  src/server/v2.0/handler/scanexport.go
  src/server/v2.0/handler/scanexport_test.go
Labels: release-note/ignore-for-release, area/cve-export

#17343 project userid not found log level into debug
  src/controller/project/controller.go
Labels: release-note/ignore-for-release

#17345 [cherry-pick] fix: validate export cve request params
  src/jobservice/job/impl/scandataexport/scan_data_export.go
  src/jobservice/job/impl/scandataexport/scan_data_export_test.go
  src/server/v2.0/handler/scanexport.go
  src/server/v2.0/handler/scanexport_test.go
Labels: target/2.6.0, release-note/ignore-for-release, area/cve-export

#17357 Fix ui issues found in testing-day-round-2
  src/portal/src/app/base/left-side-nav/clearing-job/audit-log-purge/history/purge-history.component.ts
  src/portal/src/app/base/left-side-nav/clearing-job/audit-log-purge/set-job/set-job.component.html
  src/portal/src/app/base/left-side-nav/clearing-job/audit-log-purge/set-job/set-job.component.scss
  src/portal/src/app/base/left-side-nav/clearing-job/gc-page/gc/gc-history/gc-history.component.ts
  src/portal/src/app/base/left-side-nav/clearing-job/gc-page/gc/gc.component.html
  src/portal/src/app/base/left-side-nav/clearing-job/gc-page/gc/gc.component.scss
  src/portal/src/app/base/project/project-detail/project-detail.component.html
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: release-note/enhancement

#17310 Improve input validator for copy-component
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
  src/portal/src/app/shared/components/image-name-input/image-name-input.component.html
  src/portal/src/app/shared/components/image-name-input/image-name-input.component.ts
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
Labels: release-note/enhancement

#17358 [Cherry-pick]Fix ui issues found in testing-day-round-2
  src/portal/src/app/base/left-side-nav/clearing-job/audit-log-purge/history/purge-history.component.ts
  src/portal/src/app/base/left-side-nav/clearing-job/audit-log-purge/set-job/set-job.component.html
  src/portal/src/app/base/left-side-nav/clearing-job/audit-log-purge/set-job/set-job.component.scss
  src/portal/src/app/base/left-side-nav/clearing-job/gc-page/gc/gc-history/gc-history.component.ts
  src/portal/src/app/base/left-side-nav/clearing-job/gc-page/gc/gc.component.html
  src/portal/src/app/base/left-side-nav/clearing-job/gc-page/gc/gc.component.scss
  src/portal/src/app/base/project/project-detail/project-detail.component.html
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: release-note/enhancement

#17360 Bump up version to v2.5.4
  VERSION
Labels: release-note/ignore-for-release, target/2.5.4

#17373 [Cherry-pick]Improve unit test for sub-accessories component
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/sub-accessories/sub-accessories.component.spec.ts
Labels: release-note/enhancement

#17372 Improve unit test for sub-accessories component
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/sub-accessories/sub-accessories.component.spec.ts
Labels: release-note/enhancement

#17369 [cherry-pick]Update replication and trivy testcases
  tests/resources/Harbor-Pages/Replication.robot
  tests/resources/Harbor-Pages/Replication_Elements.robot
  tests/resources/Harbor-Pages/Vulnerability.robot
  tests/robot-cases/Group1-Nightly/Trivy.robot
Labels: release-note/infra

#17368 [cherry-pick]Update replication and trivy testcases
  tests/resources/Harbor-Pages/Replication.robot
  tests/resources/Harbor-Pages/Replication_Elements.robot
  tests/resources/Harbor-Pages/Vulnerability.robot
  tests/robot-cases/Group1-Nightly/Trivy.robot
Labels: release-note/infra

#17367 Update replication and trivy testcases
  tests/resources/Harbor-Pages/Replication.robot
  tests/resources/Harbor-Pages/Replication_Elements.robot
  tests/resources/Harbor-Pages/Vulnerability.robot
  tests/robot-cases/Group1-Nightly/Trivy.robot
Labels: release-note/infra

#17380 bump the base version
  VERSION
Labels: release-note/ignore-for-release

#17397 enhancement: add error log for create task
  src/pkg/task/execution.go
  src/pkg/task/task.go
Labels: release-note/update

#17403 [cherry-pick] enhancement: add error log for create task
  src/pkg/task/execution.go
  src/pkg/task/task.go
Labels: release-note/update, target/2.5.4

#17404 [cherry-pick] enhancement: add error log for create task
  src/pkg/task/execution.go
  src/pkg/task/task.go
Labels: release-note/update

#17398 add deprecation msg for chartmsuem and notary
  make/install.sh
Labels: release-note/ignore-for-release

#17303 Update to latest version of angular
  src/portal/PACKAGE.md
  src/portal/angular.json
  src/portal/package-lock.json
  src/portal/package.json
  src/portal/src/app/base/left-side-nav/interrogation-services/scanner/new-scanner-form/new-scanner-form.component.spec.ts
  src/portal/src/app/base/left-side-nav/interrogation-services/scanner/new-scanner-form/new-scanner-form.component.ts
  src/portal/src/app/base/left-side-nav/interrogation-services/scanner/new-scanner-modal/new-scanner-modal.component.spec.ts
  src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.ts
  src/portal/src/app/oidc-onboard/oidc-onboard.component.ts
  src/portal/src/app/shared/components/image-name-input/image-name-input.component.ts
  src/portal/tsconfig.json
Labels: area/ui-library, release-note/update

#17416 [cherry-pick]support docker compose v2
  make/common.sh
  make/install.sh
Labels: release-note/update

#17417 [cherry-pick]add deprecation msg for chartmsuem and notary
  make/install.sh
Labels: release-note/ignore-for-release

#17418 adjust golangci-lint installation hint
  Makefile
Labels: release-note/ignore-for-release

#17420 add an example of harbor systemd service
  tools/systemd/harbor.service
Labels: release-note/ignore-for-release

#17433 fix: correct description for export cve project parameter
  api/v2.0/swagger.yaml
Labels: release-note/ignore-for-release, area/cve-export

#17434 [cherry-pick] fix: correct description for export cve project parameter
  api/v2.0/swagger.yaml
Labels: target/2.6.0, release-note/ignore-for-release, area/cve-export

#17437 fix: validate the existence of project for export cve api
  src/server/v2.0/handler/scanexport.go
  src/server/v2.0/handler/scanexport_test.go
Labels: release-note/ignore-for-release, area/cve-export

#17441 [cherry-pick] fix: validate the existence of project for export cve api
  src/server/v2.0/handler/scanexport.go
  src/server/v2.0/handler/scanexport_test.go
Labels: target/2.6.0, release-note/ignore-for-release, area/cve-export

#17444 Bump up version to v1.10.13
  VERSION
Labels: release-note/ignore-for-release

#15770 Add autoescape parameter to jinja environments
  make/photon/prepare/migrations/version_1_10_0/__init__.py
  make/photon/prepare/migrations/version_1_9_0/__init__.py
  make/photon/prepare/migrations/version_2_0_0/__init__.py
  make/photon/prepare/migrations/version_2_1_0/__init__.py
  make/photon/prepare/migrations/version_2_2_0/__init__.py
  make/photon/prepare/migrations/version_2_3_0/__init__.py
  make/photon/prepare/migrations/version_2_4_0/__init__.py
  make/photon/prepare/utils/jinja.py
Labels: pending-for-more-info, release-note/ignore-for-release

#17428 Refactor swagger ui
  .gitignore
  make/photon/portal/Dockerfile
  make/photon/prepare/templates/portal/nginx.conf.jinja
  src/portal/.eslintrc.json
  src/portal/.stylelintrc.json
  src/portal/PACKAGE.md
  src/portal/README.md
  src/portal/angular.json
  src/portal/app-swagger-ui/README.md
  src/portal/app-swagger-ui/favicon.ico
  src/portal/app-swagger-ui/index.html
  src/portal/app-swagger-ui/package-lock.json
  src/portal/app-swagger-ui/package.json
  src/portal/app-swagger-ui/src/index.js
  src/portal/app-swagger-ui/webpack.dev.js.temp
  src/portal/app-swagger-ui/webpack.prod.js
  src/portal/docker-build/Dockerfile
  src/portal/docker-build/nginx.conf.example
  src/portal/package-lock.json
  src/portal/package.json
  src/portal/src/app/dev-center/dev-center-base.ts
  src/portal/src/app/dev-center/dev-center.component.html
  src/portal/src/app/dev-center/dev-center.component.scss
  src/portal/src/app/dev-center/dev-center.component.spec.ts
  src/portal/src/app/dev-center/dev-center.component.ts
  src/portal/src/app/dev-center/dev-center.module.ts
  src/portal/src/app/harbor-routing.module.ts
  src/portal/src/polyfills.ts
  src/portal/tsconfig.json
Labels: release-note/enhancement

#17447 Add WASM filter for artifacts list
  src/portal/src/app/base/project/repository/artifact/artifact.ts
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: release-note/enhancement

#17448 [Chrry-pick]Add WASM filter for artifacts list
  src/portal/src/app/base/project/repository/artifact/artifact.ts
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: release-note/enhancement

#17442 Update portal-base and nginx-base Dockerfile.base
  make/photon/nginx/Dockerfile.base
  make/photon/portal/Dockerfile.base
Labels: area/build, release-note/update

#17446 [cherry-pick]Update portal-base and nginx-base Dockerfile.base
  make/photon/nginx/Dockerfile.base
  make/photon/portal/Dockerfile.base
Labels: area/build, release-note/update, target/2.5.4

#17445 [cherry-pick]Update portal-base and nginx-base Dockerfile.base
  make/photon/nginx/Dockerfile.base
  make/photon/portal/Dockerfile.base
Labels: area/build, target/2.6.0, release-note/update

#17451 Change title for Swagger UI
  src/portal/app-swagger-ui/README.md
  src/portal/app-swagger-ui/index.html
Labels: release-note/update

#17464 Update replication filter_label xpath
  tests/resources/Harbor-Pages/Replication.robot
  tests/resources/Harbor-Pages/Replication_Elements.robot
Labels: area/test automation/nightly-testing, release-note/ignore-for-release

#17465 Add audit log and log rotation test cases
  tests/resources/Harbor-Pages/Log_Rotation.robot
  tests/resources/Harbor-Pages/Log_Rotation_Elements.robot
  tests/resources/Harbor-Pages/Logs.robot
  tests/resources/Harbor-Pages/Logs_Elements.robot
  tests/resources/Harbor-Pages/Project.robot
  tests/resources/Harbor-Pages/Project_Elements.robot
  tests/resources/Harbor-Pages/ToolKit.robot
  tests/resources/Harbor-Pages/UserProfile.robot
  tests/resources/Util.robot
  tests/robot-cases/Group1-Nightly/Common.robot
  tests/robot-cases/Group1-Nightly/Schedule.robot
Labels: area/test automation/nightly-testing, release-note/infra

#17470 Refresh base images
  .buildbaselog
Labels: release-note/ignore-for-release

#17471 Refresh base images
  .buildbaselog
Labels: release-note/ignore-for-release

#17439 Add autoescape parameter for 2.5 & 2.6 jinja
  make/photon/prepare/migrations/version_2_5_0/__init__.py
  make/photon/prepare/migrations/version_2_6_0/__init__.py
Labels: release-note/ignore-for-release

#17468 Remove preload for theme css files
  src/portal/scripts/generate-build-timestamp.js
  src/portal/src/index.html
Labels: release-note/update

#17457 Correct i18n key for zh-cn-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
Labels: release-note/update
