Repository goharbor/harbor, pull requests merged in 2022-01, with the labels that each got.

#16150 Cosign artifact api
  api/v2.0/swagger.yaml
  src/common/rbac/const.go
  src/common/rbac/project/rbac_role.go
  src/controller/artifact/controller.go
  src/controller/artifact/controller_test.go
  src/controller/artifact/helper_test.go
  src/controller/artifact/model.go
  src/pkg/accessory/dao/dao.go
  src/pkg/accessory/dao/dao_test.go
  src/pkg/accessory/manager.go
  src/pkg/accessory/manager_test.go
  src/pkg/accessory/model/accessory.go
  src/pkg/accessory/model/base/base.go
  src/pkg/accessory/model/base/base_test.go
  src/pkg/accessory/model/cosign/cosign_test.go
  src/server/v2.0/handler/artifact.go
  src/server/v2.0/handler/model/accessory.go
  src/server/v2.0/handler/model/artifact.go
  src/testing/pkg/accessory/dao/dao.go
  src/testing/pkg/accessory/manager.go
  src/testing/pkg/accessory/model/accessory.go
  src/testing/pkg/pkg.go
Labels: target/2.5.0, area/cosign

#16107 feat: async update artifact pull time and repository pull count
  src/controller/artifact/controller.go
  src/controller/artifact/controller_test.go
  src/controller/event/handler/internal/artifact.go
  src/controller/event/handler/internal/artifact_test.go
  src/controller/repository/controller.go
  src/controller/repository/controller_test.go
  src/pkg/artifact/dao/dao.go
  src/pkg/artifact/dao/dao_test.go
  src/pkg/artifact/manager.go
  src/pkg/artifact/manager_test.go
  src/pkg/repository/dao/dao.go
  src/pkg/repository/dao/dao_test.go
  src/pkg/repository/manager.go
  src/pkg/repository/manager_test.go
  src/testing/controller/repository/controller.go
  src/testing/pkg/artifact/manager.go
  src/testing/pkg/repository/dao/dao.go
  src/testing/pkg/repository/manager.go
Labels: area/performance, target/2.5.0

#16155 Add co-sign UI
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list-page.component.html
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list-page.component.spec.ts
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list-page.component.ts
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list-page.service.spec.ts
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list-page.service.ts
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-info/artifact-info.component.html
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-info/artifact-info.component.scss
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-info/artifact-info.component.spec.ts
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-info/artifact-info.component.ts
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.scss
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.spec.ts
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/sub-accessories/sub-accessories.component.html
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/sub-accessories/sub-accessories.component.scss
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/sub-accessories/sub-accessories.component.spec.ts
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/sub-accessories/sub-accessories.component.ts
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list.component.html
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list.component.spec.ts
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list.component.ts
  src/portal/src/app/base/project/repository/artifact/artifact-summary.component.html
  src/portal/src/app/base/project/repository/artifact/artifact-summary.component.ts
  src/portal/src/app/base/project/repository/artifact/artifact-tag/artifact-tag.component.html
  src/portal/src/app/base/project/repository/artifact/artifact.module.ts
  src/portal/src/app/base/project/repository/artifact/artifact.service.ts
  src/portal/src/app/base/project/repository/artifact/artifact.ts
  src/portal/src/app/shared/entities/shared.const.ts
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: target/2.5.0

#16191 Update Artifact size cell xpath
  tests/resources/Harbor-Pages/Replication.robot
Labels: area/test automation/ui-e2e, area/test automation/nightly-testing

#16094 feat: add failure-tolerance for gc
  src/jobservice/job/impl/gc/garbage_collection.go
Labels: area/gc, target/2.5.0

#16187 Cosign policy checker
  api/v2.0/swagger.yaml
  src/pkg/project/models/pro_meta.go
  src/pkg/project/models/project.go
  src/server/middleware/contenttrust/cosign.go
  src/server/middleware/contenttrust/cosign_test.go
  src/server/middleware/contenttrust/notary.go
  src/server/middleware/contenttrust/notary_test.go
  src/server/middleware/util/util.go
  src/server/middleware/vulnerable/vulnerable.go
  src/server/registry/route.go
  src/server/v2.0/handler/project_metadata.go
Labels: target/2.5.0, area/cosign

#16184 Add co-sign checkbox for project policy
  src/portal/src/app/base/project/project-config/project-policy-config/project-policy-config.component.html
  src/portal/src/app/base/project/project-config/project-policy-config/project-policy-config.component.ts
  src/portal/src/app/base/project/project-config/project-policy-config/project.ts
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.scss
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
  src/portal/src/app/shared/services/project.service.ts
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: target/2.5.0

#16219 Update Deployment security Notary xpath
  tests/resources/Harbor-Pages/Project-Config.robot
  tests/robot-cases/Group1-Nightly/Notary.robot
Labels: area/test automation/nightly-testing, target/2.5.0

#16208 Specify postgresql version to 13
  make/photon/db/Dockerfile.pg96
  tests/ci/api_run.sh
Labels: target/2.5.0

#16235 fix: Clean old version scan reports of trivy
  make/migrations/postgresql/0080_2.5.0_schema.up.sql
Labels: target/2.5.0

#16194 modify artifact copy api to support cosign
  src/controller/artifact/controller.go
  src/controller/artifact/controller_test.go
  src/pkg/accessory/manager.go
  src/pkg/accessory/manager_test.go
  src/server/registry/manifest.go
  src/server/v2.0/handler/artifact.go
  src/testing/controller/artifact/controller.go
  src/testing/pkg/accessory/manager.go
Labels: target/2.5.0, area/cosign

#16228 fix cosign conflict error on landing data
  src/server/middleware/cosign/cosign.go
  src/server/middleware/cosign/cosign_test.go
Labels: target/2.5.0

#16237 update pull policy code
  src/server/middleware/contenttrust/notary.go
  src/server/middleware/contenttrust/notary_test.go
  src/server/middleware/vulnerable/vulnerable.go
  src/server/middleware/vulnerable/vulnerable_test.go
Labels: target/2.5.0

#16238 Add cosign UI test case
  tests/resources/Cosign_Util.robot
  tests/resources/Harbor-Pages/Project-Artifact-Elements.robot
  tests/resources/Harbor-Pages/Project-Config.robot
  tests/resources/Harbor-Pages/Project.robot
  tests/resources/Util.robot
  tests/robot-cases/Group1-Nightly/Common.robot
  tests/robot-cases/Group1-Nightly/Notary.robot
  tests/test-engine-image/Dockerfile.common
  tests/test-engine-image/Dockerfile.ui_test
Labels: area/test automation/ui-e2e, area/test automation/nightly-testing, target/2.5.0

#16250 fix: add worker pool for execution sweep to limit workers
  src/pkg/task/execution.go
  src/pkg/task/execution_test.go
Labels: area/task-execution, target/2.5.0

#16247 Add cosign Artifact API test case
  tests/apitests/python/library/artifact.py
  tests/apitests/python/library/cosign.py
  tests/apitests/python/test_cosign_sign_artifact.py
  tests/ci/api_run.sh
  tests/robot-cases/Group0-BAT/API_DB.robot
  tests/test-engine-image/Dockerfile.api_test
Labels: area/test automation/pytest-e2e, target/2.5.0, area/cosign

#16257 Add copy accessory test case
  tests/resources/Docker-Util.robot
  tests/robot-cases/Group1-Nightly/Common.robot
Labels: area/test automation/ui-e2e, area/test automation/nightly-testing, target/2.5.0

#16261 Move removing old version scan reports of trivy to 2.4.2
  make/migrations/postgresql/0071_2.4.2_schema.up.sql
  make/migrations/postgresql/0080_2.5.0_schema.up.sql
Labels: target/2.5.0

#16263 Bump up spectral to v6.1.0
  .spectral.yaml
  Makefile
Labels: target/2.5.0

#16260 Group members lose access to push or see projects on Harbor
  src/pkg/usergroup/manager.go
  src/pkg/usergroup/manager_test.go
Labels: target/2.5.0

#16268 (cherry-pick) Group members lose access to push or see projects on Harbor
  src/pkg/usergroup/manager.go
  src/pkg/usergroup/manager_test.go
Labels: target/2.4.2

#16262 Remove old version scan reports of trivy
  make/migrations/postgresql/0071_2.4.2_schema.up.sql
Labels: target/2.4.2

#16281 Bump up version to 2.4.2
  VERSION
Labels: target/2.4.2

#16282 add cosign support in replication
  src/controller/artifact/model.go
  src/controller/artifact/model_test.go
  src/pkg/accessory/model/accessory.go
  src/pkg/accessory/model/accessory_test.go
  src/pkg/reg/adapter/harbor/v2/client.go
Labels: target/2.5.0, area/cosign

#16302 Specify postgresql version to 13
  make/photon/db/Dockerfile.base
Labels: area/build

#16306 [cherry-pick]Specify postgresql version to 13
  Makefile
  make/photon/db/Dockerfile.base
Labels: area/ci

#16305 [cherry-pick]Specify postgresql version to 13
  make/photon/db/Dockerfile.base
Labels: area/build

#16304 fix accessory lost tags
  src/controller/artifact/controller.go
Labels: target/2.5.0, area/cosign

#16313 Add replication cosign test case
  tests/resources/Harbor-Pages/Robot_Account.robot
  tests/robot-cases/Group1-Nightly/Replication.robot
Labels: area/test automation/nightly-testing, target/2.5.0

#16307 fix 16224
  src/controller/scan/base_controller.go
  src/controller/scan/base_controller_test.go
  src/controller/scan/checker.go
  src/controller/scan/checker_test.go
  src/server/v2.0/handler/scan.go
Labels: target/2.5.0
