Repository goharbor/harbor, pull requests merged in 2022-11, with the labels that each got.

#17602 feat: introduce the copy by chunk for replication
  api/v2.0/swagger.yaml
  make/migrations/postgresql/0100_2.7.0_schema.up.sql
  src/controller/artifact/abstractor_test.go
  src/controller/artifact/annotation/v1alpha1_test.go
  src/controller/artifact/controller_test.go
  src/controller/artifact/processor/base/manifest_test.go
  src/controller/artifact/processor/chart/chart_test.go
  src/controller/artifact/processor/cnab/cnab_test.go
  src/controller/artifact/processor/default_test.go
  src/controller/artifact/processor/image/manifest_v2_test.go
  src/controller/artifact/processor/wasm/wasm_test.go
  src/controller/icon/controller_test.go
  src/controller/proxy/local_test.go
  src/controller/registry/controller.go
  src/controller/replication/flow/copy.go
  src/controller/replication/flow/mock_adapter_test.go
  src/controller/replication/model/model.go
  src/controller/replication/transfer/chart/transfer.go
  src/controller/replication/transfer/chart/transfer_test.go
  src/controller/replication/transfer/image/transfer.go
  src/controller/replication/transfer/image/transfer_test.go
  src/controller/replication/transfer/options.go
  src/controller/replication/transfer/options_test.go
  src/controller/replication/transfer/transfer.go
  src/jobservice/job/impl/replication/replication.go
  src/jobservice/job/impl/replication/replication_test.go
  src/pkg/reg/adapter/adapter.go
  src/pkg/reg/adapter/harbor/base/adapter.go
  src/pkg/reg/adapter/harbor/base/adapter_test.go
  src/pkg/reg/model/registry.go
  src/pkg/registry/client.go
  src/pkg/replication/model/model.go
  src/pkg/systemartifact/manager_test.go
  src/server/v2.0/handler/registry.go
  src/server/v2.0/handler/replication.go
  src/testing/pkg/registry/client.go
  src/testing/pkg/registry/fake_registry_client.go
Labels: release-note/new-feature

#17617 Add copy_by-chunk checkbox for replication rule
  src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.html
  src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.scss
  src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.spec.ts
  src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.ts
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: release-note/new-feature

#17728 [cherry-pick] feat: introduce the copy by chunk for replication
  api/v2.0/swagger.yaml
  make/migrations/postgresql/0091_2.6.2_schema.up.sql
  src/controller/artifact/abstractor_test.go
  src/controller/artifact/annotation/v1alpha1_test.go
  src/controller/artifact/controller_test.go
  src/controller/artifact/processor/base/manifest_test.go
  src/controller/artifact/processor/chart/chart_test.go
  src/controller/artifact/processor/cnab/cnab_test.go
  src/controller/artifact/processor/default_test.go
  src/controller/artifact/processor/image/manifest_v2_test.go
  src/controller/artifact/processor/wasm/wasm_test.go
  src/controller/icon/controller_test.go
  src/controller/proxy/local_test.go
  src/controller/registry/controller.go
  src/controller/replication/flow/copy.go
  src/controller/replication/flow/mock_adapter_test.go
  src/controller/replication/model/model.go
  src/controller/replication/transfer/chart/transfer.go
  src/controller/replication/transfer/chart/transfer_test.go
  src/controller/replication/transfer/image/transfer.go
  src/controller/replication/transfer/image/transfer_test.go
  src/controller/replication/transfer/options.go
  src/controller/replication/transfer/options_test.go
  src/controller/replication/transfer/transfer.go
  src/jobservice/job/impl/replication/replication.go
  src/jobservice/job/impl/replication/replication_test.go
  src/pkg/reg/adapter/adapter.go
  src/pkg/reg/adapter/harbor/base/adapter.go
  src/pkg/reg/adapter/harbor/base/adapter_test.go
  src/pkg/reg/model/registry.go
  src/pkg/registry/client.go
  src/pkg/replication/model/model.go
  src/pkg/systemartifact/manager_test.go
  src/server/v2.0/handler/registry.go
  src/server/v2.0/handler/replication.go
  src/testing/pkg/registry/client.go
  src/testing/pkg/registry/fake_registry_client.go
Labels: release-note/update, target/2.6.2

#17726 fix: add human friendly message when export cve job failure
  src/controller/scandataexport/execution.go
  src/controller/scandataexport/execution_test.go
  src/jobservice/job/impl/scandataexport/scan_data_export.go
  src/jobservice/job/impl/scandataexport/scan_data_export_test.go
  src/server/v2.0/handler/scanexport.go
  src/server/v2.0/handler/scanexport_test.go
Labels: release-note/update, area/cve-export

#17727 [Cherry-pick]Add copy_by-chunk checkbox for replication rule
  src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.html
  src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.scss
  src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.spec.ts
  src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.ts
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: release-note/new-feature

#17729 [cherry-pick] fix: add human friendly message when export cve job failure
  src/controller/scandataexport/execution.go
  src/controller/scandataexport/execution_test.go
  src/jobservice/job/impl/scandataexport/scan_data_export.go
  src/jobservice/job/impl/scandataexport/scan_data_export_test.go
  src/server/v2.0/handler/scanexport.go
  src/server/v2.0/handler/scanexport_test.go
Labels: release-note/update, target/2.6.2

#17656 Add FOSSA badge and licence analysis
  README.md
Labels: release-note/infra

#17731 Add triggers and filters check for target changing under push mode
  src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.ts
Labels: release-note/update, target/2.7.0

#17732 [Cherry-pick]Add triggers and filters check for target changing under push mode
  src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.ts
Labels: release-note/update, target/2.6.2

#17735 fix: cherry pick 262 sql for migrations
  make/migrations/postgresql/0091_2.6.2_schema.up.sql
Labels: release-note/ignore-for-release

#17658 Add jobservice monitoring api list pool, worker and stop running task
  api/v2.0/swagger.yaml
  src/common/job/client.go
  src/common/rbac/const.go
  src/common/rbac/system/policies.go
  src/controller/jobmonitor/monitor.go
  src/controller/jobmonitor/monitor_test.go
  src/jobservice/api/handler.go
  src/jobservice/api/router.go
  src/jobservice/job/models.go
  src/pkg/jobmonitor/model.go
  src/pkg/jobmonitor/pool.go
  src/pkg/jobmonitor/worker.go
  src/pkg/task/mock_jobservice_client_test.go
  src/server/v2.0/handler/handler.go
  src/server/v2.0/handler/jobservice.go
  src/testing/job/mock_client.go
  src/testing/pkg/jobmonitor/job_service_monitor_client.go
  src/testing/pkg/jobmonitor/pool_manager.go
  src/testing/pkg/jobmonitor/worker_manager.go
  src/testing/pkg/pkg.go
Labels: release-note/new-feature

#17711 Remove email config page
  src/portal/src/app/base/left-side-nav/config/config.component.html
  src/portal/src/app/base/left-side-nav/config/config.module.ts
  src/portal/src/app/base/left-side-nav/config/email/config-email.component.html
  src/portal/src/app/base/left-side-nav/config/email/config-email.component.scss
  src/portal/src/app/base/left-side-nav/config/email/config-email.component.spec.ts
  src/portal/src/app/base/left-side-nav/config/email/config-email.component.ts
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: release-note/deprecation

#17744 Update the way for generating new cli secret
  src/portal/PACKAGE.md
  src/portal/package.json
  src/portal/src/app/base/account-settings/account-settings-modal-service.service.spec.ts
  src/portal/src/app/base/account-settings/account-settings-modal-service.service.ts
  src/portal/src/app/base/account-settings/account-settings-modal.component.html
  src/portal/src/app/base/account-settings/account-settings-modal.component.spec.ts
  src/portal/src/app/base/account-settings/account-settings-modal.component.ts
  src/portal/src/app/base/harbor-shell/harbor-shell.component.spec.ts
  src/portal/src/app/shared/units/shared.utils.ts
Labels: release-note/enhancement, target/2.7.0

#17740 add cli randomly for empty update
  src/server/v2.0/handler/user.go
  src/server/v2.0/handler/user_test.go
Labels: release-note/update, target/2.7.0

#17749 Fix wording in harbor issue template
  .github/ISSUE_TEMPLATE/issue.md
Labels: release-note/ignore-for-release

#17743 add cli randomly for empty update
  src/server/v2.0/handler/user.go
  src/server/v2.0/handler/user_test.go
Labels: release-note/enhancement, target/2.6.2

#17745 [Cherry-pick]Update the way for refreshing cli-secret
  src/portal/PACKAGE.md
  src/portal/package.json
  src/portal/src/app/base/account-settings/account-settings-modal-service.service.spec.ts
  src/portal/src/app/base/account-settings/account-settings-modal-service.service.ts
  src/portal/src/app/base/account-settings/account-settings-modal.component.html
  src/portal/src/app/base/account-settings/account-settings-modal.component.spec.ts
  src/portal/src/app/base/account-settings/account-settings-modal.component.ts
  src/portal/src/app/base/harbor-shell/harbor-shell.component.spec.ts
  src/portal/src/app/shared/units/shared.utils.ts
Labels: release-note/enhancement, target/2.6.2

#17738 Add JFrog Artifactory As Supported Proxy-Cache Registry Source
  make/photon/prepare/templates/core/env.jinja
  src/portal/src/app/base/left-side-nav/projects/create-project/create-project.component.ts
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: needs/test-case, release-note/enhancement, target/2.7.0

#17750 bump up golang to 1.18.8
  .github/workflows/CI.yml
  .github/workflows/build-package.yml
  .github/workflows/conformance_test.yml
  CONTRIBUTING.md
  Makefile
  make/photon/chartserver/builder
  make/photon/registry/Dockerfile.binary
  make/photon/trivy-adapter/Dockerfile.binary
  make/photon/trivy-adapter/builder.sh
  tests/ci/distro_installer.sh
Labels: release-note/update, target/2.6.2

#17751 bump up golang to 1.19.3
  .github/workflows/CI.yml
  .github/workflows/build-package.yml
  .github/workflows/conformance_test.yml
  CONTRIBUTING.md
  Makefile
  make/photon/chartserver/builder
  make/photon/registry/Dockerfile.binary
  make/photon/trivy-adapter/Dockerfile.binary
  make/photon/trivy-adapter/builder.sh
  tests/ci/distro_installer.sh
Labels: release-note/update, target/2.7.0

#17734 Improve css for tags column
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.scss
Labels: release-note/enhancement, target/2.7.0

#17762 Refresh base images
  .buildbaselog
Labels: release-note/ignore-for-release

#17763 Remove email config testcases
  tests/resources/Harbor-Pages/Configuration.robot
  tests/resources/Harbor-Pages/Configuration_Elements.robot
  tests/resources/Harbor-Pages/Verify.robot
  tests/robot-cases/Group1-Nightly/Common.robot
  tests/robot-cases/Group1-Nightly/Routing.robot
Labels: area/test automation/nightly-testing, release-note/infra

#17768 feat: support customize registry http client timeout
  src/pkg/registry/client.go
Labels: area/doc, release-note/update

#17752 Add OIDC group filter input
  src/portal/src/app/base/left-side-nav/config/auth/config-auth.component.html
  src/portal/src/app/base/left-side-nav/config/config.ts
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: release-note/enhancement, release-note/docs, target/2.7.0

#17736 Add OIDC group filter
  api/v2.0/swagger.yaml
  src/common/const.go
  src/lib/config/metadata/metadatalist.go
  src/lib/config/models/model.go
  src/lib/config/userconfig.go
  src/pkg/oidc/helper.go
  src/pkg/oidc/helper_test.go
Labels: release-note/enhancement, target/2.7.0

#17775 Fix permission issue for edit button of repo info
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-info/artifact-info.component.html
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-info/artifact-info.component.spec.ts
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-info/artifact-info.component.ts
Labels: release-note/update

#17619 fix permission denied error for non existing projects (#17586)
  src/server/v2.0/handler/base.go
Labels: release-note/update

#17793 Update e2e engine image
  tests/apitests/python/library/oras.py
  tests/ci/api_run.sh
  tests/resources/Harbor-Pages/Verify.robot
  tests/resources/Util.robot
  tests/test-engine-image/Dockerfile.api_test
  tests/test-engine-image/Dockerfile.common
  tests/test-engine-image/Dockerfile.ui_test
  tests/test-engine-image/build.sh
Labels: area/test automation/nightly-testing, release-note/infra

#17712 Remove email configuration
  api/v2.0/legacy_swagger.yaml
  api/v2.0/swagger.yaml
  src/controller/config/test/controller_test.go
  src/core/api/email.go
  src/core/api/email_test.go
  src/core/api/harborapi_test.go
  src/lib/config/metadata/metadatalist.go
  src/lib/config/models/model.go
  src/lib/config/test/userconfig_test.go
  src/lib/config/userconfig.go
  src/pkg/config/db/manager_test.go
  src/server/v2.0/route/legacy.go
Labels: release-note/deprecation

#17784 revise the gomod path
  .github/dependabot.yml
Labels: release-note/ignore-for-release

#17779 fix: pre check notification enable for artifact webhook
  src/controller/event/handler/webhook/artifact/artifact.go
Labels: release-note/update, target/2.7.0

#17795 Add metrics test case
  tests/apitests/python/library/base.py
  tests/apitests/python/library/statistic.py
  tests/apitests/python/library/system_info.py
  tests/apitests/python/test_verify_metrics_enabled.py
Labels: area/test automation/nightly-testing, release-note/infra

#17767 feat: support customize session timeout
  api/v2.0/swagger.yaml
  src/common/const.go
  src/core/session/session.go
  src/core/session/session_test.go
  src/lib/config/metadata/metadatalist.go
  src/lib/config/userconfig.go
Labels: release-note/new-feature, target/2.7.0

#17769 Add session timeout input
  src/portal/src/app/base/left-side-nav/config/config.ts
  src/portal/src/app/base/left-side-nav/config/system/system-settings.component.html
  src/portal/src/app/base/left-side-nav/config/system/system-settings.component.ts
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: release-note/new-feature, target/2.7.0

#17708 Sort group search result by most match order
  src/server/v2.0/handler/usergroup.go
  src/server/v2.0/handler/usergroup_test.go
Labels: release-note/enhancement, target/2.7.0

#17753 Add auto-assignee for new PRs
  .github/auto-assignees.yml
  .github/workflows/auto_assign_prs.yml
Labels: release-note/community, release-note/enhancement, release-note/infra

#17814 Update cve export UI
  src/portal/src/app/shared/components/operation/operation.component.ts
Labels: release-note/enhancement, target/2.7.0

#17817 update golangci-lint for golang1.19
  src/.golangci.yaml
  src/chartserver/cache.go
  src/common/api/base.go
  src/controller/artifact/processor/default.go
  src/controller/p2p/preheat/controller.go
  src/jobservice/job/impl/purge/purge.go
  src/jobservice/job/impl/sample/job.go
  src/jobservice/job/impl/scandataexport/scan_data_export.go
  src/jobservice/logger/base.go
  src/lib/orm/metadata.go
  src/lib/orm/orm.go
  src/lib/orm/query.go
  src/pkg/accessory/model/accessory.go
  src/pkg/cached/base_manager.go
  src/pkg/p2p/preheat/provider/driver.go
  src/pkg/reg/adapter/googlegcr/adapter.go
  src/pkg/scan/rest/v1/models.go
  src/server/registry/tag.go
  src/server/v2.0/handler/auditlog.go
  src/server/v2.0/handler/model/gc.go
  src/server/v2.0/handler/notification_job.go
  src/server/v2.0/handler/notification_policy.go
  src/server/v2.0/handler/preheat.go
  src/server/v2.0/handler/purge.go
  src/server/v2.0/handler/scan_all.go
  src/server/v2.0/handler/scanexport.go
  tests/ci/ut_install.sh
Labels: release-note/ignore-for-release

#17816 fix: skip to push system artifact for empty CSV file
  src/controller/scandataexport/execution.go
  src/jobservice/job/impl/scandataexport/scan_data_export.go
  src/jobservice/job/impl/scandataexport/scan_data_export_test.go
  src/pkg/scan/export/constants.go
  src/server/v2.0/handler/scanexport.go
  src/server/v2.0/handler/scanexport_test.go
  tests/apitests/python/test_scan_data_export.py
Labels: release-note/update, target/2.7.0

#17823 fix: refine the quay adapter UT
  src/replication/adapter/quayio/adapter_test.go
Labels: release-note/ignore-for-release

#17789 Fix issue related to redhat registry proxy cache
  src/controller/proxy/controller.go
  src/controller/proxy/manifestcache.go
Labels: release-note/update, target/2.7.0

#17780 Modify audit log forward test case
  tests/apitests/python/test_audit_log_forward.py
  tests/apitests/python/testutils.py
  tests/ci/api_run.sh
  tests/resources/APITest-Util.robot
  tests/resources/Harbor-Pages/Configuration.robot
  tests/resources/Harbor-Pages/Logs.robot
  tests/resources/SeleniumUtil.robot
  tests/resources/Util.robot
  tests/robot-cases/Group0-BAT/API_DB.robot
  tests/robot-cases/Group1-Nightly/Common.robot
Labels: release-note/infra

#17822 Bump up version to v1.10.15
  VERSION
Labels: release-note/infra

#17824 (cherry-pick) Fix issue related to redhat registry proxy cache
  src/controller/proxy/controller.go
  src/controller/proxy/manifestcache.go
Labels: release-note/update

#17829 Updated German Translation
  src/portal/src/i18n/lang/de-de-lang.json
Labels: release-note/update

#17825 (cherry-pick) Fix issue related to redhat registry proxy cache
  src/controller/proxy/controller.go
  src/controller/proxy/manifestcache.go
Labels: release-note/enhancement

#17838 add migration script for 2.7
  make/harbor.yml.tmpl
  make/photon/prepare/commands/migrate.py
  make/photon/prepare/migrations/__init__.py
  make/photon/prepare/migrations/version_2_7_0/__init__.py
  make/photon/prepare/migrations/version_2_7_0/harbor.yml.jinja
Labels: release-note/update

#17844 Add Cron, CronType and Update Time for schedule
  api/v2.0/swagger.yaml
  src/server/v2.0/handler/jobservice.go
Labels: release-note/ignore-for-release

#17847 Fix setup gcloud error
  .github/workflows/build-package.yml
  .github/workflows/publish_release.yml
Labels: release-note/infra

#17848 [cherry-pick]Fix setup gcloud error
  .github/workflows/build-package.yml
  .github/workflows/publish_release.yml
Labels: release-note/infra

#17849 [cherry-pick]Fix setup gcloud error
  .github/workflows/build-package.yml
  .github/workflows/publish_release.yml
Labels: release-note/infra

#17851 Update schedule list
  src/portal/src/app/base/left-side-nav/job-service-dashboard/job-service-dashboard.interface.ts
  src/portal/src/app/base/left-side-nav/job-service-dashboard/schedule-list/schedule-list.component.html
  src/portal/src/app/base/left-side-nav/job-service-dashboard/schedule-list/schedule-list.component.ts
  src/portal/src/app/shared/components/cron-schedule/cron-schedule.component.ts
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: release-note/update

#17854 Update UI-UT cases
  src/portal/package-lock.json
  src/portal/src/app/base/left-side-nav/log/recent-log.component.spec.ts
  src/portal/src/app/base/project/project-log/audit-log.component.spec.ts
Labels: release-note/ignore-for-release

#17842 Stop Pending Job cannot update status
  src/common/job/client.go
  src/controller/jobmonitor/monitor.go
  src/pkg/jobmonitor/redis.go
Labels: release-note/ignore-for-release, target/2.7.0

#17841 Increase golangci-lint timeout value
  src/.golangci.yaml
Labels: release-note/ignore-for-release

#17850 [cherry-pick]Fix setup gcloud error
  .github/workflows/build-package.yml
Labels: release-note/infra

#17818 add new workflow for nightly image scan
  .github/workflows/nightly-trivy-scan.yml
Labels: release-note/infra

#17877 Keep CheckInAt time empty when it is empty
  src/server/v2.0/handler/jobservice.go
Labels: release-note/ignore-for-release, target/2.7.0

#17878 Remove job parameters and schedule extra attribute
  api/v2.0/swagger.yaml
  src/pkg/jobmonitor/model.go
  src/server/v2.0/handler/jobservice.go
Labels: release-note/ignore-for-release, target/2.7.0

#17883 Refresh base images
  .buildbaselog
Labels: release-note/ignore-for-release

#17884 Update i18n for group filter and schedule list
  src/portal/src/app/base/left-side-nav/job-service-dashboard/schedule-list/schedule-list.component.html
  src/portal/src/app/base/left-side-nav/job-service-dashboard/schedule-list/schedule-list.component.ts
  src/portal/src/app/base/left-side-nav/job-service-dashboard/worker-list/worker-list.component.html
  src/portal/src/app/base/left-side-nav/job-service-dashboard/worker-list/worker-list.component.scss
  src/portal/src/app/base/left-side-nav/job-service-dashboard/worker-list/worker-list.component.ts
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: release-note/update

#16641 add parameters for PostgreSQL
  make/harbor.yml.tmpl
  make/photon/prepare/templates/core/env.jinja
  make/photon/prepare/templates/exporter/env.jinja
  make/photon/prepare/utils/configs.py
  src/cmd/exporter/main.go
  src/common/const.go
  src/common/dao/base.go
  src/common/dao/pgsql.go
  src/common/models/database.go
  src/lib/config/metadata/metadatalist.go
  src/lib/config/metadata/type.go
  src/lib/config/metadata/value.go
  src/lib/config/metadata/value_test.go
  src/lib/config/systemconfig.go
  src/pkg/config/manager.go
Labels: release-note/enhancement, target/2.7.0
