Repository goharbor/harbor, pull requests merged in 2022-12, with the labels that each got.

#17894 Update jobservice dashboard UI
  src/portal/src/app/base/left-side-nav/job-service-dashboard/job-service-dashboard-shared-data.service.spec.ts
  src/portal/src/app/base/left-side-nav/job-service-dashboard/job-service-dashboard-shared-data.service.ts
  src/portal/src/app/base/left-side-nav/job-service-dashboard/job-service-dashboard.interface.ts
  src/portal/src/app/base/left-side-nav/job-service-dashboard/job-service-dashboard.module.ts
  src/portal/src/app/base/left-side-nav/job-service-dashboard/pending-job-card/pending-job-card.component.html
  src/portal/src/app/base/left-side-nav/job-service-dashboard/pending-job-card/pending-job-card.component.scss
  src/portal/src/app/base/left-side-nav/job-service-dashboard/pending-job-card/pending-job-card.component.spec.ts
  src/portal/src/app/base/left-side-nav/job-service-dashboard/pending-job-card/pending-job-card.component.ts
  src/portal/src/app/base/left-side-nav/job-service-dashboard/pending-job-list/pending-job-list.component.html
  src/portal/src/app/base/left-side-nav/job-service-dashboard/pending-job-list/pending-job-list.component.spec.ts
  src/portal/src/app/base/left-side-nav/job-service-dashboard/pending-job-list/pending-job-list.component.ts
  src/portal/src/app/base/left-side-nav/job-service-dashboard/schedule-card/schedule-card.component.html
  src/portal/src/app/base/left-side-nav/job-service-dashboard/schedule-card/schedule-card.component.scss
  src/portal/src/app/base/left-side-nav/job-service-dashboard/schedule-card/schedule-card.component.spec.ts
  src/portal/src/app/base/left-side-nav/job-service-dashboard/schedule-card/schedule-card.component.ts
  src/portal/src/app/base/left-side-nav/job-service-dashboard/schedule-list/schedule-list.component.html
  src/portal/src/app/base/left-side-nav/job-service-dashboard/schedule-list/schedule-list.component.spec.ts
  src/portal/src/app/base/left-side-nav/job-service-dashboard/schedule-list/schedule-list.component.ts
  src/portal/src/app/base/left-side-nav/job-service-dashboard/worker-card/worker-card.component.html
  src/portal/src/app/base/left-side-nav/job-service-dashboard/worker-card/worker-card.component.spec.ts
  src/portal/src/app/base/left-side-nav/job-service-dashboard/worker-card/worker-card.component.ts
  src/portal/src/app/base/left-side-nav/job-service-dashboard/worker-list/worker-list.component.html
  src/portal/src/app/base/left-side-nav/job-service-dashboard/worker-list/worker-list.component.spec.ts
  src/portal/src/app/base/left-side-nav/job-service-dashboard/worker-list/worker-list.component.ts
  src/portal/src/app/services/event-service/event.service.ts
Labels: release-note/update

#17875 Update the execution status after tasks stopped
  src/controller/jobmonitor/monitor.go
  src/pkg/task/dao/task.go
  src/pkg/task/dao/task_test.go
  src/pkg/task/mock_task_dao_test.go
  src/pkg/task/mock_task_manager_test.go
  src/pkg/task/task.go
  src/testing/pkg/task/manager.go
Labels: release-note/ignore-for-release, target/2.7.0

#17897 Change inputs type from text to number
  src/portal/src/app/base/harbor-shell/harbor-shell.component.html
  src/portal/src/app/base/harbor-shell/harbor-shell.component.ts
  src/portal/src/app/base/left-side-nav/config/system/system-settings.component.html
  src/portal/src/app/base/left-side-nav/config/system/system-settings.component.scss
  src/portal/src/app/base/left-side-nav/config/system/system-settings.component.ts
Labels: release-note/update

#17902 update system artifact schedult timeout
  src/core/main.go
Labels: release-note/update, target/2.7.0

#17903 fix: align some configuration api fields validation with frontend
  src/common/const.go
  src/controller/config/controller.go
  src/controller/config/controller_test.go
Labels: release-note/update, target/2.7.0

#17907 Refresh base images
  .buildbaselog
Labels: release-note/ignore-for-release

#17910 bump up golang.org/x/net to v0.2.0
  src/go.mod
  src/go.sum
  src/vendor/golang.org/x/net/http2/headermap.go
  src/vendor/golang.org/x/net/http2/hpack/static_table.go
  src/vendor/golang.org/x/net/http2/hpack/tables.go
  src/vendor/golang.org/x/net/http2/server.go
  src/vendor/golang.org/x/net/http2/transport.go
  src/vendor/golang.org/x/sys/unix/sockcmsg_unix.go
  src/vendor/golang.org/x/sys/unix/syscall_linux.go
  src/vendor/golang.org/x/term/terminal.go
  src/vendor/modules.txt
Labels: release-note/update

#17909 bump up golang.org/x/net to v0.2.0
  src/go.mod
  src/go.sum
  src/vendor/golang.org/x/net/http2/headermap.go
  src/vendor/golang.org/x/net/http2/hpack/static_table.go
  src/vendor/golang.org/x/net/http2/hpack/tables.go
  src/vendor/golang.org/x/net/http2/server.go
  src/vendor/golang.org/x/net/http2/transport.go
  src/vendor/golang.org/x/sys/unix/sockcmsg_unix.go
  src/vendor/golang.org/x/sys/unix/syscall_linux.go
  src/vendor/golang.org/x/term/terminal.go
  src/vendor/modules.txt
Labels: release-note/update

#17914 Bump the auto assignees to 3
  .github/auto-assignees.yml
Labels: release-note/infra

#17915 controller/robot: use global regexp vars
  src/controller/robot/controller.go
Labels: release-note/update

#15916 fix dragonfly response when p2p preheat
  src/pkg/p2p/preheat/provider/dragonfly.go
  src/pkg/p2p/preheat/provider/dragonfly_test.go
  src/pkg/p2p/preheat/provider/mock.go
Labels: area/P2P-Distribution, release-note/update

#17921 bump up golang 1.17.13 for release-2.4.0
  .github/workflows/CI.yml
  .github/workflows/build-package.yml
  .github/workflows/conformance_test.yml
  CONTRIBUTING.md
  Makefile
  make/photon/chartserver/builder
  make/photon/registry/Dockerfile.binary
  make/photon/trivy-adapter/Dockerfile.binary
  make/photon/trivy-adapter/builder.sh
  tests/ci/distro_installer.sh
Labels: release-note/update

#17918 fix the setting of data slice length for tablewriter
  src/pkg/retention/job.go
Labels: release-note/update

#17913 remove artifact_blob with aritfact deletion
  src/jobservice/job/impl/gc/garbage_collection.go
Labels: release-note/update

#17936 Update the log information in proxy cache
  src/pkg/p2p/preheat/provider/dragonfly.go
  src/server/middleware/repoproxy/proxy.go
Labels: release-note/update, target/2.7.0

#17946 Avoid internal error in the UI when reset a schedule
  src/pkg/scheduler/scheduler.go
  src/pkg/task/execution.go
Labels: release-note/update

#17959 remove the redundant data from table artifact_blob
  make/migrations/postgresql/0100_2.7.0_schema.up.sql
Labels: release-note/update, target/2.7.0

#17945 (cherry-pick) Update the log information in proxy cache
  src/server/middleware/repoproxy/proxy.go
Labels: release-note/update, target/2.7.0

#17960 (cherry-pick) Avoid internal error in the UI when reset a schedule
  src/pkg/scheduler/scheduler.go
  src/pkg/task/execution.go
Labels: release-note/update, target/2.7.0

#17963 Refresh the base images
  .buildbaselog
Labels: release-note/infra

#17965 [Cherry-pick]Fix some UI issues
  src/portal/src/app/base/left-side-nav/job-service-dashboard/job-service-dashboard-shared-data.service.ts
  src/portal/src/app/base/left-side-nav/job-service-dashboard/pending-job-card/pending-job-card.component.scss
  src/portal/src/app/base/left-side-nav/job-service-dashboard/schedule-card/schedule-card.component.scss
  src/portal/src/app/base/left-side-nav/replication/replication/replication.component.ts
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: release-note/update

#17964 Fix some UI issues
  src/portal/src/app/base/left-side-nav/job-service-dashboard/job-service-dashboard-shared-data.service.ts
  src/portal/src/app/base/left-side-nav/job-service-dashboard/pending-job-card/pending-job-card.component.scss
  src/portal/src/app/base/left-side-nav/job-service-dashboard/schedule-card/schedule-card.component.scss
  src/portal/src/app/base/left-side-nav/replication/replication/replication.component.ts
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: release-note/update

#17972 Bump up version to v2.5.5
  VERSION
Labels: release-note/infra

#17971 Bump up version to v2.4.4
  Makefile
  VERSION
Labels: release-note/infra

#17973 [cherry-pick]Update portal-base and nginx-base Dockerfile.base (#17442)
  .buildbaselog
  make/photon/nginx/Dockerfile.base
  make/photon/portal/Dockerfile.base
Labels: release-note/infra

#17937 remove the redundant data from table artifact_blob
  make/migrations/postgresql/0110_2.8.0_schema.up.sql
Labels: release-note/update

#17977 [Cherry-pick] fix: upgrade trivy version to v0.35.0 and trivy-adapter version to v0.30.3
  Makefile
Labels: release-note/update

#17976 fix: upgrade trivy version to v0.35.0 and trivy-adapter version to v0.30.3
  Makefile
Labels: release-note/update

#17978 [cherry-pick] fix: upgrade trivy version to v0.35.0 and trivy-adapter version to v0.30.3
  Makefile
Labels: release-note/update

#17979 [Cherry-pick] fix: upgrade trivy version to v0.35.0 and trivy-adapter version to v0.30.3
  Makefile
Labels: release-note/update

#17980 [Cherry-pick] fix: upgrade trivy version to v0.35.0 and trivy-adapter version to v0.30.3
  Makefile
Labels: release-note/update

#17989 Refresh base images on release-2.5.0
  .buildbaselog
Labels: release-note/infra

#17987 [cherry-pick] fix: fix the time duration type duplicated parse for config
  src/lib/config/metadata/type.go
  src/lib/config/metadata/type_test.go
  src/lib/config/metadata/value.go
Labels: release-note/ignore-for-release, target/2.7.0

#17983 Update RELEASE and CONTRIBUTING with main instead of master
  CONTRIBUTING.md
  RELEASES.md
Labels: release-note/community

#17986 fix: Don't supress redis error messages to make debugging easier
  src/jobservice/job/impl/gc/util.go
Labels: release-note/update

#17996 Bump up golang 1.19.4 for release 2.7.0
  .github/workflows/CI.yml
  .github/workflows/build-package.yml
  .github/workflows/conformance_test.yml
  CONTRIBUTING.md
  Makefile
  make/photon/chartserver/builder
  make/photon/registry/Dockerfile.binary
  make/photon/trivy-adapter/Dockerfile.binary
  make/photon/trivy-adapter/builder.sh
  tests/ci/distro_installer.sh
Labels: release-note/update

#17997 bump up golang to 1.19.4 for main
  .github/workflows/CI.yml
  .github/workflows/build-package.yml
  .github/workflows/conformance_test.yml
  CONTRIBUTING.md
  Makefile
  make/photon/chartserver/builder
  make/photon/registry/Dockerfile.binary
  make/photon/trivy-adapter/Dockerfile.binary
  make/photon/trivy-adapter/builder.sh
  tests/ci/distro_installer.sh
Labels: release-note/update

#18002 fix: upgrade TRIVYADAPTERVERSION to v0.30.5
  Makefile
Labels: release-note/update

#18003 [Cherry-pick] fix: upgrade TRIVYADAPTERVERSION to v0.30.5
  Makefile
Labels: release-note/update

#17975 Skip CI tests when *.md modifications are made
  .github/workflows/CI.yml
  .github/workflows/codeql-analysis.yml
Labels: release-note/infra

#18009 Fix: Small typos in harbor.yml.tmpl
  make/harbor.yml.tmpl
Labels: release-note/ignore-for-release

#17916 i18n: fix password+secret limit tooltips
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: release-note/update

#18022 Switch listUsers to searchUsers for adding project member
  src/portal/src/app/base/project/member/add-group/add-group.component.ts
  src/portal/src/app/base/project/member/add-member/add-member.component.spec.ts
  src/portal/src/app/base/project/member/add-member/add-member.component.ts
Labels: release-note/update
