Repository goharbor/harbor, pull requests merged in 2023-01, with the labels that each got.

#18023 fix purge info typo
  src/jobservice/job/impl/purge/purge.go
Labels: release-note/ignore-for-release

#18040 Refresh the base image on release-2.6.0
  .buildbaselog
Labels: release-note/infra

#18045 Bump up version to v2.6.3
  VERSION
Labels: release-note/infra

#18041 Refresh the base image on release-2.5.0
  .buildbaselog
Labels: release-note/infra

#18048 bump up helm/v3/pkg to v3.10.3 on release-2.6.0
  src/go.mod
  src/go.sum
  src/vendor/helm.sh/helm/v3/pkg/chartutil/create.go
  src/vendor/helm.sh/helm/v3/pkg/chartutil/jsonschema.go
  src/vendor/helm.sh/helm/v3/pkg/repo/index.go
  src/vendor/helm.sh/helm/v3/pkg/repo/repo.go
  src/vendor/modules.txt
Labels: release-note/update

#18055 [Cherry-pick] Bump up TRIVYADAPTERVERSION to v0.30.6
  Makefile
Labels: release-note/update

#18056 [Cherry-pick] Bump up TRIVYADAPTERVERSION to v0.30.6
  Makefile
Labels: release-note/update

#18050 bump up helm/v3/pkg to v3.10.3 on main
  src/go.mod
  src/go.sum
  src/vendor/helm.sh/helm/v3/pkg/chartutil/create.go
  src/vendor/helm.sh/helm/v3/pkg/chartutil/jsonschema.go
  src/vendor/helm.sh/helm/v3/pkg/repo/index.go
  src/vendor/helm.sh/helm/v3/pkg/repo/repo.go
  src/vendor/modules.txt
Labels: release-note/update

#18062 Bump up version to v2.8.0
  VERSION
Labels: release-note/infra

#18061 add 2.7.0 tag to nightly trivy scan
  .github/workflows/nightly-trivy-scan.yml
Labels: area/ci, release-note/ignore-for-release

#18059 Upgrade Angular and Clarity to the latest version
  .github/workflows/CI.yml
  make/photon/portal/Dockerfile
  src/portal/.browserslistrc
  src/portal/PACKAGE.md
  src/portal/angular.json
  src/portal/package-lock.json
  src/portal/package.json
  src/portal/src/app/harbor-routing.module.ts
  src/portal/src/global.scss
  src/portal/src/main.ts
  src/portal/src/polyfills.ts
  src/portal/src/test.ts
  src/portal/tsconfig.app.json
  src/portal/tsconfig.json
  src/portal/tsconfig.spec.json
Labels: release-note/update

#18052 Bump up TRIVYADAPTERVERSION to v0.30.6
  Makefile
Labels: release-note/update

#18054 [Cherry-pick] Bump up TRIVYADAPTERVERSION to v0.30.6
  Makefile
Labels: release-note/update

#18072 update trivy scan ci image tag to v2.7.0-dev
  .github/workflows/nightly-trivy-scan.yml
Labels: release-note/ignore-for-release

#18070 Update datePicker component
  src/portal/src/app/account/sign-in/sign-in.component.spec.ts
  src/portal/src/app/base/left-side-nav/config/security/security.component.spec.ts
  src/portal/src/app/base/left-side-nav/config/security/security.component.ts
  src/portal/src/app/base/project/project-log/audit-log.component.spec.ts
  src/portal/src/app/shared/components/datetime-picker/date-validator.directive.ts
  src/portal/src/app/shared/components/datetime-picker/datetime-picker.component.scss
  src/portal/src/app/shared/components/datetime-picker/datetime-picker.component.spec.ts
  src/portal/src/app/shared/components/datetime-picker/datetime-picker.component.ts
  src/portal/src/app/shared/components/navigator/navigator.component.html
  src/portal/src/app/shared/components/navigator/navigator.component.spec.ts
  src/portal/src/app/shared/components/navigator/navigator.component.ts
  src/portal/src/app/shared/directives/date-validator.directive.ts
  src/portal/src/app/shared/entities/shared.const.ts
  src/portal/src/app/shared/shared.module.ts
  src/portal/src/app/shared/units/utils.ts
Labels: doc-impact, release-note/enhancement, target/2.8.0

#18071 fix: resolve the golint issues of source code
  src/common/http/transport.go
  src/common/models/user.go
  src/controller/artifact/controller.go
  src/controller/replication/transfer/iothrottler.go
  src/controller/robot/model.go
  src/lib/config/metadata/type.go
  src/lib/config/trace.go
  src/lib/endpoint_test.go
  src/lib/errors/const.go
  src/lib/orm/orm.go
  src/lib/strings.go
  src/lib/trace/config.go
  src/lib/trace/trace.go
  src/pkg/accessory/manager.go
  src/pkg/accessory/model/accessory.go
  src/pkg/project/models/project.go
  src/pkg/reg/adapter/harbor/base/client.go
  src/pkg/reg/model/policy.go
  src/pkg/reg/util/util.go
  src/pkg/task/dao/execution.go
  src/pkg/task/dao/execution_test.go
  src/server/middleware/cosign/cosign.go
  src/server/middleware/cosign/cosign_test.go
  src/server/registry/route.go
Labels: release-note/ignore-for-release

#18057 add job status unit test
  src/jobservice/job/status_test.go
Labels: release-note/ignore-for-release

#18076 Add i18n support for Clarity components
  src/portal/src/app/shared/components/navigator/navigator.component.ts
  src/portal/src/app/shared/entities/shared.const.ts
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: release-note/enhancement, target/2.8.0

#18097 Refresh the base image on release-2.5.0
  .buildbaselog
Labels: release-note/infra

#18092 add match many version pattern test
  src/pkg/reg/util/pattern_test.go
Labels: release-note/ignore-for-release

#18113 docs(readme): fix syntax errors in the document
  ADOPTERS.md
  CONTRIBUTING.md
  README.md
  RELEASES.md
  ROADMAP.md
  SECURITY.md
Labels: release-note/docs

#18109 fix: remove the scan exports volume
  make/photon/jobservice/Dockerfile
  make/photon/prepare/templates/docker_compose/docker-compose.yml.jinja
  make/photon/prepare/utils/jobservice.py
  src/pkg/scan/export/constants.go
Labels: release-note/update, target/2.7.1

#18107 fix: remove the scan exports volume
  make/photon/jobservice/Dockerfile
  make/photon/prepare/templates/docker_compose/docker-compose.yml.jinja
  make/photon/prepare/utils/jobservice.py
  src/pkg/scan/export/constants.go
Labels: release-note/update

#18147 Bump to version to v1.10.16
  Makefile
  VERSION
  tests/apitests/python/library/repository.py
  tests/apitests/python/test_retention.py
  tests/ci/ut_install.sh
Labels: release-note/ignore-for-release
