Repository goharbor/harbor, pull requests merged in 2023-03, with the labels that each got.

#18273 Sort user and usergroup by most match order
  src/common/utils/utils.go
  src/common/utils/utils_test.go
  src/server/v2.0/handler/user.go
  src/server/v2.0/handler/usergroup.go
  src/server/v2.0/handler/usergroup_test.go
Labels: release-note/enhancement

#18274 Update the replication rule related to the Chartmuseum
  make/migrations/postgresql/0110_2.8.0_schema.up.sql
Labels: area/replication, release-note/deprecation, target/2.8.0

#18255 refactor: refact the webhook API and life process
  api/v2.0/swagger.yaml
  src/controller/webhook/controller.go
  src/controller/webhook/controller_test.go
  src/core/middlewares/middlewares.go
  src/core/service/notifications/base.go
  src/core/service/notifications/jobs/handler.go
  src/pkg/notification/hook/hook.go
  src/pkg/notification/job/dao/dao.go
  src/pkg/notification/job/dao/dao_test.go
  src/pkg/notification/job/manager.go
  src/pkg/notification/job/manager_test.go
  src/pkg/notification/job/model/model.go
  src/pkg/notification/notification.go
  src/pkg/notification/policy/manager.go
  src/pkg/notification/policy/manager_test.go
  src/server/route.go
  src/server/v2.0/handler/handler.go
  src/server/v2.0/handler/model/notification_job.go
  src/server/v2.0/handler/model/webhook_job.go
  src/server/v2.0/handler/model/webhook_policy.go
  src/server/v2.0/handler/webhook.go
  src/server/v2.0/handler/webhook_job.go
  src/server/v2.0/handler/webhook_job_test.go
  src/server/v2.0/handler/webhook_test.go
  src/testing/controller/controller.go
  src/testing/controller/task/controller.go
  src/testing/controller/task/execution_controller.go
  src/testing/controller/webhook/controller.go
  src/testing/pkg/notification/job/dao/dao.go
  src/testing/pkg/notification/policy/manager.go
  src/testing/pkg/pkg.go
Labels: release-note/new-feature, target/2.8.0

#18297 Add retry times for calling CVE data export execution list API
  src/portal/src/app/shared/components/operation/operation.component.ts
Labels: release-note/update

#18261 Get job log by job_id in worker
  api/v2.0/swagger.yaml
  make/photon/prepare/templates/jobservice/config.yml.jinja
  src/controller/jobmonitor/monitor.go
  src/jobservice/config/config.go
  src/jobservice/config/config_test.go
  src/jobservice/config_test.yml
  src/jobservice/logger/getter/db_getter.go
  src/jobservice/logger/getter/file_getter.go
  src/jobservice/logger/getter/file_getter_test.go
  src/jobservice/logger/getter/testdata/normal.log
  src/jobservice/logger/getter/testdata/truncated.log
  src/pkg/task/mock_task_manager_test.go
  src/pkg/task/task.go
  src/server/v2.0/handler/jobservice.go
  src/testing/pkg/task/manager.go
Labels: release-note/new-feature

#18303 Update UI for the deprecation of Artifact Hub
  src/portal/src/app/base/left-side-nav/registries/create-edit-endpoint/create-edit-endpoint.component.html
  src/portal/src/app/base/left-side-nav/registries/create-edit-endpoint/create-edit-endpoint.component.scss
  src/portal/src/app/base/left-side-nav/registries/create-edit-endpoint/create-edit-endpoint.component.ts
  src/portal/src/app/base/left-side-nav/registries/endpoint.component.html
  src/portal/src/app/base/left-side-nav/registries/endpoint.component.ts
  src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.ts
  src/portal/src/app/base/left-side-nav/replication/replication/list-replication-rule/list-replication-rule.component.html
  src/portal/src/app/base/left-side-nav/replication/replication/list-replication-rule/list-replication-rule.component.ts
  src/portal/src/app/shared/services/endpoint.service.ts
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: release-note/update, target/2.8.0

#18307 Add logs column for worker datagrid
  src/portal/src/app/base/left-side-nav/job-service-dashboard/worker-list/worker-list.component.html
  src/portal/src/app/base/left-side-nav/job-service-dashboard/worker-list/worker-list.component.ts
Labels: release-note/new-feature, target/2.8.0

#18106 Modified to check the expiration time of the allowlist when determining the vulnerability of an artifact
  src/controller/p2p/preheat/enforcer.go
  src/controller/p2p/preheat/enforcer_test.go
  src/controller/scan/base_controller.go
  src/controller/scan/controller.go
  src/server/middleware/vulnerable/vulnerable.go
  src/testing/controller/scan/controller.go
Labels: release-note/update

#18321 Update robot account to skip NotFoundErr
  src/controller/robot/controller.go
Labels: area/robot-account, release-note/update

#18278 replace subject id with digest
  api/v2.0/swagger.yaml
  make/migrations/postgresql/0110_2.8.0_schema.up.sql
  src/controller/artifact/controller.go
  src/controller/artifact/controller_test.go
  src/controller/artifact/model_test.go
  src/pkg/accessory/dao/dao.go
  src/pkg/accessory/dao/dao_test.go
  src/pkg/accessory/dao/model.go
  src/pkg/accessory/manager.go
  src/pkg/accessory/manager_test.go
  src/pkg/accessory/model/accessory.go
  src/pkg/accessory/model/base/base_test.go
  src/pkg/accessory/model/cosign/cosign_test.go
  src/pkg/accessory/model/nydus/nydus_test.go
  src/server/middleware/contenttrust/cosign_test.go
  src/server/middleware/contenttrust/notary_test.go
  src/server/middleware/cosign/cosign.go
  src/server/middleware/cosign/cosign_test.go
  src/server/middleware/nydus/nydus.go
  src/server/middleware/nydus/nydus_test.go
  src/server/middleware/vulnerable/vulnerable_test.go
  src/server/v2.0/handler/artifact.go
  src/server/v2.0/handler/model/accessory.go
  src/testing/pkg/accessory/manager.go
Labels: release-note/update, release-note/breaking-change, target/2.8.0

#18304 fix robot account list project
  src/common/security/robot/context.go
  src/common/security/robot/context_test.go
Labels: release-note/update, target/2.8.0

#18317 Skip robot account for oidc_cli middleware
  src/server/middleware/security/oidc_cli.go
Labels: release-note/update

#18311 Check tag name for OCI spec
  src/controller/tag/controller.go
  src/controller/tag/controller_test.go
Labels: release-note/update

#18316 Migrate robot account and notification policy related to Chartmuseum
  make/migrations/postgresql/0110_2.8.0_schema.up.sql
Labels: release-note/deprecation, target/2.8.0

#18323 Add agent config for ng serve
  .gitignore
  src/portal/README.md
  src/portal/angular.json
  src/portal/package-lock.json
  src/portal/package.json
  src/portal/proxy.config.mjs.temp
Labels: release-note/infra

#18318 Remove go routine to reloadSetting
  src/core/controllers/oidc.go
  src/pkg/oidc/helper.go
  src/pkg/oidc/helper_test.go
Labels: release-note/update

#18180 Fixes Publish to Github Packages
  .github/workflows/publish_release.yml
  tools/release/release_utils.sh
Labels: area/ci, release-note/infra

#18325 Improve webhook UI
  src/portal/src/app/base/project/webhook/add-webhook-form/add-webhook-form.component.ts
  src/portal/src/app/base/project/webhook/excutions/executions.component.html
  src/portal/src/app/base/project/webhook/excutions/executions.component.ts
  src/portal/src/app/base/project/webhook/webhook.service.ts
Labels: release-note/update, target/2.8.0

#18331 Add dynamic column support
  src/portal/src/app/base/left-side-nav/replication/replication/list-replication-rule/list-replication-rule.component.html
  src/portal/src/app/base/left-side-nav/replication/replication/list-replication-rule/list-replication-rule.component.scss
  src/portal/src/app/base/left-side-nav/replication/replication/list-replication-rule/list-replication-rule.component.ts
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
  src/portal/src/app/shared/units/utils.spec.ts
  src/portal/src/app/shared/units/utils.ts
Labels: release-note/new-feature

#17489 Support vpc and internal network (goharbor#17488)
  src/pkg/reg/adapter/aliacr/adapter.go
  src/pkg/reg/adapter/aliacr/adapter_test.go
  src/pkg/reg/adapter/aliacr/types.go
  src/portal/src/app/base/left-side-nav/registries/create-edit-endpoint/create-edit-endpoint.component.spec.ts
  src/portal/src/app/base/left-side-nav/registries/endpoint.component.spec.ts
Labels: release-note/community, release-note/enhancement

#18289 Improve Portal french translation
  src/portal/src/app/base/left-side-nav/system-robot-accounts/system-robot-accounts.component.html
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/sub-accessories/sub-accessories.component.html
  src/portal/src/app/base/project/robot-account/robot-account.component.html
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: release-note/community, release-note/enhancement

#18342 migration: add sql to migrate the old webhook job to new way
  make/migrations/postgresql/0110_2.8.0_schema.up.sql
Labels: release-note/update, target/2.8.0

#18103 Remove release-note/update label from dependabot for github-actions
  .github/dependabot.yml
Labels: release-note/infra

#18312 Update UI packages
  src/portal/PACKAGE.md
  src/portal/app-swagger-ui/package-lock.json
  src/portal/app-swagger-ui/package.json
  src/portal/package-lock.json
  src/portal/package.json
  src/portal/src/app/base/left-side-nav/clearing-job/audit-log-purge/history/purge-history.component.html
  src/portal/src/app/base/left-side-nav/clearing-job/gc-page/gc/gc-history/gc-history.component.html
  src/portal/src/app/base/left-side-nav/distribution/distribution-instances/distribution-instances.component.html
  src/portal/src/app/base/left-side-nav/log/recent-log.component.html
  src/portal/src/app/base/left-side-nav/projects/list-project/list-project.component.html
  src/portal/src/app/base/left-side-nav/registries/endpoint.component.html
  src/portal/src/app/base/left-side-nav/replication/replication/replication-tasks/replication-tasks.component.html
  src/portal/src/app/base/left-side-nav/replication/replication/replication.component.html
  src/portal/src/app/base/left-side-nav/system-robot-accounts/list-all-projects/list-all-projects.component.html
  src/portal/src/app/base/left-side-nav/system-robot-accounts/new-robot/new-robot.component.html
  src/portal/src/app/base/left-side-nav/system-robot-accounts/projects-modal/projects-modal.component.html
  src/portal/src/app/base/left-side-nav/system-robot-accounts/system-robot-accounts.component.html
  src/portal/src/app/base/left-side-nav/user/user.component.html
  src/portal/src/app/base/project/p2p-provider/policy/policy.component.html
  src/portal/src/app/base/project/p2p-provider/task-list/task-list.component.html
  src/portal/src/app/base/project/project-log/audit-log.component.html
  src/portal/src/app/base/project/repository/artifact/artifact-additions/artifact-vulnerabilities/artifact-vulnerabilities.component.html
  src/portal/src/app/base/project/repository/artifact/artifact-additions/build-history/build-history.component.html
  src/portal/src/app/base/project/repository/artifact/artifact-additions/values/values.component.html
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list-page.component.html
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/sub-accessories/sub-accessories.component.html
  src/portal/src/app/base/project/repository/artifact/artifact-summary.component.html
  src/portal/src/app/base/project/repository/artifact/artifact-tag/artifact-tag.component.html
  src/portal/src/app/base/project/repository/artifact/vulnerability-scanning/result-tip-histogram/result-tip-histogram.component.html
  src/portal/src/app/base/project/repository/artifact/vulnerability-scanning/result-tip.component.html
  src/portal/src/app/base/project/repository/repository-gridview.component.html
  src/portal/src/app/base/project/robot-account/add-robot/add-robot.component.html
  src/portal/src/app/base/project/robot-account/robot-account.component.html
  src/portal/src/app/base/project/summary/summary.component.html
  src/portal/src/app/base/project/tag-feature-integration/tag-retention/tag-retention-tasks/tag-retention-tasks/tag-retention-tasks.component.html
  src/portal/src/app/base/project/tag-feature-integration/tag-retention/tag-retention.component.html
  src/portal/src/app/base/project/webhook/excutions/executions.component.html
  src/portal/src/app/base/project/webhook/tasks/tasks.component.html
  src/portal/src/app/base/project/webhook/tasks/tasks.component.ts
  src/portal/src/app/base/project/webhook/webhook.component.html
  src/portal/src/app/shared/components/label/label.component.html
  src/portal/src/app/shared/components/list-project-ro/list-project-ro.component.html
  src/portal/src/app/shared/entities/shared.const.ts
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: release-note/update, target/2.8.0

#18366 Support accessory recursion for artifact list
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/sub-accessories/sub-accessories.component.html
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/sub-accessories/sub-accessories.component.spec.ts
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/sub-accessories/sub-accessories.component.ts
  src/portal/src/app/base/project/repository/artifact/artifact.ts
  src/portal/src/app/services/event-service/event.service.ts
Labels: release-note/enhancement

#18364 add external redis username config to support redis6 ACL
  make/harbor.yml.tmpl
  make/photon/prepare/utils/configs.py
  src/go.mod
  src/go.sum
  src/vendor/github.com/gomodule/redigo/LICENSE
  src/vendor/github.com/gomodule/redigo/redis/commandinfo.go
  src/vendor/github.com/gomodule/redigo/redis/conn.go
  src/vendor/github.com/gomodule/redigo/redis/doc.go
  src/vendor/github.com/gomodule/redigo/redis/go16.go
  src/vendor/github.com/gomodule/redigo/redis/log.go
  src/vendor/github.com/gomodule/redigo/redis/pool.go
  src/vendor/github.com/gomodule/redigo/redis/pool17.go
  src/vendor/github.com/gomodule/redigo/redis/pubsub.go
  src/vendor/github.com/gomodule/redigo/redis/redis.go
  src/vendor/github.com/gomodule/redigo/redis/reply.go
  src/vendor/github.com/gomodule/redigo/redis/scan.go
  src/vendor/github.com/gomodule/redigo/redis/script.go
  src/vendor/modules.txt
Labels: release-note/update

#18357 Make label filter editable for replication rule
  src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.html
  src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.scss
  src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.ts
Labels: release-note/enhancement

#18362 docs: Updated Web UI URL in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: release-note/community

#18370 feat: upgrade golang to 1.20.1
  .github/workflows/CI.yml
  .github/workflows/build-package.yml
  .github/workflows/conformance_test.yml
  Makefile
  make/photon/registry/Dockerfile.binary
  make/photon/trivy-adapter/Dockerfile.binary
  make/photon/trivy-adapter/builder.sh
  src/go.mod
  src/lib/retry/retry.go
  src/pkg/permission/evaluator/rbac/casbin_match.go
  tests/ci/distro_installer.sh
  tests/ci/ut_install.sh
  tests/ci/ut_run.sh
Labels: release-note/update

#18371 Fix some UI issues
  src/portal/src/app/account/sign-in/sign-in.component.ts
  src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.spec.ts
  src/portal/src/app/base/left-side-nav/replication/replication/list-replication-rule/list-replication-rule.component.html
  src/portal/src/app/base/left-side-nav/replication/replication/list-replication-rule/list-replication-rule.component.ts
  src/portal/src/app/base/left-side-nav/replication/replication/replication-tasks/replication-tasks.component.ts
  src/portal/src/app/base/left-side-nav/replication/replication/replication.component.html
  src/portal/src/app/base/left-side-nav/replication/replication/replication.component.spec.ts
  src/portal/src/app/base/left-side-nav/replication/replication/replication.component.ts
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
  src/portal/src/app/shared/services/interface.ts
  src/portal/src/app/shared/services/replication.service.ts
Labels: release-note/update

#18365 feat: support configrate the jobservice logger sweeper duration
  make/harbor.yml.tmpl
  make/photon/prepare/commands/migrate.py
  make/photon/prepare/migrations/__init__.py
  make/photon/prepare/migrations/version_2_8_0/__init__.py
  make/photon/prepare/migrations/version_2_8_0/harbor.yml.jinja
  make/photon/prepare/templates/jobservice/config.yml.jinja
  make/photon/prepare/utils/configs.py
  make/photon/prepare/utils/jobservice.py
Labels: release-note/update, target/2.8.0

#18374 fix: fix the webhook migration sql
  make/migrations/postgresql/0110_2.8.0_schema.up.sql
Labels: release-note/ignore-for-release, target/2.8.0

#18369 add middleware for artifact with subject
  src/core/main.go
  src/pkg/accessory/model/accessory.go
  src/pkg/accessory/model/subject/subject.go
  src/pkg/accessory/model/subject/subject_test.go
  src/server/middleware/subject/subject.go
  src/server/middleware/subject/subject_test.go
  src/server/registry/referrers.go
  src/server/registry/referrers_test.go
  src/server/registry/route.go
Labels: release-note/new-feature, target/2.8.0

#18361 refactor: refactor the old goroutine execution sweep
  src/controller/gc/controller.go
  src/controller/p2p/preheat/enforcer.go
  src/controller/replication/execution.go
  src/controller/retention/controller.go
  src/controller/scan/base_controller.go
  src/controller/scan/callback.go
  src/controller/scandataexport/execution.go
  src/controller/systemartifact/execution.go
  src/controller/task/sweep.go
  src/core/main.go
  src/jobservice/job/known_jobs.go
  src/jobservice/runner/redis.go
  src/jobservice/runtime/bootstrap.go
  src/pkg/task/execution.go
  src/pkg/task/execution_test.go
  src/pkg/task/mock.go
  src/pkg/task/mock_sweep_manager_test.go
  src/pkg/task/sweep_job.go
  src/pkg/task/sweep_job_test.go
  src/pkg/task/sweep_manager.go
  src/pkg/task/sweep_manager_test.go
  src/server/v2.0/handler/scan_all.go
  tests/apitests/python/test_job_service_dashboard.py
Labels: kind/refactor, release-note/update, target/2.8.0

#18382 feat: support configurate the http client timeout for webhook job
  make/harbor.yml.tmpl
  make/photon/prepare/migrations/version_2_8_0/harbor.yml.jinja
  make/photon/prepare/templates/jobservice/env.jinja
  make/photon/prepare/utils/configs.py
  src/jobservice/job/impl/notification/http_helper.go
  src/jobservice/job/impl/notification/http_helper_test.go
  src/jobservice/job/impl/notification/webhook_job.go
Labels: release-note/update, target/2.8.0

#18377 revert subject id in the accessory
  api/v2.0/swagger.yaml
  make/migrations/postgresql/0110_2.8.0_schema.up.sql
  src/controller/artifact/controller.go
  src/controller/artifact/controller_test.go
  src/pkg/accessory/dao/dao.go
  src/pkg/accessory/dao/model.go
  src/pkg/accessory/manager.go
  src/pkg/accessory/manager_test.go
  src/pkg/accessory/model/accessory.go
  src/pkg/accessory/model/base/base_test.go
  src/server/middleware/cosign/cosign.go
  src/server/middleware/subject/subject.go
  src/server/v2.0/handler/artifact.go
  src/server/v2.0/handler/model/accessory.go
  src/testing/pkg/accessory/manager.go
Labels: release-note/update

#14615 Change storage_service.redirect.disabled in harbor.yml.tmpl to storage_service.redirect.deactivate
  make/harbor.yml.tmpl
  make/photon/prepare/migrations/version_2_8_0/harbor.yml.jinja
  make/photon/prepare/utils/configs.py
Labels: pending-for-more-info, kind/helm-chart-impact, release-note/update, target/2.8.0

#18390 fix: register sweeper retain counts for purge audit log job
  src/jobservice/job/known_jobs.go
Labels: release-note/update, target/2.8.0

#18389 fix 2.8 migration issue
  make/migrations/postgresql/0110_2.8.0_schema.up.sql
Labels: release-note/update, target/2.8.0

#18392 fix: change the default max retry count for webhook job to 3
  make/harbor.yml.tmpl
  make/photon/prepare/migrations/version_2_8_0/harbor.yml.jinja
  src/jobservice/job/impl/notification/slack_job.go
  src/jobservice/job/impl/notification/slack_job_test.go
  src/jobservice/job/impl/notification/webhook_job.go
  src/jobservice/job/impl/notification/webhook_job_test.go
Labels: release-note/ignore-for-release, target/2.8.0

#18417 Update the support matrix
  RELEASES.md
Labels: release-note/ignore-for-release

#18271 Fix project setup step.
  CONTRIBUTING.md
Labels: release-note/community, release-note/docs

#18411 Fix sql error in FixDanglingStateExecution
  src/pkg/task/sweep_manager.go
  src/pkg/task/sweep_manager_test.go
Labels: release-note/update, target/2.8.0

#18430 fix referrers api response issue
  src/server/registry/referrers.go
  src/server/registry/referrers_test.go
Labels: release-note/update, target/2.8.0

#18426 fix: add remove chartmuseum notice message
  make/install.sh
Labels: release-note/update, target/2.8.0

#18421 [cherry-pick] fix: fix the invalid jobid for scan data export
  src/controller/scandataexport/execution.go
  src/jobservice/job/impl/scandataexport/scan_data_export.go
  src/jobservice/job/impl/scandataexport/scan_data_export_test.go
  src/pkg/scan/export/manager.go
Labels: kind/bug, release-note/update, area/cve-export, target/2.7.2

#18420 [cherry-pick] fix: fix the invalid jobid for scan data export
  src/controller/scandataexport/execution.go
  src/jobservice/job/impl/scandataexport/scan_data_export.go
  src/jobservice/job/impl/scandataexport/scan_data_export_test.go
  src/pkg/scan/export/manager.go
Labels: kind/bug, release-note/update, area/cve-export, target/2.6.5

#18433 Add copy digest button for accessories
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/sub-accessories/sub-accessories.component.html
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/sub-accessories/sub-accessories.component.scss
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/sub-accessories/sub-accessories.component.ts
  src/portal/src/app/services/event-service/event.service.ts
  src/portal/src/css/common.scss
Labels: release-note/enhancement

#18398 fix: fix the invalid jobid for scan data export
  src/controller/scandataexport/execution.go
  src/jobservice/job/impl/scandataexport/scan_data_export.go
  src/jobservice/job/impl/scandataexport/scan_data_export_test.go
  src/pkg/scan/export/manager.go
Labels: release-note/update, area/cve-export, target/2.8.0

#18439 Remove markdown pipe for webhook payload data
  src/portal/src/app/base/project/webhook/excutions/executions.component.html
Labels: release-note/update

#18441 fix the copy artifact issue
  src/controller/artifact/controller.go
Labels: release-note/update, target/2.8.0

#18437 [cherry-pick] fix: escape the event data for slack webhook payload
  src/pkg/notifier/handler/notification/slack_handler.go
  src/pkg/notifier/handler/notification/slack_handler_test.go
Labels: area/webhook, release-note/update, target/2.7.2

#18436 [cherry-pick] fix: escape the event data for slack webhook payload
  src/pkg/notifier/handler/notification/slack_handler.go
  src/pkg/notifier/handler/notification/slack_handler_test.go
Labels: area/webhook, release-note/update, target/2.6.5

#18456 Update webhook and repliation element xpath
  tests/resources/Harbor-Pages/Job_Service_Dashboard.robot
  tests/resources/Harbor-Pages/Project-Webhooks.robot
  tests/resources/Harbor-Pages/Replication.robot
  tests/resources/Harbor-Pages/Replication_Elements.robot
Labels: area/test automation/nightly-testing, release-note/infra, target/2.8.0

#18449 Add new app level warning message
  src/portal/src/app/account/sign-in/sign-in.component.html
  src/portal/src/app/app.component.ts
  src/portal/src/app/base/base.module.ts
  src/portal/src/app/base/harbor-shell/app-level-alerts/app-level-alerts.component.html
  src/portal/src/app/base/harbor-shell/app-level-alerts/app-level-alerts.component.scss
  src/portal/src/app/base/harbor-shell/app-level-alerts/app-level-alerts.component.spec.ts
  src/portal/src/app/base/harbor-shell/app-level-alerts/app-level-alerts.component.ts
  src/portal/src/app/base/harbor-shell/harbor-shell.component.html
  src/portal/src/app/base/harbor-shell/harbor-shell.component.scss
  src/portal/src/app/base/harbor-shell/harbor-shell.component.spec.ts
  src/portal/src/app/base/harbor-shell/harbor-shell.component.ts
  src/portal/src/app/base/left-side-nav/job-service-dashboard/job-service-dashboard-health-check.service.spec.ts
  src/portal/src/app/base/left-side-nav/job-service-dashboard/job-service-dashboard-health-check.service.ts
  src/portal/src/app/base/left-side-nav/job-service-dashboard/pending-job-list/pending-job-list.component.html
  src/portal/src/app/base/left-side-nav/job-service-dashboard/pending-job-list/pending-job-list.component.scss
  src/portal/src/app/base/left-side-nav/job-service-dashboard/pending-job-list/pending-job-list.component.ts
  src/portal/src/app/base/project/webhook/add-webhook/add-webhook.component.scss
  src/portal/src/app/base/project/webhook/webhook.service.spec.ts
  src/portal/src/app/base/project/webhook/webhook.service.ts
  src/portal/src/app/shared/components/global-message/message.component.html
  src/portal/src/app/shared/components/global-message/message.component.scss
  src/portal/src/app/shared/components/global-message/message.component.spec.ts
  src/portal/src/app/shared/components/global-message/message.component.ts
  src/portal/src/app/shared/entities/shared.const.ts
  src/portal/src/app/shared/services/message-handler.service.ts
  src/portal/src/app/shared/services/session.service.ts
  src/portal/src/css/common.scss
  src/portal/src/css/dark-theme.scss
  src/portal/src/css/light-theme.scss
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: release-note/enhancement, target/2.8.0

#18424 fix: escape the event data for slack webhook payload
  src/pkg/notifier/handler/notification/slack_handler.go
  src/pkg/notifier/handler/notification/slack_handler_test.go
Labels: area/webhook, release-note/update, target/2.8.0
