Repository goharbor/harbor, pull requests merged in 2023-08, with the labels that each got.

#19056 [cherry-pick]fix accessory import issue
  src/jobservice/main.go
Labels: release-note/update, target/2.7.3

#19006 Bump up photon version from 4.0 to 5.0
  make/photon/core/Dockerfile.base
  make/photon/db/Dockerfile.base
  make/photon/exporter/Dockerfile.base
  make/photon/jobservice/Dockerfile.base
  make/photon/log/Dockerfile.base
  make/photon/nginx/Dockerfile.base
  make/photon/portal/Dockerfile.base
  make/photon/prepare/Dockerfile.base
  make/photon/redis/Dockerfile.base
  make/photon/registry/Dockerfile.base
  make/photon/registryctl/Dockerfile.base
  make/photon/trivy-adapter/Dockerfile.base
Labels: area/build, release-note/infra, target/2.9.0

#19068 Remove cache for project policy updating
  src/portal/src/app/services/routing-resolvers/artifact-detail-routing-resolver.service.ts
  src/portal/src/app/services/routing-resolvers/project-routing-resolver.service.ts
  src/portal/src/app/shared/router-guard/member-guard-activate.service.ts
  src/portal/src/app/shared/services/project.service.ts
Labels: release-note/update

#19069 Update style for banner message ui
  src/portal/src/app/base/harbor-shell/app-level-alerts/app-level-alerts.component.html
  src/portal/src/app/base/harbor-shell/app-level-alerts/app-level-alerts.component.scss
  src/portal/src/app/base/left-side-nav/config/system/system-settings.component.html
  src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-summary/vulnerability-summary.component.scss
Labels: release-note/update

#19057 Add validator for duration of banner message
  src/portal/src/app/base/left-side-nav/config/system/system-settings.component.html
  src/portal/src/app/base/left-side-nav/config/system/system-settings.component.ts
Labels: release-note/update

#19066 bump golang 1.20.6 on main
  .github/workflows/CI.yml
  .github/workflows/build-package.yml
  .github/workflows/conformance_test.yml
  CONTRIBUTING.md
  Makefile
  make/photon/registry/Dockerfile.binary
  make/photon/trivy-adapter/Dockerfile.binary
  make/photon/trivy-adapter/builder.sh
  tests/ci/distro_installer.sh
Labels: release-note/update, target/2.9.0

#19087 fix: bump up TRIVYVERSION=v0.44.0 and TRIVYADAPTERVERSION=v0.30.15
  Makefile
Labels: release-note/update, target/2.9.0

#19088 fix: bump up TRIVYVERSION=v0.44.0 and TRIVYADAPTERVERSION=v0.30.15
  Makefile
Labels: release-note/update, target/2.8.4

#19089 fix: TRIVYVERSION=v0.44.0 && TRIVYADAPTERVERSION=v0.30.15
  Makefile
Labels: release-note/update, target/2.7.3

#19079 Merge cosign check and notation check
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
  src/portal/src/app/base/project/repository/artifact/artifact.ts
Labels: release-note/update

#19081 [Cherry-pick]Convert the string "0" to number 0
  src/portal/src/app/base/project/tag-feature-integration/tag-retention/add-rule/add-rule.component.ts
Labels: release-note/update

#19094 Update ui for gc history and banner message
  src/portal/src/app/base/left-side-nav/clearing-job/gc-page/gc/gc-history/gc-history.component.scss
  src/portal/src/app/base/left-side-nav/config/system/system-settings.component.html
  src/portal/src/app/base/left-side-nav/config/system/system-settings.component.ts
Labels: release-note/update

#19082 [Cherry-pick]Convert the string "0" to number 0
  src/portal/src/app/base/project/tag-feature-integration/tag-retention/add-rule/add-rule.component.ts
Labels: release-note/update

#19078 Show banner message on log in page
  src/portal/src/app/account/sign-in/sign-in.component.html
  src/portal/src/app/base/base.module.ts
  src/portal/src/app/base/left-side-nav/config/system/system-settings.component.html
  src/portal/src/app/shared/components/app-level-alerts/app-level-alerts.component.html
  src/portal/src/app/shared/components/app-level-alerts/app-level-alerts.component.scss
  src/portal/src/app/shared/components/app-level-alerts/app-level-alerts.component.spec.ts
  src/portal/src/app/shared/components/app-level-alerts/app-level-alerts.component.ts
  src/portal/src/app/shared/shared.module.ts
Labels: release-note/update

#19083 Update cron ui for add replicatipn rule page
  src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.html
  src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.scss
  src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.ts
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: release-note/update

#19080 Convert the string "0" to number 0
  src/portal/src/app/base/project/tag-feature-integration/tag-retention/add-rule/add-rule.component.ts
Labels: release-note/update

#19090 fix: fix replication list projects with pure numberic name
  src/pkg/reg/adapter/harbor/base/adapter.go
Labels: release-note/update, target/2.9.0

#19100 Update style for add-replication-rule page
  src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.html
  src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.scss
Labels: release-note/update

#19106 Fix incorrect artifact and scanned artifact count issue
  src/controller/securityhub/controller.go
  src/controller/securityhub/controller_test.go
  src/pkg/securityhub/dao/security.go
  src/pkg/securityhub/dao/security_test.go
  src/pkg/securityhub/manager.go
  src/testing/pkg/securityhub/manager.go
Labels: release-note/update, target/2.9.0

#19102 Add artifact digest to query condition
  api/v2.0/swagger.yaml
  src/pkg/securityhub/dao/security.go
  src/pkg/securityhub/dao/security_test.go
Labels: release-note/update, target/2.9.0

#19103 Sort most dangerous vulnerabilities by score and severity level
  make/migrations/postgresql/0120_2.9.0_schema.up.sql
  src/pkg/securityhub/dao/security.go
  src/pkg/securityhub/dao/security_test.go
Labels: release-note/update, target/2.9.0

#19109 fix ScheduleObj.type in swagger
  api/v2.0/swagger.yaml
Labels: release-note/update, target/2.9.0

#19110 fix: skip to delete scan reports if the digest still referenced
  src/controller/event/handler/internal/artifact.go
  src/controller/event/handler/internal/artifact_test.go
Labels: release-note/update, target/2.9.0

#19093 [cherry-pick] fix: fix replication list projects with pure numberic name
  src/pkg/reg/adapter/harbor/base/adapter.go
Labels: release-note/update, target/2.7.3

#19092 [cherry-pick] fix: fix replication list projects with pure numberic name
  src/pkg/reg/adapter/harbor/base/adapter.go
Labels: release-note/update, target/2.8.4

#19101 Update ui to fix some issues
  src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/security-hub.component.ts
  src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/security-hub.interface.ts
  src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-filter/vulnerability-filter.component.ts
  src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-summary/vulnerability-summary.component.html
  src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-summary/vulnerability-summary.component.ts
  src/portal/src/app/services/app-config.service.ts
  src/portal/src/app/shared/components/app-level-alerts/app-level-alerts.component.html
  src/portal/src/app/shared/components/app-level-alerts/app-level-alerts.component.ts
Labels: release-note/update, target/2.9.0

#19111 bump golang 1.20.7 on main
  .github/workflows/CI.yml
  .github/workflows/build-package.yml
  .github/workflows/conformance_test.yml
  CONTRIBUTING.md
  Makefile
  make/photon/registry/Dockerfile.binary
  make/photon/trivy-adapter/Dockerfile.binary
  make/photon/trivy-adapter/builder.sh
  tests/ci/distro_installer.sh
Labels: release-note/update

#19091 fix: privileges member successfully typo
  tests/apitests/python/test_robot_account.py
  tests/apitests/python/test_scan_image_artifact_in_public_project.py
  tests/integration.sh
Labels: release-note/update

#19114 Refresh base images on 2.9.0
  .buildbaselog
Labels: release-note/ignore-for-release, target/2.9.0

#19118 [cherry-pick]Bump up setup-gcloud to 430.0.0
  .github/workflows/publish_release.yml
Labels: release-note/infra

#19116 Bump up setup-gcloud to 430.0.0
  .github/workflows/publish_release.yml
Labels: release-note/infra

#19117 [cherry-pick]Bump up setup-gcloud to 430.0.0
  .github/workflows/publish_release.yml
Labels: release-note/infra

#19119 [cherry-pick]Bump up setup-gcloud to 430.0.0
  .github/workflows/publish_release.yml
Labels: release-note/infra

#19095 fix: add storage_limit check
  src/controller/quota/driver/project/project.go
  src/controller/quota/driver/project/project_test.go
  src/lib/quota_storage_limit.go
  src/lib/quota_storage_limit_test.go
  src/pkg/config/manager.go
  src/pkg/quota/types/resources.go
Labels: release-note/update, target/2.9.0

#19071 fix: cron string validation
  src/common/utils/utils.go
  src/common/utils/utils_test.go
  src/controller/p2p/preheat/controller.go
  src/controller/p2p/preheat/controllor_test.go
  src/controller/retention/controller.go
  src/controller/retention/controller_test.go
  src/pkg/p2p/preheat/models/policy/policy.go
  src/pkg/p2p/preheat/models/policy/policy_test.go
  src/pkg/retention/policy/models.go
  src/pkg/retention/policy/models_test.go
  src/server/v2.0/handler/gc.go
  src/server/v2.0/handler/purge.go
  src/server/v2.0/handler/scan_all.go
Labels: release-note/update, target/2.9.0

#19124 bump up base version
  VERSION
Labels: release-note/infra

#19144 [Cherry-pick] fix: add storage_limit check (add ValidateQuotaLimit as a general met…
  src/controller/quota/driver/project/project.go
  src/controller/quota/driver/project/project_test.go
  src/lib/quota_storage_limit.go
  src/lib/quota_storage_limit_test.go
  src/pkg/config/manager.go
  src/pkg/quota/types/resources.go
Labels: release-note/update, target/2.9.0

#19145 [Cherry-pick] fix: cron string validation (the 1st field of a cron string must be 0…
  src/common/utils/utils.go
  src/common/utils/utils_test.go
  src/controller/p2p/preheat/controller.go
  src/controller/p2p/preheat/controllor_test.go
  src/controller/retention/controller.go
  src/controller/retention/controller_test.go
  src/pkg/p2p/preheat/models/policy/policy.go
  src/pkg/p2p/preheat/models/policy/policy_test.go
  src/pkg/retention/policy/models.go
  src/pkg/retention/policy/models_test.go
  src/server/v2.0/handler/gc.go
  src/server/v2.0/handler/purge.go
  src/server/v2.0/handler/scan_all.go
Labels: release-note/update, target/2.9.0

#19138 bump go 1.20.7 && install git for p4 base golang image
  .github/workflows/CI.yml
  .github/workflows/build-package.yml
  .github/workflows/conformance_test.yml
  CONTRIBUTING.md
  Makefile
  make/photon/golang/Dockerfile
  make/photon/registry/Dockerfile.binary
  make/photon/trivy-adapter/Dockerfile.binary
  make/photon/trivy-adapter/builder.sh
  tests/ci/distro_installer.sh
Labels: release-note/update, target/2.8.4

#19165 log: change log level to reduce the noise logs
  src/cmd/exporter/main.go
  src/core/session/session.go
  src/lib/cache/redis/redis.go
  src/pkg/notifier/notifier.go
  src/server/registry/manifest.go
Labels: release-note/update, target/2.9.0

#19162 bump go1.19.12 on release-2.7.0 base on ph4
  .github/workflows/CI.yml
  .github/workflows/build-package.yml
  .github/workflows/conformance_test.yml
  CONTRIBUTING.md
  Makefile
  make/photon/chartserver/builder
  make/photon/golang/Dockerfile
  make/photon/registry/Dockerfile.binary
  make/photon/trivy-adapter/Dockerfile.binary
  make/photon/trivy-adapter/builder.sh
  tests/ci/distro_installer.sh
Labels: release-note/update

#19122 [cherry-pick] chore: fix incorrect otel timeout in harbor yaml template
  make/harbor.yml.tmpl
  make/photon/prepare/migrations/version_2_4_0/harbor.yml.jinja
  make/photon/prepare/migrations/version_2_5_0/harbor.yml.jinja
  make/photon/prepare/migrations/version_2_6_0/harbor.yml.jinja
  make/photon/prepare/migrations/version_2_7_0/harbor.yml.jinja
  make/photon/prepare/migrations/version_2_8_0/harbor.yml.jinja
  make/photon/prepare/models.py
Labels: release-note/update, target/2.8.4

#19170 Bump up version to v2.8.4
  VERSION
Labels: release-note/ignore-for-release, target/2.8.4

#19123 [cherry-pick] chore: fix incorrect otel timeout in harbor yaml template
  make/harbor.yml.tmpl
  make/photon/prepare/migrations/version_2_4_0/harbor.yml.jinja
  make/photon/prepare/migrations/version_2_5_0/harbor.yml.jinja
  make/photon/prepare/migrations/version_2_6_0/harbor.yml.jinja
  make/photon/prepare/migrations/version_2_7_0/harbor.yml.jinja
  make/photon/prepare/migrations/version_2_8_0/harbor.yml.jinja
  make/photon/prepare/migrations/version_2_9_0/harbor.yml.jinja
  make/photon/prepare/models.py
Labels: release-note/update, target/2.9.0

#19180 ignore spaces for vulnerability filters
  src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-filter/vulnerability-filter.component.ts
  src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-summary/vulnerability-summary.component.html
Labels: release-note/update

#19181 [Cherry-pick]ignore spaces for vulnerability filters
  src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-filter/vulnerability-filter.component.ts
  src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-summary/vulnerability-summary.component.html
Labels: release-note/update

#19184 fix: support customize cache db for business
  make/harbor.yml.tmpl
  make/photon/prepare/migrations/version_2_8_0/harbor.yml.jinja
  make/photon/prepare/templates/core/env.jinja
  make/photon/prepare/templates/jobservice/env.jinja
  make/photon/prepare/utils/configs.py
  src/core/main.go
  src/jobservice/main.go
  src/lib/cache/cache.go
  src/pkg/cached/base_manager.go
Labels: release-note/update, target/2.8.4

#19161 Update zh-tw (Traditional Chinese) locale
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: area/i18n, release-note/update

#19121 [cherry-pick] chore: fix incorrect otel timeout in harbor yaml template
  make/harbor.yml.tmpl
  make/photon/prepare/migrations/version_2_4_0/harbor.yml.jinja
  make/photon/prepare/migrations/version_2_5_0/harbor.yml.jinja
  make/photon/prepare/migrations/version_2_6_0/harbor.yml.jinja
  make/photon/prepare/migrations/version_2_7_0/harbor.yml.jinja
  make/photon/prepare/models.py
Labels: release-note/update, target/2.7.3

#19120 chore: fix incorrect otel timeout in harbor yaml template
  make/harbor.yml.tmpl
  make/photon/prepare/migrations/version_2_4_0/harbor.yml.jinja
  make/photon/prepare/migrations/version_2_5_0/harbor.yml.jinja
  make/photon/prepare/migrations/version_2_6_0/harbor.yml.jinja
  make/photon/prepare/migrations/version_2_7_0/harbor.yml.jinja
  make/photon/prepare/migrations/version_2_8_0/harbor.yml.jinja
  make/photon/prepare/migrations/version_2_9_0/harbor.yml.jinja
  make/photon/prepare/models.py
Labels: release-note/update

#19194 Update the max length for the filters
  src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-filter/vulnerability-filter.component.ts
Labels: release-note/update

#19195 [Cherry-pick]Update the max length for the filters
  src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-filter/vulnerability-filter.component.ts
Labels: release-note/update

#19190 [cherry-pick] fix: support customize cache db for business
  make/harbor.yml.tmpl
  make/photon/prepare/migrations/version_2_7_0/harbor.yml.jinja
  make/photon/prepare/migrations/version_2_8_0/harbor.yml.jinja
  make/photon/prepare/migrations/version_2_9_0/harbor.yml.jinja
  make/photon/prepare/templates/core/env.jinja
  make/photon/prepare/templates/jobservice/env.jinja
  make/photon/prepare/utils/configs.py
  src/controller/quota/controller.go
  src/core/main.go
  src/jobservice/main.go
  src/lib/cache/cache.go
  src/lib/redis/client.go
  src/lib/redis/client_test.go
  src/pkg/cached/base_manager.go
Labels: release-note/update, target/2.9.0

#19189 [cherry-pick] fix: support customize cache db for business
  make/harbor.yml.tmpl
  make/photon/prepare/migrations/version_2_7_0/harbor.yml.jinja
  make/photon/prepare/templates/core/env.jinja
  make/photon/prepare/templates/jobservice/env.jinja
  make/photon/prepare/utils/configs.py
  src/core/main.go
  src/jobservice/main.go
  src/lib/cache/cache.go
  src/pkg/cached/base_manager.go
Labels: release-note/update, target/2.7.3

#19187 Filter artifact without CVE from top 5 dangerous artifacts
  src/pkg/securityhub/dao/security.go
Labels: release-note/update

#19146 log: change log level to reduce the noise logs
  src/cmd/exporter/main.go
  src/core/session/session.go
  src/lib/cache/redis/redis.go
  src/pkg/notifier/notifier.go
  src/server/registry/manifest.go
Labels: release-note/update

#19203 (cherry-pick) Filter artifact without CVE from top 5 dangerous artifacts
  src/pkg/securityhub/dao/security.go
Labels: release-note/update, target/2.9.0

#19205 (cherry-pick) Wrong artifact scanned count
  src/pkg/securityhub/dao/security.go
Labels: release-note/update, target/2.9.0

#19198 Wrong artifact scanned count
  src/pkg/securityhub/dao/security.go
Labels: release-note/update

#19206 bump go1.20.7 on release-1.10.0 base on ph4
  .github/workflows/CI.yml
  .github/workflows/build-package.yml
  CONTRIBUTING.md
  Makefile
  docs/compile_guide.md
  docs/use_make.md
  make/photon/registry/Dockerfile.binary
  src/chartserver/cache.go
  src/common/api/base_test.go
  src/common/config/store/driver/db_test.go
  src/common/dao/dao_test.go
  src/common/utils/notary/helper_test.go
  src/core/api/api_test.go
  src/core/api/log_test.go
  src/core/api/models/admin_job_test.go
  src/core/api/project_test.go
  src/core/api/reg_gc.go
  src/core/api/repository_test.go
  src/core/api/scan_all.go
  src/core/api/scanners_test.go
  src/core/api/search_test.go
  src/core/api/statistic_test.go
  src/core/api/sys_cve_whitelist_test.go
  src/core/api/systeminfo_test.go
  src/core/api/user_test.go
  src/core/auth/auth_test.go
  src/core/auth/db/db_test.go
  src/core/auth/ldap/ldap_test.go
  src/core/config/config_test.go
  src/core/controllers/controllers_test.go
  src/core/middlewares/util/util.go
  src/core/service/token/token_test.go
  src/core/utils/response_handlers_test.go
  src/core/utils/utils_test.go
  src/jobservice/api/handler_test.go
  src/jobservice/config/config_test.go
  src/jobservice/core/controller_test.go
  src/jobservice/hook/hook_client_test.go
  src/jobservice/job/impl/utils/utils_test.go
  src/jobservice/logger/base.go
  src/jobservice/period/basic_scheduler_test.go
  src/jobservice/period/enqueuer_test.go
  src/jobservice/period/policy_store_test.go
  src/jobservice/runner/redis_test.go
  src/jobservice/worker/cworker/c_worker_test.go
  src/pkg/scan/api/scan/controller.go
  src/pkg/scan/rest/v1/models.go
  src/replication/dao/execution.go
  tests/ci/api_common_install.sh
  tests/ci/distro_installer.sh
  tests/ci/ut_install.sh
  tests/ci/ut_run.sh
Labels: release-note/update

#19182 fix: support customize cache db for business
  make/harbor.yml.tmpl
  make/photon/prepare/migrations/version_2_7_0/harbor.yml.jinja
  make/photon/prepare/migrations/version_2_8_0/harbor.yml.jinja
  make/photon/prepare/migrations/version_2_9_0/harbor.yml.jinja
  make/photon/prepare/templates/core/env.jinja
  make/photon/prepare/templates/jobservice/env.jinja
  make/photon/prepare/utils/configs.py
  src/controller/quota/controller.go
  src/core/main.go
  src/jobservice/main.go
  src/lib/cache/cache.go
  src/lib/redis/client.go
  src/lib/redis/client_test.go
  src/pkg/cached/base_manager.go
Labels: release-note/update

#19210 fix gc dry run issue
  src/jobservice/job/impl/gc/garbage_collection.go
Labels: release-note/update, target/2.9.0

#19208 fix gc dry run issue
  src/jobservice/job/impl/gc/garbage_collection.go
Labels: release-note/update, target/2.9.0

#19217 Add new uri path to ShouldNotReuseRoute array
  src/portal/src/app/route-reuse-strategy/harbor-route-reuse-strategy.ts
Labels: release-note/update

#19218 [Cherry-pick]Add new uri path to ShouldNotReuseRoute array
  src/portal/src/app/route-reuse-strategy/harbor-route-reuse-strategy.ts
Labels: release-note/update

#19219 [Cherry-pick]Add new uri path to ShouldNotReuseRoute array
  src/portal/src/app/route-reuse-strategy/harbor-route-reuse-strategy.ts
Labels: release-note/update

#19228 Refine total artifact and scanned artifact
  src/pkg/securityhub/dao/security.go
  src/pkg/securityhub/dao/security_test.go
Labels: release-note/update

#19229 (cherry-pick) Refine total artifact and scanned artifact
  src/pkg/securityhub/dao/security.go
  src/pkg/securityhub/dao/security_test.go
Labels: release-note/update, target/2.9.0

#19140 i18n: fix typo for CONFIRM_SECRET
  src/portal/src/i18n/lang/zh-cn-lang.json
Labels: release-note/update

#19231 Add a tooltip for the page title of security hub
  src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-summary/vulnerability-summary.component.html
  src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-summary/vulnerability-summary.component.scss
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: release-note/update

#19232 [Cherry-pick]Add a tooltip for the page title of security hub
  src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-summary/vulnerability-summary.component.html
  src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-summary/vulnerability-summary.component.scss
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: area/i18n, release-note/update

#19212 change Referrers Content-Type to application/vnd.oci.image.index.v1+json
  src/server/registry/referrers.go
Labels: release-note/update

#18878 Add NS as Harbor adopter
  ADOPTERS.md
Labels: release-note/community

#19246 Refresh base images on release-2.9.0
  .buildbaselog
Labels: release-note/ignore-for-release, target/2.9.0

#19061 Delete unused code
  src/lib/config/systemconfig.go
Labels: release-note/update

#18884 Add PITS Globale Datenrettungsdienste as an adopter
  ADOPTERS.md
Labels: release-note/community

#19097 Add CERN as adopter
  ADOPTERS.md
Labels: release-note/community

#18840 exporter: add field alias for count(*) func
  src/pkg/exporter/project_collector.go
Labels: release-note/update

#19263 [Cherry-pick]Switch to a new chart library
  src/portal/package-lock.json
  src/portal/package.json
  src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/single-bar/single-bar.component.ts
  src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-summary/vulnerability-summary.component.html
  src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-summary/vulnerability-summary.component.ts
  src/portal/src/app/shared/shared.module.ts
Labels: release-note/update, target/2.9.0

#19265 Update the image version for trivy scan
  .github/workflows/nightly-trivy-scan.yml
Labels: release-note/infra

#19264 Update the image version for trivy scan
  .github/workflows/nightly-trivy-scan.yml
Labels: release-note/infra
