Repository goharbor/harbor, pull requests merged in 2023-11, with the labels that each got.

#19505 Replace comma in username to avoid casbin issue
  src/common/const.go
  src/common/utils/utils.go
  src/core/controllers/oidc.go
  src/pkg/user/manager.go
  src/pkg/user/manager_test.go
  src/server/v2.0/handler/user.go
  src/server/v2.0/handler/user_test.go
Labels: release-note/update

#19525 Update the style for severity
  src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/security-hub.component.scss
  src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/security-hub.interface.ts
  src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/single-bar/single-bar.component.ts
  src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-summary/vulnerability-summary.component.scss
  src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-summary/vulnerability-summary.component.ts
  src/portal/src/app/base/project/repository/artifact/artifact-additions/artifact-vulnerabilities/artifact-vulnerabilities.component.scss
  src/portal/src/app/base/project/repository/artifact/artifact.module.ts
  src/portal/src/app/base/project/repository/artifact/vulnerability-scanning/result-bar-chart.component.spec.ts
  src/portal/src/app/base/project/repository/artifact/vulnerability-scanning/result-tip-histogram/result-tip-histogram.component.scss
  src/portal/src/app/base/project/repository/artifact/vulnerability-scanning/result-tip-histogram/result-tip-histogram.component.ts
  src/portal/src/app/base/project/repository/artifact/vulnerability-scanning/result-tip.component.html
  src/portal/src/app/base/project/repository/artifact/vulnerability-scanning/result-tip.component.spec.ts
  src/portal/src/app/base/project/repository/artifact/vulnerability-scanning/result-tip.component.ts
  src/portal/src/app/base/project/repository/artifact/vulnerability-scanning/scanning.scss
Labels: release-note/update

#19530 [cherry-pick]Add banner message UI test case
  tests/apitests/python/test_banner_message.py
  tests/resources/Harbor-Pages/Configuration.robot
  tests/resources/Harbor-Pages/Configuration_Elements.robot
  tests/robot-cases/Group1-Nightly/Common.robot
  tests/robot-cases/Group1-Nightly/Routing.robot
Labels: area/test automation/nightly-testing, release-note/infra

#19529 Add banner message UI test case
  tests/apitests/python/test_banner_message.py
  tests/resources/Harbor-Pages/Configuration.robot
  tests/resources/Harbor-Pages/Configuration_Elements.robot
  tests/robot-cases/Group1-Nightly/Common.robot
  tests/robot-cases/Group1-Nightly/Routing.robot
Labels: area/test automation/nightly-testing, release-note/infra

#19535 Use absolute path for the profile.cov
  tests/coverage4gotest.sh
Labels: release-note/ignore-for-release

#19500 fix: bump up TRIVYVERSION=v0.46.1 && TRIVYADAPTERVERSION=v0.30.18
  Makefile
Labels: release-note/update

#19544 Update E2E test engine images
  tests/resources/SeleniumUtil.robot
  tests/test-engine-image/Dockerfile.api_test
  tests/test-engine-image/Dockerfile.common
  tests/test-engine-image/Dockerfile.ui_test
Labels: area/test automation/pytest-e2e, area/test automation/nightly-testing, release-note/infra

#19549 Add notation sign artifact API test case
  tests/apitests/python/library/base.py
  tests/apitests/python/library/notation.py
  tests/apitests/python/test_cosign_sign_artifact.py
  tests/apitests/python/test_notation_sign_artifact.py
  tests/robot-cases/Group0-BAT/API_DB.robot
Labels: area/test automation/pytest-e2e, release-note/infra

#19552 Skip to validate username when update user profile
  src/server/v2.0/handler/user.go
  src/server/v2.0/handler/user_test.go
Labels: release-note/update

#19553 Update UI package to clear security alerts
  src/portal/app-swagger-ui/package-lock.json
  src/portal/app-swagger-ui/package.json
  src/portal/package-lock.json
  src/portal/package.json
Labels: release-note/update

#19523 Delete project member when delete project
  src/controller/event/handler/internal/project.go
  src/controller/event/handler/internal/project_test.go
  src/pkg/member/dao/dao.go
  src/pkg/member/dao/dao_test.go
  src/pkg/member/manager.go
  src/testing/pkg/member/fake_member_manager.go
Labels: release-note/update

#19543 add permission api
  api/v2.0/swagger.yaml
  src/common/rbac/const.go
  src/controller/member/controller.go
  src/controller/member/controller_test.go
  src/pkg/cached/project/redis/manager.go
  src/pkg/project/dao/dao.go
  src/pkg/project/manager.go
  src/server/v2.0/handler/handler.go
  src/server/v2.0/handler/permissions.go
  src/testing/pkg/project/manager.go
Labels: release-note/update, target/2.10.0

#19507 Add full permissions for the robot account
  src/portal/src/app/base/left-side-nav/system-robot-accounts/list-all-projects/list-all-projects.component.html
  src/portal/src/app/base/left-side-nav/system-robot-accounts/list-all-projects/list-all-projects.component.scss
  src/portal/src/app/base/left-side-nav/system-robot-accounts/list-all-projects/list-all-projects.component.spec.ts
  src/portal/src/app/base/left-side-nav/system-robot-accounts/list-all-projects/list-all-projects.component.ts
  src/portal/src/app/base/left-side-nav/system-robot-accounts/new-robot/new-robot.component.html
  src/portal/src/app/base/left-side-nav/system-robot-accounts/new-robot/new-robot.component.scss
  src/portal/src/app/base/left-side-nav/system-robot-accounts/new-robot/new-robot.component.spec.ts
  src/portal/src/app/base/left-side-nav/system-robot-accounts/new-robot/new-robot.component.ts
  src/portal/src/app/base/left-side-nav/system-robot-accounts/projects-modal/projects-modal.component.html
  src/portal/src/app/base/left-side-nav/system-robot-accounts/projects-modal/projects-modal.component.scss
  src/portal/src/app/base/left-side-nav/system-robot-accounts/projects-modal/projects-modal.component.ts
  src/portal/src/app/base/left-side-nav/system-robot-accounts/system-robot-accounts.component.html
  src/portal/src/app/base/left-side-nav/system-robot-accounts/system-robot-accounts.component.scss
  src/portal/src/app/base/left-side-nav/system-robot-accounts/system-robot-accounts.component.ts
  src/portal/src/app/base/left-side-nav/system-robot-accounts/system-robot-util.ts
  src/portal/src/app/base/project/robot-account/add-robot/add-robot.component.html
  src/portal/src/app/base/project/robot-account/add-robot/add-robot.component.scss
  src/portal/src/app/base/project/robot-account/add-robot/add-robot.component.ts
  src/portal/src/app/base/project/robot-account/robot-account.component.html
  src/portal/src/app/base/project/robot-account/robot-account.component.scss
  src/portal/src/app/base/project/robot-account/robot-account.component.spec.ts
  src/portal/src/app/base/project/robot-account/robot-account.component.ts
  src/portal/src/app/shared/components/remaining-time/remaining-time.component.spec.ts
  src/portal/src/app/shared/components/robot-permissions-panel/robot-permissions-panel.component.html
  src/portal/src/app/shared/components/robot-permissions-panel/robot-permissions-panel.component.scss
  src/portal/src/app/shared/components/robot-permissions-panel/robot-permissions-panel.component.spec.ts
  src/portal/src/app/shared/components/robot-permissions-panel/robot-permissions-panel.component.ts
  src/portal/src/app/shared/shared.module.ts
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: release-note/enhancement

#19533 perf: optimize the trigger retention API
  src/controller/retention/controller.go
  src/controller/retention/controller_test.go
Labels: area/tag-retention, release-note/enhancement, target/2.10.0

#19563 [cherry-pick] Allow POST method to request service/token in readonly mode
  src/core/middlewares/middlewares.go
Labels: release-note/update, target/2.9.2

#19562 [cherry-pick] Allow POST method to request service/token in readonly mode
  src/core/middlewares/middlewares.go
Labels: release-note/update, target/2.8.5

#19564 19559 cannot see full label easily
  src/portal/src/app/shared/components/label/label-piece/label-piece.component.html
Labels: release-note/update

#19538 fix: sorting quota
  api/v2.0/swagger.yaml
  src/lib/q/builder.go
  src/lib/q/builder_test.go
  src/pkg/quota/dao/dao_test.go
  src/pkg/quota/dao/util.go
  src/pkg/quota/dao/util_test.go
Labels: release-note/update, target/2.10.0

#19571 Add API permission testcase
  tests/apitests/python/test_permission.py
Labels: area/test automation/pytest-e2e, release-note/infra

#19575 Add oidc provider name to systeminfo API
  api/v2.0/swagger.yaml
  src/controller/systeminfo/controller.go
  src/controller/systeminfo/controller_test.go
  src/server/v2.0/handler/systeminfo.go
Labels: release-note/enhancement

#19581 Show OIDC provider name on the OIDC login button
  src/portal/src/app/account/sign-in/sign-in.component.html
  src/portal/src/app/account/sign-in/sign-in.component.scss
  src/portal/src/app/account/sign-in/sign-in.component.ts
  src/portal/src/app/services/app-config.ts
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: release-note/enhancement

#19576 Add quota sorting to the project quotas list
  src/portal/src/app/base/left-side-nav/project-quotas/project-quotas/project-quotas.component.html
  src/portal/src/app/base/left-side-nav/project-quotas/project-quotas/project-quotas.component.ts
Labels: release-note/enhancement

#19536 Add a placeholder to the cards for the security-hub
  src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-summary/vulnerability-summary.component.html
  src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-summary/vulnerability-summary.component.scss
  src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-summary/vulnerability-summary.component.ts
Labels: release-note/enhancement

#19561 Avoid menu closure when filtering labels
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
  src/portal/src/app/shared/components/label-selector/label-selector.component.html
  src/portal/src/app/shared/components/label-selector/label-selector.component.ts
Labels: release-note/update

#19570 Correct loop condition for replication tasks
  src/portal/PACKAGE.md
  src/portal/src/app/base/left-side-nav/replication/replication/replication-tasks/replication-tasks.component.ts
Labels: release-note/update

#19584 Add API(audit-log,project,registry,replication) permission testcase
  tests/apitests/python/test_permission.py
Labels: area/test automation/nightly-testing, release-note/infra

#19577 Return empty result when no scanner configured
  src/controller/securityhub/controller.go
  src/pkg/scan/scanner/manager.go
  src/server/v2.0/handler/security.go
Labels: release-note/update

#17396 Feature: GDPR compliant audit logs
  src/common/const.go
  src/controller/user/controller.go
  src/jobservice/job/impl/gdpr/audit_logs_data_masking.go
  src/jobservice/job/impl/gdpr/audit_logs_data_masking_test.go
  src/jobservice/job/known_jobs.go
  src/jobservice/runtime/bootstrap.go
  src/lib/config/metadata/metadatalist.go
  src/lib/config/models/model.go
  src/lib/config/userconfig.go
  src/pkg/audit/dao/dao.go
  src/pkg/audit/manager.go
  src/pkg/user/manager.go
  src/pkg/user/manager_test.go
  src/testing/pkg/audit/dao/dao.go
  src/testing/pkg/audit/manager.go
  src/testing/pkg/user/manager.go
  tests/apitests/python/test_job_service_dashboard.py
Labels: release-note/new-feature, never-stale

#19578 fix: increase beego max memory and upload size
  src/common/const.go
  src/core/main.go
  src/lib/config/metadata/metadatalist.go
  src/lib/config/systemconfig.go
Labels: release-note/update, target/2.10.0

#19601 bump golang to 1.21.4
  .github/workflows/CI.yml
  .github/workflows/build-package.yml
  .github/workflows/conformance_test.yml
  CONTRIBUTING.md
  Makefile
  make/photon/registry/Dockerfile.binary
  make/photon/trivy-adapter/Dockerfile.binary
  make/photon/trivy-adapter/builder.sh
  tests/ci/distro_installer.sh
Labels: release-note/update, target/2.10.0

#19557 perf: optimize the performance of accessory query
  make/migrations/postgresql/0130_2.10.0_schema.up.sql
  src/go.mod
  src/go.sum
  src/pkg/artifact/dao/dao.go
Labels: release-note/enhancement, target/2.10.0

#19604 Bump up version to v2.7.4
  VERSION
Labels: release-note/ignore-for-release

#19598 add permission validation for robot creating and updating.
  src/common/rbac/const.go
  src/server/v2.0/handler/robot.go
  src/server/v2.0/handler/robot_test.go
  tests/apitests/python/library/robot.py
  tests/apitests/python/test_robot_account.py
Labels: area/robot-account, release-note/update, target/2.10.0

#19600 add prepare migration script for 2.10
  make/harbor.yml.tmpl
  make/photon/prepare/commands/migrate.py
  make/photon/prepare/migrations/__init__.py
  make/photon/prepare/migrations/version_2_10_0/__init__.py
  make/photon/prepare/migrations/version_2_10_0/harbor.yml.jinja
Labels: release-note/update, target/2.10.0

#19603 Update the permission scope
  src/common/rbac/const.go
  src/portal/src/app/shared/components/robot-permissions-panel/robot-permissions-panel.component.ts
  tests/apitests/python/test_robot_account.py
Labels: release-note/update, target/2.10.0

#19593 Add test cases for the project level permissions
  tests/apitests/python/test_project_permission.py
Labels: release-note/infra, target/2.10.0

#19595 Add API(scan,volumes,jobservice,scanner,label,securityhub,catalog) permission testcases
  tests/apitests/python/test_permission.py
Labels: area/test automation/pytest-e2e, release-note/infra

#19605 Add notation accessory copy test case
  tests/resources/Harbor-Pages/Project.robot
  tests/resources/Notation_Util.robot
  tests/resources/Util.robot
  tests/robot-cases/Group1-Nightly/Common.robot
  tests/robot-cases/Group1-Nightly/Replication.robot
Labels: area/test automation/nightly-testing, release-note/infra

#19606 [cherry-pick]Add notation accessory copy test case
  tests/resources/Harbor-Pages/Project.robot
  tests/resources/Notation_Util.robot
  tests/resources/Util.robot
  tests/robot-cases/Group1-Nightly/Common.robot
  tests/robot-cases/Group1-Nightly/Replication.robot
Labels: area/test automation/nightly-testing, release-note/infra

#19607 fix: bump TRIVYVERSION=v0.46.1 & TRIVYADAPTERVERSION=v0.30.18
  Makefile
Labels: release-note/update, target/2.7.4

#19620 fix: upgrade github.com/gorilla/mux/otelmux to v0.44.0
  src/go.mod
  src/go.sum
  src/vendor/go.opentelemetry.io/contrib/.gitattributes
  src/vendor/go.opentelemetry.io/contrib/.gitignore
  src/vendor/go.opentelemetry.io/contrib/.golangci.yml
  src/vendor/go.opentelemetry.io/contrib/CHANGELOG.md
  src/vendor/go.opentelemetry.io/contrib/CODEOWNERS
  src/vendor/go.opentelemetry.io/contrib/CONTRIBUTING.md
  src/vendor/go.opentelemetry.io/contrib/LICENSE
  src/vendor/go.opentelemetry.io/contrib/Makefile
  src/vendor/go.opentelemetry.io/contrib/README.md
  src/vendor/go.opentelemetry.io/contrib/RELEASING.md
  src/vendor/go.opentelemetry.io/contrib/contrib.go
  src/vendor/go.opentelemetry.io/contrib/instrumentation/github.com/gorilla/mux/otelmux/config.go
  src/vendor/go.opentelemetry.io/contrib/instrumentation/github.com/gorilla/mux/otelmux/internal/semconvutil/gen.go
  src/vendor/go.opentelemetry.io/contrib/instrumentation/github.com/gorilla/mux/otelmux/internal/semconvutil/httpconv.go
  src/vendor/go.opentelemetry.io/contrib/instrumentation/github.com/gorilla/mux/otelmux/internal/semconvutil/netconv.go
  src/vendor/go.opentelemetry.io/contrib/instrumentation/github.com/gorilla/mux/otelmux/mux.go
  src/vendor/go.opentelemetry.io/contrib/instrumentation/github.com/gorilla/mux/otelmux/version.go
  src/vendor/go.opentelemetry.io/contrib/pre_release.sh
  src/vendor/go.opentelemetry.io/contrib/tag.sh
  src/vendor/modules.txt
Labels: release-note/update, target/2.7.4

#19621 fix system label resource
  src/server/v2.0/handler/label.go
Labels: area/robot-account, release-note/update, target/2.10.0

#19625 Add notation pull policy test case
  tests/resources/Harbor-Pages/Project-Config.robot
  tests/robot-cases/Group1-Nightly/Common.robot
Labels: area/test automation/nightly-testing, release-note/infra

#19628 [cherry-pick]Add jump to CNAB Bundle index artifact list test case
  tests/robot-cases/Group1-Nightly/Common.robot
Labels: area/test automation/nightly-testing, release-note/infra

#19624 fix: update TRIVYVERSION=v0.47.0 && TRIVYADAPTERVERSION=v0.30.19
  Makefile
Labels: release-note/update, target/2.10.0

#19623 Update the test script for the project permissions
  tests/apitests/python/test_project_permission.py
Labels: release-note/infra

#19637 [cherry-pick]Add user API test case
  tests/apitests/python/library/user.py
  tests/apitests/python/test_user_crud.py
  tests/robot-cases/Group0-BAT/API_DB.robot
Labels: area/test automation/pytest-e2e, release-note/infra

#19638 Add user API test case
  tests/apitests/python/library/user.py
  tests/apitests/python/test_user_crud.py
  tests/robot-cases/Group0-BAT/API_DB.robot
Labels: area/test automation/pytest-e2e, release-note/infra

#19644 Refresh base images on release-2.7.0
  .buildbaselog
Labels: release-note/infra, target/2.7.4

#19651 [release-note/docs] swagger.yaml "repositoryName" parameter description update
  api/v2.0/swagger.yaml
Labels: release-note/docs
