Repository goharbor/harbor, pull requests merged in 2023-09, with the labels that each got.

#19262 Switch to a new chart library
  src/portal/package-lock.json
  src/portal/package.json
  src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/single-bar/single-bar.component.ts
  src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-summary/vulnerability-summary.component.html
  src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-summary/vulnerability-summary.component.ts
  src/portal/src/app/shared/shared.module.ts
Labels: release-note/update, target/2.10.0

#19285 Update Support Matrix
  RELEASES.md
Labels: area/doc, release-note/ignore-for-release, target/2.9.0

#19227 Remove job status track information from redis after stop
  src/pkg/jobmonitor/redis.go
  src/pkg/jobmonitor/redis_test.go
Labels: release-note/update

#19307 (cherry-pick) Remove job status track information from redis after stop the job in the queue
  src/pkg/jobmonitor/redis.go
  src/pkg/jobmonitor/redis_test.go
Labels: release-note/update, target/2.9.1

#19305 (cherry-pick) Remove job status track information from redis after stop the job in the queue
  src/pkg/jobmonitor/redis.go
  src/pkg/jobmonitor/redis_test.go
Labels: release-note/update, target/2.8.5

#19306 (cherry-pick) Remove job status track information from redis after stop the job in the queue
  src/pkg/jobmonitor/redis.go
  src/pkg/jobmonitor/redis_test.go
Labels: release-note/update, target/2.7.3

#19314 Bump up version to v2.7.3
  VERSION
Labels: release-note/ignore-for-release, target/2.7.3

#19324 bump goharbor/golang 1.19.13 on release-2.7.0
  .github/workflows/CI.yml
  .github/workflows/build-package.yml
  .github/workflows/conformance_test.yml
  CONTRIBUTING.md
  Makefile
  make/photon/chartserver/builder
  make/photon/golang/Dockerfile
  make/photon/registry/Dockerfile.binary
  make/photon/trivy-adapter/Dockerfile.binary
  make/photon/trivy-adapter/builder.sh
  tests/ci/distro_installer.sh
Labels: release-note/update

#19329 fix: bump up TRIVYVERSION=v0.45.0 && TRIVYADAPTERVERSION=v0.30.16
  Makefile
Labels: release-note/update, target/2.7.3

#18722 remove chart-museum related to logic
  src/server/v2.0/handler/label.go
Labels: release-note/update

#19337 (cherry-pick)fix storage.redirect.disable migrate template error release-2.8.0
  make/photon/prepare/migrations/version_2_8_0/harbor.yml.jinja
Labels: release-note/update, target/2.8.5

#19336 (cherry-pick) fix storage.redirect.disable migrate template error release-2.9.0
  make/photon/prepare/migrations/version_2_8_0/harbor.yml.jinja
  make/photon/prepare/migrations/version_2_9_0/harbor.yml.jinja
Labels: release-note/update, target/2.9.1

#19335 fix storage.redirect.disable migrate template error
  make/photon/prepare/migrations/version_2_8_0/harbor.yml.jinja
  make/photon/prepare/migrations/version_2_9_0/harbor.yml.jinja
Labels: release-note/update, target/2.9.1

#19330 Upgrade UI packages
  src/portal/package-lock.json
  src/portal/package.json
Labels: release-note/update

#19351 [cherry-pick]Refactor unstable test cases
  tests/resources/Harbor-Pages/Administration-Users.robot
  tests/resources/Harbor-Pages/Configuration.robot
  tests/resources/Harbor-Pages/Configuration_Elements.robot
  tests/resources/Harbor-Pages/GC_Elements.robot
  tests/resources/Harbor-Pages/Log_Rotation.robot
  tests/resources/Harbor-Pages/Project-Config.robot
  tests/resources/Harbor-Pages/Project-Copy.robot
  tests/resources/Harbor-Pages/Project-Members.robot
  tests/resources/Harbor-Pages/Project-Members_Elements.robot
  tests/resources/Harbor-Pages/Project-P2P-Preheat.robot
  tests/resources/Harbor-Pages/Project-Repository.robot
  tests/resources/Harbor-Pages/Project-Webhooks.robot
  tests/resources/Harbor-Pages/Project.robot
  tests/resources/Harbor-Pages/Project_Elements.robot
  tests/resources/Harbor-Pages/Public_Elements.robot
  tests/resources/Harbor-Pages/Replication.robot
  tests/resources/Harbor-Pages/Replication_Elements.robot
  tests/resources/Harbor-Pages/Robot_Account.robot
  tests/resources/Harbor-Pages/Robot_Account_Elements.robot
  tests/resources/Harbor-Pages/ToolKit.robot
  tests/resources/Harbor-Pages/Verify.robot
  tests/resources/Harbor-Pages/Vulnerability.robot
  tests/robot-cases/Group1-Nightly/Common.robot
  tests/robot-cases/Group1-Nightly/OIDC.robot
Labels: area/test automation/nightly-testing, release-note/infra

#19350 Refactor unstable test cases
  tests/resources/Harbor-Pages/Administration-Users.robot
  tests/resources/Harbor-Pages/Configuration.robot
  tests/resources/Harbor-Pages/Configuration_Elements.robot
  tests/resources/Harbor-Pages/GC_Elements.robot
  tests/resources/Harbor-Pages/Log_Rotation.robot
  tests/resources/Harbor-Pages/Project-Config.robot
  tests/resources/Harbor-Pages/Project-Copy.robot
  tests/resources/Harbor-Pages/Project-Members.robot
  tests/resources/Harbor-Pages/Project-Members_Elements.robot
  tests/resources/Harbor-Pages/Project-P2P-Preheat.robot
  tests/resources/Harbor-Pages/Project-Repository.robot
  tests/resources/Harbor-Pages/Project-Webhooks.robot
  tests/resources/Harbor-Pages/Project.robot
  tests/resources/Harbor-Pages/Project_Elements.robot
  tests/resources/Harbor-Pages/Public_Elements.robot
  tests/resources/Harbor-Pages/Replication.robot
  tests/resources/Harbor-Pages/Replication_Elements.robot
  tests/resources/Harbor-Pages/Robot_Account.robot
  tests/resources/Harbor-Pages/Robot_Account_Elements.robot
  tests/resources/Harbor-Pages/ToolKit.robot
  tests/resources/Harbor-Pages/Verify.robot
  tests/resources/Harbor-Pages/Vulnerability.robot
  tests/robot-cases/Group1-Nightly/Common.robot
  tests/robot-cases/Group1-Nightly/OIDC.robot
Labels: area/test automation/nightly-testing, release-note/infra

#19349 deprecate resource label
  make/migrations/postgresql/0130_2.10.0_schema.up.sql
  src/common/dao/resource_label.go
  src/common/dao/resource_label_test.go
  src/common/models/base.go
  src/common/models/label.go
  src/common/models/label_test.go
  src/core/api/label_resource.go
  src/core/label/errors.go
  src/core/label/errors_test.go
  src/core/label/manager.go
  src/pkg/label/model/model.go
Labels: release-note/deprecation, target/2.10.0

#19347 Remove duplicated sort fields from order by clause
  src/lib/q/query.go
  src/lib/q/query_test.go
Labels: release-note/update

#19366 fix user resource
  src/server/v2.0/handler/user.go
Labels: release-note/update

#19376 Add security hub API test case
  tests/apitests/python/library/base.py
  tests/apitests/python/library/repository.py
  tests/apitests/python/library/securityhub.py
  tests/apitests/python/test_security_hub.py
  tests/robot-cases/Group0-BAT/API_DB.robot
Labels: area/test automation/pytest-e2e, release-note/infra

#19377 [cherry-pick]Add security hub API test case
  tests/apitests/python/library/base.py
  tests/apitests/python/library/repository.py
  tests/apitests/python/library/securityhub.py
  tests/apitests/python/test_security_hub.py
  tests/robot-cases/Group0-BAT/API_DB.robot
Labels: area/test automation/pytest-e2e, release-note/infra

#19372 update default processor for unknwon type config
  src/controller/artifact/annotation/v1alpha1_test.go
  src/controller/artifact/processor/default.go
  src/controller/artifact/processor/default_test.go
  src/server/middleware/subject/subject.go
Labels: area/OCI, release-note/update, target/2.10.0

#19375 support accessory in either order
  src/pkg/accessory/dao/dao.go
  src/pkg/accessory/dao/dao_test.go
  src/pkg/accessory/manager.go
  src/pkg/accessory/manager_test.go
  src/server/middleware/subject/subject.go
  src/server/middleware/subject/subject_test.go
  src/testing/pkg/accessory/dao/dao.go
  src/testing/pkg/accessory/manager.go
Labels: release-note/update, target/2.10.0

#19396 [Cherry-pick]Hide version property if the value is undefined
  src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-summary/vulnerability-summary.component.html
Labels: release-note/update

#19395 Hide version property if the value is undefined
  src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-summary/vulnerability-summary.component.html
Labels: release-note/update
