Repository goharbor/harbor, pull requests merged in 2023-06, with the labels that each got.

#18776 [cherry-pick]Add Referrers API testcase
  tests/apitests/python/library/cosign.py
  tests/apitests/python/library/referrers_api.py
  tests/apitests/python/test_referrers_api.py
  tests/files/sbom_test.json
  tests/robot-cases/Group0-BAT/API_DB.robot
Labels: area/test automation/pytest-e2e, release-note/infra

#18779 add more details in gc history
  src/controller/gc/callback.go
  src/controller/gc/callback_test.go
  src/jobservice/job/impl/gc/garbage_collection.go
  src/jobservice/job/impl/gc/garbage_collection_test.go
Labels: release-note/enhancement

#18782 fix: update TRIVYVERSION=v0.42.0 & TRIVYADAPTERVERSION=v0.30.12
  Makefile
Labels: release-note/update, target/2.8.2

#18783 Remove wrong format for boolean value in api definition
  api/v2.0/swagger.yaml
Labels: release-note/update

#17392 feat: Optimize quota checking when pushing images
  src/controller/quota/controller_test.go
  src/pkg/quota/util.go
  src/server/middleware/quota/post_initiate_blob_upload.go
  src/server/middleware/quota/post_initiate_blob_upload_test.go
Labels: release-note/enhancement, candidate/2.9.0

#16661 Update/improve grafana dashboard
  contrib/grafana-dashboard/README.md
  contrib/grafana-dashboard/dashboard.png
  contrib/grafana-dashboard/metrics-example.json
  contrib/grafana-dashborad/metrics-example.json
Labels: pending-for-more-info, release-note/update, never-stale

#18790 Add podman pull & push testcase
  tests/apitests/python/library/podman.py
  tests/apitests/python/test_podman_pull_push.py
  tests/apitests/python/test_referrers_api.py
  tests/robot-cases/Group0-BAT/API_DB.robot
  tests/test-engine-image/Dockerfile.api_test
Labels: area/test automation/pytest-e2e, release-note/infra, target/2.9.0

#18787 Add a tooltip for slack notification
  src/portal/src/app/base/project/webhook/add-webhook-form/add-webhook-form.component.html
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: release-note/enhancement

#18784 Changed logic search projects in gitlab adapter for 2.7.0
  src/pkg/reg/adapter/gitlab/adapter.go
  src/pkg/reg/adapter/gitlab/adapter_test.go
  src/pkg/reg/adapter/gitlab/client.go
  src/pkg/reg/adapter/gitlab/testdata/projects/-docker.json
  src/pkg/reg/adapter/gitlab/testdata/projects/dev-.json
Labels: release-note/update

#18717 【UT】add unit test for collector system info
  src/pkg/exporter/system_collector_test.go
Labels: release-note/enhancement

#18795 fix: optimize the mechanism of quota refresh
  src/controller/quota/controller.go
Labels: release-note/update

#18797 Add Details column for gc history
  src/portal/src/app/base/left-side-nav/clearing-job/gc-page/gc/gc-history/gc-history.component.html
  src/portal/src/app/base/left-side-nav/clearing-job/gc-page/gc/gc-history/gc-history.component.scss
  src/portal/src/app/base/left-side-nav/clearing-job/gc-page/gc/gc-history/gc-history.component.ts
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: area/i18n, release-note/enhancement

#18802 [cherry-pick][2.7] fix: add retry on the caller of v2DeleteManifest instead within v2DeleteManifest
  src/jobservice/job/impl/gc/garbage_collection.go
  src/jobservice/job/impl/gc/util.go
Labels: release-note/update, target/2.7.3

#18803 [cherry-pick][2.8] fix: add retry on the caller of v2DeleteManifest instead within v2DeleteManifest
  src/jobservice/job/impl/gc/garbage_collection.go
  src/jobservice/job/impl/gc/util.go
Labels: release-note/update, target/2.8.3

#18810 Add Podman push command to the UI
  src/portal/src/app/base/left-side-nav/clearing-job/gc-page/gc/gc-history/gc-history.component.html
  src/portal/src/app/base/left-side-nav/clearing-job/gc-page/gc/gc-history/gc-history.component.scss
  src/portal/src/app/shared/components/push-image/push-image.component.html
  src/portal/src/app/shared/components/push-image/push-image.component.spec.ts
  src/portal/src/app/shared/components/push-image/push-image.component.ts
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: release-note/enhancement

#18814 Update the text for the oidc cli secret tooltip
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: area/i18n, release-note/update

#18821 jobservice: add DB to job logger config
  src/jobservice/README.md
Labels: release-note/update

#18823 Add Dynatrace as adopter and fix master to main
  ADOPTERS.md
Labels: release-note/community

#18849 jobservice: update readme
  src/jobservice/README.md
  src/jobservice/mgt/manager.go
Labels: release-note/update

#18857 Add new client Podman to the pull command
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/pull-command/pull-command.component.html
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/pull-command/pull-command.component.scss
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/pull-command/pull-command.component.spec.ts
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/pull-command/pull-command.component.ts
  src/portal/src/app/base/project/repository/artifact/artifact-tag/artifact-tag.component.html
  src/portal/src/app/base/project/repository/artifact/artifact-tag/artifact-tag.component.scss
  src/portal/src/app/base/project/repository/artifact/artifact-tag/artifact-tag.component.ts
  src/portal/src/app/base/project/repository/artifact/artifact.module.ts
  src/portal/src/app/base/project/repository/artifact/artifact.ts
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: doc-impact, release-note/enhancement

#18855 add multiple deletion of GC
  src/controller/gc/controller.go
  src/controller/gc/model.go
  src/go.mod
  src/go.sum
  src/jobservice/job/impl/gc/garbage_collection.go
  src/jobservice/job/impl/gc/garbage_collection_test.go
  src/jobservice/job/impl/gc/util.go
  src/jobservice/job/impl/gc/util_test.go
  src/server/v2.0/handler/gc.go
  src/server/v2.0/handler/gc_test.go
  src/vendor/golang.org/x/sync/LICENSE
  src/vendor/golang.org/x/sync/PATENTS
  src/vendor/golang.org/x/sync/errgroup/errgroup.go
  src/vendor/golang.org/x/sync/errgroup/go120.go
  src/vendor/golang.org/x/sync/errgroup/pre_go120.go
  src/vendor/modules.txt
Labels: release-note/enhancement, target/2.9.0

#18854 Update table scan_report and extract cvss_v3_score from vendor attribute
  make/migrations/postgresql/0120_2.9.0_schema.up.sql
  src/pkg/scan/dao/scan/model.go
  src/pkg/scan/dao/scan/report.go
  src/pkg/scan/postprocessors/report_converters.go
  src/pkg/scan/postprocessors/report_converters_test.go
  src/pkg/scan/report/manager.go
  src/testing/pkg/scan/report/manager.go
Labels: release-note/new-feature, target/2.9.0
