Repository goharbor/harbor, pull requests merged in 2023-07, with the labels that each got.

#18873 Add unit test for hidden columns
  src/portal/src/app/base/left-side-nav/replication/replication/list-replication-rule/list-replication-rule.component.spec.ts
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.spec.ts
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
Labels: release-note/update

#18827 Add costomized banner message UI
  README.md
  api/v2.0/swagger.yaml
  src/common/const.go
  src/controller/systeminfo/controller.go
  src/controller/systeminfo/controller_test.go
  src/lib/config/metadata/metadatalist.go
  src/lib/config/userconfig.go
  src/portal/src/app/base/harbor-shell/app-level-alerts/app-level-alerts.component.html
  src/portal/src/app/base/harbor-shell/app-level-alerts/app-level-alerts.component.ts
  src/portal/src/app/base/left-side-nav/config/config.service.ts
  src/portal/src/app/base/left-side-nav/config/config.ts
  src/portal/src/app/base/left-side-nav/config/system/system-settings.component.html
  src/portal/src/app/base/left-side-nav/config/system/system-settings.component.scss
  src/portal/src/app/base/left-side-nav/config/system/system-settings.component.ts
  src/portal/src/app/services/app-config.ts
  src/portal/src/app/services/event-service/event.service.ts
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
  src/server/v2.0/handler/systeminfo.go
Labels: area/i18n, release-note/new-feature

#18882 Add worker parameter for GC
  src/portal/src/app/base/left-side-nav/clearing-job/clearing-job-interfact.ts
  src/portal/src/app/base/left-side-nav/clearing-job/gc-page/gc/gc.component.html
  src/portal/src/app/base/left-side-nav/clearing-job/gc-page/gc/gc.component.scss
  src/portal/src/app/base/left-side-nav/clearing-job/gc-page/gc/gc.component.ts
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: doc-impact, release-note/new-feature

#18885 support OCI-Subject header
  src/server/middleware/subject/subject.go
  src/server/middleware/subject/subject_test.go
Labels: release-note/update, target/2.9.0

#18890 Correct the hidden property for clrDgHideableColumn
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
Labels: release-note/update

#18799 API: update ScannerRegistration.properties.url format
  api/v2.0/swagger.yaml
  src/server/v2.0/handler/model/scanner.go
Labels: release-note/update

#18898 Refactor the keyword in the testcase
  tests/apitests/python/test_proxy_cache.py
  tests/resources/Harbor-Pages/Project-Config.robot
  tests/resources/Harbor-Pages/Project-Members.robot
  tests/resources/Harbor-Pages/Project-P2P-Preheat.robot
  tests/resources/Harbor-Pages/Project-Repository.robot
  tests/resources/Harbor-Pages/Project-Tag-Retention.robot
  tests/resources/Harbor-Pages/Project-Webhooks.robot
  tests/resources/Harbor-Pages/Project.robot
  tests/resources/Harbor-Pages/Replication.robot
  tests/resources/Harbor-Pages/ToolKit.robot
  tests/resources/Harbor-Pages/Verify.robot
  tests/resources/Harbor-Pages/Vulnerability.robot
  tests/resources/TestCaseBody.robot
  tests/resources/Util.robot
  tests/robot-cases/Group0-Util/bundle.json
  tests/robot-cases/Group1-Nightly/Common.robot
  tests/robot-cases/Group1-Nightly/Common_GC.robot
  tests/robot-cases/Group1-Nightly/Replication.robot
  tests/robot-cases/Group1-Nightly/Routing.robot
  tests/robot-cases/Group1-Nightly/Schedule.robot
  tests/robot-cases/Group1-Nightly/Trivy.robot
  tests/robot-cases/Group1-Nightly/multi_scanners.robot
Labels: area/test automation/nightly-testing, release-note/infra, target/2.9.0

#18903 [cherry-pick]Add replication by chunk testcase
  tests/resources/Harbor-Pages/Replication.robot
  tests/resources/Harbor-Pages/Replication_Elements.robot
  tests/robot-cases/Group1-Nightly/Replication.robot
Labels: area/test automation/nightly-testing, release-note/infra

#18904 Add replication by chunk testcase
  tests/resources/Harbor-Pages/Replication.robot
  tests/resources/Harbor-Pages/Replication_Elements.robot
  tests/robot-cases/Group1-Nightly/Replication.robot
Labels: area/test automation/nightly-testing, release-note/infra

#18871 perf: introduce update quota by redis
  src/common/const.go
  src/controller/blob/controller.go
  src/controller/quota/controller.go
  src/go.mod
  src/lib/cache/redis/redis_test.go
  src/lib/config/metadata/metadatalist.go
  src/lib/config/systemconfig.go
  src/lib/redis/client.go
  src/lib/redis/client_test.go
  src/lib/redis/instance.go
  src/lib/redis/instance_test.go
  src/lib/redis/pool.go
  src/vendor/golang.org/x/sync/singleflight/singleflight.go
  src/vendor/modules.txt
Labels: area/performance, release-note/enhancement, target/2.9.0

#18907 [cherry-pick]Add CloudEvents format webhook testcase
  tests/resources/Harbor-Pages/Project-Webhooks.robot
  tests/resources/Harbor-Pages/Project-Webhooks_Elements.robot
  tests/resources/TestCaseBody.robot
  tests/resources/Webhook-Util.robot
  tests/robot-cases/Group1-Nightly/Webhook.robot
Labels: area/test automation/nightly-testing, release-note/infra

#18908 Add CloudEvents format webhook testcase
  tests/resources/Harbor-Pages/Project-Webhooks.robot
  tests/resources/Harbor-Pages/Project-Webhooks_Elements.robot
  tests/resources/TestCaseBody.robot
  tests/resources/Webhook-Util.robot
  tests/robot-cases/Group1-Nightly/Webhook.robot
Labels: area/test automation/nightly-testing, release-note/infra, target/2.9.0

#18915 [cherry-pick]Add OIDC filter group testcase
  tests/resources/Util.robot
  tests/robot-cases/Group1-Nightly/OIDC.robot
Labels: area/test automation/nightly-testing, release-note/infra

#18916 fix: add password/secret length check to be <= 128
  src/controller/robot/controller.go
  src/controller/robot/controller_test.go
  src/server/v2.0/handler/robot.go
  src/server/v2.0/handler/user.go
  src/server/v2.0/handler/user_test.go
Labels: release-note/update

#18921 Add CVE Allowlist expires Test Cases
  tests/resources/Harbor-Pages/Configuration.robot
  tests/resources/Harbor-Pages/Configuration_Elements.robot
  tests/resources/TestCaseBody.robot
  tests/robot-cases/Group1-Nightly/Trivy.robot
Labels: area/test automation/nightly-testing, release-note/infra, target/2.9.0

#18872 Add security hub summary API
  api/v2.0/swagger.yaml
  src/common/rbac/const.go
  src/common/rbac/system/policies.go
  src/controller/securityhub/controller.go
  src/controller/securityhub/controller_test.go
  src/pkg/scan/postprocessors/report_converters.go
  src/pkg/securityhub/dao/security.go
  src/pkg/securityhub/dao/security_test.go
  src/pkg/securityhub/manager.go
  src/pkg/securityhub/model/model.go
  src/server/v2.0/handler/handler.go
  src/server/v2.0/handler/security.go
  src/testing/controller/controller.go
  src/testing/controller/securityhub/controller.go
  src/testing/pkg/pkg.go
  src/testing/pkg/securityhub/manager.go
Labels: release-note/enhancement

#18909 add notation support
  icons/notation.png
  src/controller/icon/controller.go
  src/core/main.go
  src/lib/icon/const.go
  src/pkg/accessory/manager.go
  src/pkg/accessory/model/accessory.go
  src/pkg/accessory/model/notation/notation.go
  src/pkg/accessory/model/notation/notation_test.go
  src/server/middleware/subject/subject.go
Labels: release-note/new-feature, target/2.9.0

#18927 enable notary v2 policy checker
  src/server/middleware/contenttrust/contentrust.go
  src/server/middleware/contenttrust/contentrust_test.go
  src/server/middleware/util/util.go
  src/server/registry/route.go
  tests/apitests/python/test_project_level_policy_content_trust.py
  tests/robot-cases/Group1-Nightly/Common.robot
Labels: release-note/new-feature, target/2.9.0

#18934 fix gc schedule issue
  src/controller/gc/controller.go
  src/controller/gc/controller_test.go
Labels: area/gc, release-note/ignore-for-release, target/2.9.0

#18937 Log warning message when current user is freeze
  src/core/auth/authenticator.go
Labels: release-note/update

#18924 Add vulnerability search API
  api/v2.0/swagger.yaml
  make/migrations/postgresql/0120_2.9.0_schema.up.sql
  src/common/rbac/system/policies.go
  src/controller/securityhub/controller.go
  src/controller/securityhub/controller_test.go
  src/pkg/scan/scanner/manager.go
  src/pkg/scan/scanner/manager_test.go
  src/pkg/securityhub/dao/security.go
  src/pkg/securityhub/dao/security_test.go
  src/pkg/securityhub/manager.go
  src/pkg/securityhub/model/model.go
  src/server/v2.0/handler/security.go
  src/testing/controller/securityhub/controller.go
  src/testing/pkg/scan/scanner/manager.go
  src/testing/pkg/securityhub/manager.go
Labels: release-note/new-feature

#18952 Add Notation UI for deployment security
  src/portal/src/app/base/project/project-config/project-policy-config/project-policy-config.component.html
  src/portal/src/app/base/project/project-config/project-policy-config/project-policy-config.component.ts
  src/portal/src/app/base/project/project-config/project-policy-config/project.ts
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.spec.ts
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/pull-command/pull-command.component.ts
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/sub-accessories/sub-accessories.component.ts
  src/portal/src/app/base/project/repository/artifact/artifact.service.ts
  src/portal/src/app/base/project/repository/artifact/artifact.ts
  src/portal/src/app/services/event-service/event.service.ts
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: release-note/new-feature, target/2.9.0

#18947 Update the regex for policy name and the tooltip message
  src/portal/src/app/base/project/p2p-provider/add-p2p-policy/add-p2p-policy.component.html
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: release-note/update

#18942 Add Security Hub UI
  src/portal/angular.json
  src/portal/package-lock.json
  src/portal/package.json
  src/portal/src/app/base/harbor-shell/harbor-shell.component.ts
  src/portal/src/app/base/left-side-nav/interrogation-services/interrogation-services.component.html
  src/portal/src/app/base/left-side-nav/interrogation-services/interrogation-services.module.ts
  src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/security-hub.component.html
  src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/security-hub.component.scss
  src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/security-hub.component.spec.ts
  src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/security-hub.component.ts
  src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/security-hub.interface.ts
  src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/single-bar/single-bar.component.html
  src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/single-bar/single-bar.component.scss
  src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/single-bar/single-bar.component.spec.ts
  src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/single-bar/single-bar.component.ts
  src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-filter/vulnerability-filter.component.html
  src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-filter/vulnerability-filter.component.scss
  src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-filter/vulnerability-filter.component.spec.ts
  src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-filter/vulnerability-filter.component.ts
  src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-summary/vulnerability-summary.component.html
  src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-summary/vulnerability-summary.component.scss
  src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-summary/vulnerability-summary.component.spec.ts
  src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-summary/vulnerability-summary.component.ts
  src/portal/src/app/base/project/repository/artifact/artifact-additions/artifact-vulnerabilities/artifact-vulnerabilities.component.ts
  src/portal/src/app/base/project/repository/artifact/artifact-summary.component.ts
  src/portal/src/app/base/project/summary/summary.component.html
  src/portal/src/app/services/event-service/event.service.ts
  src/portal/src/app/shared/components/list-repository-ro/list-repository-ro.component.ts
  src/portal/src/app/shared/directives/scroll/scroll-anchor.directive.spec.ts
  src/portal/src/app/shared/directives/scroll/scroll-anchor.directive.ts
  src/portal/src/app/shared/directives/scroll/scroll-manager.service.spec.ts
  src/portal/src/app/shared/directives/scroll/scroll-manager.service.ts
  src/portal/src/app/shared/directives/scroll/scroll-section.directive.spec.ts
  src/portal/src/app/shared/directives/scroll/scroll-section.directive.ts
  src/portal/src/app/shared/shared.module.ts
  src/portal/src/app/shared/units/utils.ts
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: release-note/new-feature

#18949 Create index in vulnerability_record table
  make/migrations/postgresql/0120_2.9.0_schema.up.sql
Labels: release-note/enhancement

#18961 Refresh base images on 2.8
  .buildbaselog
Labels: release-note/infra

#18953 support nydus as a accessory
  src/core/main.go
  src/server/middleware/nydus/nydus.go
  src/server/middleware/nydus/nydus_test.go
  src/server/middleware/subject/subject.go
  src/server/middleware/subject/subject_test.go
Labels: release-note/new-feature, target/2.9.0

#18923 fix: replication policy cron setting - the 1st field must be 0; the Minutes field cannot be *
  src/controller/replication/model/model.go
  src/controller/replication/model/model_test.go
  src/controller/replication/policy_test.go
Labels: release-note/update, target/2.9.0

#18963 Update the parameter to search cosign
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
Labels: release-note/update

#18977 Fix APITEST_DB_PROXY_CACHE x509
  tests/apitests/python/test_proxy_cache.py
Labels: area/test automation/pytest-e2e, release-note/infra

#18978 [cherry-pick]Fix APITEST_DB_PROXY_CACHE x509
  tests/apitests/python/test_proxy_cache.py
Labels: area/test automation/pytest-e2e, release-note/infra

#18979 [cherry-pick]Fix APITEST_DB_PROXY_CACHE x509
  tests/apitests/python/test_proxy_cache.py
Labels: area/test automation/pytest-e2e, release-note/infra

#18959 refactor: remove duplicated artifact deletion handler
  src/controller/event/handler/init.go
  src/controller/event/handler/internal/artifact.go
  src/controller/event/handler/internal/artifact_test.go
  src/controller/event/handler/webhook/scan/delete.go
  src/controller/event/handler/webhook/scan/delete_test.go
Labels: release-note/update, target/2.9.0

#18980 [cherry-pick]Fix APITEST_DB_PROXY_CACHE x509
  tests/apitests/python/test_proxy_cache.py
Labels: area/test automation/pytest-e2e, release-note/infra

#18965 refactor: replace the gc redigo client to the standard cache
  src/jobservice/job/impl/gc/garbage_collection.go
  src/jobservice/job/impl/gc/util.go
  src/jobservice/job/impl/gc/util_test.go
Labels: release-note/update, target/2.9.0

#18928 feat: add the configuration for quota update provider
  make/harbor.yml.tmpl
  make/photon/prepare/models.py
  make/photon/prepare/templates/core/env.jinja
  make/photon/prepare/utils/configs.py
  src/controller/quota/controller.go
Labels: release-note/enhancement, target/2.9.0

#18994 [Cherry-pick] fix: bump-up TRIVYVERSION=v0.43.0 and TRIVYADAPTERVERSION=v0.30.14
  Makefile
Labels: release-note/update, target/2.8.3

#18993 fix: bump-up TRIVYVERSION=v0.43.0 and TRIVYADAPTERVERSION=v0.30.14
  Makefile
Labels: release-note/update, target/2.9.0

#18975 Fix wrong scanned artifact count when there are multiple report for an artifact
  src/pkg/securityhub/dao/security.go
  src/pkg/securityhub/dao/security_test.go
Labels: release-note/update, target/2.9.0

#18998 Update webhook and replication testcase
  tests/resources/Harbor-Pages/Project-P2P-Preheat.robot
  tests/resources/TestCaseBody.robot
  tests/robot-cases/Group1-Nightly/Common_GC.robot
  tests/robot-cases/Group1-Nightly/Replication.robot
  tests/robot-cases/Group1-Nightly/Webhook.robot
Labels: area/test automation/nightly-testing, release-note/infra

#19003 Fix build harbor-db-base error
  make/photon/db/Dockerfile.base
Labels: area/build, release-note/infra, target/2.9.0

#18997 add migration script for 2.9
  make/harbor.yml.tmpl
  make/photon/prepare/commands/migrate.py
  make/photon/prepare/migrations/__init__.py
  make/photon/prepare/migrations/version_2_9_0/__init__.py
  make/photon/prepare/migrations/version_2_9_0/harbor.yml.jinja
Labels: release-note/update, target/2.9.0

#18976 Skip to run migrate script when data available
  make/migrations/postgresql/0120_2.9.0_schema.up.sql
Labels: release-note/update, target/2.9.0

#19001 fix signer name
  src/server/middleware/contenttrust/contentrust.go
  tests/apitests/python/test_project_level_policy_content_trust.py
  tests/robot-cases/Group1-Nightly/Common.robot
Labels: release-note/ignore-for-release, target/2.9.0

#19007 Bump up version to v2.8.3
  VERSION
Labels: release-note/infra

#19024 update installation hint
  make/harbor.yml.tmpl
  make/install.sh
Labels: release-note/update, target/2.9.0

#18990 bump golang1.20.6 on release-2.8.0& build golang based on photon
  .github/workflows/CI.yml
  .github/workflows/build-package.yml
  .github/workflows/conformance_test.yml
  CONTRIBUTING.md
  Makefile
  make/photon/golang/Dockerfile
  make/photon/registry/Dockerfile.binary
  make/photon/trivy-adapter/Dockerfile.binary
  make/photon/trivy-adapter/builder.sh
  tests/ci/distro_installer.sh
Labels: release-note/update, target/2.8.3

#18995 [Cherry-pick] fix: bump-up TRIVYVERSION=v0.43.0 and TRIVYADAPTERVERSION=v0.30.14
  Makefile
Labels: release-note/update, target/2.7.3

#18875 Conserve sentinel_master_set value between upgraded versions
  make/photon/prepare/migrations/version_2_0_0/harbor.yml.jinja
  make/photon/prepare/migrations/version_2_1_0/harbor.yml.jinja
  make/photon/prepare/migrations/version_2_2_0/harbor.yml.jinja
  make/photon/prepare/migrations/version_2_3_0/harbor.yml.jinja
  make/photon/prepare/migrations/version_2_4_0/harbor.yml.jinja
  make/photon/prepare/migrations/version_2_5_0/harbor.yml.jinja
  make/photon/prepare/migrations/version_2_6_0/harbor.yml.jinja
  make/photon/prepare/migrations/version_2_7_0/harbor.yml.jinja
  make/photon/prepare/migrations/version_2_8_0/harbor.yml.jinja
Labels: release-note/update, target/2.9.0, target/2.8.3

#19053 fix accessory import issue
  src/jobservice/main.go
Labels: release-note/update, target/2.9.0

#19050 add details for gc dry-run
  src/jobservice/job/impl/gc/garbage_collection.go
  src/portal/src/app/base/left-side-nav/clearing-job/gc-page/gc/gc-history/gc-history.component.html
  src/portal/src/app/base/left-side-nav/clearing-job/gc-page/gc/gc-history/gc-history.component.ts
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: release-note/ignore-for-release, target/2.9.0

#19054 fixes 19043
  src/server/middleware/util/util.go
Labels: release-note/ignore-for-release, target/2.9.0

#19058 [cherry-pick]fix accessory import issue
  src/jobservice/main.go
Labels: release-note/update, target/2.8.4

#19060 fix dry run creation time
  src/jobservice/job/impl/gc/garbage_collection.go
Labels: release-note/update, target/2.9.0

#19062 Update security hub ui
  src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/security-hub.component.html
  src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/security-hub.component.ts
  src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/security-hub.interface.ts
  src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/single-bar/single-bar.component.ts
  src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-filter/vulnerability-filter.component.ts
  src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-summary/vulnerability-summary.component.html
  src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-summary/vulnerability-summary.component.ts
  src/portal/src/app/shared/services/project.service.ts
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: release-note/update
