Repository goharbor/harbor, pull requests merged in 2023-04, with the labels that each got.

#18445 fix: add default payload_format for http type webhook
  api/v2.0/swagger.yaml
  make/migrations/postgresql/0110_2.8.0_schema.up.sql
  src/server/v2.0/handler/webhook.go
Labels: release-note/ignore-for-release, target/2.8.0

#18460 fix copy artifact issue
  src/server/middleware/blob/copy_artifact.go
Labels: release-note/update, target/2.8.0

#18451 fix: generate uuid as CloudEvents id and add additional requestid
  src/pkg/notifier/formats/cloudevents.go
  src/pkg/notifier/formats/cloudevents_test.go
Labels: area/webhook, release-note/ignore-for-release, target/2.8.0

#18464 [cherry-pick]fix copy artifact issue
  src/server/middleware/blob/copy_artifact.go
Labels: release-note/update, target/2.7.2

#18465 [cherrt-pick]fix copy artifact issue
  src/server/middleware/blob/copy_artifact.go
Labels: release-note/update, target/2.6.5

#18463 Update styles for UI according to the designer's suggestions
  src/portal/src/app/base/left-side-nav/config/system/system-settings.component.scss
  src/portal/src/app/base/project/webhook/excutions/executions.component.scss
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: release-note/enhancement, target/2.8.0

#18462 fix: correct the retention webhook payload
  src/controller/event/handler/webhook/artifact/retention.go
  src/controller/event/metadata/retention.go
  src/controller/event/topic.go
Labels: release-note/update, target/2.8.0

#18458 fix: wrap schedule/exec/task creation as orm tx
  src/controller/systemartifact/execution.go
  src/core/main.go
  src/pkg/scheduler/scheduler.go
  src/pkg/scheduler/scheduler_test.go
Labels: release-note/update, target/2.8.0

#18469 bump golang 1.20.2
  .github/workflows/CI.yml
  .github/workflows/build-package.yml
  .github/workflows/conformance_test.yml
  CONTRIBUTING.md
  Makefile
  make/photon/registry/Dockerfile.binary
  make/photon/trivy-adapter/Dockerfile.binary
  make/photon/trivy-adapter/builder.sh
  tests/ci/distro_installer.sh
Labels: release-note/update, target/2.8.0

#18471 fix accessory replication issue
  src/pkg/reg/adapter/harbor/v2/client.go
Labels: release-note/update, target/2.8.0

#18473 feat: update TRIVYVERSION=v0.38.2 & TRIVYADAPTERVERSION=v0.30.9
  Makefile
Labels: release-note/update, target/2.8.0

#18434 refactor: refresh the execution status in async mode
  src/common/const.go
  src/core/main.go
  src/lib/config/metadata/metadatalist.go
  src/lib/config/systemconfig.go
  src/lib/gtask/pool.go
  src/lib/gtask/pool_test.go
  src/lib/shuffle.go
  src/pkg/task/dao/execution.go
  src/pkg/task/dao/execution_test.go
  src/pkg/task/hook.go
  src/pkg/task/hook_test.go
  src/pkg/task/mock_execution_dao_test.go
  tests/apitests/python/test_log_rotation.py
  tests/ci/api_common_install.sh
Labels: release-note/update, target/2.8.0

#18475 style: adjust the style of migration SQL
  make/migrations/postgresql/0110_2.8.0_schema.up.sql
Labels: release-note/ignore-for-release, target/2.8.0

#18477 Refresh base images on release-2.8.0
  .buildbaselog
Labels: release-note/ignore-for-release

#18482 [cherry-pick] fix: fix the regexp of execution status outdate key
  src/pkg/task/dao/execution.go
  src/pkg/task/dao/execution_test.go
Labels: release-note/ignore-for-release, target/2.8.0

#18481 fix: fix the regexp of execution status outdate key
  src/pkg/task/dao/execution.go
  src/pkg/task/dao/execution_test.go
Labels: release-note/ignore-for-release

#18487 fix: fix error bitsize of jobservice reaper scan locks
  src/jobservice/worker/cworker/reaper.go
Labels: release-note/update

#18490 [cherry-pick]Update UI testcases
  tests/resources/Harbor-Pages/Project-Copy.robot
  tests/resources/Harbor-Pages/Project-P2P-Preheat.robot
  tests/resources/Harbor-Pages/Replication.robot
  tests/resources/Harbor-Pages/Replication_Elements.robot
  tests/robot-cases/Group1-Nightly/Common.robot
Labels: area/test automation/nightly-testing, release-note/infra

#18491 Update UI testcases
  tests/resources/Harbor-Pages/Project-Copy.robot
  tests/resources/Harbor-Pages/Project-P2P-Preheat.robot
  tests/resources/Harbor-Pages/Replication.robot
  tests/resources/Harbor-Pages/Replication_Elements.robot
  tests/robot-cases/Group1-Nightly/Common.robot
Labels: area/test automation/nightly-testing, release-note/infra

#18379 Update proposal process with steps and board
  CONTRIBUTING.md
Labels: release-note/community

#18495 bump golang 1.20.3 on release-2.8.0
  .github/workflows/CI.yml
  .github/workflows/build-package.yml
  .github/workflows/conformance_test.yml
  CONTRIBUTING.md
  Makefile
  make/photon/registry/Dockerfile.binary
  make/photon/trivy-adapter/Dockerfile.binary
  make/photon/trivy-adapter/builder.sh
  tests/ci/distro_installer.sh
Labels: release-note/update

#18492 bump golang 1.20.3 on main
  .github/workflows/CI.yml
  .github/workflows/build-package.yml
  .github/workflows/conformance_test.yml
  CONTRIBUTING.md
  Makefile
  make/photon/registry/Dockerfile.binary
  make/photon/trivy-adapter/Dockerfile.binary
  make/photon/trivy-adapter/builder.sh
  tests/ci/distro_installer.sh
Labels: release-note/update

#18496 bump golang 1.19.8 on release-2.7.0
  .github/workflows/CI.yml
  .github/workflows/build-package.yml
  .github/workflows/conformance_test.yml
  CONTRIBUTING.md
  Makefile
  make/photon/chartserver/builder
  make/photon/registry/Dockerfile.binary
  make/photon/trivy-adapter/Dockerfile.binary
  make/photon/trivy-adapter/builder.sh
  tests/ci/distro_installer.sh
Labels: release-note/update

#18485 bump base version
  VERSION
Labels: release-note/infra

#18493 [cherry-pick] fix: fix error bitsize of jobservice reaper scan locks
  src/jobservice/worker/cworker/reaper.go
Labels: release-note/update, target/2.8.0

#18502 [Cherry-pick] feat: update TRIVYVERSION=v0.39.0 & TRIVYADAPTERVERSION=v0.30.10
  Makefile
Labels: release-note/update, target/2.8.0

#18501 feat: update TRIVYVERSION=v0.39.0 & TRIVYADAPTERVERSION=v0.30.10
  Makefile
Labels: release-note/update

#18510 Update nightly-trivy-scan.yml for the workflows
  .github/workflows/nightly-trivy-scan.yml
Labels: release-note/infra

#18302 Bump up photon version to 4.0 on release-1.10.0
  Makefile
  make/photon/chartserver/Dockerfile.base
  make/photon/clair-adapter/Dockerfile.base
  make/photon/clair/Dockerfile.base
  make/photon/core/Dockerfile.base
  make/photon/db/Dockerfile
  make/photon/db/Dockerfile.base
  make/photon/db/docker-entrypoint.sh
  make/photon/db/initdb.sh
  make/photon/db/postgres.spec
  make/photon/db/rpm_builder.sh
  make/photon/db/upgrade.sh
  make/photon/jobservice/Dockerfile.base
  make/photon/log/Dockerfile.base
  make/photon/nginx/Dockerfile.base
  make/photon/notary-server/Dockerfile.base
  make/photon/notary-signer/Dockerfile.base
  make/photon/portal/Dockerfile.base
  make/photon/prepare/Dockerfile.base
  make/photon/prepare/utils/cert.py
  make/photon/redis/Dockerfile.base
  make/photon/redis/redis.conf
  make/photon/registry/Dockerfile.base
  make/photon/registryctl/Dockerfile.base
Labels: release-note/update

#18513 Reword quotas for 2.8
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
Labels: area/i18n, release-note/update

#18516 Refresh base images on release-2.8.0
  .buildbaselog
Labels: release-note/infra

#18518 Synchronize text modification of quota tooltip to all the i18n files
  src/portal/src/app/base/left-side-nav/project-quotas/project-quotas/edit-project-quotas/edit-project-quotas.component.html
  src/portal/src/app/base/left-side-nav/project-quotas/project-quotas/edit-project-quotas/edit-project-quotas.component.scss
  src/portal/src/app/base/left-side-nav/projects/statictics/statistics-panel.component.html
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: release-note/update

#18386 GC: correctly handle manifest unknown (404) condition in v2DeleteManifest retry loop
  src/jobservice/job/impl/gc/util.go
Labels: release-note/update

#18519 [cherry-pick] fix: clean the redis if the execution is not found
  src/pkg/task/dao/execution.go
  src/pkg/task/sweep_manager.go
Labels: release-note/ignore-for-release, target/2.8.0

#17919 Change the permissions of the *.go file from 0755 to 0644
  src/common/const.go
  src/common/rbac/const.go
  src/core/main.go
  src/pkg/notification/policy/manager.go
  src/pkg/notifier/model/event.go
Labels: release-note/update

#18527 fix: update stopped execution status immediately instead of async update
  src/pkg/task/hook.go
Labels: release-note/ignore-for-release

#18528 [cherry-pick] fix: update stopped execution status immediately instead of async update
  src/pkg/task/hook.go
Labels: release-note/ignore-for-release, target/2.8.0

#18181 feat: log with trace ID
  src/lib/trace/helper.go
  src/lib/trace/helper_test.go
  src/server/middleware/log/log.go
  src/server/middleware/log/log_test.go
Labels: release-note/update

#18151 Fix typos in common.sh
  make/common.sh
Labels: release-note/update

#18547 feat: bump up TRIVYVERSION=v0.39.0, TRIVYADAPTERVERSION=v0.30.10
  Makefile
Labels: release-note/update, target/2.7.2

#18550 Bump up version to v2.7.2
  VERSION
Labels: release-note/ignore-for-release

#18559 feat: update TRIVYVERSION=v0.40.0, TRIVYADAPTERVERSION=v0.30.11
  Makefile
Labels: release-note/update, target/2.7.2

#18555 Add Job Service Dashboard Schedules testcase
  tests/resources/Harbor-Pages/Job_Service_Dashboard.robot
  tests/resources/Harbor-Pages/Job_Service_Dashboard_Elements.robot
  tests/resources/Harbor-Pages/Project-Artifact.robot
  tests/resources/Harbor-Pages/Project-P2P-Preheat.robot
  tests/resources/Harbor-Pages/Project-Tag-Retention.robot
  tests/resources/Harbor-Pages/Project-Tag-Retention_Elements.robot
  tests/resources/Harbor-Pages/Replication.robot
  tests/resources/Harbor-Pages/Vulnerability.robot
  tests/resources/TestCaseBody.robot
  tests/robot-cases/Group1-Nightly/Common.robot
  tests/robot-cases/Group1-Nightly/Schedule.robot
Labels: area/test automation/nightly-testing, release-note/infra

#18557 [cherry-pick]Add Job Service Dashboard Schedules testcase
  tests/resources/Harbor-Pages/Job_Service_Dashboard.robot
  tests/resources/Harbor-Pages/Job_Service_Dashboard_Elements.robot
  tests/resources/Harbor-Pages/Project-Artifact.robot
  tests/resources/Harbor-Pages/Project-P2P-Preheat.robot
  tests/resources/Harbor-Pages/Project-Tag-Retention.robot
  tests/resources/Harbor-Pages/Project-Tag-Retention_Elements.robot
  tests/resources/Harbor-Pages/Replication.robot
  tests/resources/Harbor-Pages/Vulnerability.robot
  tests/resources/TestCaseBody.robot
  tests/robot-cases/Group1-Nightly/Common.robot
  tests/robot-cases/Group1-Nightly/Schedule.robot
Labels: area/test automation/nightly-testing, release-note/infra

#18556 [cherry-pick]Add Job Service Dashboard Schedules testcase
  tests/resources/Harbor-Pages/Job_Service_Dashboard.robot
  tests/resources/Harbor-Pages/Job_Service_Dashboard_Elements.robot
  tests/resources/Harbor-Pages/Project-Artifact.robot
  tests/resources/Harbor-Pages/Project-P2P-Preheat.robot
  tests/resources/Harbor-Pages/Project-Tag-Retention.robot
  tests/resources/Harbor-Pages/Project-Tag-Retention_Elements.robot
  tests/resources/Harbor-Pages/Replication.robot
  tests/resources/Harbor-Pages/Vulnerability.robot
  tests/resources/TestCaseBody.robot
  tests/robot-cases/Group1-Nightly/Common.robot
  tests/robot-cases/Group1-Nightly/Schedule.robot
Labels: area/test automation/nightly-testing, release-note/infra

#18564 Handling skipped but required checks
  .github/workflows/CI.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/pass-CI.yml
  .github/workflows/pass-codeql-analysis.yml
Labels: release-note/infra

#18570 Fix Handling skipped but required checks
  .github/workflows/codeql-analysis.yml
  .github/workflows/pass-CI.yml
  .github/workflows/pass-codeql-analysis.yml
Labels: release-note/infra

#18540 Update Support Matrix
  RELEASES.md
Labels: release-note/infra

#18577 Bump up version to v1.10.18
  .github/workflows/CI.yml
  .github/workflows/build-package.yml
  VERSION
Labels: release-note/ignore-for-release

#18578 Add missing i18n key-value for helm chart
  src/portal/src/app/base/left-side-nav/distribution/distribution-instances/distribution-instances.component.html
  src/portal/src/app/base/project/repository/artifact/artifact-additions/artifact-additions.component.html
  src/portal/src/app/base/project/repository/artifact/artifact-additions/dependencies/dependencies.component.html
  src/portal/src/app/base/project/repository/artifact/artifact-additions/summary/summary.component.html
  src/portal/src/app/base/project/repository/artifact/artifact-additions/values/values.component.html
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: release-note/update

#18579 [Cherry-pick]Add missing i18n key-value for helm chart
  src/portal/src/app/base/left-side-nav/distribution/distribution-instances/distribution-instances.component.html
  src/portal/src/app/base/project/repository/artifact/artifact-additions/artifact-additions.component.html
  src/portal/src/app/base/project/repository/artifact/artifact-additions/dependencies/dependencies.component.html
  src/portal/src/app/base/project/repository/artifact/artifact-additions/summary/summary.component.html
  src/portal/src/app/base/project/repository/artifact/artifact-additions/values/values.component.html
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: release-note/update

#18583 Fix setup docker error
  .github/workflows/build-package.yml
  .github/workflows/publish_release.yml
Labels: area/ci, release-note/infra

#18584 [cherry-pick]Fix setup docker error
  .github/workflows/build-package.yml
  .github/workflows/publish_release.yml
Labels: area/ci, release-note/infra

#18585 [cherry-pick]Fix setup docker error
  .github/workflows/build-package.yml
  .github/workflows/publish_release.yml
Labels: area/ci, release-note/infra

#18582 Add Job Service Dashboard Workers testcase
  tests/resources/Harbor-Pages/Job_Service_Dashboard.robot
  tests/resources/Harbor-Pages/Job_Service_Dashboard_Elements.robot
  tests/robot-cases/Group1-Nightly/Common.robot
Labels: area/test automation/nightly-testing, release-note/infra

#18581 [cherry-pick]Add Job Service Dashboard Workers testcase
  tests/resources/Harbor-Pages/Job_Service_Dashboard.robot
  tests/resources/Harbor-Pages/Job_Service_Dashboard_Elements.robot
  tests/robot-cases/Group1-Nightly/Common.robot
Labels: area/test automation/nightly-testing, release-note/infra

#18580 Add Job Service Dashboard Workers testcase
  tests/resources/Harbor-Pages/Job_Service_Dashboard.robot
  tests/resources/Harbor-Pages/Job_Service_Dashboard_Elements.robot
  tests/robot-cases/Group1-Nightly/Common.robot
Labels: area/test automation/nightly-testing, release-note/infra

#18586 [cherry-pick]allow redis password safe special characters on release-2.7.0
  make/photon/prepare/utils/configs.py
  make/photon/prepare/utils/registry.py
Labels: release-note/update

#18587 [cherry-pick]allow redis password safe special characters on release-2.8.0
  make/photon/prepare/utils/configs.py
  make/photon/prepare/utils/registry.py
Labels: release-note/update

#18566 Allow redis password using safe special characters
  make/photon/prepare/utils/configs.py
  make/photon/prepare/utils/registry.py
Labels: release-note/update

#18282 Fixed Golint & FGT installation commands in Project Setup Documentation
  CONTRIBUTING.md
Labels: release-note/ignore-for-release

#18588 fix: link to Github's rate limiting documentation.
  make/harbor.yml.tmpl
Labels: release-note/update

#18613 Fix message prompt under the header
  src/portal/src/app/base/harbor-shell/harbor-shell.component.html
  src/portal/src/app/base/harbor-shell/harbor-shell.component.scss
Labels: release-note/enhancement

#18605 Specify proper language in CONTRIBUTING.md code blocks
  CONTRIBUTING.md
Labels: release-note/docs

#18622 fix: update TRIVYVERSION=v0.40.0 & TRIVYADAPTERVERSION=v0.30.11
  Makefile
Labels: release-note/update, target/2.7.2

#18610 fix: improve the performance of list artifacts
  make/migrations/postgresql/0120_2.9.0_schema.up.sql
  src/controller/scan/base_controller.go
  src/controller/scan/base_controller_test.go
  src/pkg/task/dao/task.go
  src/pkg/task/dao/task_test.go
  src/pkg/task/mock_task_dao_test.go
  src/pkg/task/mock_task_manager_test.go
  src/pkg/task/task.go
  src/pkg/task/task_test.go
  src/testing/pkg/task/manager.go
Labels: release-note/enhancement, target/2.9.0
