Repository goharbor/harbor, pull requests merged in 2024-11, with the labels that each got.

#21129 Bump up trivy adapter to v0.32.0-rc.2
  Makefile
Labels: release-note/ignore-for-release

#21126 refresh base
  .buildbaselog
Labels: release-note/update

#21150 Update support matrix for 2.12.x
  RELEASES.md
Labels: release-note/ignore-for-release

#21166 refersh base release-2.11.0
  .buildbaselog
Labels: release-note/ignore-for-release

#21167 bump golang to 1.22.9 on release-2.11
  .github/workflows/CI.yml
  .github/workflows/build-package.yml
  .github/workflows/conformance_test.yml
  CONTRIBUTING.md
  Makefile
  make/photon/registry/Dockerfile.binary
  make/photon/trivy-adapter/Dockerfile.binary
  make/photon/trivy-adapter/builder.sh
  src/go.mod
  tests/ci/distro_installer.sh
Labels: release-note/update

#21165 Update image tag for nightly-trivy-scan
  .github/workflows/nightly-trivy-scan.yml
Labels: release-note/ignore-for-release

#21171 replace cicd to registry.goharbor.io on release-2.11.0
  tests/apitests/python/test_proxy_cache.py
  tests/robot-cases/Group1-Nightly/Common.robot
  tests/robot-cases/Group1-Nightly/LDAP.robot
  tests/robot-cases/Group1-Nightly/OIDC.robot
  tests/robot-cases/Group1-Nightly/Replication.robot
  tests/robot-cases/Group1-Nightly/Schedule.robot
Labels: release-note/ignore-for-release

#21168 disable gpg sign for release-2.11.0
  .github/workflows/build-package.yml
Labels: release-note/ignore-for-release

#21177 bump version 2.11.2
  VERSION
Labels: release-note/ignore-for-release

#21178 fix gpg sign build package release-2.11.0
  .github/workflows/build-package.yml
Labels: release-note/ignore-for-release

#21000 [Cherrypick to v2.11] bump up beego to v2.2.1 (#20555)
  src/go.mod
  src/go.sum
  src/lib/orm/query.go
  src/pkg/artifact/dao/dao.go
  src/pkg/task/dao/execution.go
  src/pkg/task/dao/task.go
Labels: release-note/update

#21135 Bump up to trivy adapter v0.32.0
  Makefile
Labels: release-note/ignore-for-release

#21180 bump up dependency on release-2.11.0
  src/go.mod
  src/go.sum
Labels: release-note/update

#21181 Bump up Trivy Adapter for v2.11.x
  Makefile
  make/photon/trivy-adapter/Dockerfile.binary
  make/photon/trivy-adapter/builder.sh
Labels: release-note/update

#21186 remove slack notification release-2.12.0
  .github/workflows/build-package.yml
Labels: release-note/ignore-for-release

#21185 remove slack notification
  .github/workflows/build-package.yml
Labels: release-note/ignore-for-release

#21184 remove slack notification release-2.11.0
  .github/workflows/build-package.yml
Labels: release-note/ignore-for-release

#21183 Change the source of trivy-db to avoid 429 error
  .github/workflows/nightly-trivy-scan.yml
Labels: release-note/ignore-for-release

#21154 update csrf key generation
  src/server/middleware/csrf/csrf.go
  src/server/middleware/csrf/csrf_test.go
Labels: release-note/breaking-change

#21214 remove asc files handling
  tools/release/release_utils.sh
Labels: release-note/infra

#21216 remove asc files handling
  tools/release/release_utils.sh
Labels: release-note/infra

#21217 remove asc files handling
  tools/release/release_utils.sh
Labels: release-note/infra

#21191 Update testcase for test env change, especially for webhook config
  tests/apitests/python/library/cnab.py
  tests/apitests/python/test_push_cnab_bundle.py
  tests/apitests/python/test_system_permission.py
  tests/resources/Docker-Util.robot
  tests/resources/TestCaseBody.robot
  tests/robot-cases/Group1-Nightly/Replication.robot
  tests/robot-cases/Group1-Nightly/Webhook.robot
Labels: release-note/ignore-for-release

#21232 Enable MAX_JOB_DURATION_SECONDS in the jobservice container
  src/go.mod
  src/go.sum
Labels: needs/test-case, release-note/enhancement

#21007 Fix postgres script permissions
  make/photon/db/Dockerfile
Labels: release-note/update

#21215 fix: event-based replication deletion not work when policy with label
  src/controller/artifact/controller.go
  src/controller/artifact/controller_test.go
  src/controller/artifact/model.go
  src/controller/artifact/model_test.go
  src/controller/event/handler/replication/replication.go
  src/controller/event/metadata/artifact.go
  src/controller/event/metadata/tag.go
  src/controller/event/topic.go
  src/server/v2.0/handler/artifact.go
Labels: release-note/update, target/2.13.0

#21234 fix robot deletion event
  src/controller/event/metadata/robot.go
  src/controller/robot/controller.go
  src/controller/robot/model.go
  src/controller/scan/callback.go
  src/controller/scan/callback_test.go
  src/testing/controller/robot/controller.go
Labels: release-note/update
