Repository goharbor/harbor, pull requests merged in 2024-04, with the labels that each got.

#20190 fix: typo
  src/cmd/exporter/main.go
Labels: release-note/update, target/2.11.0

#20195 Bump up version to v2.10.2
  VERSION
Labels: release-note/ignore-for-release, target/2.10.2

#20194 bump golang to 1.21.8 on release-2.10.0
  .github/workflows/CI.yml
  .github/workflows/build-package.yml
  .github/workflows/conformance_test.yml
  CONTRIBUTING.md
  Makefile
  make/photon/registry/Dockerfile.binary
  make/photon/trivy-adapter/Dockerfile.binary
  make/photon/trivy-adapter/builder.sh
  tests/ci/distro_installer.sh
Labels: release-note/update, target/2.10.2

#20196 bump golang 1.21.8 on release-2.9.0
  .github/workflows/CI.yml
  .github/workflows/build-package.yml
  .github/workflows/conformance_test.yml
  CONTRIBUTING.md
  Makefile
  make/photon/registry/Dockerfile.binary
  make/photon/trivy-adapter/Dockerfile.binary
  make/photon/trivy-adapter/builder.sh
  tests/ci/distro_installer.sh
Labels: release-note/update, target/2.9.4

#20197 bump golang 1.21.8 on main
  .github/workflows/CI.yml
  .github/workflows/build-package.yml
  .github/workflows/conformance_test.yml
  CONTRIBUTING.md
  Makefile
  make/photon/registry/Dockerfile.binary
  make/photon/trivy-adapter/Dockerfile.binary
  make/photon/trivy-adapter/builder.sh
  tests/ci/distro_installer.sh
Labels: release-note/update

#20189 fix: close file
  src/pkg/scan/export/digest_calculator.go
Labels: release-note/update

#20210 fix: update TRIVYVERSION=v0.50.1 && TRIVYADAPTERVERSION=v0.30.23
  Makefile
Labels: release-note/update, target/2.10.2

#20211 fix: update TRIVYVERSION=v0.50.1 && TRIVYADAPTERVERSION=v0.30.23
  Makefile
Labels: release-note/update, target/2.9.4

#20212 fix: update TRIVYVERSION=v0.50.1 && TRIVYADAPTERVERSION=v0.30.23
  Makefile
Labels: release-note/update, target/2.8.6

#20222 fix: close file
  src/pkg/scan/export/digest_calculator.go
Labels: release-note/update, target/2.8.6

#20220 fix: close file
  src/pkg/scan/export/digest_calculator.go
Labels: release-note/update, target/2.10.2

#20221 fix: close file
  src/pkg/scan/export/digest_calculator.go
Labels: release-note/update, target/2.9.4

#20214 Update GenAccessoryArt API to generate valid accessory for SBOM
  src/pkg/scan/util.go
  src/pkg/scan/util_test.go
Labels: release-note/update

#20215 Add SBOM scan REST API
  api/v2.0/swagger.yaml
  src/controller/scan/options.go
  src/server/v2.0/handler/scan.go
Labels: release-note/new-feature

#20153 delete membership=0 in getProjectsByName
  src/pkg/reg/adapter/gitlab/client.go
Labels: replication/adapters

#20209 feat: add api test case for quota sorting
  tests/apitests/python/library/quota_sorting.py
  tests/apitests/python/test_quota_sorting.py
  tests/robot-cases/Group0-BAT/API_DB.robot
Labels: release-note/infra, target/2.11.0

#20237 [cherry-pick] Allow empty path in redirect_url
  src/common/utils/utils.go
  src/common/utils/utils_test.go
Labels: release-note/update, target/2.10.2

#20236 [cherry-pick] Allow empty path in redirect_url
  src/common/utils/utils.go
  src/common/utils/utils_test.go
Labels: release-note/update, target/2.9.4

#20240 fix: test robot account permission
  api/v2.0/swagger.yaml
  tests/apitests/python/test_project_permission.py
Labels: release-note/update, target/2.11.0

#20241 fix: test robot account permission
  api/v2.0/swagger.yaml
  tests/apitests/python/test_project_permission.py
Labels: release-note/update, target/2.10.2

#20242 fix: add 400 response code for /scan/{report_id}/log
  api/v2.0/swagger.yaml
Labels: release-note/update, target/2.9.4

#20243 fix: add 400 response code for /scan/{report_id}/log
  api/v2.0/swagger.yaml
Labels: release-note/update, target/2.8.6

#20239 update artifact_type column alteration
  make/migrations/postgresql/0140_2.11.0_schema.up.sql
Labels: release-note/update

#20238 Allow empty path in redirect_url
  src/common/utils/utils.go
  src/common/utils/utils_test.go
Labels: release-note/update

#20225 fix: close blob io ReadCloser
  src/controller/artifact/annotation/v1alpha1.go
Labels: release-note/update

#20177 Refactor scan job service make it easy to add new scan type
  src/controller/scan/base_controller.go
  src/controller/scan/base_controller_test.go
  src/controller/scan/options.go
  src/core/main.go
  src/jobservice/main.go
  src/pkg/scan/handler.go
  src/pkg/scan/job.go
  src/pkg/scan/job_test.go
  src/pkg/scan/rest/v1/models.go
  src/pkg/scan/util.go
  src/pkg/scan/util_test.go
  src/pkg/scan/vuln/report.go
  src/pkg/scan/vulnerability/vul.go
  src/pkg/scan/vulnerability/vul_test.go
Labels: release-note/new-feature

#20207 update referrer manifest descriptor size
  src/server/registry/referrers.go
  src/server/registry/referrers_test.go
Labels: release-note/update, target/2.11.0

#20250 Add auto generate SBOM on push feature
  src/controller/event/handler/internal/artifact.go
  src/controller/event/handler/internal/util.go
  src/controller/event/handler/internal/util_test.go
Labels: release-note/new-feature

#20245 adopt cosign with oci-spec 1.1
  src/server/middleware/cosign/cosign.go
  src/server/middleware/subject/subject.go
Labels: kind/distribution-spec, area/cosign, release-note/update, target/2.11.0

#20179 Updated internationalisation : fr-fr
  src/portal/src/i18n/lang/fr-fr-lang.json
Labels: area/i18n, release-note/update

#20234 Update swagger API to display SBOM content in addition API
  src/controller/artifact/processor/chart/chart.go
  src/controller/artifact/processor/sbom/sbom.go
  src/controller/artifact/processor/sbom/sbom_test.go
Labels: release-note/new-feature

#20244 Support list artifact with_sbom_overview option
  src/controller/scan/base_controller.go
  src/controller/scan/base_controller_test.go
  src/pkg/scan/rest/v1/models.go
  src/pkg/scan/rest/v1/models_test.go
  src/pkg/scan/rest/v1/spec.go
  src/server/v2.0/handler/artifact.go
  src/server/v2.0/handler/assembler/report.go
  src/server/v2.0/handler/assembler/report_test.go
  src/server/v2.0/handler/model/artifact.go
  src/server/v2.0/handler/model/option.go
  src/server/v2.0/handler/model/option_test.go
Labels: release-note/new-feature

#20223 fix: update e2e test engine images
  tests/test-engine-image/Dockerfile.common
  tests/test-engine-image/Dockerfile.ui_test
Labels: area/test automation/pytest-e2e, area/test automation/nightly-testing, release-note/infra, target/2.11.0

#20257 feat: expose `trivy.timeout` to configure the duration to wait for scan completion
  make/harbor.yml.tmpl
Labels: release-note/update, target/2.11.0

#20262 fix: update version to v2.9.4
  VERSION
Labels: release-note/ignore-for-release, target/2.9.4

#20263 bump golang 1.21.9 on release-2.9.0
  .github/workflows/CI.yml
  .github/workflows/build-package.yml
  .github/workflows/conformance_test.yml
  CONTRIBUTING.md
  Makefile
  make/photon/registry/Dockerfile.binary
  make/photon/trivy-adapter/Dockerfile.binary
  make/photon/trivy-adapter/builder.sh
  tests/ci/distro_installer.sh
Labels: release-note/update

#20266 fix: bump up VERSION to v2.8.6
  VERSION
Labels: release-note/ignore-for-release, target/2.8.6

#20256 bump golang to 1.22.2
  .github/workflows/CI.yml
  .github/workflows/build-package.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/conformance_test.yml
  CONTRIBUTING.md
  Makefile
  make/photon/registry/Dockerfile.binary
  make/photon/trivy-adapter/Dockerfile.binary
  make/photon/trivy-adapter/builder.sh
  src/go.mod
  tests/ci/distro_installer.sh
  tests/ci/ut_install.sh
Labels: release-note/update

#20267 bump golang to 1.21.9 on release-2.8.0
  .github/workflows/CI.yml
  .github/workflows/build-package.yml
  .github/workflows/conformance_test.yml
  CONTRIBUTING.md
  Makefile
  make/photon/golang/Dockerfile
  make/photon/registry/Dockerfile.binary
  make/photon/trivy-adapter/Dockerfile.binary
  make/photon/trivy-adapter/builder.sh
  tests/ci/distro_installer.sh
Labels: release-note/update, target/2.8.6

#20270 add SBOM icon
  icons/sbom.png
  src/controller/icon/controller.go
  src/lib/icon/const.go
  src/pkg/accessory/manager.go
Labels: release-note/ignore-for-release, target/2.11.0

#20275 Refresh bash image
  .buildbaselog
Labels: release-note/ignore-for-release, target/2.9.4

#17917 Sending signals by closing the channel
  src/cmd/migrate-patch/main.go
  src/core/main.go
Labels: release-note/update, never-stale

#20278 fix: update the image reference format for audit log when pulling image
  src/controller/event/topic.go
Labels: release-note/update, target/2.11.0

#20274 fix issue 20269
  src/pkg/scan/postprocessors/report_converters.go
  src/pkg/scan/postprocessors/report_converters_test.go
Labels: release-note/update, target/2.11.0

#20285 fix: update TRIVYVERSION=v0.50.1 && TRIVYADAPTERVERSION=v0.31.0
  Makefile
Labels: release-note/update, target/2.11.0

#20251 Add generate SBOM feature
  api/v2.0/swagger.yaml
  src/common/rbac/const.go
  src/common/rbac/project/rbac_role.go
  src/controller/artifact/controller.go
  src/controller/artifact/processor/sbom/sbom.go
  src/controller/artifact/processor/sbom/sbom_test.go
  src/controller/scan/base_controller.go
  src/controller/scan/base_controller_test.go
  src/controller/scanner/base_controller.go
  src/core/main.go
  src/jobservice/main.go
  src/pkg/scan/dao/scanner/model.go
  src/pkg/scan/handler.go
  src/pkg/scan/job.go
  src/pkg/scan/job_test.go
  src/pkg/scan/rest/v1/client.go
  src/pkg/scan/rest/v1/client_test.go
  src/pkg/scan/rest/v1/models.go
  src/pkg/scan/sbom/model/summary.go
  src/pkg/scan/sbom/sbom.go
  src/pkg/scan/sbom/sbom_test.go
  src/pkg/scan/vulnerability/vul.go
  src/pkg/scan/vulnerability/vul_test.go
  src/server/v2.0/handler/model/scanner.go
  src/server/v2.0/handler/project.go
  src/server/v2.0/handler/project_test.go
  src/server/v2.0/handler/scan.go
  src/testing/pkg/scan/rest/v1/client.go
Labels: release-note/new-feature

#20287 feat: add test case for customizing OIDC provider name
  tests/robot-cases/Group1-Nightly/OIDC.robot
Labels: area/test automation/nightly-testing, release-note/infra, target/2.11.0

#20288 Rename scan request type
  api/v2.0/swagger.yaml
  src/controller/scan/base_controller.go
  src/server/v2.0/handler/scan.go
Labels: release-note/update

#20297 refactor: update controller.go
  src/controller/scanner/controller.go
Labels: release-note/update

#19946 SBOM UI feature implementation
  src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.spec.ts
  src/portal/src/app/base/project/repository/artifact/artifact-additions/artifact-additions.component.html
  src/portal/src/app/base/project/repository/artifact/artifact-additions/artifact-additions.component.ts
  src/portal/src/app/base/project/repository/artifact/artifact-additions/artifact-sbom/artifact-sbom.component.html
  src/portal/src/app/base/project/repository/artifact/artifact-additions/artifact-sbom/artifact-sbom.component.scss
  src/portal/src/app/base/project/repository/artifact/artifact-additions/artifact-sbom/artifact-sbom.component.spec.ts
  src/portal/src/app/base/project/repository/artifact/artifact-additions/artifact-sbom/artifact-sbom.component.ts
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list-page.service.ts
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.spec.ts
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
  src/portal/src/app/base/project/repository/artifact/artifact-summary.component.html
  src/portal/src/app/base/project/repository/artifact/artifact-summary.component.spec.ts
  src/portal/src/app/base/project/repository/artifact/artifact-summary.component.ts
  src/portal/src/app/base/project/repository/artifact/artifact.module.ts
  src/portal/src/app/base/project/repository/artifact/artifact.ts
  src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-scan.component.spec.ts
  src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-scan.component.ts
  src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-tip-histogram/sbom-tip-histogram.component.ts
  src/portal/src/app/base/project/repository/artifact/vulnerability-scanning/result-bar-chart.component.spec.ts
  src/portal/src/app/base/project/repository/artifact/vulnerability-scanning/result-bar-chart.component.ts
  src/portal/src/app/services/routing-resolvers/artifact-detail-routing-resolver.service.ts
  src/portal/src/app/shared/shared.module.ts
  src/portal/src/app/shared/units/utils.ts
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/ko-kr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: release-note/update, target/2.11.0

#20298 Allow generate sbom in proxy cache project
  src/server/middleware/repoproxy/proxy.go
  src/server/middleware/repoproxy/proxy_test.go
Labels: release-note/update, target/2.11.0

#20302 Fixed an issue where the scan stop button can only be clicked once
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
Labels: release-note/ignore-for-release

#20299 Add enableCapabilities to extraAttrs for stop
  src/controller/scan/base_controller.go
Labels: release-note/update

#20306 Set default capability for old scanners
  src/pkg/scan/rest/v1/models.go
  src/pkg/scan/rest/v1/models_test.go
Labels: release-note/update

#20308 Wrong values shown for the columns of support_sbom and support_vulnerability in scanner list
  src/portal/src/app/base/left-side-nav/interrogation-services/scanner/config-scanner.component.ts
  src/portal/src/app/base/left-side-nav/interrogation-services/scanner/scanner-metadata/scanner-metadata.html
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/ko-kr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: area/ui, release-note/update, target/2.11.0

#20311 feat: add tc for limited guest of a project to get repository
  .gitignore
  tests/apitests/python/test_user_limited_guest_get_repository.py
  tests/robot-cases/Group0-BAT/API_DB.robot
Labels: area/test automation/nightly-testing, release-note/infra, target/2.11.0

#20314 Log and skip adapter ping error when retrieve adapter capability
  src/controller/scanner/base_controller.go
  src/controller/scanner/controller.go
  src/server/v2.0/handler/project.go
  src/server/v2.0/handler/project_test.go
  src/testing/controller/scanner/controller.go
Labels: release-note/update, target/2.11.0

#20344 Add 422 in the swagger.yaml
  api/v2.0/swagger.yaml
  src/controller/scan/base_controller.go
  src/pkg/scan/sbom/sbom.go
Labels: release-note/update, target/2.11.0

#20348 fix: update image reference to "@" in audit log when pushing & deleting images
  src/controller/event/topic.go
Labels: release-note/update, target/2.11.0

#20358 Add scanner info and report_id to sbom_overview on listing artifact
  api/v2.0/swagger.yaml
  src/controller/scan/base_controller.go
  src/controller/scan/base_controller_test.go
  src/pkg/scan/sbom/model/summary.go
  src/pkg/scan/sbom/sbom.go
  src/server/v2.0/handler/assembler/report.go
Labels: release-note/update

#20366 fix: fresh scanner list when updating scanner
  tests/resources/Harbor-Pages/Vulnerability_Elements.robot
  tests/resources/Util.robot
  tests/robot-cases/Group1-Nightly/Trivy.robot
Labels: area/test automation/nightly-testing, release-note/infra, target/2.11.0

#20354 fix: update nightly test case for verifying audit log of image digest
  tests/robot-cases/Group1-Nightly/Common.robot
Labels: area/test automation/nightly-testing, release-note/infra, target/2.11.0

#20361 fix: update to "clr-dg-cell[10]" to fix the pull time tc due to addin…
  tests/robot-cases/Group1-Nightly/Common.robot
Labels: area/test automation/nightly-testing, release-note/infra, target/2.11.0

#20353 fix: add stop_scan_payload when call stop scan api
  tests/apitests/python/test_project_permission.py
Labels: area/test automation/nightly-testing, release-note/infra, target/2.11.0

#20352 fix: update total permission count to 59
  tests/resources/Harbor-Pages/Project_Robot_Account.robot
  tests/robot-cases/Group1-Nightly/Common.robot
Labels: area/test automation/nightly-testing, release-note/infra, target/2.11.0

#20365 Delete scan_report when accessory is removed
  src/controller/event/handler/internal/artifact.go
  src/pkg/scan/dao/scan/report.go
  src/pkg/scan/dao/scan/report_test.go
  src/pkg/scan/report/manager.go
  src/testing/pkg/scan/report/manager.go
Labels: release-note/update

#20369 fix: update stop scan tc
  tests/resources/Harbor-Pages/Project-Repository.robot
Labels: area/test automation/nightly-testing, release-note/infra, target/2.11.0

#20368 Fix UI sbom status not updated to grid item after job done
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
  src/portal/src/app/base/project/repository/artifact/sbom-scanning/scanning.scss
Labels: release-note/ignore-for-release, target/2.11.0

#20363 Add scan type in webhook event
  src/controller/event/handler/webhook/scan/scan.go
  src/controller/event/metadata/scan.go
  src/controller/event/model/event.go
  src/controller/event/topic.go
  src/controller/scan/callback.go
  src/pkg/notifier/model/event.go
Labels: release-note/update, target/2.11.0

#20360 do not delete accessory relationship while still referenced
  src/controller/artifact/controller.go
Labels: release-note/update, target/2.11.0
