Repository goharbor/harbor, pull requests merged in 2024-02, with the labels that each got.

#19931 fix: cve export label filter xpath
  tests/resources/Harbor-Pages/Project.robot
  tests/resources/Harbor-Pages/SecurityHub.robot
  tests/resources/Harbor-Pages/SecurityHub_Elements.robot
Labels: area/test automation/nightly-testing, release-note/infra

#19930 fix: change filter_label_xpath to vulnerabilities_filter_label_xpath …
  tests/resources/Harbor-Pages/SecurityHub.robot
Labels: area/test automation/nightly-testing, release-note/infra

#19935 add UI test for project quota sorting
  tests/resources/Harbor-Pages/Administration-Project-Quotas.robot
  tests/resources/Harbor-Pages/Administration-Project-Quotas_Elements.robot
  tests/resources/Util.robot
  tests/robot-cases/Group1-Nightly/Common_GC.robot
Labels: area/test automation/nightly-testing, release-note/infra

#19940 add ip_family config in harbor.yml on release-2.9.0
  make/harbor.yml.tmpl
  make/photon/prepare/migrations/version_2_9_0/harbor.yml.jinja
  make/photon/prepare/templates/nginx/nginx.https.conf.jinja
  make/photon/prepare/templates/portal/nginx.conf.jinja
  make/photon/prepare/utils/configs.py
  make/photon/prepare/utils/nginx.py
  make/photon/prepare/utils/portal.py
Labels: release-note/update, target/2.9.3

#19943 Bump up version to v2.9.3
  VERSION
Labels: release-note/ignore-for-release

#19934 add ip_family config in harbor.yml
  make/harbor.yml.tmpl
  make/photon/prepare/migrations/version_2_10_0/harbor.yml.jinja
  make/photon/prepare/migrations/version_2_9_0/harbor.yml.jinja
  make/photon/prepare/templates/nginx/nginx.https.conf.jinja
  make/photon/prepare/templates/portal/nginx.conf.jinja
  make/photon/prepare/utils/configs.py
  make/photon/prepare/utils/nginx.py
  make/photon/prepare/utils/portal.py
Labels: release-note/update

#19939 add ip_family config in harbor.yml on release-2.10
  make/harbor.yml.tmpl
  make/photon/prepare/migrations/version_2_10_0/harbor.yml.jinja
  make/photon/prepare/migrations/version_2_9_0/harbor.yml.jinja
  make/photon/prepare/templates/nginx/nginx.https.conf.jinja
  make/photon/prepare/templates/portal/nginx.conf.jinja
  make/photon/prepare/utils/configs.py
  make/photon/prepare/utils/nginx.py
  make/photon/prepare/utils/portal.py
Labels: release-note/update, target/2.10.1

#19947 [Cherry-pick] fix: cve export label filter xpath (#19931)
  tests/resources/Harbor-Pages/Project.robot
  tests/resources/Harbor-Pages/SecurityHub.robot
  tests/resources/Harbor-Pages/SecurityHub_Elements.robot
Labels: release-note/infra

#19951 reverse ip_family config for release-2.9
  make/harbor.yml.tmpl
  make/photon/prepare/migrations/version_2_9_0/harbor.yml.jinja
  make/photon/prepare/templates/nginx/nginx.https.conf.jinja
  make/photon/prepare/templates/portal/nginx.conf.jinja
  make/photon/prepare/utils/configs.py
  make/photon/prepare/utils/nginx.py
  make/photon/prepare/utils/portal.py
Labels: release-note/update

#19949 remove ipfamily config migrate jinja in 2.9 and 2.10
  make/photon/prepare/migrations/version_2_10_0/harbor.yml.jinja
  make/photon/prepare/migrations/version_2_9_0/harbor.yml.jinja
Labels: release-note/update

#19960 update retry of get_scan_data_export_execution from 5 to 15
  tests/apitests/python/test_scan_data_export.py
Labels: area/test automation/pytest-e2e, release-note/infra

#19958 update retry of get_scan_data_export_execution from 5 to 15
  tests/apitests/python/test_scan_data_export.py
Labels: area/test automation/pytest-e2e, release-note/infra

#19959 update retry of get_scan_data_export_execution from 5 to 15
  tests/apitests/python/test_scan_data_export.py
Labels: area/test automation/pytest-e2e, release-note/infra

#19915 Updated internationalisation : fr-fr
  src/portal/src/i18n/lang/fr-fr-lang.json
Labels: help wanted, area/i18n, release-note/enhancement

#19996 feat: enable configuration of skip_java_db_update
  Makefile
  make/harbor.yml.tmpl
  make/photon/prepare/templates/trivy-adapter/env.jinja
  make/photon/prepare/utils/configs.py
Labels: kind/helm-chart-impact, release-note/update, target/2.11.0

#19998 [Cherry-pick] feat: enable configuration of skip_java_db_update
  Makefile
  make/harbor.yml.tmpl
  make/photon/prepare/templates/trivy-adapter/env.jinja
  make/photon/prepare/utils/configs.py
Labels: kind/helm-chart-impact, release-note/update, target/2.10.1

#19997 [Cherry-pick] feat: enable configuration of skip_java_db_update
  Makefile
  make/harbor.yml.tmpl
  make/photon/prepare/templates/trivy-adapter/env.jinja
  make/photon/prepare/utils/configs.py
Labels: kind/helm-chart-impact, release-note/update, target/2.9.3

#20005 Refresh base images on release-2.9.0
  .buildbaselog
Labels: release-note/infra

#19802 [Token/JWT] Update to golang-jwt v5.2.0
  src/common/const.go
  src/core/service/token/authutils.go
  src/core/service/token/token_test.go
  src/go.mod
  src/go.sum
  src/pkg/token/claims/robot/robot.go
  src/pkg/token/claims/v2/claims.go
  src/pkg/token/claims/v2/claims_test.go
  src/pkg/token/option_test.go
  src/pkg/token/options.go
  src/pkg/token/token.go
  src/pkg/token/token_test.go
  src/server/middleware/security/v2_token.go
Labels: release-note/update, target/2.11.0

#20007 Remove redundant file package-lock.json under src folder
  package-lock.json
Labels: release-note/update

#20013 Limit url to local site
  src/core/controllers/oidc.go
Labels: release-note/update

#20025 Limit url to local path
  src/common/utils/utils.go
  src/common/utils/utils_test.go
  src/core/controllers/oidc.go
Labels: release-note/update

#20020 [cherry-pick] limit url to local site
  src/common/utils/utils.go
  src/common/utils/utils_test.go
  src/core/controllers/oidc.go
Labels: release-note/update, target/2.10.1

#20016 update help message for bandwidth of replication rule
  src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.html
  src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.ts
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: release-note/ignore-for-release, target/2.11.0

#20024 [cherry-pick]Limit URL to local site
  make/photon/db/Dockerfile.base
  src/common/utils/utils.go
  src/common/utils/utils_test.go
  src/core/controllers/oidc.go
Labels: release-note/update, target/2.8.5

#20032 Check if the internal_tls_config is not null when get strong_ssl_ciph…
  make/photon/prepare/utils/configs.py
Labels: release-note/update

#20021 Move strong_ssl_ciphers to top level in harbor.yml
  make/photon/prepare/templates/nginx/nginx.https.conf.jinja
  make/photon/prepare/templates/portal/nginx.conf.jinja
  make/photon/prepare/utils/configs.py
  make/photon/prepare/utils/nginx.py
  make/photon/prepare/utils/portal.py
Labels: release-note/update, target/2.9.3

#20041 Bump up version to v2.8.5
  VERSION
Labels: release-note/ignore-for-release

#20047 Refresh base images on release-2.9.0
  .buildbaselog
Labels: release-note/ignore-for-release

#20049 revise the tags of Interrogation Services
  src/portal/src/app/base/left-side-nav/interrogation-services/interrogation-services.component.html
  src/portal/src/app/base/left-side-nav/interrogation-services/interrogation-services.module.ts
Labels: release-note/docs, target/2.11.0
