Repository goharbor/harbor, pull requests merged in 2024-12, with the labels that each got.

#21272 [cherry-pick] fix robot deletion event (#21234)
  src/controller/event/metadata/robot.go
  src/controller/robot/controller.go
  src/controller/robot/model.go
  src/controller/scan/callback.go
  src/controller/scan/callback_test.go
  src/testing/controller/robot/controller.go
Labels: release-note/update, target/2.12.1

#21278 revert change of artifact event
  src/controller/artifact/controller.go
Labels: release-note/update

#21289 Bump up trivy to v0.57.1 and trivy-adapter to v0.32.1-rc.1
  Makefile
Labels: release-note/update

#21296 revert change of artifact event
  src/controller/artifact/controller.go
Labels: release-note/update, target/2.11.3

#21305 bump go version
  CONTRIBUTING.md
  Makefile
  make/photon/registry/Dockerfile.binary
  make/photon/trivy-adapter/Dockerfile.binary
  make/photon/trivy-adapter/builder.sh
  src/go.mod
  tests/ci/distro_installer.sh
Labels: release-note/update, target/2.12.1

#21310 fix robot account creation issue
  src/server/v2.0/handler/robot.go
  src/server/v2.0/handler/robot_test.go
Labels: release-note/update

#21308 Bump up to use trivy adapter v0.32.1 (GAed version)
  Makefile
Labels: release-note/update, target/2.12.1

#21313 fix robot account creation issue
  src/server/v2.0/handler/robot.go
  src/server/v2.0/handler/robot_test.go
Labels: release-note/update, target/2.12.1

#21322 Bump up trivy adapter to fix a CVE
  Makefile
Labels: release-note/ignore-for-release

#21325 fix export cve permission issue
  src/common/rbac/const.go
Labels: release-note/update

#21115 feat: extend the p2p preheat policy
  Makefile
  api/v2.0/swagger.yaml
  make/migrations/postgresql/0160_2.13.0_schema.up.sql
  make/photon/Makefile
  src/controller/p2p/preheat/enforcer.go
  src/controller/p2p/preheat/enforcer_test.go
  src/pkg/p2p/preheat/models/policy/policy.go
  src/pkg/p2p/preheat/models/policy/policy_test.go
  src/pkg/p2p/preheat/provider/dragonfly.go
  src/pkg/p2p/preheat/provider/dragonfly_test.go
  src/pkg/p2p/preheat/provider/preheat_image.go
  src/portal/src/app/base/project/p2p-provider/add-p2p-policy/add-p2p-policy.component.html
  src/portal/src/app/base/project/p2p-provider/add-p2p-policy/add-p2p-policy.component.ts
  src/portal/src/app/base/project/p2p-provider/p2p-provider.service.ts
  src/portal/src/app/base/project/p2p-provider/policy/policy.component.scss
  src/portal/src/app/base/project/p2p-provider/policy/policy.component.ts
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/ko-kr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
  src/server/v2.0/handler/preheat.go
  src/server/v2.0/handler/preheat_test.go
Labels: release-note/enhancement, candidate/2.13.0, needs/design

#21337 Pin trivy adapter v0.32.2
  Makefile
Labels: release-note/ignore-for-release

#21338 bump go dep
  src/go.mod
  src/go.sum
Labels: release-note/update, target/2.12.2

#21343 Change commit-msg hook.sh address to right place
  CONTRIBUTING.md
Labels: release-note/ignore-for-release

#21357 Fixed the type in DTR adapter info
  src/pkg/reg/adapter/dtr/adapter.go
Labels: release-note/update

#21350 fix: unify the auth data handle to the decode method
  src/pkg/p2p/preheat/instance/manager.go
  src/pkg/p2p/preheat/models/provider/instance.go
  src/pkg/p2p/preheat/models/provider/instance_test.go
Labels: release-note/update, target/2.13.0

#21363 refresh base images
  .buildbaselog
Labels: release-note/infra

#21364 update VERSION
  VERSION
Labels: release-note/infra
