Repository goharbor/harbor, pull requests merged in 2024-10, with the labels that each got.

#21015 Bump up trivy adapter
  Makefile
  make/photon/trivy-adapter/Dockerfile.binary
  make/photon/trivy-adapter/builder.sh
Labels: release-note/ignore-for-release

#21022 add prepare migration script for 2.12.0
  make/harbor.yml.tmpl
  make/photon/prepare/commands/migrate.py
  make/photon/prepare/migrations/__init__.py
  make/photon/prepare/migrations/version_2_12_0/__init__.py
  make/photon/prepare/migrations/version_2_12_0/harbor.yml.jinja
Labels: release-note/update, target/2.12.0

#19658 Feat: add acr ee support
  src/go.mod
  src/go.sum
  src/pkg/reg/adapter/aliacr/adapter.go
  src/pkg/reg/adapter/aliacr/adapter_test.go
  src/pkg/reg/adapter/aliacr/auth.go
  src/pkg/reg/adapter/aliacr/openapi.go
  src/pkg/reg/adapter/aliacr/openapi_test.go
  src/pkg/reg/adapter/aliacr/types.go
  src/portal/src/app/base/left-side-nav/registries/create-edit-endpoint/create-edit-endpoint.component.spec.ts
  src/portal/src/app/base/left-side-nav/registries/endpoint.component.spec.ts
Labels: release-note/new-feature, target/2.12.0

#19692 feat: support Alibaba ACR proxy cache type
  make/photon/prepare/templates/core/env.jinja
  src/portal/src/app/base/left-side-nav/projects/create-project/create-project.component.ts
  src/portal/src/app/shared/services/endpoint.service.ts
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: release-note/update, candidate/2.12.0

#21028 remove the robot update permission
  src/common/rbac/const.go
  src/server/v2.0/handler/robot.go
Labels: release-note/update, target/2.12.0

#21034 Change the log level from warning to debug to avoid noise when there …
  src/core/auth/ldap/ldap.go
Labels: release-note/update

#21046 fix: nil pointer dereference when failed to scan out the quota records from redis
  src/controller/quota/controller.go
Labels: release-note/update

#21035 Change the base directory of prepare container in macOS
  make/prepare
Labels: release-note/update

#21048 Fixes-21021 Display proxy cache in project configuration page
  src/portal/src/app/base/project/project-config/project-policy-config/project-policy-config.component.html
  src/portal/src/app/base/project/project-config/project-policy-config/project-policy-config.component.scss
  src/portal/src/app/base/project/project-config/project-policy-config/project-policy-config.component.spec.ts
  src/portal/src/app/base/project/project-config/project-policy-config/project-policy-config.component.ts
  src/portal/src/app/base/project/project-config/project-policy-config/project.ts
  src/portal/src/app/shared/services/project.service.ts
Labels: release-note/docs

#21047 Change setHealth to setUnHealth to avoid misunderstanding
  src/portal/src/app/app.component.ts
  src/portal/src/app/base/left-side-nav/job-service-dashboard/job-service-dashboard-health-check.service.ts
Labels: release-note/update

#21033 Fix Default Horizontal Scrollbar in Replication Page
  src/portal/src/app/base/left-side-nav/replication/replication/list-replication-rule/list-replication-rule.component.html
  src/portal/src/app/base/left-side-nav/replication/replication/list-replication-rule/list-replication-rule.component.ts
Labels: priority/low, release-note/update, needs/follow-up

#21084 refresh base image
  .buildbaselog
Labels: release-note/update, target/2.12.0

#21081 add pagesize for replicaiton
  src/pkg/reg/adapter/harbor/v2/adapter.go
  src/pkg/reg/adapter/harbor/v2/client.go
Labels: release-note/update, target/2.12.0

#21085 temporary disable gpg sign
  .github/workflows/build-package.yml
Labels: release-note/update

#20483 Fix auth config oidc scope regex
  src/portal/src/app/base/left-side-nav/config/auth/config-auth.component.html
Labels: area/oidc, env/oidc/azure-ad, release-note/update, target/2.13.0

#21087 fix build package issue
  .github/workflows/build-package.yml
Labels: release-note/update

#21090 fix build package issue
  .github/workflows/build-package.yml
Labels: release-note/update, target/2.12.0

#21088 bump up dependencies
  src/go.mod
  src/go.sum
Labels: release-note/ignore-for-release

#20791 Remove unused files
  contrib/Configure_mirror.md
  contrib/registryapi/README.md
  contrib/registryapi/cli.py
  contrib/registryapi/registry.py
Labels: Stale, release-note/ignore-for-release

#21092 bump up dependencies
  src/go.mod
  src/go.sum
Labels: release-note/ignore-for-release

#21095 refresh base for v2.12
  .buildbaselog
Labels: release-note/infra

#21082 Update fr-fr-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
Labels: help wanted, release-note/update, target/2.12.0

#21097 [cherry-pick] Update fr-fr-lang.json (#21082)
  src/portal/src/i18n/lang/fr-fr-lang.json
Labels: release-note/update, target/2.12.0

#21100 fix release script
  .github/workflows/publish_release.yml
Labels: release-note/infra

#21101 fix release script
  .github/workflows/publish_release.yml
Labels: release-note/infra, target/2.12.0

#21113 Update the testcase for v2.12.0, changes include
  tests/apitests/python/library/cnab.py
  tests/apitests/python/test_push_cnab_bundle.py
  tests/resources/Docker-Util.robot
  tests/resources/Harbor-Pages/Configuration.robot
  tests/resources/Harbor-Pages/Configuration_Elements.robot
  tests/resources/Harbor-Pages/Project_Robot_Account.robot
  tests/resources/TestCaseBody.robot
  tests/robot-cases/Group1-Nightly/Common.robot
  tests/robot-cases/Group1-Nightly/P2P_Preheat.robot
  tests/robot-cases/Group1-Nightly/Replication.robot
  tests/robot-cases/Group1-Nightly/Schedule.robot
  tests/robot-cases/Group1-Nightly/Webhook.robot
Labels: release-note/ignore-for-release
