Repository goharbor/harbor, pull requests merged in 2024-08, with the labels that each got.

#20765 refactor: unify the mock file generation
  src/.mockery.yaml
  src/controller/artifact/controller_test.go
  src/controller/artifact/processor/chart/chart_test.go
  src/controller/p2p/preheat/controllor_test.go
  src/controller/p2p/preheat/enforcer_test.go
  src/controller/scan/base_controller_test.go
  src/controller/scan/callback_test.go
  src/controller/securityhub/controller_test.go
  src/controller/tag/controller_test.go
  src/jobservice/job/impl/gc/garbage_collection_test.go
  src/pkg/scan/vulnerability/vul_test.go
  src/testing/lib/libcache/cache.go
  src/testing/pkg/artifactrash/manager.go
  src/testing/pkg/chart/operator.go
  src/testing/pkg/distribution/manifest.go
  src/testing/pkg/immutable/matcher.go
  src/testing/pkg/p2p/preheat/instance/manager.go
  src/testing/pkg/p2p/preheat/policy/manager.go
  src/testing/pkg/parser/parser.go
  src/testing/pkg/processor/processor.go
  src/testing/pkg/scan/dao/scan/vulnerability_record_dao.go
  src/testing/pkg/scan/postprocessors/native_scan_report_converter.go
  src/testing/pkg/scan/postprocessors/report_converters.go
  src/testing/pkg/tag/manager.go
  src/testing/registryctl/client.go
Labels: release-note/update

#20803 add list project arifacts API
  api/v2.0/swagger.yaml
  src/controller/artifact/controller.go
  src/controller/artifact/controller_test.go
  src/controller/artifact/model.go
  src/pkg/artifact/dao/dao.go
  src/pkg/artifact/dao/dao_test.go
  src/pkg/artifact/manager.go
  src/pkg/artifact/manager_test.go
  src/pkg/cached/artifact/redis/manager.go
  src/server/v2.0/handler/artifact.go
  src/server/v2.0/handler/model/artifact.go
  src/server/v2.0/handler/project.go
  src/testing/controller/artifact/controller.go
  src/testing/pkg/artifact/manager.go
Labels: release-note/enhancement, target/2.12.0

#20814 [cherry-pick ]Release 2.11.0 cp 20803
  api/v2.0/swagger.yaml
  src/controller/artifact/controller.go
  src/controller/artifact/controller_test.go
  src/controller/artifact/model.go
  src/pkg/artifact/dao/dao.go
  src/pkg/artifact/dao/dao_test.go
  src/pkg/artifact/manager.go
  src/pkg/artifact/manager_test.go
  src/pkg/cached/artifact/redis/manager.go
  src/server/v2.0/handler/artifact.go
  src/server/v2.0/handler/model/artifact.go
  src/server/v2.0/handler/project.go
  src/testing/controller/artifact/controller.go
  src/testing/pkg/artifact/manager.go
Labels: release-note/update, target/2.11.1

#20816 Fixes-20799 can't remove artifact labels
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
Labels: release-note/ignore-for-release

#20817 cherry-pick: Fixes-20799 can't remove artifact labels
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
Labels: release-note/ignore-for-release

#20648 Extend AWS ECR regex for c2s support
  src/pkg/reg/adapter/awsecr/adapter.go
  src/pkg/reg/adapter/awsecr/adapter_test.go
Labels: release-note/update

#20812 feat: implement bandwidth limit for proxy-cache
  api/v2.0/swagger.yaml
  src/controller/proxy/controller.go
  src/controller/proxy/options.go
  src/controller/proxy/options_test.go
  src/controller/proxy/remote.go
  src/controller/replication/transfer/image/transfer.go
  src/lib/iothrottler.go
  src/pkg/project/models/pro_meta.go
  src/pkg/project/models/project.go
  src/server/middleware/repoproxy/proxy.go
  src/server/middleware/repoproxy/tag.go
  src/server/v2.0/handler/project.go
  src/server/v2.0/handler/project_metadata.go
Labels: release-note/new-feature, target/2.12.0

#20824 cherry-pick #20603
  src/pkg/task/sweep_manager.go
Labels: release-note/update, 2.11.1

#20826 Refresh base images
  .buildbaselog
Labels: release-note/ignore-for-release, target/2.11.1

#20705 Parallel attach ldap group
  api/v2.0/swagger.yaml
  make/photon/prepare/templates/nginx/nginx.http.conf.jinja
  src/common/const.go
  src/core/auth/ldap/ldap.go
  src/lib/config/metadata/metadatalist.go
  src/lib/config/models/model.go
  src/lib/config/userconfig.go
  src/portal/src/app/base/left-side-nav/config/auth/config-auth.component.html
  src/portal/src/app/base/left-side-nav/config/auth/config-auth.component.ts
  src/portal/src/app/base/left-side-nav/config/config.ts
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
Labels: release-note/enhancement, target/2.12.0

#20619 remove migrate-patch
  Makefile
  src/cmd/migrate-patch/README.md
  src/cmd/migrate-patch/main.go
Labels: release-note/update, target/2.12.0, target/2.11.1

#20834 remove migrate patch
  Makefile
  src/cmd/migrate-patch/README.md
  src/cmd/migrate-patch/main.go
Labels: release-note/update, target/2.11.1

#20832 Check create when fire the artifact event
  src/controller/artifact/controller.go
Labels: release-note/update, target/2.11.1

#20827 Bump up version to v2.11.1
  VERSION
Labels: release-note/ignore-for-release, target/2.11.1

#20838 [cherry-pick] Check create when fire the artifact event
  src/controller/artifact/controller.go
Labels: release-note/update, target/2.11.1

#20659 Fix #20658 docker-compose `version` is obsolete warning
  make/photon/prepare/templates/docker_compose/docker-compose.yml.jinja
Labels: release-note/infra

#20839 fix: bump up golang to v1.22.6
  .github/workflows/CI.yml
  .github/workflows/build-package.yml
  .github/workflows/conformance_test.yml
  CONTRIBUTING.md
  Makefile
  make/photon/registry/Dockerfile.binary
  make/photon/trivy-adapter/Dockerfile.binary
  make/photon/trivy-adapter/builder.sh
  src/go.mod
  tests/ci/distro_installer.sh
Labels: release-note/update, target/2.11.1

#20830 fix: fix the GC job index data race
  src/jobservice/job/impl/gc/garbage_collection.go
Labels: area/gc, release-note/update, target/2.12.0

#20841 Fix typo in Swagger API docs
  api/v2.0/swagger.yaml
Labels: release-note/ignore-for-release

#20845 fix: update e2e test engine images
  tests/test-engine-image/Dockerfile.common
  tests/test-engine-image/Dockerfile.ui_test
Labels: area/test automation/pytest-e2e, area/test automation/nightly-testing, release-note/infra, target/2.12.0

#20843 enable audit log for robot
  src/controller/event/handler/auditlog/auditlog.go
  src/controller/event/handler/init.go
  src/controller/event/metadata/robot.go
  src/controller/event/metadata/robot_test.go
  src/controller/event/topic.go
  src/controller/robot/controller.go
  src/controller/robot/controller_test.go
Labels: release-note/new-feature, target/2.12.0

#20846 add creator for robot
  api/v2.0/swagger.yaml
  make/migrations/postgresql/0150_2.12.0_schema.up.sql
  src/controller/robot/controller.go
  src/controller/robot/controller_test.go
  src/controller/scan/base_controller.go
  src/controller/scan/base_controller_test.go
  src/pkg/robot/dao/dao_test.go
  src/pkg/robot/model/model.go
  src/server/v2.0/handler/model/robot.go
  src/server/v2.0/handler/robot.go
Labels: release-note/new-feature, target/2.12.0

#20854 fix: bump trivy-adapter version to v0.31.4 and trivy version to v0.54.1;
  .buildbaselog
  Makefile
Labels: release-note/update, target/2.11.1

#20842 [cherry-pick] Check create when fire the artifact event
  src/controller/artifact/controller.go
Labels: release-note/update

#20858 fix: update helm.sh/helm/v3 and github.com/google/go-containerregistry
  src/go.mod
  src/go.sum
Labels: release-note/update

#20872 fix: migrate cicd to registry goharbor
  tests/apitests/python/test_proxy_cache.py
  tests/robot-cases/Group1-Nightly/Common.robot
  tests/robot-cases/Group1-Nightly/LDAP.robot
  tests/robot-cases/Group1-Nightly/OIDC.robot
  tests/robot-cases/Group1-Nightly/Replication.robot
  tests/robot-cases/Group1-Nightly/Schedule.robot
Labels: area/test automation/nightly-testing, release-note/update

#18679 Feature export Harbor statistics as Prometheus metric
  src/pkg/exporter/collector_test.go
  src/pkg/exporter/exporter.go
  src/pkg/exporter/project_collector_test.go
  src/pkg/exporter/statistics_collector.go
  src/pkg/exporter/statistics_collector_test.go
Labels: release-note/enhancement, never-stale, candidate/2.12.0

#20871 Fixed the ui bug of banner coming over the search result container
  src/portal/src/app/shared/components/global-search/search-result.component.html
  src/portal/src/app/shared/components/global-search/search-result.component.ts
  src/portal/src/app/shared/components/global-search/search.component.scss
Labels: area/ui, release-note/update

#20861 Fix typos in src/common
  src/common/api/base.go
  src/common/const.go
  src/common/http/tls.go
  src/common/job/client.go
  src/common/job/models/models.go
  src/common/models/job.go
  src/common/models/uaa.go
  src/common/rbac/project/evaluator_test.go
  src/common/secret/request.go
  src/common/utils/email/mail.go
  src/common/utils/email/mail_test.go
  src/common/utils/encrypt.go
  src/common/utils/passports.go
  src/common/utils/test/config.go
  src/common/utils/test/test.go
  src/common/utils/utils.go
  src/server/route.go
Labels: release-note/ignore-for-release

#20886 [Cherrypick to v2.11]add Test Case for SBOM feature (#20797)
  tests/apitests/python/library/artifact.py
  tests/apitests/python/library/scan.py
  tests/apitests/python/library/scan_stop.py
  tests/apitests/python/test_project_permission.py
  tests/apitests/python/test_sbom_generation_of_image_artifact.py
  tests/apitests/python/test_stop_sbom_generation_of_image_artifact.py
  tests/resources/Harbor-Pages/Project-Repository.robot
  tests/resources/Harbor-Pages/Project-Repository_Elements.robot
  tests/resources/Harbor-Pages/Vulnerability.robot
  tests/resources/TestCaseBody.robot
  tests/robot-cases/Group0-BAT/API_DB.robot
  tests/robot-cases/Group1-Nightly/Trivy.robot
Labels: release-note/ignore-for-release

#20883 refactor: remove useless error check for scan data export job
  src/jobservice/job/impl/scandataexport/scan_data_export.go
Labels: release-note/update, area/cve-export
