Repository goharbor/harbor, pull requests merged in 2024-09, with the labels that each got.

#20892 Escape the - with \- when it is a char of itself
  src/portal/src/app/base/left-side-nav/projects/create-project/create-project.component.html
  src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.html
  src/portal/src/app/base/left-side-nav/system-robot-accounts/new-robot/new-robot.component.html
  src/portal/src/app/base/project/robot-account/add-robot/add-robot.component.html
Labels: area/ui, release-note/update

#20900 Update ".buildbaselog" to trigger refresh of base image
  .buildbaselog
Labels: release-note/ignore-for-release

#20905 Install docker-compose in build-package action
  .github/workflows/build-package.yml
Labels: release-note/ignore-for-release

#20907 update the version of docker-compose to be installed in "build-package"
  .github/workflows/build-package.yml
Labels: release-note/ignore-for-release

#20916 bump up the pacakges in base image
  .buildbaselog
Labels: release-note/ignore-for-release

#20918 update robot creator database scheme
  api/v2.0/swagger.yaml
  make/migrations/postgresql/0150_2.12.0_schema.up.sql
  src/controller/robot/controller.go
  src/controller/scan/base_controller.go
  src/controller/scan/base_controller_test.go
  src/pkg/robot/dao/dao_test.go
  src/pkg/robot/model/model.go
  src/server/v2.0/handler/model/robot.go
  src/server/v2.0/handler/robot.go
Labels: area/robot-account, release-note/update, target/2.12.0

#20942 Update fr-fr-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
Labels: help wanted, release-note/update

#20922 Refactor: p2p preheat dragonfly driver
  api/v2.0/swagger.yaml
  make/migrations/postgresql/0150_2.12.0_schema.up.sql
  src/controller/p2p/preheat/enforcer.go
  src/controller/p2p/preheat/enforcer_test.go
  src/pkg/p2p/preheat/instance/manager.go
  src/pkg/p2p/preheat/job.go
  src/pkg/p2p/preheat/models/policy/policy.go
  src/pkg/p2p/preheat/models/policy/policy_test.go
  src/pkg/p2p/preheat/provider/dragonfly.go
  src/pkg/p2p/preheat/provider/dragonfly_test.go
  src/pkg/p2p/preheat/provider/driver.go
  src/pkg/p2p/preheat/provider/mock.go
  src/pkg/p2p/preheat/provider/preheat_image.go
  src/portal/src/app/base/project/p2p-provider/add-p2p-policy/add-p2p-policy.component.html
  src/portal/src/app/base/project/p2p-provider/add-p2p-policy/add-p2p-policy.component.ts
  src/portal/src/app/base/project/p2p-provider/p2p-provider.service.ts
  src/portal/src/app/base/project/p2p-provider/policy/policy.component.ts
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/ko-kr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
  src/server/v2.0/handler/preheat.go
  src/server/v2.0/handler/preheat_test.go
Labels: kind/refactor, area/P2P-Distribution, release-note/enhancement, release-note/update

#20955 bump up dependencies
  src/go.mod
  src/go.sum
Labels: release-note/ignore-for-release

#20929 Update comments in template file of installation configurations
  make/harbor.yml.tmpl
Labels: release-note/ignore-for-release

#20959 Bump up portal packages
  src/portal/app-swagger-ui/package-lock.json
  src/portal/app-swagger-ui/package.json
  src/portal/package-lock.json
  src/portal/package.json
Labels: release-note/ignore-for-release

#20754 enable robot full access
  src/common/rbac/const.go
  src/common/rbac/const_test.go
  src/controller/robot/controller.go
  src/controller/robot/model.go
  src/controller/scan/base_controller.go
  src/controller/scan/base_controller_test.go
  src/portal/src/app/base/left-side-nav/system-robot-accounts/system-robot-util.ts
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/ko-kr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
  src/server/v2.0/handler/permissions.go
  src/server/v2.0/handler/robot.go
  src/server/v2.0/handler/robot_test.go
Labels: release-note/new-feature, target/2.12.0

#20946 UI Changes for Configuring Proxy-Cache Speed Limit
  src/portal/src/app/base/left-side-nav/projects/create-project/create-project.component.html
  src/portal/src/app/base/left-side-nav/projects/create-project/create-project.component.ts
  src/portal/src/app/base/project/project.ts
  src/portal/src/app/shared/entities/shared.const.ts
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/ko-kr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: release-note/enhancement, target/2.12.0

#20968 fix: p2p instance test connection
  src/pkg/p2p/preheat/provider/client/http_client.go
  src/pkg/p2p/preheat/provider/dragonfly.go
  src/portal/src/app/base/left-side-nav/distribution/distribution-setup-modal/distribution-setup-modal.component.ts
  src/server/v2.0/handler/preheat.go
  src/server/v2.0/handler/preheat_test.go
Labels: area/P2P-Distribution, release-note/update
