Repository goharbor/harbor, pull requests merged in 2024-01, with the labels that each got.

#19753 update project-SelectScanner modal Default field css
  src/portal/src/app/base/project/scanner/scanner.component.html
Labels: release-note/update

#19789 Bump up PostgreSQL from 14 to 15
  make/photon/db/Dockerfile
  make/photon/db/Dockerfile.base
Labels: area/database, release-note/update

#19786 fix invalid links in harbor.yml.tmpl
  make/harbor.yml.tmpl
Labels: release-note/update

#19799 Add quota permissions to robot account
  src/common/rbac/const.go
  src/portal/src/app/base/left-side-nav/system-robot-accounts/system-robot-util.ts
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: area/robot-account, release-note/update

#19800 [cherry-pick]Add quota permissions to robot account
  src/common/rbac/const.go
  src/portal/src/app/base/left-side-nav/system-robot-accounts/system-robot-util.ts
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: area/robot-account, release-note/update, target/2.10.1

#19721 registryctl/api/registry/blob: fix dropped test error
  src/registryctl/api/registry/blob/blob_test.go
Labels: release-note/update

#19818 [cherry-pick]Remove robot account update quota permission
  src/common/rbac/const.go
Labels: release-note/update

#19819 Remove robot account update quota permission
  src/common/rbac/const.go
Labels: release-note/update

#19801 Cache image list with digest key
  src/controller/proxy/controller.go
  src/controller/proxy/controller_test.go
  src/controller/proxy/manifestcache.go
Labels: area/proxy-cache, release-note/update

#19822 Add quota permissions testcase
  tests/apitests/python/test_system_permission.py
  tests/resources/Harbor-Pages/Project_Robot_Account.robot
  tests/robot-cases/Group1-Nightly/Common.robot
Labels: area/test automation/nightly-testing, release-note/infra

#19823 [cherry-pick]Add quota permissions testcase
  tests/apitests/python/test_system_permission.py
  tests/resources/Harbor-Pages/Project_Robot_Account.robot
  tests/robot-cases/Group1-Nightly/Common.robot
Labels: area/test automation/nightly-testing, release-note/infra

#19828 deprecate gosec in makefile
  Makefile
Labels: release-note/infra

#19838 [cherry-pick] Cache image list with digest key
  src/controller/proxy/controller.go
  src/controller/proxy/controller_test.go
  src/controller/proxy/manifestcache.go
Labels: release-note/update, target/2.10.1

#19829 Add verification that robot account duration is not 0
  api/v2.0/swagger.yaml
  src/controller/robot/controller.go
  src/controller/scan/base_controller.go
  src/controller/scan/base_controller_test.go
  src/server/v2.0/handler/model/robot.go
  src/server/v2.0/handler/robot.go
  src/server/v2.0/handler/robot_test.go
Labels: area/robot-account, release-note/update

#19837 [cherry-pick] Cache image list with digest key
  src/controller/proxy/controller.go
  src/controller/proxy/controller_test.go
  src/controller/proxy/manifestcache.go
Labels: release-note/update, target/2.9.2

#19807 fix artifact page bug
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-filter/artifact-filter.component.html
  src/portal/src/app/shared/components/label-selector/label-selector.component.spec.ts
  src/portal/src/app/shared/components/label-selector/label-selector.component.ts
Labels: release-note/update

#19815 [Cherry pick] add repository read permission to limitedGuest
  src/common/rbac/project/rbac_role.go
Labels: release-note/update, target/2.9.2

#19816 [Cherry pick] add repository read permission to limitedGuest
  src/common/rbac/project/rbac_role.go
Labels: release-note/update, target/2.10.1

#19845 remove the log for ScannerSkipUpdatePullTime
  src/lib/config/userconfig.go
Labels: release-note/ignore-for-release

#19294 Log ensureArtifact ConflictErr
  src/controller/artifact/controller.go
  src/controller/artifact/controller_test.go
Labels: release-note/update

#19840 Fixing typo for About UI
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
Labels: release-note/update

#19846 [cherry-pick]remove the log for ScannerSkipUpdatePullTime
  src/lib/config/userconfig.go
Labels: release-note/enhancement, target/2.10.1

#19847 [cherry-pick]remove the log for ScannerSkipUpdatePullTime
  src/lib/config/userconfig.go
Labels: release-note/enhancement, target/2.9.2

#19848 Bump up version to v2.9.2
  VERSION
Labels: release-note/ignore-for-release

#19851 Refresh base images on release-2.9.0
  .buildbaselog
Labels: release-note/update

#19843 Update isValidDuration function
  src/server/v2.0/handler/robot.go
Labels: area/robot-account, release-note/update

#19850 fix label select bugs
  src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.scss
  src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.ts
Labels: release-note/update

#19857 fix: update to TRIVYVERSION=v0.48.3 and TRIVYADAPTERVERSION=v0.30.21
  Makefile
Labels: release-note/update, target/2.9.2

#19456 feat: volc cr adapter
  src/go.mod
  src/go.sum
  src/jobservice/job/impl/replication/replication.go
  src/pkg/reg/adapter/volcenginecr/adapter.go
  src/pkg/reg/adapter/volcenginecr/adapter_test.go
  src/pkg/reg/adapter/volcenginecr/artifact_registry.go
  src/pkg/reg/adapter/volcenginecr/artifact_registry_test.go
  src/pkg/reg/adapter/volcenginecr/auth.go
  src/pkg/reg/adapter/volcenginecr/auth_test.go
  src/pkg/reg/adapter/volcenginecr/consts.go
  src/pkg/reg/adapter/volcenginecr/helper.go
  src/pkg/reg/adapter/volcenginecr/helper_test.go
  src/pkg/reg/adapter/volcenginecr/volccr.go
  src/pkg/reg/adapter/volcenginecr/volccr_test.go
  src/pkg/reg/manager.go
  src/pkg/reg/model/registry.go
  src/portal/src/app/shared/services/endpoint.service.ts
Labels: area/replication, release-note/new-feature, target/2.11.0

#19339 skip transaction for POST /service/token
  src/core/middlewares/middlewares.go
Labels: release-note/enhancement, release-note/update

#19862 [cherry-pick]fix label select bugs (#19850)
  src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.scss
  src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.ts
Labels: release-note/update

#19861 [cherry-pick]fix label select bugs (#19850)
  src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.scss
  src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.ts
Labels: release-note/update

#19891 Refresh base images on release-2.9.0
  .buildbaselog
Labels: release-note/update

#19869 feat: add auto_sbom_generation for SBOM auto generation on pushing a …
  api/v2.0/swagger.yaml
Labels: release-note/update, target/2.11.0

#19895 Update replication rule filter label xpath
  tests/resources/Harbor-Pages/Replication_Elements.robot
Labels: release-note/infra

#19901 [cherry-pick]Update replication rule filter label xpath
  tests/resources/Harbor-Pages/Replication_Elements.robot
Labels: area/test automation/nightly-testing, release-note/infra, target/2.9.2

#19893 [cherry-pick]add v6 port for nginx ad portal config
  make/photon/prepare/templates/nginx/nginx.https.conf.jinja
  make/photon/prepare/templates/portal/nginx.conf.jinja
Labels: release-note/update, target/2.9.2

#19868 add v6 port for nginx and portal config
  make/photon/prepare/templates/nginx/nginx.https.conf.jinja
  make/photon/prepare/templates/portal/nginx.conf.jinja
Labels: release-note/update, target/2.11.0

#19904 [Cherry-Pick] Update replication rule filter label xpath (#19895)
  tests/resources/Harbor-Pages/Replication_Elements.robot
Labels: release-note/infra, target/2.10.1

#19894 [cherry-pick]add v6 port for nginx ad portal config
  make/photon/prepare/templates/nginx/nginx.https.conf.jinja
  make/photon/prepare/templates/portal/nginx.conf.jinja
Labels: release-note/update, target/2.10.1

#19913 fix: cve export label filter xpath
  tests/resources/Harbor-Pages/Project.robot
  tests/resources/Harbor-Pages/SecurityHub.robot
  tests/resources/Harbor-Pages/SecurityHub_Elements.robot
Labels: release-note/infra
