Repository goharbor/harbor, pull requests merged in 2024-05, with the labels that each got.

#20390 fix update TRIVYVERSION=v0.50.4 & TRIVYADAPTERVERSION=v0.31.1
  Makefile
Labels: release-note/update, target/2.11.0

#20378 fix: enale stop_scan for ci
  tests/ci/api_run.sh
Labels: area/ci, release-note/update, target/2.11.0

#20414 Update scan job request log for enabled_capabilities
  src/pkg/scan/job.go
Labels: release-note/update, target/2.11.0

#20416 fix issue 20407
  src/pkg/scan/rest/v1/models.go
  src/pkg/scan/sbom/sbom.go
  src/pkg/scan/sbom/sbom_test.go
  src/pkg/scan/util.go
Labels: release-note/update, target/2.11.0

#20415 Skip scan in-toto sbom artifact
  src/controller/artifact/controller.go
  src/controller/artifact/controller_test.go
  src/controller/scan/base_controller.go
  src/controller/scan/base_controller_test.go
  src/controller/scan/checker.go
  src/controller/scan/checker_test.go
  src/testing/controller/artifact/controller.go
Labels: release-note/update, target/2.11.0

#20400 add membership=true back for gitlab replication adapter
  src/pkg/reg/adapter/gitlab/client.go
Labels: area/test automation/nightly-testing, release-note/update, release-note/infra, target/2.11.0

#20425 Display status in sbom_overview for image index
  src/server/v2.0/handler/assembler/report.go
  src/server/v2.0/handler/assembler/report_test.go
Labels: release-note/update, target/2.11.0

#20423 Add additional link for sboms
  src/controller/artifact/model.go
  src/server/v2.0/handler/assembler/report.go
  src/server/v2.0/handler/assembler/report_test.go
Labels: release-note/update, target/2.11.0

#20433 bump golang 1.22.3
  .github/workflows/CI.yml
  .github/workflows/build-package.yml
  .github/workflows/conformance_test.yml
  CONTRIBUTING.md
  Makefile
  make/photon/registry/Dockerfile.binary
  make/photon/trivy-adapter/Dockerfile.binary
  make/photon/trivy-adapter/builder.sh
  src/go.mod
  tests/ci/api_common_install.sh
  tests/ci/distro_installer.sh
Labels: release-note/update

#20437 Initialize execution Manager in Report Assembler
  src/server/v2.0/handler/assembler/report.go
Labels: release-note/update, target/2.11.0

#20426 Fix and Should to display Unsupported if no SBOM accessories found
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
  src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-scan-component.html
  src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-scan.component.spec.ts
  src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-scan.component.ts
  src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-tip-histogram/sbom-tip-histogram.component.html
  src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-tip-histogram/sbom-tip-histogram.component.spec.ts
  src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-tip-histogram/sbom-tip-histogram.component.ts
  src/portal/src/app/base/project/repository/artifact/vulnerability-scanning/result-bar-chart.component.ts
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/ko-kr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: release-note/ignore-for-release, target/2.11.0

#20438 fresh base image
  .buildbaselog
Labels: release-note/ignore-for-release, target/2.11.0

#20442 fix: update doublestar lib
  src/go.mod
  src/go.sum
  tests/ci/api_common_install.sh
Labels: release-note/update, target/2.10.3

#20443 fix: update doublestar dep
  src/go.mod
  src/go.sum
  src/vendor/github.com/bmatcuk/doublestar/.gitignore
  src/vendor/github.com/bmatcuk/doublestar/.travis.yml
  src/vendor/github.com/bmatcuk/doublestar/README.md
  src/vendor/github.com/bmatcuk/doublestar/doublestar.go
  src/vendor/modules.txt
  tests/ci/api_common_install.sh
Labels: release-note/update, target/2.9.5

#20441 fix ui test failure
  src/portal/package-lock.json
  src/portal/package.json
  src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-scan.component.spec.ts
Labels: release-note/ignore-for-release

#20444 Cherry-pick 20441-fix ui test failure
  src/portal/package-lock.json
  src/portal/package.json
  src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-scan.component.spec.ts
Labels: release-note/ignore-for-release, target/2.11.0

#20460 Fix-20459 Wrong sbom status displayed in UI
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
  src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-scan.component.spec.ts
  src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-scan.component.ts
  src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-tip-histogram/sbom-tip-histogram.component.html
  src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-tip-histogram/sbom-tip-histogram.component.scss
  src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-tip-histogram/sbom-tip-histogram.component.ts
Labels: release-note/ignore-for-release

#20450 Bump up trivy version to v0.51.2, trivyadapter to v0.31.2
  Makefile
Labels: release-note/update

#20468 bump up trivy and trivy-adapter version
  Makefile
Labels: release-note/update, target/2.11.0

#20475 Fix - 20469 sbom status and download issue
  src/portal/src/app/base/project/repository/artifact/artifact-additions/artifact-sbom/artifact-sbom.component.ts
  src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-scan.component.spec.ts
  src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-scan.component.ts
Labels: release-note/ignore-for-release, target/2.11.0

#20471 Fix - 20469 sbom status and download issue
  src/portal/src/app/base/project/repository/artifact/artifact-additions/artifact-sbom/artifact-sbom.component.ts
  src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-scan.component.spec.ts
  src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-scan.component.ts
Labels: area/ui, release-note/update

#20473 Add sbom_report table to store sbom related information
  make/migrations/postgresql/0140_2.11.0_schema.up.sql
  src/controller/event/handler/internal/artifact.go
  src/controller/event/handler/webhook/scan/scan.go
  src/controller/scan/base_controller.go
  src/controller/scan/base_controller_test.go
  src/controller/scan/controller.go
  src/pkg/scan/dao/scan/report_test.go
  src/pkg/scan/handler.go
  src/pkg/scan/job.go
  src/pkg/scan/job_test.go
  src/pkg/scan/sbom/dao/dao.go
  src/pkg/scan/sbom/dao/dao_test.go
  src/pkg/scan/sbom/manager.go
  src/pkg/scan/sbom/model/report.go
  src/pkg/scan/sbom/sbom.go
  src/pkg/scan/sbom/sbom_test.go
  src/pkg/scan/vulnerability/vul.go
  src/pkg/scan/vulnerability/vul_test.go
  src/pkg/task/mock_task_manager_test.go
  src/pkg/task/task.go
  src/pkg/task/task_test.go
  src/server/v2.0/handler/assembler/report.go
  src/testing/controller/scan/controller.go
  src/testing/pkg/pkg.go
  src/testing/pkg/scan/handler.go
  src/testing/pkg/scan/sbom/manager.go
  src/testing/pkg/task/manager.go
Labels: release-note/update, target/2.11.0

#20482 [cherry-pick] Add sbom_report table to store sbom related information
  make/migrations/postgresql/0140_2.11.0_schema.up.sql
  src/controller/event/handler/internal/artifact.go
  src/controller/event/handler/webhook/scan/scan.go
  src/controller/scan/base_controller.go
  src/controller/scan/base_controller_test.go
  src/controller/scan/controller.go
  src/pkg/scan/dao/scan/report_test.go
  src/pkg/scan/handler.go
  src/pkg/scan/job.go
  src/pkg/scan/job_test.go
  src/pkg/scan/sbom/dao/dao.go
  src/pkg/scan/sbom/dao/dao_test.go
  src/pkg/scan/sbom/manager.go
  src/pkg/scan/sbom/model/report.go
  src/pkg/scan/sbom/sbom.go
  src/pkg/scan/sbom/sbom_test.go
  src/pkg/scan/vulnerability/vul.go
  src/pkg/scan/vulnerability/vul_test.go
  src/pkg/task/mock_task_manager_test.go
  src/pkg/task/task.go
  src/pkg/task/task_test.go
  src/server/v2.0/handler/assembler/report.go
  src/testing/controller/scan/controller.go
  src/testing/pkg/pkg.go
  src/testing/pkg/scan/handler.go
  src/testing/pkg/scan/sbom/manager.go
  src/testing/pkg/task/manager.go
Labels: release-note/update, target/2.11.0

#20507 Bump up base image
  .buildbaselog
Labels: release-note/ignore-for-release, target/2.11.0

#20508 [cherry-pick] Separate the execution vendor type sbom from image_scan
  src/controller/scan/base_controller.go
  src/controller/scan/base_controller_test.go
  src/jobservice/job/known_jobs.go
  src/pkg/scan/handler.go
  src/pkg/scan/sbom/sbom.go
  src/pkg/scan/vulnerability/vul.go
  src/testing/pkg/scan/handler.go
Labels: release-note/update, target/2.11.0

#20511 [cherry-pick] Fix tooltip issue related to SBOM.Details
  src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-tip-histogram/sbom-tip-histogram.component.html
Labels: release-note/update, target/2.11.0

#20509 [cherry-pick] fix 20496
  src/pkg/scan/sbom/sbom.go
  src/pkg/scan/sbom/sbom_test.go
Labels: release-note/update, target/2.11.0

#20503 Fix multiple SBOM
  src/pkg/scan/sbom/sbom.go
  src/pkg/scan/sbom/sbom_test.go
Labels: release-note/update, target/2.11.0

#20510 Fix tooltip issue related to SBOM.Details
  src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-tip-histogram/sbom-tip-histogram.component.html
Labels: release-note/update

#20514 tls support for pushing sbom
  src/pkg/scan/util.go
Labels: release-note/update, target/2.11.0

#20515 tls support for pushing sbom
  src/pkg/scan/util.go
Labels: release-note/update, target/2.11.0

#20520 Fix UI bugs - Pagination is missing on tag immutability rules
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.scss
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.spec.ts
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
  src/portal/src/app/base/project/repository/artifact/artifact.ts
  src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-scan.component.spec.ts
  src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-scan.component.ts
  src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-tip-histogram/sbom-tip-histogram.component.html
  src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-tip-histogram/sbom-tip-histogram.component.scss
  src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-tip-histogram/sbom-tip-histogram.component.spec.ts
  src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-tip-histogram/sbom-tip-histogram.component.ts
  src/portal/src/app/base/project/repository/artifact/sbom-scanning/scanning.scss
  src/portal/src/app/base/project/tag-feature-integration/immutable-tag/immutable-tag.component.ts
  src/portal/src/app/shared/units/utils.ts
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/ko-kr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: release-note/ignore-for-release, target/2.11.0

#20501 Fix UI bugs - Pagination is missing on tag immutability rules
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.scss
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.spec.ts
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
  src/portal/src/app/base/project/repository/artifact/artifact.ts
  src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-scan.component.spec.ts
  src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-scan.component.ts
  src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-tip-histogram/sbom-tip-histogram.component.html
  src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-tip-histogram/sbom-tip-histogram.component.scss
  src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-tip-histogram/sbom-tip-histogram.component.spec.ts
  src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-tip-histogram/sbom-tip-histogram.component.ts
  src/portal/src/app/base/project/repository/artifact/sbom-scanning/scanning.scss
  src/portal/src/app/base/project/tag-feature-integration/immutable-tag/immutable-tag.component.ts
  src/portal/src/app/shared/units/utils.ts
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/ko-kr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: release-note/ignore-for-release, target/2.11.0

#20522 [cherry-pick] fix 20518
  src/pkg/scan/sbom/sbom.go
Labels: release-note/update, target/2.11.0

#20521 fix 20518
  src/pkg/scan/sbom/sbom.go
Labels: release-note/update, target/2.11.0

#20528 [cherry-pick] fix http client to push sbom accessory
  src/pkg/scan/util.go
Labels: release-note/update, target/2.11.0

#20527 [cherry-pick] Response an error message when there is incomplete sbom generate job
  src/pkg/scan/sbom/sbom.go
  src/pkg/scan/sbom/sbom_test.go
  src/pkg/task/mock_task_manager_test.go
  src/pkg/task/task.go
  src/testing/pkg/task/manager.go
Labels: release-note/update, target/2.11.0

#20525 fix http client to push sbom accessory
  src/pkg/scan/util.go
Labels: release-note/update

#20526 Response an error message when there is incomplete sbom generate job
  src/pkg/scan/sbom/sbom.go
  src/pkg/scan/sbom/sbom_test.go
  src/pkg/task/mock_task_manager_test.go
  src/pkg/task/task.go
  src/testing/pkg/task/manager.go
Labels: release-note/update, target/2.11.0
