Repository goharbor/harbor, pull requests merged in 2024-03, with the labels that each got.

#20069 add sbom settings for project
  src/pkg/project/models/pro_meta.go
  src/pkg/project/models/project.go
  src/server/v2.0/handler/project_metadata.go
Labels: release-note/update, target/2.11.0

#20068 update referrers api
  src/server/registry/referrers.go
  src/server/registry/referrers_test.go
Labels: kind/distribution-spec, release-note/update, target/2.11.0

#20075 Update migration tools
  tools/migrate_chart/Dockerfile
  tools/migrate_chart/migrate_chart.py
  tools/migrate_chart/test_migrate_chart.py
Labels: release-note/ignore-for-release

#20059 Configure to auto generate SBOM or not on project configuration page.
  src/portal/src/app/base/project/project-config/project-policy-config/project-policy-config.component.html
  src/portal/src/app/base/project/project-config/project-policy-config/project-policy-config.component.spec.ts
  src/portal/src/app/base/project/project-config/project-policy-config/project-policy-config.component.ts
  src/portal/src/app/base/project/project-config/project-policy-config/project.ts
  src/portal/src/app/base/project/project.ts
  src/portal/src/app/shared/services/project.service.ts
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: area/i18n, release-note/new-feature, release-note/docs, target/2.11.0

#20106 fix: typos
  make/harbor.yml.tmpl
Labels: release-note/update

#20094 Update swagger.yaml bad request permission: helm-chart:read
  api/v2.0/swagger.yaml
Labels: release-note/update

#20097 add generate sbom object utility
  src/controller/scan/base_controller.go
  src/go.mod
  src/go.sum
  src/pkg/scan/rest/v1/models.go
  src/pkg/scan/util.go
  src/pkg/scan/util_test.go
  src/server/middleware/subject/subject_test.go
  src/server/registry/referrers_test.go
Labels: release-note/new-feature, target/2.11.0

#20030 Update support for artifactType for both manifest and index
  make/migrations/postgresql/0140_2.11.0_schema.up.sql
  src/controller/artifact/abstractor.go
  src/controller/artifact/abstractor_test.go
  src/controller/artifact/processor/default_test.go
  src/go.mod
  src/go.sum
  src/pkg/artifact/dao/model.go
  src/pkg/artifact/model.go
  src/pkg/artifact/model_test.go
  src/pkg/blob/dao/dao_test.go
  src/pkg/blob/manager_test.go
  src/pkg/securityhub/dao/security_test.go
  src/server/middleware/subject/subject.go
  src/server/registry/referrers.go
  src/server/registry/referrers_test.go
Labels: kind/distribution-spec, release-note/update

#20073 Update deletion for index type of accessory
  src/controller/artifact/controller.go
  src/server/registry/manifest.go
Labels: kind/distribution-spec, release-note/update, target/2.11.0

#20122 Bump up version to v2.10.1
  VERSION
Labels: release-note/ignore-for-release, target/2.10.1

#19883 [new-feature]Add Korean Translation
  src/portal/src/i18n/lang/ko-kr-lang.json
Labels: help wanted, area/i18n, release-note/new-feature, target/2.11.0

#20126 fix: assign metas to key and value
  src/server/v2.0/handler/project_metadata.go
Labels: release-note/update, target/2.9.4

#20127 fix: assign metas to key and value
  src/server/v2.0/handler/project_metadata.go
Labels: release-note/update, target/2.8.6

#20128 fix: scanner tab change
  tests/resources/Harbor-Pages/Vulnerability.robot
Labels: release-note/infra, target/2.11.0

#20108 add type for scanner metadata
  api/v2.0/swagger.yaml
  src/pkg/scan/rest/v1/client_test.go
  src/pkg/scan/rest/v1/models.go
  src/server/v2.0/handler/model/scanner.go
Labels: release-note/update, target/2.11.0

#20161 panic due to mark retention task error
  src/controller/replication/execution.go
  src/controller/replication/execution_test.go
  src/controller/retention/controller.go
  src/controller/systemartifact/execution.go
  src/controller/systemartifact/execution_test.go
  src/pkg/task/dao/task.go
  src/pkg/task/dao/task_test.go
  src/pkg/task/execution.go
  src/testing/pkg/task/execution_manager.go
Labels: release-note/update

#20159 chore: fix function names
  src/pkg/joblog/manager.go
  src/server/v2.0/handler/model/webhook_policy.go
Labels: release-note/update

#20169 [cherry-pick] panic due to mark retention task error
  src/controller/replication/execution.go
  src/controller/replication/execution_test.go
  src/controller/retention/controller.go
  src/controller/systemartifact/execution.go
  src/controller/systemartifact/execution_test.go
  src/pkg/task/dao/task.go
  src/pkg/task/dao/task_test.go
  src/pkg/task/execution.go
  src/testing/pkg/task/execution_manager.go
Labels: release-note/update, target/2.10.2

#20168 [cherry-pick] panic due to mark retention task error
  src/controller/replication/execution.go
  src/controller/replication/execution_test.go
  src/controller/retention/controller.go
  src/controller/systemartifact/execution.go
  src/controller/systemartifact/execution_test.go
  src/pkg/task/dao/task.go
  src/pkg/task/dao/task_test.go
  src/pkg/task/execution.go
  src/testing/pkg/task/execution_manager.go
Labels: release-note/update, target/2.8.6

#20170 [cherry-pick] panic due to mark retention task error
  src/controller/replication/execution.go
  src/controller/replication/execution_test.go
  src/controller/retention/controller.go
  src/controller/systemartifact/execution.go
  src/controller/systemartifact/execution_test.go
  src/pkg/task/dao/task.go
  src/pkg/task/dao/task_test.go
  src/pkg/task/execution.go
  src/testing/pkg/task/execution_manager.go
Labels: release-note/update, target/2.9.4

#20111 Add two columns to display capability type for scanner
  src/portal/src/app/base/left-side-nav/interrogation-services/scanner/config-scanner.component.html
  src/portal/src/app/base/left-side-nav/interrogation-services/scanner/config-scanner.component.scss
  src/portal/src/app/base/left-side-nav/interrogation-services/scanner/config-scanner.component.ts
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: release-note/docs, target/2.11.0

#20087 ScanAll should only log an error when an error occurs
  src/controller/scan/base_controller.go
Labels: release-note/update, target/2.11.0

#18992 fix image name extraction
  src/controller/event/handler/webhook/artifact/replication.go
  src/controller/event/handler/webhook/artifact/replication_test.go
Labels: Stale, release-note/update
