Repository goharbor/harbor, pull requests merged in 2025-06, with the labels that each got.

#20736 README.md: add artifact hub badge
  README.md
Labels: release-note/docs

#22050 chore: fix the arguments for codecov v5
  .github/workflows/CI.yml
Labels: release-note/update

#22082 Update contributing.md
  CONTRIBUTING.md
Labels: release-note/docs

#22104 update robot case for get harbor version
  tests/resources/Harbor-Util.robot
Labels: release-note/ignore-for-release

#22095 Update CHANGELOG.md, RELEASES.md and ROADMAP.md
  CHANGELOG.md
  RELEASES.md
  ROADMAP.md
Labels: release-note/docs
