Repository goharbor/harbor, pull requests merged in 2025-03, with the labels that each got.

#21155 Revamp Copy Pull Command
  src/portal/src/app/base/harbor-shell/harbor-shell.component.html
  src/portal/src/app/base/harbor-shell/harbor-shell.component.spec.ts
  src/portal/src/app/base/harbor-shell/harbor-shell.component.ts
  src/portal/src/app/base/modal-events.const.ts
  src/portal/src/app/base/preference-settings/preference-settings.component.html
  src/portal/src/app/base/preference-settings/preference-settings.component.scss
  src/portal/src/app/base/preference-settings/preference-settings.component.spec.ts
  src/portal/src/app/base/preference-settings/preference-settings.component.ts
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.scss
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/pull-command/pull-command.component.html
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/pull-command/pull-command.component.spec.ts
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/pull-command/pull-command.component.ts
  src/portal/src/app/base/project/repository/artifact/artifact-tag/artifact-tag.component.html
  src/portal/src/app/base/project/repository/artifact/artifact-tag/artifact-tag.component.scss
  src/portal/src/app/base/project/repository/artifact/artifact.ts
  src/portal/src/app/shared/components/navigator/navigator.component.html
  src/portal/src/app/shared/components/navigator/navigator.component.ts
  src/portal/src/app/shared/components/push-image/copy-input.coponent.html
  src/portal/src/app/shared/entities/shared.const.ts
  src/portal/src/app/shared/shared.module.ts
  src/portal/src/app/shared/units/shared.utils.ts
  src/portal/src/css/common.scss
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/ko-kr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: area/ui, doc-impact, release-note/enhancement, target/2.13.0

#21702 Add PKCE support for OIDC authentication
  src/core/controllers/oidc.go
  src/go.mod
  src/go.sum
  src/lib/trace/trace.go
  src/pkg/oidc/helper.go
  src/pkg/oidc/helper_test.go
Labels: release-note/enhancement, target/2.13.0

#21681 update tlsOptions for external redis
  make/harbor.yml.tmpl
  make/photon/prepare/utils/configs.py
Labels: release-note/update, target/2.13.0

#21680 add prepare migration script for 2.13.0
  make/harbor.yml.tmpl
  make/photon/prepare/commands/migrate.py
  make/photon/prepare/migrations/__init__.py
  make/photon/prepare/migrations/version_2_13_0/__init__.py
  make/photon/prepare/migrations/version_2_13_0/harbor.yml.jinja
Labels: release-note/update, target/2.13.0

#21606 Update UI version in package.json to v2.13.0
  src/portal/package.json
Labels: release-note/ignore-for-release

#21703 Change audit log label
  src/pkg/auditext/event/user/user.go
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/ko-kr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: release-note/update, target/2.13.0

#21663 feat: implement the CNAI model processor
  api/v2.0/swagger.yaml
  icons/cnai.png
  src/controller/artifact/abstractor.go
  src/controller/artifact/controller.go
  src/controller/artifact/processor/cnai/cnai.go
  src/controller/artifact/processor/cnai/cnai_test.go
  src/controller/artifact/processor/cnai/parser/base.go
  src/controller/artifact/processor/cnai/parser/base_test.go
  src/controller/artifact/processor/cnai/parser/files.go
  src/controller/artifact/processor/cnai/parser/files_test.go
  src/controller/artifact/processor/cnai/parser/license.go
  src/controller/artifact/processor/cnai/parser/license_test.go
  src/controller/artifact/processor/cnai/parser/parser.go
  src/controller/artifact/processor/cnai/parser/readme.go
  src/controller/artifact/processor/cnai/parser/readme_test.go
  src/controller/artifact/processor/cnai/parser/util.go
  src/controller/artifact/processor/cnai/parser/util_test.go
  src/controller/icon/controller.go
  src/go.mod
  src/go.sum
  src/lib/icon/const.go
  src/pkg/artifact/model.go
Labels: release-note/new-feature, target/2.13.0

#21726 fix issue 20828
  src/controller/artifact/controller.go
  src/controller/artifact/controller_test.go
Labels: release-note/update, target/2.13.0

#21733 consume the downstream distribution
  Makefile
Labels: release-note/update

#21720 Fix: Copy Pull Button Overlap with Tag Immutable Label
  src/portal/src/app/base/preference-settings/preference-settings.component.scss
  src/portal/src/app/base/project/repository/artifact/artifact-tag/artifact-tag.component.html
  src/portal/src/app/base/project/repository/artifact/artifact-tag/artifact-tag.component.scss
Labels: release-note/update, target/2.13.0

#21718 oidclogout
  api/v2.0/swagger.yaml
  src/common/const.go
  src/core/controllers/base.go
  src/core/controllers/oidc.go
  src/core/controllers/oidc_test.go
  src/lib/config/metadata/metadatalist.go
  src/lib/config/models/model.go
  src/lib/config/test/userconfig_test.go
  src/lib/config/userconfig.go
  src/pkg/oidc/helper.go
  src/portal/src/app/base/left-side-nav/config/auth/config-auth.component.html
  src/portal/src/app/base/left-side-nav/config/config.ts
  src/portal/src/app/shared/components/navigator/navigator.component.ts
  src/portal/src/app/shared/services/session.service.ts
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/ko-kr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
  src/server/route.go
Labels: release-note/new-feature, target/2.13.0

#21474 fix: fix replication of multiple projects with numeric names
  src/pkg/reg/adapter/harbor/base/adapter.go
Labels: release-note/update, target/2.13.0

#21749 update golang to v1.23.7
  CONTRIBUTING.md
  Makefile
  make/photon/registry/Dockerfile.binary
  make/photon/trivy-adapter/Dockerfile.binary
  make/photon/trivy-adapter/builder.sh
  src/go.mod
  tests/ci/distro_installer.sh
Labels: release-note/update, target/2.13.0

#21741 Bump up trivy and trivy-adapter to the latest RC tag
  Makefile
Labels: release-note/ignore-for-release

#21697 Fix Password Validation in UI
  src/portal/src/app/base/account-settings/account-settings-modal.component.html
  src/portal/src/app/base/left-side-nav/user/change-password/change-password.component.html
  src/portal/src/app/base/password-setting/password-setting.component.html
  src/portal/src/app/shared/components/new-user-form/new-user-form.component.html
Labels: release-note/update

#21759 fix: limit the file size of the cnai model processor
  src/controller/artifact/processor/cnai/cnai_test.go
  src/controller/artifact/processor/cnai/parser/base.go
  src/controller/artifact/processor/cnai/parser/files.go
  src/controller/artifact/processor/cnai/parser/files_test.go
  src/go.mod
  src/go.sum
  src/lib/errors/const.go
  src/lib/http/error.go
Labels: release-note/update, target/2.13.0

#21764 redirect to the sign-in page
  src/core/controllers/oidc.go
Labels: release-note/update, target/2.13.0

#21765 fix logout redirect
  src/core/controllers/oidc.go
Labels: release-note/update, target/2.13.0

#21754 fix: Remove top error message about no README or license
  src/portal/src/app/base/project/repository/artifact/artifact-additions/license/license.component.html
  src/portal/src/app/base/project/repository/artifact/artifact-additions/license/license.component.ts
  src/portal/src/app/base/project/repository/artifact/artifact-additions/summary/summary.component.html
  src/portal/src/app/base/project/repository/artifact/artifact-additions/summary/summary.component.ts
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/ko-kr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: release-note/update, target/2.13.0

#20081 Fix token service returning empty token on tls certificate issue without any error
  src/pkg/token/token.go
Labels: release-note/update, candidate/2.13.0

#21607 Update UI Version to 2.12.0 in package.json
  src/portal/package.json
Labels: release-note/update

#21775 update oidc login log level
  src/core/controllers/oidc.go
Labels: release-note/update, target/2.13.0

#21778 update robot log level
  src/server/middleware/security/robot.go
Labels: release-note/update, target/2.13.0

#21792 fix 21118
  src/server/v2.0/handler/robot.go
Labels: area/robot-account, release-note/update, target/2.13.0

#21794 clean up robot account for SBOM Job
  src/controller/scan/callback.go
Labels: release-note/update

#21788 Add tips for "Other events"
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/ko-kr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
Labels: release-note/update, target/2.13.0

#21807 Add operation description for delete tag event
  .gitignore
  src/controller/event/topic.go
Labels: release-note/update, target/2.13.0

#21797 fix orm filterable issue
  src/common/models/oidc_user.go
  src/lib/orm/metadata.go
  src/lib/orm/metadata_test.go
  src/lib/orm/query.go
  src/pkg/reg/dao/model.go
  src/pkg/robot/model/model.go
  src/pkg/user/dao/user.go
Labels: release-note/update, target/2.13.0
