Repository goharbor/harbor, pull requests merged in 2025-08, with the labels that each got.

#22237 update the support list of proxy cache
  make/photon/prepare/templates/core/env.jinja
Labels: release-note/update

#22238 bump go version
  CONTRIBUTING.md
  Makefile
  src/go.mod
  tests/ci/distro_installer.sh
Labels: release-note/update

#22240 bump base images for v2.14.0
  .buildbaselog
Labels: release-note/update

#22241 bump base verson for v2.15.0
  VERSION
Labels: release-note/update

#22223 Upload build logs to github artifact
  .github/workflows/CI.yml
  tests/ci/api_run.sh
Labels: release-note/infra

#22269 Refine the sql to query non empty repositories
  src/pkg/repository/dao/dao.go
Labels: release-note/update

#22292 Adjust the xpath to find the package column in testcase
  tests/resources/Harbor-Pages/SecurityHub.robot
  tests/resources/Harbor-Pages/Vulnerability.robot
Labels: release-note/infra, target/2.14.0

#22298 Remove gitlab replication
  tests/robot-cases/Group1-Nightly/Replication.robot
Labels: release-note/infra, target/2.14.0
