Repository goharbor/harbor, pull requests merged in 2025-09, with the labels that each got.

#22309 Remove GCR replication because GCR account is removed
  tests/robot-cases/Group1-Nightly/Replication.robot
Labels: release-note/infra

#22322 Bump up trivy to 0.66.0 and pin trivy-adapter to 0.34.0
  Makefile
Labels: release-note/ignore-for-release

#22334 bump base images for v2.14.0-rc2
  .buildbaselog
Labels: release-note/update

#22354 Remove p2p preheat by event testcase
  tests/robot-cases/Group1-Nightly/P2P_Preheat.robot
Labels: release-note/ignore-for-release

#22139 Update badges
  README.md
Labels: release-note/docs

#22382 add tag deletion option for gc
  src/controller/gc/controller.go
  src/controller/gc/controller_test.go
  src/controller/gc/model.go
  src/jobservice/job/impl/gc/garbage_collection.go
  src/jobservice/job/impl/gc/garbage_collection_test.go
  src/portal/src/app/base/left-side-nav/clearing-job/gc-page/gc/gc.component.html
  src/portal/src/app/base/left-side-nav/clearing-job/gc-page/gc/gc.component.ts
  src/portal/src/i18n/lang/de-de-lang.json
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
  src/portal/src/i18n/lang/fr-fr-lang.json
  src/portal/src/i18n/lang/ko-kr-lang.json
  src/portal/src/i18n/lang/pt-br-lang.json
  src/portal/src/i18n/lang/ru-ru-lang.json
  src/portal/src/i18n/lang/tr-tr-lang.json
  src/portal/src/i18n/lang/zh-cn-lang.json
  src/portal/src/i18n/lang/zh-tw-lang.json
  src/server/v2.0/handler/gc.go
Labels: release-note/new-feature, target/2.15.0

#22394 [cherry-pick] fix robot issue-21406
  src/server/v2.0/handler/robot.go
Labels: release-note/update, target/2.14.1

#22348 Add max_upstream_conn parameter for each proxy_cache project
  api/v2.0/swagger.yaml
  src/pkg/project/models/pro_meta.go
  src/pkg/project/models/project.go
  src/pkg/proxy/connection/limit.go
  src/pkg/proxy/connection/limit_test.go
  src/server/middleware/repoproxy/proxy.go
  src/server/v2.0/handler/project.go
  src/server/v2.0/handler/project_metadata.go
  src/server/v2.0/handler/project_metadata_test.go
Labels: release-note/enhancement, target/2.14.1
