Repository goharbor/harbor, pull requests merged in 2025-05, with the labels that each got.

#21965 bump base version for v2.13.1
  VERSION
Labels: release-note/update, target/2.13.1

#21967 Pin trivy adapter to v0.32.4
  Makefile
Labels: release-note/update

#21908 [cherry-pick] Update artifact info
  src/server/v2.0/handler/repository.go
Labels: release-note/update, taget/2.12.4

#21974 Display gc progress information in running state
  src/portal/src/app/base/left-side-nav/clearing-job/gc-page/gc/gc-history/gc-history.component.ts
Labels: release-note/new-feature, target/2.14.0

#21975 upgrade the build machine to ubuntu 22
  .github/workflows/build-package.yml
  .github/workflows/publish_release.yml
Labels: release-note/update, target/2.13.1

#21976 build base images for v2.13.1
  .buildbaselog
Labels: release-note/update, target/2.13.1

#21978 bump dependencies of golang
  src/go.mod
  src/go.sum
Labels: release-note/update, target/2.13.1

#21969 Fix: Helm Chart Copy Button in UI
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/pull-command/pull-command.component.html
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/pull-command/pull-command.component.spec.ts
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/pull-command/pull-command.component.ts
Labels: release-note/update, target/2.13.1

#21983 [cherry-pick] Fix: Helm Chart Copy Button in UI
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/pull-command/pull-command.component.html
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/pull-command/pull-command.component.spec.ts
  src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/pull-command/pull-command.component.ts
Labels: release-note/update

#21984 Bump up Trivy adapter for v2.13.x
  Makefile
Labels: release-note/ignore-for-release

#21988 add build flag for harbor exporter
  .github/workflows/build-package.yml
  Makefile
  tests/ci/api_common_install.sh
  tests/ci/distro_installer.sh
  tests/resources/Harbor-Util.robot
Labels: release-note/update, target/2.14.0

#21989 update robot permission table
  make/migrations/postgresql/0170_2.14.0_schema.up.sql
Labels: release-note/update

#21994 increase docker client timeout for robot case
  tests/apitests/python/library/docker_api.py
Labels: release-note/update

#21990 Test update for adding nil value to list
  src/jobservice/common/list/list_test.go
Labels: release-note/update

#21997 Pin trivy adapter to the GA version v0.33.1
  Makefile
Labels: release-note/ignore-for-release

#21999 udpate storage to s3
  .github/workflows/build-package.yml
  .github/workflows/conformance_test.yml
  .github/workflows/publish_release.yml
  tests/ci/api_run.sh
  tests/ci/build_util.sh
  tests/integration.sh
  tools/release/release_utils.sh
Labels: release-note/infra

#22002 [cherry-pick] udpate storage to s3 (#21999)
  .github/workflows/build-package.yml
  .github/workflows/conformance_test.yml
  .github/workflows/publish_release.yml
  tests/ci/api_run.sh
  tests/ci/build_util.sh
  tests/integration.sh
  tools/release/release_utils.sh
Labels: release-note/infra

#22013 build base images for v2.13.0
  .buildbaselog
Labels: release-note/update

#22019 downgrade gorilla go mod version
  src/go.mod
  src/go.sum
Labels: release-note/update, target/2.12.4

#22022 udpate storage to s3 (#21999)
  .github/workflows/build-package.yml
  .github/workflows/conformance_test.yml
  .github/workflows/publish_release.yml
  tests/ci/api_run.sh
  tests/ci/build_util.sh
  tests/integration.sh
  tools/release/release_utils.sh
Labels: release-note/infra, target/2.12.4

#22023 downgrade gorilla go mod on release-2.13.0
  src/go.mod
  src/go.sum
Labels: release-note/update, target/2.13.1

#22024 bump version for v2.12.4
  VERSION
Labels: release-note/update
