Repository goharbor/harbor, pull requests merged in 2025-01, with the labels that each got.

#21061 Skip admin and change oidc user not found message more readable
  src/pkg/oidc/dao/meta.go
  src/server/middleware/security/oidc_cli.go
Labels: release-note/update, target/2.13.0

#21360 Add swagger api and audit_log_ext table model
  api/v2.0/swagger.yaml
  make/migrations/postgresql/0160_2.13.0_schema.up.sql
  src/server/v2.0/handler/auditlog.go
  src/server/v2.0/handler/project.go
Labels: release-note/new-feature

#21374 Update the robot account testcase
  tests/resources/Harbor-Pages/Project_Robot_Account.robot
  tests/robot-cases/Group1-Nightly/Common.robot
Labels: release-note/ignore-for-release

#21375 Update testcase in main branch
  tests/apitests/python/test_system_permission.py
  tests/resources/Harbor-Pages/Project_Robot_Account.robot
  tests/resources/TestCaseBody.robot
  tests/robot-cases/Group1-Nightly/Common.robot
Labels: release-note/ignore-for-release

#21368 Add configure item for audit_log_disable
  src/common/const.go
  src/lib/config/metadata/metadatalist.go
  src/lib/config/userconfig.go
Labels: release-note/new-feature

#21299 fix: replication rule message in UI
  src/portal/src/i18n/lang/en-us-lang.json
  src/portal/src/i18n/lang/es-es-lang.json
Labels: area/ui, area/i18n, release-note/enhancement, target/2.13.0

#21390 Add config max_job_duration_hours for jobservice
  make/harbor.yml.tmpl
  make/photon/prepare/templates/jobservice/config.yml.jinja
  make/photon/prepare/templates/jobservice/env.jinja
  make/photon/prepare/utils/configs.py
  make/photon/prepare/utils/jobservice.py
Labels: release-note/new-feature

#21393 Update the ping registry endpoint to harbor in check permission script
  tests/apitests/python/test_system_permission.py
Labels: release-note/ignore-for-release

#21395 Update prepare to avoid error when max_job_duration_hours not configured
  make/photon/prepare/utils/configs.py
Labels: release-note/update

#20991 Remove robotV1 from code base (#20958)
  api/v2.0/swagger.yaml
  src/server/v2.0/handler/handler.go
  src/server/v2.0/handler/robotV1.go
Labels: release-note/deprecation, HACKTOBERFEST-ACCEPTED, target/2.13.0

#21396 bump up swagger
  Makefile
  src/controller/quota/driver/project/project.go
  src/pkg/quota/driver/driver.go
  src/pkg/quota/models/quota.go
  src/server/v2.0/handler/model/quota.go
  src/testing/pkg/quota/driver/driver.go
  tools/swagger/Dockerfile
Labels: release-note/update, target/2.13.0

#21376 Add middleware for audit log
  src/controller/event/metadata/commonevent/model.go
  src/core/middlewares/middlewares.go
  src/server/middleware/log/log.go
Labels: release-note/new-feature

#21408 Remove id field from payload when update purge audit or gc schedule
  tests/apitests/python/test_system_permission.py
Labels: release-note/update

#21379 Add dao and manager for audit log ext
  src/.mockery.yaml
  src/common/utils/utils.go
  src/jobservice/job/impl/gdpr/audit_logs_data_masking.go
  src/jobservice/job/impl/gdpr/audit_logs_data_masking_test.go
  src/pkg/auditext/dao/dao.go
  src/pkg/auditext/dao/dao_test.go
  src/pkg/auditext/manager.go
  src/pkg/auditext/manager_test.go
  src/pkg/auditext/model/model.go
  src/testing/pkg/auditext/dao/dao.go
  src/testing/pkg/auditext/manager.go
Labels: release-note/new-feature

#21412 bump base images
  .buildbaselog
Labels: release-note/update, target/2.12.2

#21417 Bump up trivy to v0.58.2, trivy adapter to v0.32.3
  Makefile
Labels: release-note/ignore-for-release

#21410 update spectral image
  Makefile
  make/photon/Makefile
  make/photon/portal/Dockerfile
  tools/spectral/Dockerfile
Labels: release-note/update

#21069 Fix Overlay Issue in Replication Page UI
  src/portal/src/app/base/left-side-nav/replication/replication/replication-tasks/replication-tasks.component.scss
Labels: area/ui, release-note/update, target/2.13.0

#21420 remove with_signature
  api/v2.0/swagger.yaml
  src/portal/src/app/base/project/repository/artifact/artifact-tag/artifact-tag.component.ts
  tests/apitests/python/library/artifact.py
  tests/apitests/python/test_p2p.py
  tests/apitests/python/test_proxy_cache.py
  tests/apitests/python/test_push_files_by_oras.py
  tests/apitests/python/test_push_image_with_special_name.py
  tests/apitests/python/test_sbom_generation_of_image_artifact.py
  tests/apitests/python/test_scan_image_artifact.py
  tests/apitests/python/test_stop_sbom_generation_of_image_artifact.py
  tests/apitests/python/test_stop_scan_image_artifact.py
  tests/apitests/python/test_tag_immutability.py
  tests/apitests/python/test_webhook_crud.py
  tests/resources/Harbor-Pages/Project-Artifact.robot
Labels: release-note/breaking-change, target/2.13.0

#21425 separate buildin values
  Makefile
  make/photon/Makefile
  tests/ci/ut_install.sh
Labels: release-note/update, target/2.13.0

#21428 bump base version for v1.10
  .github/workflows/CI.yml
  .github/workflows/build-package.yml
  CONTRIBUTING.md
  Makefile
  VERSION
  docs/compile_guide.md
  docs/use_make.md
  make/common.sh
  make/photon/clair-adapter/Dockerfile.binary
  make/photon/clair-adapter/builder
  make/photon/clair/Dockerfile.binary
  make/photon/clair/builder
  make/photon/registry/Dockerfile.binary
  src/go.mod
  tests/ci/api_common_install.sh
  tests/ci/distro_installer.sh
Labels: target/1.10.20

#21432 disable gpg sign for 1.10
  .github/workflows/build-package.yml
  tests/integration.sh
Labels: release-note/update

#21442 Bump up trivy to v0.58.2, trivy adapter to v0.32.3 (#21417)
  Makefile
Labels: release-note/update

#21448 update exporter docker build para
  make/photon/Makefile
Labels: release-note/ignore-for-release

#21415 Add user login event to audit log
  src/controller/event/handler/auditlog/auditlog.go
  src/controller/event/handler/init.go
  src/controller/event/metadata/commonevent/model.go
  src/controller/event/model/event.go
  src/controller/event/topic.go
  src/core/main.go
  src/lib/config/userconfig.go
  src/pkg/auditext/dao/dao_test.go
  src/pkg/auditext/event/login/login.go
  src/pkg/auditext/event/login/login_test.go
  src/pkg/auditext/event/login/logout.go
  src/pkg/auditext/event/login/logout_test.go
  src/pkg/auditext/model/model.go
  src/server/v2.0/handler/auditlog.go
  tests/apitests/python/library/project.py
  tests/apitests/python/library/projectV2.py
Labels: release-note/new-feature
